### ISSUE TITLE
Plastic explosives don't destroy non-reinforced door

### ISSUE THREAD

**Issue by DaveKorhal** [ParadiseSS13/Paradise#10125]
**Problem Description**:
Plastic Explosives from the Syndicate Uplink didn't destroy a none-reinforced door they were placed on.

**What did you expect to happen**: 
The door to be destroyed.

**What happened instead**:
The door was heavily damaged and I had to bust it apart manually.

**Why is this bad/What are the consequences:**
The wiki's description of the Plastic Explosives says it will destroy anything it's set on. Why buy it if it only has a % chance of destroying what it's set on?

**Steps to reproduce the problem**:
1. Place Syndicate's Plastic Explosives on a door/wall.
2. Wait.

**Comment by variableundefined** [comment]
Kinda a balance issue. However I can see why C4 not destroying door is a big problem.

Can you make a more clear issue title like "Plastic explosives don't destroy non-reinforced door" instead of "Syndicate Plastic Explosives" - Where possible issue report should point out the problem at a glance.

If you want to fix this contact a head and a maint first as this has balance implication.

**Comment by hal9000PR** [comment]
no longer an "issue"
