### ISSUE TITLE
Mining bots their KA doesn't scale with the environment

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#10135]
**Problem Description**:
Mining bots do full damage with their KA blasts in every environment

**What did you expect to happen**: 
The KA not to break every bone in your body on the station

**What happened instead**:
The KA blast to scale to the environment it is in like the miners KA.

**Why is this bad/What are the consequences:**
It makes mining bots unstoppable. Breaking bones left and right.

**Steps to reproduce the problem**:
1. Have a mining bot on the station
2. Have it shoot a humanoid
3. Hear the crunching

**When did the problem start happening**:
Unsure but for a while now

**Comment by variableundefined** [comment]
Not sure if intended or oversight.

**Comment by KasparoVy** [comment]
OP

**Comment by TDSSS** [comment]
I ded pls nerf

**Comment by farie82** [comment]
More a everybody literally ded. :p

**Comment by KasparoVy** [comment]
^ sad that it's been left in this long but it's mainly b/c who'd suspect minebots of all things to be opieOP

**Comment by variableundefined** [comment]
I've looked into the code about this. This has to do with simple_animal/hostile directly firing a projectile, instead of going through a normal gun's process - A normal gun would call the ammo_casing's ready_proj projectile, which is where the kinetic accelerator modify its damage for on-station use. However a mining bot outright bypass that.

This is likely to require a refactor to fix properly so I am labelling it code limitation.

**Comment by The-Driker** [comment]
I witnessed this earlier this evening. It seems it's becoming a popular syndicate tool, just fully upgrade a minebot and have it murder your target on station with very little linking you back to it.
