### ISSUE TITLE
Unathi sharp snout alt head is missing from icon file (Or just stashed somewhere)

### ISSUE THREAD

**Issue by variableundefined** [ParadiseSS13/Paradise#10146]
**Problem Description**:
In the course of doing #10089 I realized that unathi sharp snout alt head never worked on both live and on my local copy. Upon investigation, the icon file was not declared on the sprite and I have no idea where the sprite is, if it is here at all.

`/datum/sprite_accessory/alt_heads/una_sharp_snout // NOTE: This is broken without any icon file or known icon_state. Remove this comment when this is fixed.
	name = "Unathi Sharp Snout"
	species_allowed = list("Unathi")
	icon_state = "head_sharp"
	suffix = "sharp"`
`/datum/sprite_accessory/alt_heads
	icon = null
	icon_state = null
	species_allowed = null
	var/suffix = null

/datum/sprite_accessory/alt_heads/none
	name = "None"`
To be fixed after 10089 is in.

Don't fix this until #10089 is merged!

**Comment by KasparoVy** [comment]
That's wack, seems to work for me. 

The sprite is currently in the unathi head .dmi [here](https://github.com/ParadiseSS13/Paradise/blob/master/icons/mob/human_races/r_lizard.dmi) and [here](https://github.com/ParadiseSS13/Paradise/blob/master/icons/mob/human_races/r_def_lizard.dmi).

It works by choosing alt head on unathi in chargen and will reset your markings/headstuff since it's validated against alt_head

Sprites render properly in character generation and in-game in my experience and I see it working on other characters as well

![proven sharp snout](https://user-images.githubusercontent.com/12377767/48104036-ab489f80-e229-11e8-872b-9abe236db200.png)
_Taken 2018-11-06_

**Comment by variableundefined** [comment]
Ahh. I see. I guess it don't work on CMA.
