### ISSUE TITLE
Wizard Cursed Heart

### ISSUE THREAD

**Issue by Ridgyaxe** [ParadiseSS13/Paradise#10155]
**Problem Description**:
Died to a bug with the cursed heart, that caused me to pass out, and immediately die. I noticed that I 'Felt extremely faint' right before passing out.

**What did you expect to happen**: 
Because it's a wizard round, and the round is over at this point. I expected to live MUCH longer.
**What happened instead**:
I died.
**Why is this bad/What are the consequences:**
New players might see this and go 'hey, this sounds great!' and then die

**Steps to reproduce the problem**:
Fuck if I know

**When did the problem start happening**:
During a wizard Round
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Wizard round. YES, I WAS PUMPING MY HEART.

**Comment by ScratKnapp** [comment]
Is the idea supposed to be if you don't pump the heart every 6 seconds you die?

**Comment by Pckables** [comment]
To be fair, new players thinking "Hey, This sounds great!" to the cursed heart is a problem even when it's working as intended.

**Comment by AzuleUtama** [comment]
So, the item itself is working as intended. Each second you go over the "limit" will cause you to lose 100 units of blood, which **will** knock you out if you keep missing the beats. It can be difficult to tell you've lost blood because of this during combat which might be why it was so sudden for you.

One thing I can agree with is that newbie mages could do with a fairer warning that the item will cause them to lose blood if they don't keep beating it. After a quick discussion in discord, I'll make a PR to change the item's description to give a clearer warning about the risks it carries.
