### ISSUE TITLE
Shadowling Jaunt Bug

### ISSUE THREAD

**Issue by Sollessa** [ParadiseSS13/Paradise#10226]
I'm unsure if it's still a bug as it's been a while since I was a shadowling but last time I played one I got hit by laser fire while jaunting.  I pressed the jaunt button and started moving, but after I disappeared I still caught and took damage from some laser shots that had been in the air already.

**Comment by Pckables** [comment]
It seems the jaunt is more of invisibility+moving through walls, rather than becoming ethereal, hence why you still take damage from lights and break glass tables.
This can also be abused to the shadowlings advantage, as they can still attack in this state. It's possible for shadowlings to use stunprods while jaunted, possibly stunning multiple people while completely invisible.

**Comment by variableundefined** [comment]
Not sure if a bug.

**Comment by farie82** [comment]
Slings got removed. Closing this issue
