### ISSUE TITLE
arcade_base.dm message runtime

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#10328]
**Problem Description**:
[2018-11-24T07:57:47] Runtime in code/modules/arcade/arcade_base.dm,112: DEBUG: to_chat called with invalid message/target.
   Message: 'Unable to access account: incorrect credentials.'
   Target: ''
   src: Claw Game (/obj/machinery/arcade/claw)
   src.loc: The carpet (140,161,1) (/turf/simulated/floor/carpet/arcade)
   usr: Unknown (CHARACTER) (/mob/living/carbon/human)
   usr.loc: The carpet (141,161,1) (/turf/simulated/floor/carpet/arcade)

Looks like something is calling pay, but without a user to the proc, and the account security level is != 0, which results in it trying to message the non-existent user.

**Comment by FalseIncarnate** [comment]
It appears no user is passed from attackby() to pay_with_card(), line 72 of the file just needs to have the user argument added. Apparently I missed that part when the arcade stuff was added and no one noticed before now.

Easy fix for a beginner to the code, otherwise I'll fix it later this week (to give newbies a chance to cut their teeth on this).

**Comment by Couls** [comment]
I think this has been fixed by now
