### ISSUE TITLE
Duct Tape taping jackboots instead of silencing it

### ISSUE THREAD

**Issue by LordMadness** [ParadiseSS13/Paradise#10374]
**Problem Description**:
Tried to silence jackboots with the duct tape and it just added a tape to the boot as if I were to stick it somewhere.

Didn't try to actually tape the boot to a wall, but well, wasn't supposed to do that anyway.
And the boots didn't get silenced either.

![screenshot_2](https://user-images.githubusercontent.com/45457447/49222099-b7072c00-f3b9-11e8-8737-6715c70ad3aa.png)

**Comment by Citinited** [comment]
This issue's been reported on the PR itself - I'll have a fix for it once I get home from work.

**Comment by Citinited** [comment]
The issue is that jackboots by default have `silence_steps = TRUE` (https://github.com/ParadiseSS13/Paradise/blob/8d40bcc7cdc248a61c8455ae0be37d0339011f6f/code/modules/clothing/shoes/miscellaneous.dm#L96) to prevent the step sound from playing as well as the jackboot sound. It's dumb but I'll see what I can do to fix it
