### ISSUE TITLE
Plastic surgery cannot restore a mob's real name

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#10578]
**Problem Description**:
If you've had plastic surgery done on you before, your real name cannot be restored through surgery.

**What did you expect to happen**: 
If I can have my face changed to another identity by surgery, it makes sense that my face could be restored to my original one

**What happened instead**:
Impossible to do

**Why is this bad/What are the consequences:**
This isn't gamebreaking as you can still restore your appearance by taking your UI and transferring it in genetics since the surgery doesn't touch DNA, but it's not intuitive

**Steps to reproduce the problem**:
Step 1. get plastic surgery to change your face to another name
Step 2. get plastic surgery done again, your real name won't show up on the list

**When did the problem start happening**:
As long as facial reconstruction been replaced with plastic surgery probably

**Comment by Fox-McCloud** [comment]
This is a feature request, not really something intended by the original surgery.

Due to the way in which names are handled (including genetically), this isn't something that can really be done without altering existing systems....it's also not something explicitly intended for plastic surgery in and of itself (and could cause potentially easy metagaming issues...security could insist on this surgery to find out their "real" identity).
