### ISSUE TITLE
Telecom control cannot control other Telecom setups

### ISSUE THREAD

**Issue by Shadow-Quill** [ParadiseSS13/Paradise#10594]
**Problem Description**:

Title

**What did you expect to happen**: 

To be able to supply a network name, so as to independently change different TComm network settings.

**What happened instead?**

Control console directly controlled tcommsat network, even when being two tiles away from a differently networked hub.

**Why is this bad/What are the consequences:**

Can't apply scripts to the backup telecoms system you made in the cargo warehouse.

**Steps to reproduce the problem**:

1) Create telecoms setup with a different network name.
2) Create control console.
3) change settings
4) observe how only the normal network is being affected

**When did the problem start happening?**

NTSL 2.0 :angryeyes:

**Comment by Shadow-Quill** [comment]
@AffectedArc07 👀

**Comment by AffectedArc07** [comment]
Due to the nature of how NTTC (NTSL2) works, this is going to require a lot of code, and may as well get the `Cant Fix/Wont Fix` label. NTTC doesnt give 2 shits about what network youre on, since it just goes *"This is a signal, lets process it"*

`code/game/machinery/telecomms/telecommunications.dm`
```dm
497]				// Run NTTC against the signal
498]				if(GLOB.nttc_config)
499]					GLOB.nttc_config.modify_signal(signal)
```

`code/game/machinery/telecomms/ntsl2.dm`
```dm
// Primary signal modification. This is where all of the variables behavior are actually implemented.
/datum/nttc_configuration/proc/modify_signal(datum/signal/signal)
```

It just chucks the signal at it and doesnt care for networks. This may be doable but will end up being an extremely large clusterfuck.
