### ISSUE TITLE
Fruit naming

### ISSUE THREAD

**Issue by Mijhead** [ParadiseSS13/Paradise#1065]
In grown.dm, lines 90 to 116, there are references to trekchem chemicals for fruit descriptions, IE pacid for acidic description. This'll need updating to goofchem for proper descriptioning.

**Comment by FalseIncarnate** [comment]
I thought I had fixed these when I did the port, but apparently did not save that if I had.

Since they are string checks, it compiled and runs fine despite the issue, not spewing runtimes or such, which is probably why I hadn't noticed. I'll fix this tomorrow unless another coder takes it while I'm asleep/at work.

**Comment by FalseIncarnate** [comment]
Ignore that reference, accidentally posted the reference in the wrong PR (removed the comment that the reference was in, that's what I get for leaving windows open and not paying attention to which one I was typing in)
