### ISSUE TITLE
Nukie Macrobomb/Multiple Microbombs triggers hundreds of Emotes, Lags Nearby Players

### ISSUE THREAD

**Issue by DaveKorhal** [ParadiseSS13/Paradise#10708]
**Problem Description**:
When the Nukie Macrobomb activates, chat is spammed with hundreds of emotes that lags out nearby players.

**What did you expect to happen**: 
It would explode.

**What happened instead**:
Hundreds of emotes simultaneously occured, lagging out nearby players for several seconds.

**Why is this bad/What are the consequences:**
I don't want to lag out for 3 seconds while running away.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**When did the problem start happening**:
It happened at 1 PM EST, January 22, 2019.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Someone was shooting the nukie with a shotgun point-blank.

![ss13](https://user-images.githubusercontent.com/9967634/51564527-28f97000-1e55-11e9-994f-fcb973e7c0c3.png)

**Comment by DaveKorhal** [comment]
Appendeum: Three Point Fourteen glanced into the issue; he believes something in the Devil PR broke implants.

**Comment by datlo** [comment]
i could not replicate this with so many messages at once but I did get 3 messages for one explosion which shouldn't happen to begin with

it seems that the implant is triggered on near death aswell instead of just on death which shouldn't happen either and is likely the root cause of the issue, i'm not sure what's the code responsible for that, couldn't find it after a quick lookover

**Comment by Emanthealmighty** [comment]
What if wizards gained points to get more and better abilities? This would mean that the longer a wizard lasts, the more chaos he can cause. 

As a round start wizard, you would have the biggest advantage, then the wizard that comes after you die you would have less starting points, thus he would have to take a different strategy and an overall less confident approach, and the one after that one too, etc.

Also, regarding demons, i think they should be kept but require a lot of points: only a round start wizard should be able to buy a real slaughter demon without having gained any points.

A nice thing to compensate would be to make cluwnes no longer "crew members" and actually have the objective to help the wizards, instead of being clumsy unmanageable useless things, so you can effectively raise an army of players to help you eventually. (Naturally how you turn people into them would have to be tweaked so that you don't just rush in and instantly tap'n'turn somebody)

**Comment by Mitchs98** [comment]
@Emanthealmighty I believe you are on the wrong PR, my good sir :thinking:

**Comment by Emanthealmighty** [comment]
@Mitch98 Indeed I am. Thanks for pointing it out!
