### ISSUE TITLE
smoke grenades affect creatures behind glass

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#11114]
**Problem Description**:
A smoke grenade will affect crew behind enclosed glass. In the case of the finding. A smoke grenade was thrown in the hallway in front of the bridge and the people on the bridge got affected.

**What did you expect to happen**: 
Smoke not to go through solid structures

**What happened instead**:
We got hit by the smoke effect

**Why is this bad/What are the consequences:**
You can spread sarin through the glass by doing this.

**Steps to reproduce the problem**:
1. Throw a smoke grenade in front of the bridge. A grenade with lets say growth serum.
2. Have somebody stand in the bridge in range of the normal grenades range.
3. See the person behind the glass grow.

**When did the problem start happening**:
Since the new smoke PR. I think

**Comment by Fox-McCloud** [comment]
Smoke has always done this, and it's semi-intentional.

It's based on a visibility check for things in range of it when it goes off; if turf can "see" something when it goes off, it's going to get smoked.

There could be marginal improvements made to check for a few things, but on the whole, it's not worth it and will created more problems than it solves, for smoke; having it pierce windows is, again, semi-intentional, and probably for the best.
