### ISSUE TITLE
Detectives Lack Security SBR Access

### ISSUE THREAD

**Issue by Mitchs98** [ParadiseSS13/Paradise#11154]
**Problem Description**:
Detective's no longer/do not have access to the security frequency on station bounced radios.

**What did you expect to happen**: 
I expected to be able to speak to my fellow harmbatonners on sec channel.

**What happened instead**:
I could not speak to fellow harmbatonners on the sec channel, only on common.

**Why is this bad/What are the consequences:**
Detective isn't an officer but they are effectively a security role. They should have access to the channel for when telecomms go down and the like.

**Steps to reproduce the problem**:
1. Be detective.
2. Get Station Bounced Radio.
3. Click it and see no security frequency.

**When did the problem start happening**:
No idea, possibly forever? Can't remember if they used to have it or not.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Nothing relevant.

**Comment by Citinited** [comment]
You know, now you mention it, I don't ever remembering detectives having security access on SBRs. 🌮

**Comment by Mitchs98** [comment]
> You know, now you mention it, I don't ever remembering detectives having security access on SBRs.

Amazing.

**Comment by ungauss** [comment]
I think it's because the detective doesn't have minimal security access:
https://github.com/ParadiseSS13/Paradise/blob/c6e89900c258dd5827430f65a752744b9abd8660/code/game/jobs/job/security.dm#L109

They have job security_access and spawn with the same ID as security officers, so they should have this. (It's kind of broken that security_access is not a superset of minimal security_access).
