### ISSUE TITLE
Faxes need toner to send faxes.

### ISSUE THREAD

**Issue by Mitchs98** [ParadiseSS13/Paradise#11172]
**Problem Description**:
Fax machines need toner to SEND faxes, not only to receive them.

**What did you expect to happen**: 
I expected my fax machine to not magically use toner to send something via a fax, as that makes no sense at all.

**What happened instead**:
It used toner and I had to get more when I shouldn't of needed it.

**Why is this bad/What are the consequences:**
It makes absolutely no sense to consume toner to SEND a fax message. It also probably shouldn't consume it to RECEIVE one unless it's specially coded to not need it for Central faxes, as this can cause many number of problems.

**Steps to reproduce the problem**:
1. Fax a bunch of things or one detailed fax with a lot of photos.
2. Fax runs out of toner as if it were a printer.

**When did the problem start happening**:
Probably forever.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Nothing relevant.

**Comment by Twinmold93** [comment]
What exact messages did you get for this?

**Comment by Twinmold93** [comment]
I believe I see where the issue is. The issue itself may have to do with the proc/send_admin_fax under faxmachine.dm, as it calls the procs of photocopier.dm, proc/copy, proc/photocopy, and proc/bundlecopy without any additional instances of this being a 'sent' fax per faxmachine.dm. Therein, it uses toner to make a non-physical copy of the faxes that get sent to admins, which is then also just nullified. It is technically printing a fax that is then deleted.

**Comment by Mitchs98** [comment]
> What exact messages did you get for this?

The standard message photocopiers use when they run out of toner.
