### ISSUE TITLE
Being set on fire doesn't immediately deal damage

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#11218]
**Problem Description**:
If you are set on fire, it takes a couple seconds for you to heat up enough to get damaged by it. Fire doesn't raise your temperature fast enough

**What did you expect to happen**: 
Fire should burn you immediately

**What happened instead**:
It took a few seconds for the fire to increase my temperature high enough to cause any damage.

**Why is this bad/What are the consequences:**
Fire should be dangerous and pose an immediate danger, but instead if you're on the ball you can put out the fire quick enough to not take any damage whatsoever.

**Steps to reproduce the problem**:
1. Set yourself on fire.
2. Don't take damage for a few
**When did the problem start happening**:
I think within the past month, unsure though.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Not sure if this is intended behaviour or not, but I figured I should open an issue anyways.

EDIT: I was a plasmaman, without a suit, will test out later if all mobs have this or if it's related to that.

**Comment by Fox-McCloud** [comment]
Pretty sure it's always been like this.

Newcrit didn't touch anything related to how the body takes fire damage, and the recent changes to reagents and pyrotechnics didn't either. Fire damage *was* nerfed a bit, but this was only once your bodytemp was already at the maximum level *and* you were on fire.

Fire doesn't actually cause damage directly; it only causes you to heat up faster than you otherwise would, but is still subject to limitations imposed by this line of code here:

`bodytemperature += (BODYTEMP_HEATING_MAX + (fire_stacks * 12))`

Firestacks really haven't changed much; if anything they've been *buffed* for chemistry related things (plasma is basically unimpacted).

Could you be more specific as to the situation? Keep in mind, depending on what you're wearing, will slow body temperature adjustments.

Firesuits, for instance greatly slow down the rate at which you heat up.

**Comment by Citinited** [comment]
Okay, I played around a bit with this. From my observations (as a naked human wearing nothing, with normal nutrition values) the following is the case:
- The method of being set on fire influences how hot you end up. ClF3, for instance, immediately raised my temperature to over the damage threshold
- I didn't take any damage until a short time after being set on fire (when `Life()` triggered, I am assuming), which is fine.
- Fire itself doesn't immediately inflict any burn damage, it all is handled on the mob's body temperature.

So I guess this is working as intended :D
