### ISSUE TITLE
Chameleon Jumpsuit can select all the jumpsuits ingame

### ISSUE THREAD

**Issue by Sikroth** [ParadiseSS13/Paradise#11469]
**Problem Description**:
What the title says. When trying to change the jumpsuit appearance you're given a list with all the jumpsuits in the game. This includes spriteless/ buggy jumpsuits, jumpsuits that aren't meant to be even used (vox/alien bodies??) and even Patreon supporter jumpsuits.

**What did you expect to happen**: 
Probably to have a less extensive list. While I hope most suits stay, there's a bunch of bugged ones and others that shouldn't really be available.

**What happened instead**:
All the jumpsuits are available

**Why is this bad/What are the consequences:**
You can use a bugged sprite which causes you to appear naked with a SUIT text beside you. You can also use "premium" suits that are supposed to belong to patreon supporters only.

**Steps to reproduce the problem**:
- Get a chameleon Jumpsuit
- Use the Change Appearance option for the suit (not the one for the whole "chameleon bundle")
- See ALL the options.

**When did the problem start happening**:
Most likely after https://github.com/ParadiseSS13/Paradise/pull/11428
The changelog doesn't go into detail about how the jumpsuit specifically was altered but I imagine this'd be the cultprit.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
- I found the jumpsuit in maintenance, not from a traitor uplink, if that changes anything.
- I also remember seeing a version of the chameleon jumpsuit that allows you to do this, a while ago, in a local testserver, but it was adminspawned only.

**Comment by Markolie** [comment]
Thank you for your report! It's much appreciated.

All jumpsuits being selectable is intentional. There's probably a few there that may need to be blacklisted but in general the blacklist should only be used for "clothing" that isn't actually clothing, like the bodies you mentioned.

Spriteless jumpsuits (or any objects that can be chameleoned like belts) should either not be in the game or be marked ABSTRACT, so those will need to be fixed (and reported) individually as that's indicative of an issue with the item itself, not the chameleon objects. Plus, it's easy to switch to another item using the chameleon system.

As for fluff items: I personally don't think it's an issue to have these available for chameleon users, as these aren't available at roundstart (they're either bought by traitors or found with a low chance in maintenance) and may be required to properly impersonate specific crew members. If this is something we're insistent on preventing, it's a fairly straightforward to fix this by adding a variable to items to mark them as fluff items and then adding a single if check to prevent them from being picked. I don't really want to invest the time to do that, however.

**Comment by Sikroth** [comment]
I personally like the ability to select most suits, other than the broken ones of course. I'm glad to hear it was intentional!

I could try to go over all the possible options and list which ones don't work properly, but that'll take a while probably. If I end up doing that, I'll add them here, or make a separate issue if this one's closed. I'll leave it open for now in case the fluff ones are to be removed.

Speaking about the fluff ones, I personally don't mind them, but I guess it's mostly the admin's decision to allow or blacklist them. You make a good point in that they can be necessary for impersonation.

**Comment by Markolie** [comment]
Yea, it's fine to use this issue. Going through them would be much appreciated, but don't feel obligated. Whenever you come across one randomly you can always just report it. Most of them should be working fine, thankfully.
