### ISSUE TITLE
Russian Revolver glitches

### ISSUE THREAD

**Issue by Couls** [ParadiseSS13/Paradise#11507]
**Problem Description**: The russian revolver instantly acts when you click so you can essentially click yourself 6 times for an instant kill
What is the problem? : Russian Revolver is instant and activates even when you're aiming for your head
**What did you expect to happen**: Progress bar that adds suspense when aiming for head
Why do you think this is an issue?: It removes the suspense from russian roulette
**What happened instead**: Instantly skipping to the *click* and killing me
How is what happened different from what you expected?: There was no progress bar
**Why is this bad/What are the consequences:** I guess you can **maybe** suicide quickly by exploiting the lack of a progress bar but I don't see how that matters much unless you have die a glorious death and security are knocking at your door
Why do you think this is an important issue?: It's not really an important issue
**Steps to reproduce the problem**: Pick up russian revolver, aim anywhere, click yourself.
**When did the problem start happening**: Unsure
If your report is about something that used to work but no longer does, when was the last time you remember it working?: At least one month ago

**Comment by Emanthealmighty** [comment]
The revolver always fires instantly when you try firing it as you'd shoot a normal weapon, and it can't even be used to shoot others because when you get the actual bullet it immediately decapitates you... Many people died by that.

**Comment by Dave-TH** [comment]
Calling this a glitch is a little misleading.

**Comment by Fox-McCloud** [comment]
This isn't a glitch. This is a feature request.

The Russian revolver was dramatically refactored in: https://github.com/ParadiseSS13/Paradise/pull/11170

It's behavior is consistent with what you're describing.

If the revolver is going off when placing it on a table or inside a backpack or equipping it? Yeah, that's a bug.

If it goes off instantly if you click anywhere other than the mentioned above? Intentional and absolutely not a bug.
