### ISSUE TITLE
[Lavaland] Outpost airlocks aren't cycling

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#11624]
**Problem Description**:
Lavaland airlocks aren't cycling airlocks, don't have vents or anything.
**What did you expect to happen**: 
For them to cycle so I don't release the air from the station.

**What happened instead**:
Station slowly but surely lost air.

**Why is this bad/What are the consequences:**
Can't enter mining station without a hardsuit from station, new miners can't get to the hardsuits without taking damage.

**Steps to reproduce the problem**:
1. go to mining station
2. use airlocks

**When did the problem start happening**:
Lavaland

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

**Comment by taukausanake** [comment]
#11392 👀

**Comment by Markolie** [comment]
You'll never need a hardsuit, as Lavaland has sufficient pressure. You just need a mask. The issue here is a bit more complex than adding regular cycling airlocks, because it'd need two canisters: one for station air and one with the Lavaland mix. Our current system does not support this, nor will the airlock spawner pull request resolve this issue. For now we'll just have to make due with the standard airlocks.

**Comment by TDSSS** [comment]
can't you just put a vent outside in lavaland to pull from there for the lavaland mix? No reason you have to pull from a tank, right?

**Comment by Markolie** [comment]
Aye, that'd also be a possibility. But our system also does not support an external vent.

**Comment by Sikroth** [comment]
While tiny fans are kind of a "i dont want to deal with atmos issues at all" solution, I feel the current airlocks are a complete pain in the ass to deal with.

They work in tg because you generally don't give a crap about atmos differences there, but in paracode when the airlock keeps getting depressurized, it causes fastmos to pull you around, which in turns makes you lose grip on your ore box all the time, or be smacked by the O2 locker there or any other objects.

Besides, having to click a small button on a window to open the airlock while an ash storm is killing you is far from ideal.

**Comment by Markolie** [comment]
We'll just roll with tiny fans then.

**Comment by taukausanake** [comment]
I _**hate**_ tiny fans

**Comment by Sikroth** [comment]
I know tiny fans are kinda dumb, but the alternatives are either leaving it is now, with the very annoying side effects of fastmos forever haunting it, or making some actually cycling airlock, which as Markolie said is complicated, and that'll mean having to wait for cycling as an ash storm kills you which sounds very not fun.

**Comment by taukausanake** [comment]
I feel like it's suiting though. Lavaland is supposed to be dangerous what with all the fauna living on it and the weather. If you have time to run to the outpost before the damage starts then it would add to the excitement to escaping death, but I don't know how ash storms work.
I really hope we get dual-cycling airlocks. Might even be good for special species rooms like Vox boxes and Plasmamen rooms

**Comment by Markolie** [comment]
The eventual goal is to have proper cycling airlocks.
