### ISSUE TITLE
Goliaths can push (bolted) airlocks away

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#11648]
**Problem Description**:
Goliaths can casually push bolted airlocks away.

**What did you expect to happen**: 
Either them not to be able to do it. Or the airlock to break

**What happened instead**:
The airlock moved as if it was just a normal structure

**Why is this bad/What are the consequences:**
Doesn't make to much sense for airlocks to be moved around. Especially bolted ones.

**Steps to reproduce the problem**:
have an airlock. Have a player controlled goliath. PUSH!

**When did the problem start happening**:
Since lavaland

**Comment by Markolie** [comment]
I double checked, and this is actually intentional. They have MOVE_FORCE_VERY_STRONG, which allows them to push most things.

**Comment by Markolie** [comment]
Yuo can close this @farie82.

**Comment by asciodev** [comment]
The discussion on the discord immediately after this issue was closed indicated a direction of goliaths breaking instead of moving airlocks. This has not happened. I would ask that this issue be reopened, because the behavior is very non-obvious, and leads to spawn-camping behavior for ghostroles like golems. It is not clear to me that this flag being set means that this behavior is intentional from a design perspective.

If this _is_ intentional from a design perspective, I think it's worth reconsidering its gameplay value vs simply breaking airlocks.
