### ISSUE TITLE
Ash Walkers have no means of obtaining leather

### ISSUE THREAD

**Issue by MrMagolor** [ParadiseSS13/Paradise#11651]
**Problem Description**:
What is the problem?
Leather, which is needed for at least the goliath hide cloak, cannot be obtained by ash walkers, as it requires a gibber and/or washing machine.
**What did you expect to happen**: 
Why do you think this is an issue?
Ash Walkers should be able to ostensibly be able to make every tribal recipe without breaking the "no-going-to-station" rule.
**What happened instead**:
How is what happened different from what you expected?
Be sad about not having a cool cloak.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Muh tribalism
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
None, really, as the entire issue is that there's no way to get it.
**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
Probably whenever lavaland was merged.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
Having a sink or puddle near the ash walker tendril to act as a washing machine, and possibly a gibber in the zone with the cargo, would work fine I think.

**Comment by Markolie** [comment]
You can obtain the goliath hide from a goliath by attacking it with a spear when it's dead. You can also use the spear to turn the hide into hairless leather by using your spear on it.

I'll make it so that you can use water bottles on the leather (which the ash walkers have in their storage) to make it wet. You can refill these bottles using the water tank. 

The only problem will be the drying. The ash walkers can create a dryer using wood, but it does need power. I think the ash walkers will just need to find a powered area to put the dryer in so they can use it.

**Comment by MrMagolor** [comment]
Perhaps you could roast the wet leather on a bonfire as a slower means of drying?

**Comment by Markolie** [comment]
If someone can create a sprite for that, sure.

**Comment by MrMagolor** [comment]
This still exists as far as I am aware -  either using the leather on a water container, or vice versa, did not create wet hide.

**Comment by Markolie** [comment]
Harm intent with water in a bucket with at least ten units will work. Make sure it’s hairless hide or it won’t work.
