### ISSUE TITLE
Fore Port Solar APC doesn't work

### ISSUE THREAD

**Issue by Sollessa** [ParadiseSS13/Paradise#11752]
Lt. Diggs was able to find the issue with the fore port solar APC.  It seems that the tile that the APC is on is not technically part of the room and is in space or something which is why it can't charge or anything.  It also seems that the rest of the room's reinforced walls aren't part of the room either.  Since the APC doesn't work neither does the solar tracker for that solar either.

**Comment by LtDiggs** [comment]
After spending some time tinkering with the solars I can point out that its only the Fore Port Array (NW). As Sol stated the APC doesn't charge nor does it distribute power to any of the room's functions yet they somewhat work anyway.
![NW Solar](https://user-images.githubusercontent.com/41313156/60092383-40cd7b00-978a-11e9-9d10-17e0c3befd85.PNG)
It remains at 90% for most of the shift unless altered/drained. Compared to the others it should look like this.
![SE Solar](https://user-images.githubusercontent.com/41313156/60092538-a02b8b00-978a-11e9-95b0-c8a64e746923.PNG)
Now though, after taking down some walls I did find that it is indeed part of the room, and so are the walls. Though removal of the APC shuts down the tracker and disallows energy production. Due to whatever reason any attempt I've made to remake and replace the APC came to naught. Though a certain response you don't usually get.
![Unable](https://user-images.githubusercontent.com/41313156/60092726-1203d480-978b-11e9-8c0e-d3d90750670c.PNG)
I checked this through several rounds and the same results occurred. I am unsure to what causes this since I don't know code or mapping.

**Comment by Citinited** [comment]
I've had a look at the map and it does look to be mapped correctly:

![image](https://user-images.githubusercontent.com/18459142/60117512-1a9be100-9772-11e9-82a9-7649c0f04037.png)

Its initial position must be correct as it spawns with the correct area name. Perhaps something is happening to the area during the round to screw it up somehow?

**Comment by LtDiggs** [comment]
That's the Aft Starboard which when I checked, yes is fine. The Fore Port (NW) Solars is the one that doesn't work properly.

**Comment by Citinited** [comment]
Oh right, I got confused by your screenshots haha

I'll take a look at it later on

**Comment by Citinited** [comment]
I had a look at all the solars and they all seem to be mapped correctly - perhaps the wire is bugging out? I have noticed recently that APCs sometimes don't charge even if the wire at the terminal is powered.

**Comment by LtDiggs** [comment]
The wires were all fine when I tested them, even removing, replacing, hotwiring and doing alternative placements. All were powered normally and appeared like they should. My thoughts of resolving this might be just to redesignate the NW solars as a room since it wouldn't even accept a new APC. Again, no mapping knowledge so that suggestion might not even work for all I know.

**Comment by Sollessa** [comment]
I couldn't figure out what was wrong either.  I had tried to fix it in the paste by redoing the wiring and such.  I showed it to Kaiikah one shift with the simple explanation that it was cursed to see if he could fix it.
