### ISSUE TITLE
Floor Plating Deconstruct

### ISSUE THREAD

**Issue by xProlithium** [ParadiseSS13/Paradise#11999]
**Problem Description**:
What is the problem?
Floor plates can be deconstructed on help intent.

**Why is this bad/What are the consequences:**
You can deconstruct the floor and breach into space far too easily and on accident as well.

**When did the problem start happening**:
#11658

**Possible Fix**
Add the step to unscrew the floor plate (from the lattice under it) before welding to deconstruct or change the intent required.

**Comment by Sikroth** [comment]
As a tangential problem to this, fighting in maintenance using a welder (as is commonly done during blob rounds, for instance) is now asking to get blinded and kill your yees in a second, if you happen to missclick your target a few times, since you'll start weldering the floor instead.

I feel like that's probably a bad thing. A non-welder previous step would be much appreciated.
