### ISSUE TITLE
[Bug] Chameleon-Projector allows you to go over lava without taking damage. Can deactivate over them without taking damage too.z

### ISSUE THREAD

**Issue by Abydos2** [ParadiseSS13/Paradise#12006]
**Problem Description**:
The Chameleon-Projector for all intents and purposes seem to physically turn that person into the item. And since an item cannot physically take fire / lava damage, anyone who has one can turn themselves into any form of item, casually go across lava without any fear of death.

**What did you expect to happen**: 
Expected the person to die when they touched the lava or burst into flames.

**What happened instead**:
Nothing. They could move around lava without any form of damage on them.

**Why is this bad/What are the consequences:**
Mainly due to the fact that anyone could grab a Projector as maint loot or spawn in one as a syndie. Can use it to try and break into Syndie outpost, or even stay safely within lava tiles without fear of dying. You can even deactivate it while on lava tiles, so you can safely kill someone with range, without them being able to attack you back.

**Steps to reproduce the problem**:
1) Spawn yourself in

2) Give yourself a Projector

3) Turn into any form of item

4) Go over lava tiles

5) Notice you aren't taking damage

6) Deactivate the projector

7) Notice you're on lava without taking damage.

**When did the problem start happening**:
Not too sure when it started happening.

![Capture](https://user-images.githubusercontent.com/15679133/63051166-9396f980-bed4-11e9-8666-1b3805c1251b.PNG)

![Capture2](https://user-images.githubusercontent.com/15679133/63051174-9691ea00-bed4-11e9-91bb-24c27b8bb62f.PNG)

![Capture3](https://user-images.githubusercontent.com/15679133/63051183-9a257100-bed4-11e9-9063-82cc3dd39846.PNG)

![Capture4](https://user-images.githubusercontent.com/15679133/63051190-9c87cb00-bed4-11e9-9509-f93ec35fba9a.PNG)

**Comment by farie82** [comment]
Issue comes from the fact that you're not a mob when you're disguised. 

Lava checks on the OnCrossed what is on it's tile. Is it a living mob? Hurt it. Otherwise if it's an obj then use fire_act.

This issue has two issues in it. The first one being the obvious immune to lava as disguise one. And the second one the fact that you can stand on top of the lava when you do actually remove the disguise.

First one is solvable by making the disguise object do something on fire_act(). Can look at it's ex_act to get an idea on how to do this.

The second issue is solved by making it so that when you undisguise that the OnCrossed proc is called. Currently the proc that undisguises uses a direct loc assignment:

```
/obj/effect/dummy/chameleon/proc/activate(var/obj/O, var/mob/M, new_icon, new_iconstate, new_overlays, new_underlays, var/obj/item/chameleon/C)
    name = O.name
    ...
    M.loc = src
    master = C
    master.active_dummy = src
```
forceMove should fix this I believe. 

All in all a good first issue to pick up using this analysis. And if you need some help feel free to PM me on discord or ask a question here!

**Comment by Henri215** [comment]
![image](https://user-images.githubusercontent.com/77684085/235455300-02063831-81da-4ea9-9c09-f319254400e1.png)
Tested, its still a thing.
