### ISSUE TITLE
IPC core moves to head when Clowning event eats him

### ISSUE THREAD

**Issue by hunakos57** [ParadiseSS13/Paradise#12025]
**Problem Description**:
What is the problem?
The IPC core is located in the torso, but this event moved it to the head.

**What did you expect to happen**: 
Why do you think this is an issue?
That it stays in the torso.

**What happened instead**:
How is what happened different from what you expected?
It moved into the head.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Well, I think nobody knows about this and if the IPC head goes missing so is the brain if they only save the torso.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Trigger green clown eating and transforming a crew member who is an IPC

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
When the event ended and gibbed the IPC body that was turned into a green clown,

**Comment by taukausanake** [comment]
> green clown

Not nearly as funny as mega Vox. But I think the Cluwne is meant to be like a different specie? At least a human that is designed to only suffer. It would make sense that an IPC would be turned into a human if that's what the cluwne is

**Comment by hunakos57** [comment]
So.. It turns out it also turned the IPC core into a brain

**Comment by hunakos57** [comment]
> > green clown
> 
> Not nearly as funny as mega Vox. But I think the Cluwne is meant to be like a different specie? At least a human that is designed to only suffer. It would make sense that an IPC would be turned into a human if that's what the cluwne is

The IPC stayed IPC, but it looks rather fat.

**Comment by taukausanake** [comment]
Are you sure the mob was still an IPC? I don't know how the cluwneing process goes but it could have made the mob a human. Not that it might matter as the gear that gets placed on you can't be removed so you might not be able to tell easily

**Comment by SomeSortaSquid** [comment]
Cluwning is effectively removal of the character from the round. Any successful recovery is an exploit.
It turns your mob into a monstrosity code-wise, you are sort of still your race, sort of cluwne.
I.e. slimepeople die instantly from cluwning, because of their brain damage modifier. When I was looking for possible ways of making slimepeople survive it, the conclusion was that it's pointless. Cluwnes are not supposed to live, anyway.

This issue, however, probably should be addressed. Recently I have had a similar case (cluwned IPC). The only reason I knew why the brain is missing and where to look for it was because I know cluwne code. Others might not. Cyborg analyzers not detective organic brain in an IPC does not help. Their head likely falling off does not help, either.
And cluwnes should still be viable candidates for borging.
I'm sure everyone is happy about IPCs needing more snowflake code.

**Comment by taukausanake** [comment]
If cluwning is such that it removes you from the round then wouldn't the solution be to just turn the effected mob into a full cluwne mob? They're already effectively dead, what does it matter what happens to their body? Why keep it the same as their old one? Just make a full cluwne mob conversion and that solves any problems races might have.

> Cluwnes are not supposed to live

> cluwnes should still be viable candidates for borging

Contradiction much? I kind of get what you are saying but I feel it's wrong.
"You are turned into a monstrosity that is not meant to live. You are effectively dead and basically removed from the round"
"Oh, but here's a way out of it too just in case, you know, you don't like suffering"
I still think that a cluwne brain should auto-apply a Cluwne module for cyborgs. Their suffering isn't meant to end, isn't it?

**Comment by DGamerL** [comment]
Heya, just like Gatchapod said, Cluwnes are a monstrosity. Having the posibrain magically move into the head is the least of it's worries. Being cluwned makes you into a cluwne species aswell, which is what causes the moving and the transformation from the posibrain into a normal brain.
If you have any other questions, feel free to reach out to me via Discord. Thanks for making this report!
