### ISSUE TITLE
People with ' in there name can not be orbited from orbit menu.

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#12031]
**Problem Description**:
What is the problem?
People with ' in there name can not be orbited from orbit menu.

**What did you expect to happen**: 
Why do you think this is an issue?
To be able to orbit them and see where they are.

**What happened instead**:
How is what happened different from what you expected?
You stay with you are, and can not orbit them.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Ghosts can not orbit the people without clicking on what they are saying.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Make a person with an id card / name that has an ' , for example "Bobb'y name
**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
Day or two ago
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

**Comment by datlo** [comment]
Related issue that was fixed : #11803 

Basically the same bug except for the teleport to area verb for ghosts.

PR that fixed it : #11806

**Comment by craftxbox** [comment]
This is something to do with unbalanced HTML or ASCII/UTF en/decodes, Judging by the ACTUAL appearance of names with special characters in the menu. ex, for ' you get `&%2339;`. This shows that in fact, there are two mismatches somewhere as ' encodes to `&#39;` not `&%2339;`, and in fact, # is what encodes as `%23`. This gives me the thought that somewhere it's actually both occurring in the line and not getting fixed by the time the client submits their choice, ending up with a mismatch between what the client sent and the server has.
