### ISSUE TITLE
Teleporter Construction Issues

### ISSUE THREAD

**Issue by VeteranKyl** [ParadiseSS13/Paradise#12123]
**Issue Description**:
Teleporters seem to have a lot of issues when it comes to constructing them. Once set up, issues can crop up in a few different ways.
- The teleporter console gives an error message about the teleporter station coming back as a null value.
- The teleporter station becomes un-interactable with no error message appearing.
- The teleport station gives an error message saying there's no destination selected, even after selecting a target and calibration finishes.
- Unable to transfer teleporter data in order to set up a gateway between two teleporters.

**What did you expect to happen**: 
It should be possible to set up the console, station, and gate all next to each other and have it working right away.

**What happened instead**:
With the many errors and bugs, it's nearly impossible to construct a new teleporter from scratch without these bugs and errors occurring.

**Why is this bad/What are the consequences**:
This can completely ruin a person's ability to build a teleporter. If one of the station's teleporters get destroyed, it may not be possible to replace it. If a traitor is trying to make one, it may just not work, wasting their time. Gates cant be set up, so connecting two locations, potentially across z-levels, through teleporters doesn't work.

**Steps to reproduce the problem**:
Construct a teleporter setup from scratch. Console, station, and gate. It may be possible this is an issue with z-levels, although I've had this occur while on the station.

**When did the problem start happening**:
A least a few month. These bugs seem to randomly occur at times, so it's hard to tell if it's suddenly been fixed or not.

**Extra information**:
These bugs has appeared on all Z-levels for me. Even replacing destroyed teleporters in the same spot they previously were sometimes has these issues.

**Comment by Shadow-Quill** [comment]
`The teleporter console gives an error message about the teleporter station coming back as a null value.`

You constructed the teleporter without the hub touching the power station.
Like this:
![image](https://user-images.githubusercontent.com/44811257/63908371-98839f00-c9e4-11e9-9769-46cf347df01e.png)

`The teleporter station becomes un-interactable with no error message appearing.`

If you mean like this: 
![image](https://user-images.githubusercontent.com/44811257/63908395-a9ccab80-c9e4-11e9-89d9-369fa3afcd34.png)
Then it's because you constructed the teleporter without the console touching the power station.
Like this:
![image](https://user-images.githubusercontent.com/44811257/63908491-e8fafc80-c9e4-11e9-9a13-476a62a0d9f9.png)
Or this:
![image](https://user-images.githubusercontent.com/44811257/63908500-f1ebce00-c9e4-11e9-8547-38bacaa15fb2.png)

`The teleport station gives an error message saying there's no destination selected, even after selecting a target and calibration finishes.`

I couldn't reproduce this. Elaborate?

`Unable to transfer teleporter data in order to set up a gateway between two teleporters.`

Couldn't reproduce. Both teleporters **must** be functional.

<hr>

In order to create a functional teleporter, the console must be touching the power station, which must be touching the hub.
Such as:
![image](https://user-images.githubusercontent.com/44811257/63908670-9f5ee180-c9e5-11e9-82d4-415fccbe3fee.png)
Or:
![image](https://user-images.githubusercontent.com/44811257/63908694-b1d91b00-c9e5-11e9-9502-783319827912.png)

**Comment by AdvnetureDrake** [comment]
I've never built the teleporter any other way than the correct way you show at the bottom of your reply. I may need time to get you images of the error messages, but I assure you that every error I listed has been with the correct setup.

**Comment by Citinited** [comment]
Did you link the hub and the station using a set of wirecutters?

**Comment by AdvnetureDrake** [comment]
Alright. I seem to of figured out what was causing some of the the bugs and the issues. 
- If the teleporter station isn't connected to the console, you get this message.
![Teleporter Console Error 2](https://user-images.githubusercontent.com/27029989/63995637-7eb28c80-cab6-11e9-8976-d81c6b756626.PNG)
- If the station isn't connected to the gate, no error message comes up when you try to start it.
- The 'No destination selected' issues seems to be random. Sometimes, even with all the machines connected, I still get that error message after choosing a target and calibrating.
- After a bit of fiddling, I got the gate mode working.
