### ISSUE TITLE
Eyes are Now Sometimes Weird Colors

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#12143]
@KasparoVy 

Players are apparently spawning in with incorrect/strange eye colors that are not what they set them to, on character setup.

Seems to have occurred ever since: https://github.com/ParadiseSS13/Paradise/pull/12114

**Comment by KasparoVy** [comment]
Are they simply brighter/darker or totally different colours?

**Comment by Fox-McCloud** [comment]
They were reporting totally different colors; someone said their character with black eyes spawned in with light blue---and another character that had green eyes spawned in with yellow. 

Another player said their eyes were pure white instead of dark blue.

**Comment by KasparoVy** [comment]
Ahh, I see what's going on. It seems that the overlays from `get_icon()` in `organ_icon.dm` don't actually carry over to `update_icons.dm` - the reason why only eyes appear to have issues is because eyes are the only thing `update_icons.dm` doesn't have it's own method of rendering

Why we're seeing light blue eyes, green eyes, yellow and light blue eyes is that they're what the eyes look like by default on the mob's sprites in `icons/mob/human_races/r_<species>.dmi`

- Humans, Vulpkanin and Tajaran default baked-in eye colour is green
- Unathi and Kidan default baked-in eye colour is yellow
- Grey have a very deep purple
- Drask have a lighter green
- Vox have a light blue

I tested with races that have darksight significant enough to shine, which 'papered over' this issue - I simply didn't test thoroughly enough
