### ISSUE TITLE
Dying On The Same Tick As Your Protector Holoparasite Dies Sends You To Null Space

### ISSUE THREAD

**Issue by Leanfrog** [ParadiseSS13/Paradise#12420]
**Issue Description**:
Getting hit with something that can kill you instantly while having a manifested protector type holoparasite sends you to null space

**What did you expect to happen**: 
To die and not end up in null space

**What happened instead**:
I went to null space

**Why is this bad/What are the consequences**:
It's not too important but it's still a glitch with the game and can permanently remove someone from the round without admin intervention

**Steps to reproduce the problem**:
Have a protector type guardian that is currently active and manifested, get hit with something that causes instant death (Wand of death being what caused this for me)

**When did the problem start happening**:
No clue, seems like it could've been an issue that went unnoticed for a long time due to its very specific requirements

**Extra information**:

**Comment by BakKeener** [comment]
Oh yeah I remember this one, we had a similar case when newcrit was well new... the holo user if I recall correctly recalled the holosite and the holosite happened to do at the same time and it sent him into nullspace and was only returned 20 minutes later with admin intervention, It might of been a protector type but I think it was a standard one... I believe the bug is tied  to newcrit.
