### ISSUE TITLE
Necrosis in vox organs.

### ISSUE THREAD

**Issue by Imotepchief** [ParadiseSS13/Paradise#12422]
**Issue Description**:
I died as a vox, a little time passed before they got around to treating me, so they had to use SR.
The SR brought me back, but I died again as they were too slow to correct the crit effects.
They tried to defib me to revive me again, but my heart was **Necrotic**

**What did you expect to happen**: 
Due to the recent changes, I expected the vox organs not to necrotize to SR.

**What happened instead**:
The vox organs became necrotic

**Why is this bad/What are the consequences**:
One of the new boons to vox, to replace low pressure immunity was to prevent organs from becoming necrotic, so now the balance is off.

**Steps to reproduce the problem**:
Have a vox be dead for 10 minutes, revive them with SR, let them die, then defib them.

**When did the problem start happening**:
Since the vox rework.

**Extra information**:

**Comment by KasparoVy** [comment]
Man we got fleeced so hard.

**Comment by Fox-McCloud** [comment]
This is intentional.

Vox organs are not meant to go necrotic from passive infection, such as surgery or having an open wound/not treating one for a while--likewise, their *internal* organs will not go necrotic while removed and sitting out of the body (external organs are a different story when unattached).

Likewise, semi-related, you will never skeletonize no matter how long you've been dead.

That said, they are, intentionally, not immune to strange reagent necrosis--dying is still meant to be somewhat of an ordeal and something you have to put *some* work into.
