### ISSUE TITLE
Can't break reinforced windows using brute melee attacks

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#12526]
**Issue Description**:
Hitting a reinforced window won't break it using brute weapons. I've tried a wrench, baton, fire extinguisher. None did any damage. Bullets did and a welder

**What did you expect to happen**: 
The window to break

**What happened instead**:
Had to use a welder to shatter glass

**Why is this bad/What are the consequences**:
No more emergency break ins

**Steps to reproduce the problem**:
1. Get brute weapon
2. Hit reinforced window
3. Get tired of clicking

**When did the problem start happening**:
Since #12245

**Comment by Fox-McCloud** [comment]
This was an intentional change.

As documented in the universal damage PR, there would be changes that would be missed. I tried to hit the high and low spots as best I could, but when you alter armor and integrity and damage behavior on close to 600 files, well, some things will be missed.

I'm not *super* attached to windows being stronger, but I do get the point.

We could make toolboxes stronger to help compensate, but if it's altered, it's not a huge deal, either.

pre-buff values: https://github.com/tgstation/tgstation/pull/45609

**Comment by Couls** [comment]
If we're going to increase their strength it makes no sense to leave them the same difficulty to deconstruct, I think it'd be better to also port the additional deconstruction steps or take them back to pre-buff values

**Comment by Mitchs98** [comment]
Personally I'd prefer putting them back to previous values. I didn't really have an issue with how they were before myself as any job, engineering or otherwise.
