### ISSUE TITLE
floor tiles can sometimes disappear

### ISSUE THREAD

**Issue by Couls** [ParadiseSS13/Paradise#12606]
**Issue Description**:

When placing floor tiles after prying up all the floor tiles you will end up with less than you initially pried out

**What did you expect to happen**: 

To be able to remove and replace all the floor tiles

**What happened instead**:

There were some unplated tiles in the end

**Why is this bad/What are the consequences**:

Floor tiles are deleting themselves

**Steps to reproduce the problem**:

Take a crowbar, remove a large patch of floor tiles anywhere on station, do not pick up all the floor tiles at once, pick them up one by one, stand over an floor tile item on the floor while holding one and place a floor tile anywhere, the one below you should disappear

**When did the problem start happening**:
No clue

**Extra information**:

**Comment by Citinited** [comment]
I've not looked at the code but my gut feeling is that tile stacking is to blame. I think it happens because the floor tile you are placing stacks with the one on the ground, which means you're actually moving two floor tiles to the plating. One gets used up in the floor tiling, and the other one gets deleted, for some reason.

**Comment by moxian** [comment]
Two minor quick notes:
- It happens not only to floor tiles but to anything you can place on the plating: Carpet, Rods, Cable coil
- When you are standing on top of a stack of items, and place something of the same type on the floor *the whole stack* disappears, not just a single item from the stack.

**Comment by moxian** [comment]
Okay, you're right, stacking IS to blame. To reproduce:

- Put some metal on the table, and some more on the floor under you.
- Take 1 sheet from the table in your right hand, and 1 sheet in your left hand.
- Stand on top of big metal stack
- With your left active hand click on the metal in your right hand to stack them
- Voila! You now have two metals in hand and zero underneath you!

**Comment by moxian** [comment]
I was too lazy to debug this normally, so instead i did the code archeology thing.

The problem was originally introduced in f133be6760fabd82030b2541d76654da3c9a2141 / #10962

However It manifested slightly differently at that time: when attempting to construct floor while standing over floor tile, the stack at your feet would NOT disappear, but the floor would not be built, and you'd get an extra 0-amount stack at your feet.

The two-hands method also does not eat the stack at the feet, but instead, again, creates a new 0-amount one.

Apparently there were more problems, so a fix was deployed in #10985, which brought us to where we are today.

This all doesn't make it any more clear how to fix the problem, but at least we now know that stacking code is terrible. Yay?..
