### ISSUE TITLE
Unable to Remove-Mito-Reimplant hearts to save a person.

### ISSUE THREAD

**Issue by Carthusia** [ParadiseSS13/Paradise#12719]
**Issue Description**:

Surgically removing a heart, to mito it to fix it, then reimplanting it, then defibing it, will result in its near instant decay to the point of it being to far gone.
This happens to normal hearts and cybernetic hearts.

**What did you expect to happen**: 

I expected their heart to restart like normal. It does not.

**What happened instead**:

Many times when i've defibed someone and their heart just crossed the threshold of decay, i've pulled them into surgery, removed it, mitoed it back to full health then reimplanted it. When you defib them, it states their heart has been corrected and everything is back to normal, but the health hud still shows them as being dead, their pulse never picked up, and by time you can attempt a second defib, the heart has completely rotted again, this has happened with cybernetic hearts to.

**Why is this bad/What are the consequences**:

It makes it impossible to attempt a heart repair in this way, as the game never lets the heart be fixed, it just dies instantly after being defibed.

**Steps to reproduce the problem**:

Take a body with a heart that has recently decayed to the point of no return, surgically remove it, mito it, reimplant the heart, defib it. 
The defib will say the heart rhythm has been corrected, but their BPM will never pick up, the health hud never shows that the were healed, and the heart seemingly instantly decays again back to where it started.

**When did the problem start happening**:

It's been happening for awhile, at least 2 months. It just doesn't come up that often as most times you can SR/SM or clone them back and fix them that way, but in scenarios where SR/SM and even cloning are not available or even an option, a mito heart fix is the only way to go, and at the current time seemingly doesn't work.

**Extra information**:

While im not 100% sure this is infact a bug, it really does seem like it is.

**Comment by moxian** [comment]
The problem here is that person takes massive oxy damage while their heart is out.
By the time you reimplant and defib them, they are in deep crit with -200+ oxy damage and stage 3 cardiac arrest.
Their heart does restart, but then very likely immediately stops due to cardiac arrest from untreated oxyloss.
The heart does *not* naturally decay from oxyloss.
Being in deep oxyloss means the *brain* takes damage, and this can (and does) manifest as person immediately dying once you defib them. This is probably what you were experiencing here.

Having epinephrine (both for oxyloss and for cardiac arrest treatment) in subject's system during the operation makes the whole endeavor much, much likely to succeed (but would likely still need to administer mannitol afterwards).
(And I can confirm that I wasn't able to perform this operation successfully without administering any chemicals).

**Comment by Carthusia** [comment]
Kind of confused at the first bit:
"The problem here is that person takes massive oxy damage while their heart is out."

Dead bodys take oxy damage?

Or do you mean the oxy damage that they have already received that caused their death and heart death, prevents this method of revival?

**Comment by moxian** [comment]
Oh, I thought you were operating on a still-alive subject (and I was experimenting on humanized monkeys, which are impossible to bring back to life after they are properly dead - defibbing does nothing).

But also, yes
> the oxy [and brain] damage that they have already received that caused their death and heart death, prevents this method of revival due to the instant redeath nature of the effect

But also, no
> no matter how much epi,saline,salb would be in the corpses system, the few seconds, if even that long they have after being defibed, wouldn't be enough to start to stabilize them

If they have salb/epi/manni in them at all, that should be enough to stabilize them after defibbing. They don't work inside dead bodies, yes, but once you bring the body back to life, they start working again. You might need several defib attempts, but one should give you some progress towards stability.

> but every single time the heart has died within seconds of implantation, cybernetic hearts included.

Are you sure it's the *heart* that dies in this situation? In my (limited) experience and testing, the heart does not really decay on its own, not even in dead bodies, and definitely not as fast as you describe. It's, rather, the brain damage.

Mini story time: The other day I took over treating a guy who seemingly couldn't be saved. I defib him - he dies within seconds. I pump him with epi/salglu, defib - he gets back to life but only for a moment. After doing this for some time and bringing him to near ~100% hp (since the chemicals do work for the short while he's alive), i drag him to health scanner, to see what's going on. Brain damage was going on. Administering manni pill, and defibbing once again brought him back to life proper.

**Comment by Carthusia** [comment]
I'll have to try pumping my next patient this occurs with an epi/saline/salb mixture to see if this will stabilize them.

I do think its the heart, as after I would defib them once the next defib would give that message along the line of "The heart has decayed beyond the point of defibrillation" Which was always odd because it was at most 10-15 seconds since implantation, but the REALLY odd bit that caught me entirely off guard was the fact it also did this to cybernetic hearts, freshly made from robotics/RnD.

**Comment by Carthusia** [comment]
I tried it again today with someone who had under 20 suffocation damage.

Injected them with over 10 salb,saline, and epi, defibbed. Same issue, their hud never goes from the dead skull to a pulse, yet it says they we're corrected and by the second defib, their heart had decayed to the point of being undefibabble.

**Comment by Imotepchief** [comment]
The heart beyond point of recovery thing, isn't actually the hearts issue now, its that they have passed the defib threshold and now either **have to be** cloned or SR'd

**Comment by Carthusia** [comment]
I thought there was no threshold? So long as the organs are healthy, they have blood, and their wounds are minor, and have the right chemicals in their system and they have a soul to return to the body in, shouldn't a defib still be possible?

The defib alerts you that the heart has decayed to a point it can't be defibed, if this is the case, if you remove it, mito it, then put it back in, I would assume this would solve the issue and enable a defib, as the message it plays after attempting this indicates a successful correction, but it never actually works, as the heart never restarts, and it immediately decays to the point of non use again. This is why this seems to be a bug to me, the defib itself tells you it worked, but it never does.

So long as a character has a working/healthy heart, shouldn't they be defibbable if the above parameters are met? Even cybernetic hearts have this decay effect, which seems odd.

**Comment by Imotepchief** [comment]
With the addition of new crit, defibbing was altered.
You have up to 2 minutes after a person has died to be able to defib them, after which time they have to be SR'd or cloned, defibbing is no longer possible, even if you were to give them a completely new set of organs (including brain), it is the body itself which is unrevivable, which doesn't make sense to me, but is how it is set.
The message you get about the heart being necrotic, isn't accurate, in that the heart can be completely fine, it is merely stating you have passed the defibbing timer.

**Comment by Carthusia** [comment]
weird, still seems like a bug or unintended effect that should be fixed, if fixing it is in fact possible.

**Comment by DGamerL** [comment]
The defib message on trying to revive someone isn't completely accurate. It is indeed saying the heart has necrosis, but it is moreso just a side-effect. If someone has been dead for longer than 5 minutes, you are supposed to either use Laz, clone them or put their brain in a substitute body.
