### ISSUE TITLE
Meteorshot can move basicly everything, including the safe, necropolis doors, and containent fields.

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#12727]
**Issue Description**:

Metorshot can basically move anything but the singularity and walls. This includes energy fields, such as containment, shields in the teleporter room, the vault safe, apcs, and the depot shields, all of which function the same as before, although damaged and moved

**What did you expect to happen**: 

To not be able to shoot holes in containment, or rearrange shields from the teleported halfway across the station

**What happened instead**:

You can do these things:
https://imgur.com/a/XZHGoiU
https://imgur.com/a/S63kFGQ
https://imgur.com/a/xDuied7

**Why is this bad/What are the consequences**:

Being able to move energy shields or other immovable objects is bad

**Steps to reproduce the problem**:

Get a shotgun
Get metorshot
Shoot something that shouldn't move
Watch it move

**When did the problem start happening**:

Probably forever

**Extra information**:

**Comment by Kyep** [comment]
@Fox-McCloud 
meteorshot was added all the way back in: https://github.com/ParadiseSS13/Paradise/pull/11
The code is here: https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/projectiles/projectile/bullets.dm#L201
The issue is that it throws ANYTHING that is /atom/movable, with no respect whatsoever for vars like anchored.
Yeah, its meant to be helpful breaching airlocks, but (A) it could just do that with damage, or a special effect on airlocks, and (B) we have tons of other things, like welders, thermite, etc for that now.

Probably best if meteorshot is just removed entirely, but failing that, it should at least be changed to not work on EVERYTHING.

**Comment by matttheficus** [comment]
Unsure if this still exists, will test later.

**Comment by Sirryan2002** [comment]
partially fixed in #17465

anything that we don't want flying off its hinges should have an INFINITY move_resist set. Note, maints/heads have in the past expressed that meteor shot blowing anchored structures off their hinges is intended, however, what is not intended is moving things that should never move, such as shields, beams, apcs, air alarms, the gateway, and more.

**Comment by Sirryan2002** [comment]
This is "resolved" in the sense that the original issue of it having no restrictions to fling shit off its anchors has been dialed back on. Currently it works on move_resist and can't fling important stuff likes APCs, Air Alarms, and any sort of energy barrier (containment, shield wall, etc) from its anchor point. Anything else it fair game however.
