### ISSUE TITLE
Fulltile Windows are broken

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#12777]
**Issue Description**:

Fulltile windows can no longer be interacted with at all.  This includes trying to pull them, use tools on them to secure them down/unsecure them, or trying to melee attack them.

**What did you expect to happen**: 

For players to be able to secure/unsecure/attack fulltile windows.

**What happened instead**:

You are unable to interact with fulltile windows at all besides shooting them at a distance.

**Why is this bad/What are the consequences**:

It prevents players from being able to use them in construction projects, remove them from locations they are already installed on, and could potentially be used exploit wise to block off people.

**Steps to reproduce the problem**:

Make a fulltile/reinforced fulltile window and try using tools, weapons, or pull it around.

**When did the problem start happening**:

My bet is this started with universal damage but went unnoticed due to how rare the windows are on the map and generally people use directional windows.

**Extra information**:

**Comment by Denthamos** [comment]
It would appear that round start windows are fine or ones admin spawned in, but if you create the window yourself using sheets then it does not work.

**Comment by KheaHyena** [comment]
I am actually very curious about this issue, because I'm of one those (if not the only one) that replaces all broken windows with full tile ones; I might even go the extra mile and use both directional and full tile on the same spot (a little trick allows you to). I simply like them best due to having armor, more hp, harder (read that as longer) to remove, you can visualize if they are damaged and actually have some explosion resistance according to the code (I only use reinforced, regular glass is weak in every way).

This to say that I have interacted many times with full tile windows and I never had an issue with deconstructing or building them.
I do realize that windows cannot be pulled (at least directional ones), though they can be pushed I think, from my experience at least. I have to experiment interacting more with them (pushing, pulling) to see how it goes in that aspect, it might be how the pulling mechanics work and how they move on each tile that prevented them from budging.

But attacking and interacting with them? Never had an issue myself. Did something change this last week?

**Comment by Denthamos** [comment]
Yea, its odd.  Most rounds the windows seem to be fully interactable but occasionally something just...breaks with them and I start getting ahelps about fulltile windows in general being un-interactable.  Not even sure what is going on with that, but I know Free also encountered the issue so its not just me.

**Comment by Kyep** [comment]
This seems like it was fixed awhile ago.

**Comment by Denthamos** [comment]
Did some testing and asked around, seems it was fixed by something randomly.  If it pops up again ill re open the bug report with more info.
