### ISSUE TITLE
Rolling antag causes you to ignore default role prefs

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#12771]
**Issue Description**:

If you roll antag and have 'be a civilian if preferences unavailable', you will be given a random job if none are available instead of being a civilian.

**What did you expect to happen**: 

Be a civilian since I didnt roll the jobs I wanted.

**What happened instead**:

I became a random job.

**Why is this bad/What are the consequences**:

Fairly edge case but this doesnt respect the user's preferences.

**Steps to reproduce the problem**:

1. roll antag 
2. dont roll any of your preferred roles, have civilian as default
3. dont get civilian but a random job

**When did the problem start happening**:

Probably an edge case thats always been there.

**Extra information**:

Happened today 3/12/2019 on live server.

**Comment by Cazdon** [comment]
iirc it ignores preferences because the 'return to lobby' preference would kinda break it.
Still, it can easily default to random job if they leave it on 'return to lobby.'

**Comment by Shockpoint** [comment]
This is intended, I believe.

Antag is rolled first, which obviously restricts you immediately from mindshielded roles. It then looks through your preferred roles that are left, and does the whole thing as usual. However, if those roles are filled, since you were successfully considered for antag, you are given a random job due to the game having already assigned you a place in the round, instead of your preferences being taken into account. 

And yes, Civilian can be full if there aren't enough security officers to manage the population.

**Comment by datlo** [comment]
Civilians cannot be full at roundstart, civvy limit is iirc only for latejoins. People who picks civilian will always get it. And people that defaults to civilian should also get the job, even in this edge case. This is caused by the logic ignoring your preferences when you roll antags to make sure you join the round and dont 'lose out' on your antag roll, but if you've selected 'civilian as default' you should get civilian.

**Comment by taukausanake** [comment]
Also, as edge case as this is there is the opportunity to use this meta-information and check against the jobs populating the server and how many there should be. If there is an extra Scientist at round start than there normally would be then you can make a good guess that the traitor/ling might be in that department. The same for any job as they all have hard limits
