### ISSUE TITLE
Cigars make you instantly addicted to nicotine

### ISSUE THREAD

**Issue by GreeyKorala** [ParadiseSS13/Paradise#13063]
**Issue Description**:

When smoking a cigar you immediately become final stage nicotine withdrawl.

**What did you expect to happen**: 

No idea

**What happened instead**:

It never made this happen before, the second you smoke the cigar now it's literally just instant addiction.

**Why is this bad/What are the consequences**:

It's not super important but it's rather annoying for people who have cigars on their characters normally.

**Steps to reproduce the problem**:

Smoke a cigar.

**When did the problem start happening**:

The latest PR.

**Extra information**:

**Comment by Fox-McCloud** [comment]
Melodrama has no place in issue reports and aren't appreciated.

(1) they don't make you "instantly addicted"
(2) You weren't at the max level of addiction "immediately".

Addiction was overhauled as per: https://github.com/ParadiseSS13/Paradise/pull/13034

I recommend reading over it. Nicotine being addictive is intentional, though the drawbacks are more minor compared to before.

My best advice is to either (1) Avoid smoking (2) Ensure you have a constant supply of nicotine to avoid withdrawl; keep on smoking the cigars or cigs---also keep an eye on cigs/cigars "losing their flavor"; when they have, the nicotine in them has run out.

It's likely the you were smoking it for a bit, and once you got addicted, you were ok---until the flavor ran out, then it hit you.
