### ISSUE TITLE
Flashbang deafness can last several minutes

### ISSUE THREAD

**Issue by Alriac** [ParadiseSS13/Paradise#13491]
**Issue Description**:
The deafness effect of multiple flashbangs accumulates an can last a very long time.

**What did you expect to happen**: 
The deafness expires in a reasonable time since the last flashbang you received.

**What happened instead**:
My character was deaf for more than 30 minutes.

**Why is this bad/What are the consequences**:
When security abuses flashbangs on someone, the deafness effect is so long that the prisioner can't communicate anymore and there is no way to cure it.

**Steps to reproduce the problem**:
1. Be an unknown in maints on green alert, wearing a gas mask.
2. Refuse to be searched by 5 officers that are patrolling in conga.
**3. Let them throw at least 10 flashbangs at you, all at the same time.**
4. You stay deaf for a very long time.

**When did the problem start happening**:
Maybe forever.

**Extra information**:
I will describe two occasions that this happened.
1. Some cargo boxes arrived to the station, it was an admin event. When I opened one, a lot of flashbangs came out and exploded, I stayed deaf for more than 10 minutes.
2. I was a perma prissioner. A few officers came in and started throwing flashbangs. I stayed deaf for more than 30 minutes until I ghosted.

**Comment by Fox-McCloud** [comment]
This isn't a bug.

Ear damage stacks and is cumulative. If you keep on receiving damage like this, yeah, it's going to last a really long time. It's why being in multiple explosions is nasty business (provided you survive).

100% intentional. Resting your ears with headphones will help---and receiving treatment with oculine is the way to correct this issue.
