### ISSUE TITLE
Lighting and power.

### ISSUE THREAD

**Issue by FireFlashie** [ParadiseSS13/Paradise#1371]
Lighting doesn't uses power.
![image](https://cloud.githubusercontent.com/assets/10612280/8310029/3f6103ee-19d6-11e5-948c-7a92e7adcdd0.png)

**Comment by Spacemanspark** [comment]
Were the lights in the area blown up?

**Comment by FireFlashie** [comment]
No, it was everywhere.

**Comment by veganzombeh** [comment]
This has been happening for a while. I've been assuming that lightning's power usage is just so negligible it rounds to 0. I'll check on that.

**Comment by Fox-McCloud** [comment]
Simple reason, actually: Bay commented out lighting taking power, when Ponies updated from Bay's lighting code regarding area power, this got commented out because Bay commented out....so we got that too, for whatever reason.

Either case, fairly easy to turn back on, but I'd like to tune and examine it a bit, as lighting is the #1 power drain for all non-Bay codebases.

I'm guessing Bay did this plus doubled their APC battery power so you could literally go like 2+ hours before having to set it up for RP reasons or something like that.

**Comment by PsiOmegaDelta** [comment]
That must have been forever and an epoc ago. The only period I'm aware that Bay-lighting didn't demand power was for very a brief period on the Dev branch during said powernet porting.

**Comment by KasparoVy** [comment]
Should probably close this
