### ISSUE TITLE
Repairing open airlocks

### ISSUE THREAD

**Issue by MarsM0nd** [ParadiseSS13/Paradise#13724]
**Issue Description**:

An airlock that is opened can is said to be getting repaired, but nothing will happen.

**What did you expect to happen**: 

Either to be told that you can't repair an open airlock, or to be able to finish the repairs

**What happened instead**:

You get the message that you start to repair the airlock, but the timer instantly stops.

**Why is this bad/What are the consequences**:

If a door gets broken while open, it'll be stuck open as the bolts will be dropped, and the broken state stops it from having power, making you unable to fix that without something to damage the door to replace it.

**Steps to reproduce the problem**:

Take any airlock and a weapon with enough force. Bolt open the airlock, and damage it past the integrity_failure threshold.

**Comment by Stealthii** [comment]
Assuming the logistical problems with repairing an airlock when it's not closed, I think the best solution here is to explicitly inform the user that an airlock must be closed in order to be repaired.

There is a degree of revised logic on tool use in TG upstream over the past year that may be a follow up to improving tool use in general on fixtures, but that represents a wider change that's probably out of scope for a bugfix.
