### ISSUE TITLE
Free Golem ship cannot be moved ("shuttle locked")

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#13844]
**Issue Description**:
Free Golem ship console displays "shuttle locked" and cannot be moved.

**What did you expect to happen**: 
Can be moved to at least one other location - or there not to be a shuttle console.

**What happened instead**:
As description.

**Why is this bad/What are the consequences**:
Confusing for golem players. Why cannot the shuttle be moved? How to fix it?

**Steps to reproduce the problem**:
1. Be free golem.
2. Interact with shuttle console
3. See "shuttle locked" message.

**When did the problem start happening**:
Likely with the PR that randomized space ruins

**Extra information**:
The free golem ship uses this list of docking ports: "freegolem_lavaland;freegolem_z5;freegolem_z6"
Freegolem_lavaland exists (on lavaland).
The other two no longer exist.
Since there's no other valid docking port, you just get the unhelpful "shuttle locked" error ingame.

**Comment by DevL-Whats-a-jpg** [comment]
This is still open however a week or two ago i played as a Golem, one of the other Golems was able to use the shuttle just fine (sent it to the USSP a few times) and i found i was to, not sure what round this was and also have not been a Golem since, so not sure if its fixed and this was just left open or what. If it isn't fixed then assuming that if the logs save that far back you might be able to find out what the difference was between that round and others, should be pretty easy as its (i'm pretty sure) the most recent time i was a Golem.

**Comment by TDSSS** [comment]
The locations the shuttle goes to (the USSP station) might just nto be a guaranteed spawn anymore, ie sometimes it spawns and sometimes it doesn't. There probably should be at least one guaranteed destination, though.
