### ISSUE TITLE
Teleporter Console Error

### ISSUE THREAD

**Issue by ProfTerrible** [ParadiseSS13/Paradise#13902]
**Issue Description**:

Interacting with the teleporter console while on NT medical shuttle causes an error, unable to get property 'powerstation' of undefined or null reference.

**What did you expect to happen**: 

teleporter console pop up that allows me to teleport to other beacons, presumably into the shielded syndi asteroid base nearby

**What happened instead**:

empty pop up and error message

**Why is this bad/What are the consequences**:

no teleport, no get in syndi base

**Steps to reproduce the problem**:

NT medical shuttle and syndi asteroid shielded base, teleporter setup on NT medical, interact with console.  Z-Level 5

**When did the problem start happening**:
7/23/2020 - 2am EST

**Extra information**:

**Comment by Kyep** [comment]
Additional info:
- This is not limited to white ship. It appears to be a general error with teleport consoles.
- "Teleporter" in this case means these 3 machines, left to right: /obj/machinery/computer/teleporter /obj/machinery/teleport/station /obj/machinery/teleport/hub
- It generates a runtime: Runtime in teleporter.dm,84: Cannot read null.calibrated
- This can be fixed by deleting/replacing the computer/teleporter, screwdrivering the hub, wirecutting it, then screwdrivering it again
- Regardless, non-connected machinery should not generate runtimes on use.
