### ISSUE TITLE
Records locker cannot be un-bolted.

### ISSUE THREAD

**Issue by DeveloperLoser** [ParadiseSS13/Paradise#14227]
**Issue Description**:
You cannot un-bolt the cabinet with everyone's records in the IAA office.

**What did you expect to happen**: 
The locker to be unbolted

**What happened instead**:
It just says you begin to but then does nothing

**Why is this bad/What are the consequences**:
Its not, just a random cabinet, albeit an immovable one

**Steps to reproduce the problem**:
Just use a wrench on the cabinet

**When did the problem start happening**:
Not sure, just encountered it.

**Extra information**:
Got Rusty Shackleford to try and un-bolt, same thing.

**Comment by Pennwick** [comment]
The records cabinet might not be finished. Due to its importance in the out of rotation Devil mode its probably not intended to be unboltable. If anything the bug is probably that the message/sound appear at all.

For its purpose it should be unmovable and nigh/fully indestructible. Though with the mode in the state it is I could see the cabinet just as easily being removed from the map instead. Admins can always spawn another one and it fills automatically.

**Comment by SabreML** [comment]
Fixed by #14616.
