### ISSUE TITLE
Dead ssd people does not stop being ssd when not ssd causing medbay to ignore them

### ISSUE THREAD

**Issue by ppi13** [ParadiseSS13/Paradise#14347]
**Issue Description**:

I have only been told of this issue, and don't really have methods to duplicate it.
But basically if someone dies while ssd, their ssd icon does not update if they stop being ssd.
And generally speaking, you don't fix ssd people, cause they are ya kno, ssd.

**What did you expect to happen**: 

I expected SSD people to stop being SSD when not.

**What happened instead**:

They appeared to be ssd when not

**Why is this bad/What are the consequences**:

First up, it's a bug, so thats by itself bad.
Secondly, you get ignored while dead.

**Steps to reproduce the problem**:

Not sure, but I guess
1. go ssd
2. die
3. get dragged to medbay
4. stop being ssd

**When did the problem start happening**:

Don't know.

**Extra information**:

**Comment by Kiyahitayika** [comment]
@ppi13 You shouldn't be getting killed while SSD. If you're SSD, you should have no expectation of coming back to the game alive. If you need to go SSD, you should go to Cryodorms.

However, I see your bug here. If you're not in your body once you come back from being SSD after you die, you can't be revived from being SSD. You're saying that once you come back from SSD and re-enter your body, it doesn't tell folks that you're no longer SSD. I think the issue is that it doesn't tell folks whether dead people are SSD in the first place either way.

**Comment by moxian** [comment]
I don't know how this works exactly, but i can confirm that dead SSD people exist.  I don't know if it's a big deal, but I can see how it can be confusing.
Screenshots (with/without MedHUD):
![dreamseeker-20201015-140619](https://user-images.githubusercontent.com/7831163/96350993-371b0580-10a8-11eb-9384-c037edbc6867.png)
![dreamseeker-20201015-140649](https://user-images.githubusercontent.com/7831163/96350994-384c3280-10a8-11eb-922c-da613ae1e409.png)

**Comment by ppi13** [comment]
Tested ingame and does not appear to be an issue. SSD people who are dead, are ssd cause they never reconnected after dying.

**Comment by moxian** [comment]
This is still a display issue though. We shouldn't be seeing ZZZ bubble on them if they are dead.
