### ISSUE TITLE
Legion Cores Burning Drasks When Used

### ISSUE THREAD

**Issue by Medium-Salad** [ParadiseSS13/Paradise#14362]
**Issue Description**:

When a Drask uses a legion core, the temperature reset passes the species threshold for overheat, causing burn damage.

**What did you expect to happen**: 

For a Drask to use a legion core and be reset to their specific species base body temperature.

**What happened instead**:

Drask gets overheated when using a legion core.

**Why is this bad/What are the consequences**:

This makes Drask as a species worse than they already are for mining, and causes an annoyance every time you use an item meant for specifically healing.

**Steps to reproduce the problem**:

Use a Legion Core as a Drask.

**Extra information**:

Not high priority whatsoever.

**Comment by Spacemanspark** [comment]
Maybe this should be made intentional tbh

It makes sense that a drask--something specifically meant to keep away from heat--is pretty boned in a place like lavaland.

**Comment by Kiyahitayika** [comment]
@Medium-Salad  @Spacemanspark  This is ... somewhat intentional. What I mean is that the way Drask is coded gives them specific heat resistance levels:
```	heat_level_1 = 300 //Default 360 - Higher is better
	heat_level_2 = 340 //Default 400
	heat_level_3 = 400 //Default 460
```
And then they take 200% damage from going over those `heat_levels`:
```heatmod = 2```

They would likely also take damage from other objects/weapons producing heat, such as the liquid cleaner from a Cleaning Grenade.

**Comment by Kiyahitayika** [comment]
Ah, going to reference Fox's comment in https://github.com/ParadiseSS13/Paradise/issues/13938
