### ISSUE TITLE
You can spawn into game with a cult ghost summon rune if you have antagHUD

### ISSUE THREAD

**Issue by kugamo** [ParadiseSS13/Paradise#14393]
**Issue Description**:
You can spawn into game with a cult ghost summon rune if you have antagHUD.

**What did you expect to happen**: 
Not be able to spawn in.

**What happened instead**:
You spawn in.

**Why is this bad/What are the consequences**:
You can play in game with restricted knowledge, and even worse the antagHUD is removed once you ghost again after spawning in. So its a means to remove the join restriction that is given with antagHUD, and to play any ghost role again.

**Steps to reproduce the problem**:
be a ghost, turn on antagHUD, respond to a cult ghost summon rune call.

**When did the problem start happening**:
No idea.

**Extra information**:

**Comment by enderman51505** [comment]
This also re-enables respawnability IIRC.

**Comment by Kyep** [comment]
@AffectedArc07 I don't think this should be considered a bug.
The purpose of stopping people from respawning if antaghud is enabled is to stop them validhunting the antags. If you're spawning in as a ghost on a cult summon rune, then you're a cultist, so you won't be validhunting the antags, and you get the cult hud, so you can see who they are anyway. So there's no point excluding antaghudded people from this.
I suppose the argument could be made that this is still a problem if you mix cult and other antag types - but due to limitations of the cult game mode, that's impossible. So right now, there's no reason not to allow this.

**Comment by AffectedArc07** [comment]
@Kyep I respectfully disagree. The whole point of antaghud is to lock people out of respawning entirely. It locks you out of maint drone even though you can barely validhunt as that role, it locks you out of random offstation ghost roles (as far as I know), and it even says in chat `You've given up your right to respawn!`

Making an exception for cult is snowflakey, and seems more like a legitimate bug to me.
