### ISSUE TITLE
Scyth not obliterating plant life as we know it

### ISSUE THREAD

**Issue by Asmerath** [ParadiseSS13/Paradise#14645]
**Issue Description**:

The Scythe that is obtained in the weed killer crate is not functioning as it should.

**What did you expect to happen**: 

The Scythe is supposed to one hit plants like glowchrooms, glowcaps, and space vines and clear them out in a 3x3

**What happened instead**:

The scythe takes 2-3 hits to kill a plant and does not clear out a 3x3

**Why is this bad/What are the consequences**:

the scythe exists for the purpose of clearing out plants such as vines and glowcaps/shrooms but instead a welder does a better job.

**Steps to reproduce the problem**:

hold a scythe, hit glowshorooms/glowcaps, or space vines with it.

**When did the problem start happening**:

not sure when, its been about a month sense I last used a scythe

**Extra information**:

thats about it

**Comment by moxian** [comment]
As it currently stands, scythes only work on space vines:

https://github.com/ParadiseSS13/Paradise/blob/2d498c72a3cab6414dd3e847a424fc44a10ef377/code/modules/hydroponics/hydroitemdefines.dm#L143-L144

Adding glowshrooms to the list is an easy change, but has obvious balance implications (not saying it's a *bad* thing, just that it needs some kind of backing from admins).

Making glowshrooms die in a single hit (instead of 2-3) also has balance implications (and only very slightly harder to implement in code - just qdel the thing on hit :upside_down_face: )

**Comment by variableundefined** [comment]
Feature request, closing
