### ISSUE TITLE
Simple mobs are cultable

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#14893]
Simple mobs like Ian are cultable. They should not be cultable. I added a check for this ages ago but something apparently keeps breaking it. Controabble moba, xenobio spawned sentient mobs, ghost spawn roles, and golems/IRC should not be cultable.
I am working a late shift I cannot dig into this right now.

**Comment by SabreML** [comment]
As far as I can tell there weren't any simple mob checks removed by Blood Cult, so if there was one in the first place it was changed a while ago.
This is the current code for checking if a mob is cultable or not:
```dm
/proc/is_convertable_to_cult(datum/mind/mind)
	if(!mind)
		return FALSE
	if(!mind.current)
		return FALSE
	if(is_sacrifice_target(mind))
		return FALSE
	if(iscultist(mind.current))
		return TRUE //If they're already in the cult, assume they are convertable
	if(mind.isholy)
		return FALSE
	if(ishuman(mind.current))
		var/mob/living/carbon/human/H = mind.current
		if(ismindshielded(H)) //mindshield protects against conversions unless removed
			return FALSE
	if(mind.offstation_role)
		return FALSE
	if(issilicon(mind.current))
		return FALSE //can't convert machines, that's ratvar's thing
	if(isguardian(mind.current))
		var/mob/living/simple_animal/hostile/guardian/G = mind.current
		if(!iscultist(G.summoner))
			return FALSE //can't convert it unless the owner is converted
	if(isgolem(mind.current))
		return FALSE
	return TRUE
```
Golems and ghost roles should be unconvertable right now, but stuff like xenobio monsters *(and Ian of course)* are still allowed.

In my opinion, while it's certainly a quick and easy way of getting more cultists it's balanced out by the fact that simple mobs can only cultspeak and activate runes, and more importantly that they count towards the Rise/Ascend threshold.

So a xenobiologist deciding to convert fifteen xenomorphs will most likely do more harm than good, since the whole cult will end up having a big 'I AM A CULTIST' sign floating over their heads.

**Comment by Aurorablade** [comment]
It was definitely removed or something was changed else where with the check cause it is seriously not intended

**Comment by Kyep** [comment]
@SabreML Does the halo work on non-carbon mobs?

**Comment by SabreML** [comment]
@Kyep 
No, it skips over them in order to avoid constructs getting a redundant halo.
I can see where you're going with this though, so I can change the check to `if(!construct)` or something.

**Comment by TheSardele** [comment]
I believe this PR caused this
https://github.com/ParadiseSS13/Paradise/pull/12571

**Comment by lolzyking** [comment]
For the longest time even in old cult you could cult simple mobs, no one ever did it since like mentioned, they can only activate runes created by other cultists. This has been forgotten by most as its pretty underwhelming and impractical.

The only time I've ever seen it used to success was a diona cultist using culted nymphs a year and a half ago to activate runes.

**Comment by Henri215** [comment]
Simple mobs can no longer be converted because of the https://github.com/ParadiseSS13/Paradise/pull/20008 PR, issue solved.
