### ISSUE TITLE
Heres a picture from TGUI problems

### ISSUE THREAD

**Issue by Jungling** [ParadiseSS13/Paradise#14933]
https://imgur.com/7jnq8KP
**Extra information**:
Was just walking around and had it pop up. No UI was actually open
I'm Tiyacha in game.   november 18th 2020 at around 8:35 EST is when it happened... idk round ID. 
Caused by using the bridge power monitor as an engineer through PDA. PDA is now this screen everytime I try to use it. :(

**Comment by Jungling** [comment]
Oh its from the PDA!

**Comment by moxian** [comment]
From the traceback, the exception is at
https://github.com/ParadiseSS13/Paradise/blob/cebc4b50ef9ca1a88f186c733ff1d64a6c1a5b53/tgui/packages/tgui/components/Icon.js#L15

Probably because (and thank you for mentioning the PDA bit!) something going wrong here https://github.com/ParadiseSS13/Paradise/blob/cebc4b50ef9ca1a88f186c733ff1d64a6c1a5b53/tgui/packages/tgui/interfaces/PDA.js#L55
Though i'm honestly unsure how pda interfaces are supposed to work, so can't see what exactly is wrong with them.

**Comment by S34NW** [comment]
PDA power monitors are broken like mad at the moment, see issue #14886 for another similar issue.

You can restore other PDA functionality by right-clicking and hitting "Reset PDA", just don't open the power menu again!

**Comment by stylemistake** [comment]
Icon name is null.
