### ISSUE TITLE
High radiation maint tile

### ISSUE THREAD

**Issue by ZanderDoggo** [ParadiseSS13/Paradise#15153]
**Issue Description**: There is a tile in EVA maints during high radiation that is not protected.

**What did you expect to happen**:  It should be protected as it is in maints.

**What happened instead**: The one tile of radiation in maints exists

**Why is this bad/What are the consequences**: It can be annoying because people can abuse an easily accessible tile of high radiation.

**Steps to reproduce the problem**: High radiation event

**When did the problem start happening**: Unknown, only noticed it a couple days ago

**Extra information**: File attached of where it is.
![BUG](https://user-images.githubusercontent.com/73790716/102702455-3a2aa180-4263-11eb-8dd3-3fbe8b875813.PNG)

**Comment by SabreML** [comment]
This is the issue:
![image](https://user-images.githubusercontent.com/57483089/102704800-dfe80b80-4277-11eb-97af-70146e2fe553.png)
That tile is in the 'Gateway' area rather than 'Maintenance'.

It would be pretty easy to fix, but since there's a mapping freeze at the moment it'll probably stay this way for a while.

**Comment by PacifistDalek** [comment]
Theres one in science maint as well, again probably for similar reasons mapping wise
