### ISSUE TITLE
The SM chamber APC is targeted by the APC shorted event

### ISSUE THREAD

**Issue by Kepplerx** [ParadiseSS13/Paradise#15394]
**Issue Description**:
The APC inside the SM chamber, is targeted by the APC shorted event, causing the air alarm to stop working and SM to delaminate.

**What did you expect to happen**: 
That the SM APC was protected from the event as the Engine APC was before, and thus would be unaffected.

**What happened instead**:
The SM APC went down, the air alarm stopped, and SM started to delaminate. This combined with  a Telecomms APC down meant SM started delaminating with no warning for a time.

**Why is this bad/What are the consequences**:
This event may cause a delamination, which I assume isnt what the event is meant to do, just as it was not meant to cause a loose engine in the past. As it is, using the event will always leave a risk of a delamination, which is a good reason not to trigger the event for admins, as well as an unexpected thing for the crew.

**Steps to reproduce the problem**:
Trigger the APC shorted event till the SM chamber APC is shorted, it should happen over some rolls.

**When did the problem start happening**:
Whenever the SM became the engine

**Extra information**:

**Comment by Kepplerx** [comment]
If this was meant to be, then this isnt a bug, but a feature, but it seems to me like an oversight at the moment

**Comment by TDSSS** [comment]
The SM is a much more forgiving engine than the old tesla or singulo, it it wasn't for a tcomms outage at the same time, I'm pretty sure that event would have not been that destructive, since engineering should have plenty of time to fix it. Personally, I'd say it's fine but we'll see what maints think.

**Comment by Kepplerx** [comment]
> The SM is a much more forgiving engine than the old tesla or singulo, it it wasn't for a tcomms outage at the same time, I'm pretty sure that event would have not been that destructive, since engineering should have plenty of time to fix it. Personally, I'd say it's fine but we'll see what maints think.

I dont think its a big issue either, but certainly something to think about when the event fires

**Comment by Kyep** [comment]
var/list/skipped_areas_apc = list(
 /area/engine/engineering,
 /area/turret_protected/ai)

/area/engine/engineering was protected from shorts.
The new /area/engine/supermatter area isn't.
Unsure if this was intentional.
I'd be surprised if this was intentional, given that the main engineering APC is still protected, its just the SM area (a new area) which isn't.
