### ISSUE TITLE
Shuttles let you create space on lavaland

### ISSUE THREAD

**Issue by Cocacolagua** [ParadiseSS13/Paradise#15460]
**Issue Description**:
Space tiles can be made in lavaland, even though the lavaland replacement of space is lava.

**What did you expect to happen**: 
For space tiles to be replaced with ash floor or lava.

**What happened instead**:
Space tiles in lavaland.

**Why is this bad/What are the consequences**:
MUH IMMERSION!!!!!
nothing major other than that, other than maybe more bugs that can happen due to that

**Steps to reproduce the problem**:
1. Deconstruct a tile in the mining shuttle / labor camp shuttle (probably golem shuttle as well) while on a z-level with space.
2. Move shuttle to lavaland.
3. Space in lavaland.

**When did the problem start happening**:
Since #15454

**Comment by Fox-McCloud** [comment]
This is actually not easy to solve; this isn't the result of the turf refactor--it was present before, it's just most people don't actually do destructive things with shuttle turfs---but if you blew a hole, in the floor, with a bomb, then this would have happened, too.

Not an easy fix---though it will be in future turf refactors---TG has an entire system of "baseturfs" instead of just a singular baseturf---in that way, you scrape away layers instead of just piercing through everything----so, in the case of the shuttle, there'd still be a hole in it, but it would be basalt underneath, instead of space.

**Comment by Kiyahitayika** [comment]
@Fox-McCloud 

I was able to replicate on a downstream server:

1. Deconstruct one of the windows in the Labor Camp Shuttle (RCD works great for this)
2. Deconstruct the Plating where the window was
3. Move the Labor Camp Shuttle to Lavaland
4. The space turf travels _with_ the Labor Camp shuttle

It looks like it could be fixed with mapping (something I do not know how to do) by replacing the destructible (simulated/floor/plating) turf under the windows on the Labor Camp shuttle with the appropriate indestructible ones you made.

**Comment by Fox-McCloud** [comment]
The fundamental issue is how the `baseturf` system works; ours is very simplistic, so anything that causes explosions or is an RCD or what have you just changes something to its baseturf status---likewise, when you move that turf, on a shuttle, it means that, yes, you're moving space.

TG solved this by having `baseturfs` be a list, as opposed to just a singular var, and they replace most behavior of `ChangeTurf(baseturf)` to `ScrapeAway`.

This removes a single turf layer, at a time.

So, a shuttle, for instance, will have quite a few layers--it'll have the shuttle turf, then the baseturfs of whatever is underneath it (plating, space, what have you).

That said, moving the shuttle manipulates this list, so if there's a hole in it, on station, that leads to space, then you move it to lavaland, it re-calculates what the baseturf list shoudl be, and instead of it being space, it's now just the lavaland surface.

It'll probably be part of the larger turf/open /turf/closed conversion----it'll also likely require a complete overhaul of the awful hellcode that is RCD's.
