### ISSUE TITLE
Perma Prison Hydro Trays

### ISSUE THREAD

**Issue by Goldenfield** [ParadiseSS13/Paradise#15494]
**Issue Description**:

The hydroponics trays in perma cannot be unhosed. how am i supposed to escape if they have some bullshit they makes them immediately hose again. i also noticed some graphical glitch where it didn't show the hose connecting the trays even though it was there and the description said so when examined. Please note this is for 3 of the 5 trays as 2 of the trays are not hosed and can be wrenched and moved.

**What did you expect to happen**: 

I CANT ESCAPE AFTER AN HOUR OF TRYING REEEEEE

**What happened instead**:

hydro trays in perma should work like all hydro trays and not special bullshit unmovable hydro trays.

**Why is this bad/What are the consequences**:

it reduces the amount of fun that can be had by preventing players from doing something they should be able to do with the game mechanics. i should be able to move those hydro trays. i cannot move those hydro trays. if you want perma to be unescapable just put reinforced walls or something.

**Steps to reproduce the problem**:

i broke a sec window to get a wrench and screwdriver, i then used both tools to repeatedly attempt to unwrench and move the trays, i used the screw on the tray and it opened it, i used the screw on the hose and it disappeared and then reappeared hosed again, sometimes the hose wouldnt show even though it had re-hosed.

**When did the problem start happening**:

dont know.

**Extra information**:

**Comment by S34NW** [comment]
To escape by the window, people break the hydroponics by throwing the cultivator at it repeatedly. Getting the wrench and screwdriver from outside seems like an odd way to go about it

**Comment by Gatchapod** [comment]
Hoses are controlled with wire cutters, not screwdrivers. You were just opening the hatch of machinery and I assume opened tray sprite overrides the one with a hose.

Perma was escapable even before you could just destroy the trays. Just because your one escape plan didn't work doesn't mean the cell cannot be escaped from. I won't lie, escaping into space is usually a suicide, anyway, so you didn't lose anything.

Overall, not an issue, just plain misunderstanding of game mechanics. Those are normal trays and you need wire cutters to remove those hoses.

**Comment by DeveloperLoser** [comment]
Fun fact for escaping perma however, monkey spam and boxes is alot of comedic fun.

Sec will never know which is you (but break the flash and injector, maybe make a blindfold to)

**Comment by matttheficus** [comment]
Does not seem to be an issue. Wrong tool was being used.
