### ISSUE TITLE
Crayon "Random Rune" button

### ISSUE THREAD

**Issue by PidgeyThePirate** [ParadiseSS13/Paradise#15670]
The "Random Rune" button on the crayon interface can pick runes 9 and 10 despite there being only eight runes.
When drawn the rune is present on the drawn surface but is invisible.

**What did you expect to happen**: 
"Random Rune" to max out at rune8.

**What happened instead**:
Maxes out at rune10.

**Why is this bad/What are the consequences**:
Minor inconsistency.

**Steps to reproduce the problem**:
1. Pick up crayon
2. Spam "Random rune" until you get rune9 or rune10
3. Draw

**When did the problem start happening**:
Probably after cult runes got their graphical update.

**Comment by SabreML** [comment]
This is happening due to this code here:
https://github.com/ParadiseSS13/Paradise/blob/fd79e342a841f628b584ebaf1a39ee1d00a4a64f/code/game/objects/items/crayons.dm#L71-L72
I fixed a similar issue above that when the crayon gets spawned in, but apparently I forgot to update the random rune thing.

This should probably be fixed in #15161 instead of a separate PR but I have no idea when that one is actually going to get merged so...
