### ISSUE TITLE
Wiped AI still makes cryo announcements in dchat

### ISSUE THREAD

**Issue by S34NW** [ParadiseSS13/Paradise#15694]
**Issue Description**:
Malf AI was carded and wiped, continued making cryo announcements in dchat.
Player who was the AI could still talk normally, and showed their name as normal, no name on whoever announces the cryo-ing.
Arrivals announcement continued without issue.
Cryo announcements stopped happening over in-round comms.
Clicking the core button shown below takes you to the player holding the intellicard that held the AI as it was wiped.
Issue persisted after a new AI was created.

**What did you expect to happen**: 
Wiped AI's should not make cryo announcements in dchat.
There should be an automated cryo announcement on common radio.

**When did the problem start happening**:
The circumstances for this to happen are hard to reproduce, I saw it on round 26124.

**Extra information**:
![image](https://user-images.githubusercontent.com/12197162/110528335-f16ee000-810f-11eb-9946-2fa84e9d4f8d.png)
![image](https://user-images.githubusercontent.com/12197162/110528923-8ffb4100-8110-11eb-9a18-4446acfc9bc5.png)

**Comment by dearmochi** [comment]
The issue is that when cryoing, the system loops through all AIs in the silicon mob list:
https://github.com/ParadiseSS13/Paradise/blob/ae3c63936b1405f9d63f66666dd6d08933d5666c/code/game/machinery/cryopod.dm#L434

It doesn't check if they're dead or not though, so this is why it's being said in dead chat.
