### ISSUE TITLE
Proto-kinetic not propelling you when fired

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#1596]
"Proto Accelerators can be used as infinite tools to navigate space , since every time you fire, it'll throw you in the opposite direction." quoting from the TG wiki

However, in practice, firing a proto-kinetic accelerator in the the same direction you are moving only halts your drift-- doing so again does not propel you in the other direction. Likewise if starting from rest and firing the proto, it doesn't propel you

**Comment by Fox-McCloud** [comment]
THis is because TG uses a different space movement system than what we have, where everything drifts through space---not just mobs--it also utilizes intertia and stuff like that.

In any event, this can't really be done without snowflaking it out, to be honest, so it's not something that will be happening any time soon. When this system is ported? Absolutely, but for now, sorry, it'll have to wait =/

**Comment by KasparoVy** [comment]
No worries it was just something I noticed and I figured a post should be made about it is all

**Comment by Spacemanspark** [comment]
ACTUALLY, it does work.
Use the arrow keys to move after firing.

**Comment by tigercat2000** [comment]
@Spacemanspark That's... uh... actually a bug if i recall correctly. Then again, it can be done with any projectile, so.
