### ISSUE TITLE
Kudzu mutating at 0 potency value.

### ISSUE THREAD

**Issue by HijackSpaghetti** [ParadiseSS13/Paradise#15985]
**Issue Description**: Kudzu mutating at 0 potency value.

**What did you expect to happen**: Kudzu not mutating at 0 potency value.

**What happened instead**: Kudzu mutating at 0 potency value.

**Why is this bad/What are the consequences**: Impossible to make reliable and benefical Kudzu.

**Steps to reproduce the problem**: Plant 0 potency Kudzu seed and wait for it to mutate.

**When did the problem start happening**: Anytime.

**Extra information**: https://github.com/ParadiseSS13/Paradise/blob/f0841b36294baccc2c5ac18678bd898defb8583d/code/modules/events/spacevine.dm - here we have 

by default 

`var/mutativeness = 1`

it changes when potency is not zero.

`if(potency != null && potency > 0)`
`		// 1 mutativeness at 10 potency`
`		// 4 mutativeness at 100 potency`
`		mutativeness = log(10, potency) ** 2`

as long as I can see, another "if"( or "else") is needed here
`if(potency = 0)`
`		mutativeness = 0`

**Comment by Sikroth** [comment]
Just for some insight, due to the fact that the mutativeness formula is a logarythm of the potency this means you can make a fully non-mutating kudzu it it has potency 1.

![image](https://user-images.githubusercontent.com/7857084/118162533-2a357900-b421-11eb-8d59-c91fdf22cc71.png)

It is a little counter intuitive, and I suspect it is also probably not intended, but I feel it is a very nifty feature to be able to make non mutating kudzu, so you can for instance grind for positive mutations and then change it to never mutate again.

If this is adressed/changed/fixed I would really hope Kudzu retains the ability to be made non-mutating, either at 1 or 0 potency.
