### ISSUE TITLE
Chaplain's Holy Constructs have incorrect sprite

### ISSUE THREAD

**Issue by ungauss** [ParadiseSS13/Paradise#16022]
**Issue Description**:
Chaplain constructs have the "blood cult" red sprites and not the blueish sprites (previously used for Reaper cult https://github.com/ParadiseSS13/Paradise/pull/12513)

**What did you expect to happen**: 
Chaplain constructs to be distinct from cult constructs since they have an entirely different origin and alignment.

**What happened instead**:
Chaplain constructs look exactly like cult constructs expect for a faint blue glow.

**Why is this bad/What are the consequences**:
It's impossible to tell if a juggernaut is trying to kill you or just looking to chat. Everyone on station was very confused and security killed most of the holy constructs.

**Steps to reproduce the problem**:
Create any holy construct. Observe the wrong sprite.

**When did the problem start happening**:
The constructs had the "reaper" sprites around 3 weeks ago.

**Comment by hal9000PR** [comment]
They use the same sprite as the god of the shift. So it is random each shift.

**Comment by ungauss** [comment]
Is Reaper cult enabled now?

**Comment by ungauss** [comment]
Everyone on Discord is saying I'm wrong, so my memory must be faulty. Apologies.

**Comment by SabreML** [comment]
There's three different Cult 'flavours' currently: Blood, Fire, and Death.

All of them have fancy different sprites for constructs as well as other things, and holy constructs just use the same sprites as the cultist ones.
It'd definitely be great if there *were* separate sprites for holy constructs (especially since as you said it can get pretty confusing sometimes), but currently there's not, so a slight blue tint will have to do unfortunately.
