### ISSUE TITLE
The drone fabricator sometimes just spawns an 'Inactive' drone with no mind

### ISSUE THREAD

**Issue by SabreML** [ParadiseSS13/Paradise#16103]
**Issue Description**:
The maintenance drone fabricator sometimes forgets to transfer the ghost into the new maintenance drone, causing them all to be 'Inactive'.

**What did you expect to happen**:
Click 'Join As Drone', and you'd spawn as a maintenance drone.

**What happened instead**:
The maintenance drone spawns, but you're never actually transferred into it.
![image](https://user-images.githubusercontent.com/57483089/119886588-072fbc80-bf2b-11eb-83e7-1c817a7855bf.png)
*(Looks like they just disconnected, but I've had this happen to me before too.)*

**Why is this bad/What are the consequences**:
It triggers the cooldown to make another maintenance drone and confuses ghosts and engineers.

**Steps to reproduce the problem**:
Honestly unsure. I've never been able to reproduce it locally but I see it once every couple of weeks on live.

Possible steps are:
- Spawn as a crew member and die
- Attempt to spawn as a maintenance drone

**When did the problem start happening**:
Also no idea here since it's so inconsistent.

**Extra information**:
@Qwertyotoforty said there weren't any related runtimes when I asked about it so it might just be a check failing or something.
Round ID 27126.

**Comment by Citinited** [comment]
Round ID: 27283
This happened today to me. I had spawned as a drone previously in the round, however at some point during the round it seems to have broken (I was a ghost instead of an observer when it failed). I was able to spam the "Respawn as drone" button (The prompt to play as a drone succeeded), creating multiple inactive drones.

Think the issue may arise in this block of code:

https://github.com/ParadiseSS13/Paradise/blob/dfa17e9d0797284746af47d60147681a23ad4a68/code/modules/mob/living/silicon/robot/drone/drone.dm#L299-L307

**Comment by WesleySmites** [comment]
This occurred with me today as well. After confirming I want to be a drone, a drone body is created but I remain a ghost. I was initially a player in this round.
