### ISSUE TITLE
Movement Speed bug

### ISSUE THREAD

**Issue by streather** [ParadiseSS13/Paradise#16131]
**Issue Description**:

If you walk diagonally into a surface like a wall you walk faster than if you walk in a straight line.

**What did you expect to happen**: 

I'd have thought it wouldn't have any effect on movement speed or be slightly slower

**What happened instead**:

Movement speed is increased

**Why is this bad/What are the consequences**:

It's not really an issue as such, more an observation I guess.

**Steps to reproduce the problem**:

Have movement speed set to run, find a wall and walk diagonally into it.

**When did the problem start happening**:

It started when diagonal movement got added but I've only just got around to raising it as a bug report

**Extra information**:

**Comment by ppi13** [comment]
Not a bug per say, this is due to an inherent limitation of this being a rectangular-tilebased game, where up, down, left and right are moving a single tile, but top-left, top-right, bottom-left and bottom-right is moving two tiles.
moving diagonally is slightly faster then moving two tiles normally, which is what causes this.

**Comment by AffectedArc07** [comment]
You move faster visually, but should not move faster in actual fact. If you can back this up with evidence however I would appreciate it.

**Comment by ppi13** [comment]
If you wear a hardsuit, or have some other slowdown, you can move at normal speeds that way.

**Comment by moxian** [comment]
Evidence: https://www.youtube.com/watch?v=M1bCc9Jm7fo

**Comment by dj-34** [comment]
Yes, such a problem exists, but it's not really a BUG, but a bad implementation of gliding (or something like that) and just visual. This has been fixed in the old-old RU Paradise fork and on TG.
We have implemented a basic glide fix on our downstream, but it's not the best way to do it.
Here is our "fix" that was reverted due to non-modular implementation:
https://github.com/ss220club/Paradise-SS220/pull/73
https://github.com/ss220club/Paradise-SS220/pull/81
https://github.com/ss220club/Paradise-SS220/pull/83
https://github.com/ss220club/Paradise-SS220/pull/108
https://github.com/ss220club/Paradise-SS220/pull/435
