### ISSUE TITLE
Staff of storms noise never stops

### ISSUE THREAD

**Issue by Herder05** [ParadiseSS13/Paradise#16238]
**Issue Description**:

when the staff of storms is used on station the noise after the storm goes on... and on... and on and please end it

**What did you expect to happen**: 

the noise to stop after a bit

**What happened instead**:

the noise has been going on for like hour

**Why is this bad/What are the consequences**:

my ears hurt

**Steps to reproduce the problem**:

staff of storms on station

**When did the problem start happening**:

dunno

**Extra information**:

**Comment by SabreML** [comment]
I ***know*** this is an issue, since I've had it happen to me a lot too, but I can't seem to reproduce it on a test server.

Attempt 1:
1. Started as a civilian, spawned a staff of storms and drake armour.
2. Activated the staff inside the sec checkpoint, and stood inside for the duration while wearing the armour.
3. Sound disappeared shortly after the storm did.

Attempt 2:
1. Same setup as attempt 1.
2. Activated the staff in the sec checkpoint, then dropped it and walked off to the bridge watching spot.
3. Sound disappeared shortly after the storm did.

Attempt 3:
1. Started as an observer, and spawned a staff of storms on the ground in the locker room, and a unathi next to it.
2. Flew to the RD's office, and called `attack_self()` on the staff with the unathi as the `user` argument.
3. Sound disappeared shortly after the storm did. (Also the unathi got husked)

**Comment by DGamerL** [comment]
The staff of storms was reworked in #21566 !
