### ISSUE TITLE
Deconstructing certain space ruins yields lava

### ISSUE THREAD

**Issue by JamieSS13** [ParadiseSS13/Paradise#16263]
**Issue Description**:
Deconstructing floors in certain ruins (i.e. mech transport ship) causes lava to appear beneath said floors

**What did you expect to happen**: 
I expected this to reveal lattice and space, rather than lava

**What happened instead**:
Deconstructing the floor revealed lava in a space ruin

**Why is this bad/What are the consequences**:
Deconstructing space ruins spawns lava in space. This should not be possible, even using SS13 logic

**Steps to reproduce the problem**:
1. Find a space ruin (in this case, the mech ship. unsure if this happens in other ruins)
2. Crowbar up floor tile (if applicable)
3. Use screwdriver/hand drill on plating
4. Use welder on loosened plating
5. See lava

**When did the problem start happening**:
N/A

**Extra information**:
N/A

**Comment by S34NW** [comment]
This is due to the area for these locations being a subtype of `/area/ruin`. (`area/ruin/powered` in the case of the mech transport ship.)
These areas are primarily used in lavaland and have a baseturf of lava.
This is a good first mapping PR for anyone interested, either make a new area with a different baseturf, or use a baseturf helper.
