### ISSUE TITLE
Dyeing a vulp makes them pure white

### ISSUE THREAD

**Issue by Herder05** [ParadiseSS13/Paradise#16314]
**Issue Description**:

when you use dye on a vulp they became pure white

**What did you expect to happen**: 

to become the colour I set

**What happened instead**:

I became pure bright white

**Why is this bad/What are the consequences**:

makes you stick out so if you were to try to be antag barber and change your fur colour you become the brightest thing in maints

**Steps to reproduce the problem**:

be vulp
be barber
use dye on body

**Comment by SabreML** [comment]
Don't seem to be able to reproduce the issue on my end. The fur colour gets set to whatever I pick in the 'Dye Generator' once I refill the bottle from it.
Are you sure that you set a colour in the machine *and* also refilled the bottle? It defaults to white, so that may have been the reason.
(If not, I'll try looking into it further)

**Comment by DGamerL** [comment]
Tested again, it indeed does work normally with any dye generator color. 
I assume that you indeed forgot to refill the hair dye bottle (which I can understand)
If this does stay being an issue, feel free to open a new report!
