### ISSUE TITLE
Radiation from the SM is heavily irradiating people well outside of the Supermatter chamber

### ISSUE THREAD

**Issue by Sirryan2002** [ParadiseSS13/Paradise#16349]
**Issue Description**:
Possibly Due to #16156 more likely due to #16147  , radiation from the SM is heavily irradiating people well outside of the SM chamber.

Despite taking all precautions: closing rad doors, keeping rad gear on in the chamber at all times, etc, considerable amounts of radiation have been found outside the SM chamber, reaching almost all the way to hardsuit storage. 

All the white painted tiles are places where radiation has been detected(mostly above 4k EER as well). This was tested on the live server. Player who reported it claims that this has happened multiple times in the past since the rad buff in the linked PR
![Image of Radiation spread](https://i.imgur.com/1hTtn3f.png) ![Image of Radiation spread](https://i.imgur.com/udP83gW.png)

**Steps to reproduce the problem**:
Turn on SM with a CO2 setup with some decent EER and watch Engineering slowly get irradiated.

**When did the problem start happening**:
When #16156 was merged

**Comment by hal9000PR** [comment]
Honestly, I'm fine with this. Running high power engines shouldnt be safe.

**Comment by Zergspower** [comment]
> Honestly, I'm fine with this. Running high power engines shouldnt be safe.

Except now it's doing it with basic N2, I think a mixture of 2 PR's have accidentally made engineering a deathtrap since we have a finite amount of suits and the hardsuits are trash (why?) with their rad plating.  it's also now going into the main lobby with lethal doses.

I'm not here to bash people who make changes, but the focus was seemingly to help with singularity stuff and wasn't reverted or worked on since after it was found out it altered engineerings bread and butter, and now another radiation tweak has made this super dangerous.  

Maybe make tweaks to the hardsuits? add shielding options to contain it within the SM Piping area? I dont see why it has to leech into surrounding maints/space/lobby as just getting to a radiation suit irradiates you fairly decently.

**Comment by ppi13** [comment]
#16147 has been reverted
#16156 only touched singularity
Is this still an issue?

**Comment by LtGerbal** [comment]
> #16147 has been reverted #16156 only touched singularity Is this still an issue?

Yes. Radiation is still going much farther than it should.
