### ISSUE TITLE
Unloading a mulebot created a ID card from thin air

### ISSUE THREAD

**Issue by michaelyesok** [ParadiseSS13/Paradise#16367]
**Issue Description**:

After i unloaded a collector crate named 2 via the mulebot app it created a ID from thin air

**What did you expect to happen**: 

Because you should not be able to create ID's from thin air

**What happened instead**:

A ID with nothing on it was created from thin air

**Why is this bad/What are the consequences**:

This is pretty immersion breaking.

**Steps to reproduce the problem**:

Order collector crate named 2
Put on mulebot
Unload mulebot via PDA app
Now you have a ID from thin air

**When did the problem start happening**:

No idea.

**Extra information**:

**Comment by SabreML** [comment]
Presumably this was the mulebot's internal ID card falling out if it was empty, although I'm not sure how that could happen.
The unload proc loops through every item in the mulebot's contents at the end, but it has a check specifically to avoid the `access_card`.
I'm thinking this was either caused by a runtime, or the access card got unset somehow.
https://github.com/ParadiseSS13/Paradise/blob/dc9ce6dad727e9ad26a85a2b812ce09a6bec63e3/code/modules/mob/living/simple_animal/bot/mulebot.dm#L437-L444
