### ISSUE TITLE
Flowering Kudzu pods and mobs take damage from Thorny trait

### ISSUE THREAD

**Issue by Ionward** [ParadiseSS13/Paradise#16381]
**Issue Description**:

As title says, the Thorny trait on Space Vines is damaging everything in contact with it, even its own mobs and flowering pods, which seems like an oversight. 

**What did you expect to happen**: 

Spawned space vines manually as an event, added all the traits listed, and lo and behold no mantraps roaming the kudzu.

**What happened instead**:

The flowerpods do not survive their gestation process and mantraps had to be manually spawned, which were also damaged by standing in thorny kudzu.

**Why is this bad/What are the consequences**:

These traits should not conflict and cause plants it creates to die to thorns it creates as well, it doesn't make sense for a plant and doesn't make sense game-mechanically.

**Steps to reproduce the problem**:

![dreamseeker_kbyAZEHJto](https://user-images.githubusercontent.com/25335231/126033605-a148f19d-ee3d-4256-997d-6f4eb1ee01af.png)
The traits on the kudzu. Admins forced the space vines event, applied these, and got damaged flowers.

**When did the problem start happening**:

Found at the date of posting.

**Extra information**:

**Comment by SabreML** [comment]
It seems to be the 'aggressive spreading' trait that's doing this rather than 'thorny'.

Both damage procs from the thorny mutation have an `isvineimmune()` check in them, which checks for the "vines" or "plants" factions:
https://github.com/ParadiseSS13/Paradise/blob/dc9ce6dad727e9ad26a85a2b812ce09a6bec63e3/code/modules/events/spacevine.dm#L301-L312 https://github.com/ParadiseSS13/Paradise/blob/dc9ce6dad727e9ad26a85a2b812ce09a6bec63e3/code/modules/events/spacevine.dm#L699-L704
Venus human traps have both of those factions added inherently, so they shouldn't ever be able to take damage unless their faction was edited somehow.
https://github.com/ParadiseSS13/Paradise/blob/dc9ce6dad727e9ad26a85a2b812ce09a6bec63e3/code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm#L65

Aggressive spreading on the other hand, only checks to see if the target is a space vine specifically, and if it's not then it calls `ex_act()` on it.
https://github.com/ParadiseSS13/Paradise/blob/dc9ce6dad727e9ad26a85a2b812ce09a6bec63e3/code/modules/events/spacevine.dm#L270-L281
