### ISSUE TITLE
joining the server before the world is done initializing generates 80000+ms lag on pressing movement keys

### ISSUE THREAD

**Issue by pinatacolada** [ParadiseSS13/Paradise#16671]
This happened 2 or 3 times to me before, staff I caught each time reported it was just me

Last time this happened was round ID 28395.

Previous round just stay in lobby, don't observe, don't join, don't anything, everything is working fine judging by the chat.
Round ends, automatically joined next round, joined server while it was initializing, very early in the initializing process, like before the red text even shows up early.
I'm not entirely sure but I may have declared ready at this point. I am certain I did at least one of the times this happened.
Server finishes initialization process, game eventually starts, immediately 300ms of lag, hair takes around 10 seconds to show up on each character, lightning flickers and sometimes is either full white or full black, movement keys get sticky, like pressing and releasing left will stay going left for an entire minute.
Standing still eventually get ping of around 100-300ms. Pressing a movement key instantly breaks everything.
5000ms ping at this point. Closing and reopening the game no change. Closing and reopening the entire byond, no change. 
Clearing cache and rejoining, lag is now 80000ms.
Doing File->Reconnect, lag stays at 80000ms, chat doesn't load at all. I can still use F1 to send admin helps, the sending and receiving sounds play, but there's no chat at all to read.
Restarting the computer and rejoining, chat is back, still 80000ms of ping on movement, even as a ghost.
Joining a different server, everything is ok. Rejoining para, back to 80000ms ping.

All other programs and internet in general were perfectly fine, I was even on a discord call with 10 people at one point.

byond is version 514.1566, this happened on previous versions too, unsure which though, but recently, maybe April-May

**Comment by AffectedArc07** [comment]
So you're wondering why the server lags and takes a bit to stabilise right in the middle of the init process, where the CPU is pegged at 100 for a minute straight.


You still getting lag after all of this is not something we can fix in code, we can't touch stuff that far down. I also haven't heard any other reports of this so I am chalking this up as a BYOND issue and something that's wrong on your end, due to no one else discussing this. 


Out of curiosity, what is your download speed on Speedtest.net, because if the game is redownloading assets, of course it's going to be slow, since your connection is maxed and there won't be enough bandwidth to send your movement and chat packets back. 

Closing due to not being something we control, or something that affects others.

**Comment by pinatacolada** [comment]
Its not hyperbole, the chat ping thing really showed 80000. 
I didnt do a speed test, but like I said, everything else worked fine so Id expect the speed test to be fine.
I would suggest that whatever automatically reconnects you after round end only do so after an introduced delay, so it doesnt connect before the server is ready. This is not something the players have control over, and if it happens then, apparently, thats it round over nothing the player can do

**Comment by AffectedArc07** [comment]
> Its not hyperbole, the chat ping thing really showed 80000.
> 80000+ms lag on pressing movement keys

Chat ping and movement are completely different. Chat ping is an approximation thats only calculated every 30 seconds, and the way its calculated is by clicking an invisible link in chat then waiting for the round trip, which is often 10ms higher because of client JS encoding/decoding, not to mention server throttling. You can have a 10,000ms chat delay, but have movement still be fluid because of how its calculated. If your chat ping calculation is, I dont know, **during a period of mass server lag such as world init**, its going to show much higher. However, after that lag period, the game is running at much lower CPU and movement is fluid, even if the chat ping is showing as higher, due to how its calculated.

> I would suggest that whatever automatically reconnects you after round end only do so after an introduced delay, so it doesnt connect before the server is ready. This is not something the players have control over, and if it happens then, apparently, thats it round over nothing the player can do

Except everyone else seems to be able to play just fine and this issue only affects you. Declaring ready wont affect this at all, since it just sticks `ready=1` on your client. Nothing in our code dictates whether you get higher ping or not. Thats entirely network related. 

You can join either right in the middle of the round or before the SS init text has even appeared, and your ping throughout the game will be the same regardless of when you join. Thats not how it works.

**Comment by pinatacolada** [comment]
well then that suggests that this happens on joining the server at that time. 
regardless of how ping is calculated, the latency is there. on one occasion my character was handcuffed and I kept getting the 'you can't move because you're handcuffed' messages for a solid 30 seconds after releasing the movement key.
and just to be clear, the lag isn't the one from server initialization, this lag stays for the entirety of the round, beyond restarting computers and routers, and is magnitudes larger that the init one.
also, this started happening around april-may, maybe june. Before, if I joined the server before init everything was fine, and there were no changes on my side since, aside from updating byond (it was happening on both versions anyway)

i understand i'm the only one experiencing this and its justifiable to have this closed and all that, but just keep the knowledge this is a thing that is happening
