### ISSUE TITLE
[Aliens] Spawning as alien causes crash

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#1671]
Spawning as an alien from ghost with full dark vision on causes byond to crash when it begins to adjust your view to alien vision.

**Comment by TheDZD** [comment]
Need to try and replicate this, but if it is consistent, it means we have another annoying BYOND issue similar to what used to happen with lighting because of problems with animate().

**Comment by Markolie** [comment]
I tried fixing it today, and couldn't reproduce it locally. Not through transforming myself, assuming direct control of a larva, having a host explode and pick me when I'm ghosted or through having myself explode and it picking me anyway.

However, this is definitely an issue, because on the live server I did crash during an Xeno round Neca made.

**Comment by Taaketa** [comment]
I think you have hit the nail on the head. I crash as I lose ghost vision and the body popping noise happens.

**Comment by Fox-McCloud** [comment]
This is likely caused by a number of things:

- Our lighting system
- Our increased view range
- BYOND issues 

Utilizing a beta version of 508 (I recommend 508.1292) helps cut down on the number of crashes, but doesn't eliminate them entirely.

**Comment by tigercat2000** [comment]
These crashes are more or less resolved now.

**Comment by Markolie** [comment]
Mhm, you sure? I believe I had the crash maybe a week ago?

**Comment by tigercat2000** [comment]
@Markolie Eh, like I said, more or less. They are waaaay less often after we killed transitions.

**Comment by Fox-McCloud** [comment]
Duplicate.
