### ISSUE TITLE
Revenants missing certain spells

### ISSUE THREAD

**Issue by Markolie** [ParadiseSS13/Paradise#1702]
@Fox-McCloud 

It seems that revenants are missing a number of spells in-game that are listed on the wiki (i.e. Seed of Draining). Is this intentional? On /tg/ these are available.

**Comment by Robertha89** [comment]
Essentially it was removed cause people cried op.

**Comment by Markolie** [comment]
Revenant as it is is boring as hell, in my opinion.

**Comment by Robertha89** [comment]
I agree. It is basicallt a minor annoyance. Not even worth to deal with. Especially since it got so lil health to begin with.

**Comment by TheDZD** [comment]
Not really sure what to tag this, but the reason the powers listed on the wiki aren't accurate to the ones available in-game is because we ported /tg/'s wiki page, which was already out of date when revenants were ported.

Originally, Revenants were a mini-antag ghosts could be shoved into due to random events, however they were largely nerfed and made to be a more passive in tgstation/-tg-station#9866.

**Comment by Markolie** [comment]
Their current code has the spells though, so that was reverted.

**Comment by TheDZD** [comment]
Err, do they? Can't find it in the [revenant_abilities.dm](https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/living/simple_animal/revenant/revenant_abilities.dm) file.

**Comment by Markolie** [comment]
Huh. I might've been on a fork then? Stupid of me. 

Might as well close this. Point stands though - revenants as is are somewhat useless.

**Comment by Fox-McCloud** [comment]
I can look into potentially re-adding some of the old abilities...because...right now, revenant is pretty much just: 

Run around safely draining bodies->wait until emergency shuttle->spam shock people to annoy them.

It's pretty boring for a mini-antag.

**Comment by Markolie** [comment]
@Fox-McCloud https://github.com/tgstation/-tg-station/pull/11187/files
