### ISSUE TITLE
Checking Law Manager of borg with syndicate MMI spams lawset message

### ISSUE THREAD

**Issue by iantine** [ParadiseSS13/Paradise#17855]
**Issue Description**:

When anyone with access (admin, the borg itself) checks the Law Manager of a borg made with the syndicate MMI, it spams the message _Lawset change detected. Syndicate override engaged._ to the borg.

**What did you expect to happen**: 

The borg not to be spammed with a message.

**What happened instead**:

Upon checking the law manager, the borg is spammed with the message.

**Why is this bad/What are the consequences**:

Confusing to the player.

**Steps to reproduce the problem**:

1. Be placed in a syndicate MMI.
2. Be placed in a borg shell.
3. Have someone check your Law Manager or do it yourself and keep the window open.

**When did the problem start happening**:

Since #15926 presumably

**Extra information**:

![image](https://user-images.githubusercontent.com/26665535/170044449-5bdd5a1b-4fee-455e-a08a-f285cd09627e.png)

**Comment by SteelSlayer** [comment]
Unable to reproduce. Tried checking the borg's laws using the Manage Silicon Laws verb, and also tried having the borg view their own law manager. No "Lawset change detected" messages appeared. Tried this with an engi-borg and also a blank borg without a module.

https://user-images.githubusercontent.com/42044220/174493011-7611ca65-ced9-4a82-aa9d-8a31176e585d.mp4

Any other conditions or information you can think of to help us reproduce this?

**Comment by moxian** [comment]
I'm not sure why it is not reproducing, but the code path is there:

https://github.com/ParadiseSS13/Paradise/blob/e5dac22f258d14ba537f1cedcf6e06723ebff10b/code/modules/tgui/modules/law_manager.dm#L153-L155
https://github.com/ParadiseSS13/Paradise/blob/e5dac22f258d14ba537f1cedcf6e06723ebff10b/code/modules/mob/living/silicon/robot/laws.dm#L43-L47
https://github.com/ParadiseSS13/Paradise/blob/e5dac22f258d14ba537f1cedcf6e06723ebff10b/code/datums/ai_laws.dm#L75-L77
https://github.com/ParadiseSS13/Paradise/blob/e5dac22f258d14ba537f1cedcf6e06723ebff10b/code/modules/mob/living/silicon/robot/laws.dm#L82-L86

Maybe it's because the test server didn't have an active ai (so the `master` was being set to `null` and the `if` was not being triggered?)

Also note this comment (i'm not sure what *exactly* it means, but the wording implies that it is relevant here):
https://github.com/ParadiseSS13/Paradise/blob/e5dac22f258d14ba537f1cedcf6e06723ebff10b/code/datums/ai_laws.dm#L76-L77
