### ISSUE TITLE
Literal white skin as human from mob spawner

### ISSUE THREAD

**Issue by Fraggloid** [ParadiseSS13/Paradise#17891]
**Issue Description**:
When spawning as a human character via the mob spawner, and with a character slot that is non human, you spawn with entirely white skin.

**What did you expect to happen**: 
Usual human fleshtones

**What happened instead**:
entirely white skin

**Why is this bad/What are the consequences**:
It looks odd. 

**Steps to reproduce the problem**:
Ghost on a non-human character slot, then load into, for example, a syndicate researcher mob spawner slot.

**When did the problem start happening**:
N/A

**Extra information**:
I've not had the chance to do many tests on this with different mobs and different species, but I usually play as Grey/Nian/Plasmaman and have had this occur with all three species.
A fix would be to allow a skintone to be set via the mirror in the syndie base, or just to allow selection during spawning.

**Comment by meow20** [comment]
![image](https://user-images.githubusercontent.com/62257265/170869813-9a0fad19-718b-4c54-9375-8fe5b2b9278e.png)
im just pale why do you insult me man wtf sun doesnt like me mkay

**Comment by Mitchs98** [comment]
I'll also point out that the same often occurs for ERT and Death Squad members, it's not localized to mob spawners.

**Comment by Norwes1** [comment]
This can also - intermittently - happen when using admin rejuv on characters. It seems to be worse with admin-spawned carbon mobs (ERTs, nukies, etc.), and it also appears to wipe certain head&face hairstyles to boot. I'd suggest allowing skin tones to be modded on regular mirrors as a temporary fix.

**Comment by moxian** [comment]
(from discord) this is due to this piece of code 
https://github.com/ParadiseSS13/Paradise/blob/8cd005788d4f3ba4bd3b1e9b34759b2a576b9686/code/__HELPERS/mobs.dm#L193-L205 (and the following proc too) which oftentimes returns negative values, when the skin tone (reportedly) ranges from 1 to 220; e.g.:

https://github.com/ParadiseSS13/Paradise/blob/8cd005788d4f3ba4bd3b1e9b34759b2a576b9686/code/game/dna/mutations/powers.dm#L862-L868

An easy fix would bot just remove all those `-` sings. A proper fix would be to investigate why it used to work before, when did the loss of negative number handling happen, and what was the proposed migration path at that time. And act accordingly.

Notably there are still places which seem to handle negative values well, for example: https://github.com/ParadiseSS13/Paradise/blob/8cd005788d4f3ba4bd3b1e9b34759b2a576b9686/code/modules/client/preference/character.dm#L811-L815
