### ISSUE TITLE
AI core law upload does not work

### ISSUE THREAD

**Issue by KittyNoodle** [ParadiseSS13/Paradise#17934]
**Issue Description**:

Normally before an ai core is constructed and on the wired state you can add laws to it. 
That isn't working now for some reason

**What did you expect to happen**: 

When you apply a law to an unfinished ai core after wires are applied it used to allow you to set laws for the core, this is still in the code.

**What happened instead**:

The ai had a default unedited lawset

**Why is this bad/What are the consequences**:

Means you cannot build a slaved ai as a traitor/other antag

**Steps to reproduce the problem**:

Build an ai up to wiring state.
Apply a valid law board
Finish the ai.

**When did the problem start happening**:

discovered it didn't work on round 31613
]

**Comment by alex-gh** [comment]
Fixed in  #17935

**Comment by SteelSlayer** [comment]
Tested, and this was indeed fixed in #17935. 

However, adding a freeform law during AI core creation does add it directly on top of the default law set. I.e. say you have crewsimov with the laws being in the 1, 2 and 3 slots. Adding a freeform law during AI core creation will set that law to slot 4 instead of 15 or higher. That is unrelated to the PR which fixed that though, and that can be addressed in another PR. Might even do that myself.
