### ISSUE TITLE
TK: Cannot Open ID Locked Doors

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#1798]
Currently TK is capable of opening doors, from afar, if teh door is 100% public and has no ID requirements. 

That said, any door that does have an ID requirement doesn't appear to open properly, even if you do have proper access.

A long time ago this did work on all doors.

**Comment by tigercat2000** [comment]
Not really a bug per say. TK underwent a major overhaul, as did the access checkers, so.

**Comment by SpaceTimeNow** [comment]
I have to agree, i don't necessarily see this as a bug either. It makes sense that i can open a airlock without requirements because the Airlock doesn't need to scan against a ID. But if the airlock requires access how should the Airlock know what ID to scan for access? So i would see this more like a convenience / balance issue. 

The same logic must apply to remote activating computers or buttons.

**Comment by tigercat2000** [comment]
This is still not a bug. The old TK system (based on throws) had snowflake checks in getAccess, if I recall correctly. Probably closer to a feature request.

**Comment by tigercat2000** [comment]
This being not-a-bug hasn't changed in the last 3 months, it can probably be closed!
:cat:

**Comment by tigercat2000** [comment]
@Fox-McCloud mroooowwwwwwwlll
