### ISSUE TITLE
Runtime in Photocopier.dm due to paper overlays

### ISSUE THREAD

**Issue by Sirryan2002** [ParadiseSS13/Paradise#18042]
**Issue Description**:
```
[2022-06-22T15:13:38] Runtime in photocopier.dm,90: list index out of bounds
   proc name: papercopy (/obj/machinery/photocopier/proc/papercopy)
   src: the long range fax machine (/obj/machinery/photocopier/faxmachine/longrange)
   src.loc: the floor (98,176,2) (/turf/simulated/floor/plasteel)
   call stack:
   the long range fax machine (/obj/machinery/photocopier/faxmachine/longrange): papercopy(NT Representative Introduction (/obj/item/paper/nanotrasen), 0, 0)
   the long range fax machine (/obj/machinery/photocopier/faxmachine/longrange): print fax(NT Representative Introduction (/obj/item/paper/nanotrasen))
   /datum/callback (/datum/callback): InvokeAsync()
   Timer (/datum/controller/subsystem/timer): fire(0)
   Timer (/datum/controller/subsystem/timer): ignite(0)
   Master (/datum/controller/master): RunQueue()
   Master (/datum/controller/master): Loop()
   Master (/datum/controller/master): StartProcessing(0)
```
Since fax machines are a child type of photocopier (WHY???), it relies on procs used in photocopier which aren't playing nice with overlays & faxes. When crew members use a local station fax machine to send a fax with an overlay to another local station fax machine, it will produce this error. However, faxes still function correctly, it's just runtiming.

**Steps to reproduce the problem**:
Send a fax with stamps to another fax machine on station.

**When did the problem start happening**:
When #17001 was merged

**Comment by moxian** [comment]
This is due to emissive blockers being an overlay, but copiers expecting that all the paper overlays are managed by /obj/item/paper and not by overall extrenal systems like "lighting".
In more detail, the code expects that  /obj/item/paper.ico[i]` is a exactly a textual description of overlay `/atom.overlays[i]`, but that's not true.

A solution would be convering the `ico` var from being a list of just text string to being an associative list of `text string => corresponding overlay`. And then iterating over this list, rather than over the `.overlays`  in photocopier.dm

Possibly a good first issue.

**Comment by Sirryan2002** [comment]
Thank you for the explanation, you're likely 100% right. I'm also very happy to accept this explanation because it means my own PR didn't cause this :trollface: I'll throw the good first issue label on there because this should be rather easy to fix

**Comment by BunnyGirlJen** [comment]
When I tried to recreate the problem, I didn't encounter a runtime error. I tried with every type of stamp on both long-range and regular fax machines, but each time no runtime error occurred. I might've been doing something wrong or another pull request might've fixed the issue without anyone realising?

**Comment by Sirryan2002** [comment]
Unable to reproduce
