### ISSUE TITLE
typo? preventing floorbots from fixing shuttle areas

### ISSUE THREAD

**Issue by restedwaves** [ParadiseSS13/Paradise#18428]
**Issue Description**:

typo on line 267 of the floorbot.dm seems to be causing issues with fixing any shuttle area, correcting it seems to cause more

**What did you expect to happen**: 

floor bots should be able to fix shuttle areas

**What happened instead**:

they ignore shuttle tile breaches or roll up to them and stop all other floor bots from fixing things

**Why is this bad/What are the consequences**:

shuttles tend not to have air alarms so fixing holes is kind of important due to the limited supply of breathable air

**Steps to reproduce the problem**:

go to code section, see the shameful error in grammar
for an in game example try putting a floorbot near any blown out or removed shuttle tile

**When did the problem start happening**:

looking at the date of it, six years ago

**Extra information**:

after 10 hours of slamming my head into this wall i somehow got it semi working twice but when the bot moves to fix that part of the hull it stopped attempting to fix anything holes and somehow so did all other floorbots on the station, they can still patrol however

**Comment by Oyu-De** [comment]
So, when typo is fixed, any floorbot attempting to fix tiles will be broken and get stuck?

**Comment by restedwaves** [comment]
when fixed if a floorbot attempts to fix a shuttle tile, it stops all others from fixing anything and will also not fix the shuttle tile

**Comment by lewcc** [comment]
I think this might be by design.
https://github.com/ParadiseSS13/Paradise/blob/949b73acf274ea17194469e2e573883d6a7e108c/code/modules/mob/living/simple_animal/bot/floorbot.dm#L265-L270
There isn't a typo here, It looks for the substring `huttle` in the area's name (probably so it can pick up `shuttle` and `Shuttle`, though `findtext()` is not case sensitive lol). If it finds it, it ignores the area. I think it makes sense behavior-wise, since shuttles can be special cases sometimes.

**Comment by Sirryan2002** [comment]
This is technically working as intended but is poor design IMO
