### ISSUE TITLE
Labor Points Console broken since TGUI merge

### ISSUE THREAD

**Issue by Nerfection** [ParadiseSS13/Paradise#18693]
**Issue Description**:
The new labor camp points manager with TGUI is broken for sec - who can no longer log on to them to use their tracker function.

**What did you expect to happen**: 
I expected to be able to log onto the new console much in the same wait as the sec logs console.

**What happened instead**:
When you try to insert your ID to log on, you just hit your ID on it. You cannot log on without the ID being in the machine.

**Why is this bad/What are the consequences**:
Sec can no longer track perma inmates/parolees.

**Steps to reproduce the problem**:
As warden attempted to log onto the new console. The 'log on' button was greyed out. Tried to insert ID into machine as normal but just hit the machine with it and was unable to get it to insert.

**When did the problem start happening**:
The problem happened when the labor points console TGUI PR was merged.

**Extra information**:
N/A

**Comment by Sirryan2002** [comment]
Technically not really a bug, the Labor Points Console is not "broken" you just can't insert the ID by hitting the machine with it, you just click on the ID insert button on the login screen, otherwise it works perfectly fine, I agree that this is an oversight as other computers with login screen behave the way you are expecting the labor points console to work so this should probably be corrected.
