### ISSUE TITLE
Mesons are not working properly.

### ISSUE THREAD

**Issue by maxlel** [ParadiseSS13/Paradise#18771]
**Issue Description**:

Currently Mesons are not preventing hallucinations. I am not sure if this is a personal issue, but every time i use mesons near SM it doesnt work. I am an IPC player and I do not think it affects my fellow co workers, but it's getting a bit on my nerves since I recently died to a hallucination just popping in out of nowhere, while I still had my mesons on.

**When did the problem start happening**:

I would say a week ago, I'm not entirely sure. It could be a lot longer.

**Extra information**:

**Comment by lewcc** [comment]
As of https://github.com/ParadiseSS13/Paradise/pull/18501, IPCs are no longer immune to radiation, and in fact receive hallucinations and brain damage from it. I believe that you were irradiated by being around the SM, and while the mesons protected you from one source of hallucinations, they didn't protect you from those caused by rads.
