### ISSUE TITLE
Wooden airlocks in reworked science maintenance cannot be destroyed

### ISSUE THREAD

**Issue by Dsdiy** [ParadiseSS13/Paradise#18882]
**Issue Description**:
Wooden airlocks in the reworked science maintenance can't be destroyed by attacks and cause runtimes when destroyed.

When someone attempts to destroy a wooden airlock by force, it drops some metal and gets stuck in the partially finished state.
Corresponding runtime:
![RuntimeError](https://user-images.githubusercontent.com/40638666/186205811-2ca8dfd5-64d0-4f48-b27c-8681cc8d9667.png)

**What did you expect to happen**: 

The airlock to be properly destroyed, and drop some wood.

**What happened instead**:

The airlock gets stuck partially destroyed, drops some metal, and runtimes.

**Why is this bad/What are the consequences**:

1: Runtimes bad. 2: Indestructible airlocks bad

**Steps to reproduce the problem**:

Go into the reworked science maintenance, and attempt to destroy the wooden doors in there.

**When did the problem start happening**:

Unsure, but possibly since the maints were first added in.

**Extra information**:

**Comment by Dovixx** [comment]
Some extra information.
This isn't an issue with the mapping itself but rather the code. When deconstructed or destroyed airlocks try to drop sheets with the subtype of /obj/item/stack/sheet/mineral and since wood doesn't have the mineral subtype it runtimes.

**Comment by NethIafin** [comment]
mhm, I see the issue, wood is not a mineral and airlocks always expect a mineral

**Comment by Sirryan2002** [comment]
This is a good intro into refactoring stuff, would be happy to help walk someone through this. The problem here is that each mineral door assembly has a "mineral type" that is just a string. It uses this string to build a typepath which is really bad practice due to the linters/tests not being able to pick this up.

Door assemblies should only take the dropped mineral as a hardcoded type path instead of a string.
