### ISSUE TITLE
After a room turns green due to a toxins leak, the original room color cannot be restored.

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#1890]
This is SUPER annoying.

**Comment by tigercat2000** [comment]
I'm not even sure why it turns green, honestly.

**Comment by Alex6511** [comment]
It SEEMS to be related to toxins in the room.

**Comment by Markolie** [comment]
I looked into it, and it has to do with the color of the turf being set through (I think) update_lumcount() and the colors of the light sources (perhaps the color plasma gives off?). It definitely has to do with our light overlays.

**Comment by FalseIncarnate** [comment]
While it may not be directly related to this issue, I can confirm that colored lights do seem to improperly refuse to adjust their color under unknown conditions.

While testing glofish prior to posting the recent sushi update, I noticed that light from the tanks would remain green from the glofish even when the tank light (a pink/purple color) was turned back on. The fish were intended to cause a green light to emanate from the tank while the tank light was off, and then cease causing the green light when the tank light was on (allowing the tank light color to shine through instead). This however was not the case, and the light would be green even with the tank light on.

I suspect both issues are caused by the same bit of code not properly updating the light colors, though I do not know where or why this is occurring.

**Comment by TheDZD** [comment]
Similar issue, if you take any light source (such as a flare), light it, put it in a locker, close the locker, and then move the locker, the light source stays at the original spot where the the closet was closed. The light does update once you pick up and move the light source however.

**Comment by Fox-McCloud** [comment]
I recall @PJB3005 stating that colors behaving in such a manner has to do with some overflows, if I recall correctly, though it's been a while, and I may be misremembering.

**Comment by PJB3005** [comment]
@TheDZD that issue is due to a lack of `forceMove()` in locker code, simple replace whatever is setting the `loc` of the items to the locker to a `forceMove()`, the light source isn't being registered as being inside the locker, so updates don't happen.

@Fox-McCloud, hrm, don't really know what you mean with colours overflowing.

I know that during testing of one of the optimizations (I think it was `smart_vis_update()` testing?) I actually had a floating point issue due to some `round()`s being poorly placed, I moved the `round()` calls around and it didn't seem to happen but I'll double check.

**Comment by Markolie** [comment]
https://github.com/ParadiseSS13/Paradise/pull/1926 for the locker issue.

**Comment by Fox-McCloud** [comment]
@PJB3005 

My mistaken, I was referring to the floating point error.
