### ISSUE TITLE
Crafted Thermal Drill Not working

### ISSUE THREAD

**Issue by B0xy1** [ParadiseSS13/Paradise#18916]
**Issue Description**:

I  crafted a thermal drill using two empty cells got it to the vault safe it was drilling just fine but at the end of the loading bar it kept  loading with out the bar moving kept going ad infinity with out making noise after it indicated it was done and the safe didn't open 

**What did you expect to happen**: 

For the drill loading bar to stop loading and that opening the safe

**What happened instead**:

The drill kept loading past its bar ending ad infinity 

**Why is this bad/What are the consequences**:

It ruined a perfect heist and the fun of the round for me and it means that one item is not only useless but will create the same problem for others

**Steps to reproduce the problem**:

Create a thermal drill using uncharged batterys  
Place it on the Vault safe
Fill the vault with burning plasma using a bomb or a flamethrower 
Do an AI hostile lockdown mid drill loading 

**When did the problem start happening**:

As far as i know the day i am writing this is the first time 

**Extra information**:

Round ID 32601

Round time the event happened Approximately 00:59:00: - 01:05:05

**Comment by Coolrune206** [comment]
Tried to replicate. I believe what happened here is actually quite a common thing people do when they use the safe drill. Because the drill's progress bar "finishing" doesn't emit any chat message or change the safe's visual appearance, they assume it failed so they start it up again. What actually happens however,
![image](https://user-images.githubusercontent.com/71326864/187098995-6438a5de-e1ce-4a9e-b411-1a496699ce2c.png)
is that when you remove the drill instead of turning it back on, there's a little hole in the safe
![image](https://user-images.githubusercontent.com/71326864/187099012-0cee94c8-4d66-433c-a5c0-46cbcaa29072.png)
and it can be opened thereafter.
Perhaps some kind of chat message, or making it so interacting with a drill on a safe which already has a hole in it automatically removes it so players don't fall into the trap of assuming the drill needs to be run again.

**Comment by B0xy1** [comment]
I think that message could help greatly thanks for clarifying.
