### ISSUE TITLE
Goliath meat does not properly cook on grill

### ISSUE THREAD

**Issue by Sadhorizon** [ParadiseSS13/Paradise#19407]
**Issue Description**:
When cooked on grill, goliath meat keeps it's toxin contents

**What did you expect to happen**: 
(cooked on lava/bonfire)
![image](https://user-images.githubusercontent.com/108196626/196022381-5014b09a-0540-4579-86b4-6c553506939a.png)

**What happened instead**:
(cooked on grill)
![image](https://user-images.githubusercontent.com/108196626/196022401-dae15cec-2304-4dfb-8aa1-abfde5dee2a8.png)

**Why is this bad/What are the consequences**:
Why should chef be unable to serve goliath?

**Steps to reproduce the problem**:
Get Goliath meat, cook it on lava/bonfire, then cook it on grill

**When did the problem start happening**:
_shrug_

**Extra information**:
This _may_ be intended but at the same time, feels like a bug

**Comment by warriorstar-orion** [comment]
I believe this is intended. Goliath meat is meant to be safe after cooked over a bonfire because that makes it a viable food source for ashlanders and other stranded lavaland players. However it's not actually getting cooked, just deleted and swapped out with a cooked steak.

Kitchen machines are intended to preserve their reagents, so that harmful chemicals can make their way into finished dishes. Special casing the machines to only remove this one reagent from this one food item would be a lot of effort for very little gain.
