### ISSUE TITLE
Brains get deleted when a player is gibbed (by an explosion)

### ISSUE THREAD

**Issue by Somniworld** [ParadiseSS13/Paradise#19613]
**Issue Description**:
Upon being gibbed by an explosion, (notably, a Syndicate Minibomb), your brain might get instantly deleted by the very same explosion, knocking you out of the round forever.

**What did you expect to happen**: 
To not have my brain reduced to smithereens by an explosion, even though my body was.

**What happened instead**:
My brain was deleted completely, preventing me from being brought back, other than through pre-scans.

**Why is this bad/What are the consequences**:
I like playing the videogame, this is a "cheap" way of permakilling someone, since you don't even have to secure their brain. Furthermore, this can fuck over antags which have a "steal X's brain" objective, as was the case of my assaillant, which accidentally fucked himself over through complete RNG.

**Steps to reproduce the problem**:
1) Get Blown up by an explosion (Syndicate Pipebombs are certain to work for this)
2) Get "Lucky", this isn't a 100% occurence.
3) Notice that your brain is no more, making you a spectator forever

**Extra information**:

This reportedly happens to other organs, which means that, sometimes, your heart gets completely deleted, this is less annoying, since you don't need a heart to be revived, but nevertheless.

**Comment by warriorstar-orion** [comment]
This is seen as not an issue by the dev team; brains aren't meant to be invulnerable and blowing someone up isn't really a reliable way to keep their organs intact. If that's their objective, a different approach might be necessary.

The fact that an organ may or may not be completely destroyed is also expected since bombs are processed in an outgoing radius from the source, so an organ may be caught (or not caught) in the next radius.
