### ISSUE TITLE
firing range console on the NSS Kerberos does not work

### ISSUE THREAD

**Issue by restedwaves** [ParadiseSS13/Paradise#19682]
**Issue Description**:

firing range console does not work

**What did you expect to happen**: 

it to move the target

**What happened instead**:

it did not

**Why is this bad/What are the consequences**:

security will continue to be unable to shoot if their life depended on it

**Steps to reproduce the problem**:

try any command in it and it still will not work

**When did the problem start happening**:

honestly this is the first time i tried improving my aim in a nonviolent manner so i can't say

**Extra information**:

**Comment by warriorstar-orion** [comment]
Was able to reproduce. The issue seems to be the lack of a magnetic controller under the target stake. Compare Box vs Delta:

![20_25_11__paradise dme  cyberiad dmm  - StrongDMM-](https://user-images.githubusercontent.com/59303604/201556693-7dc7fa34-3cd6-417d-a70b-83716ab03f66.png)

![20_25_02__paradise dme  delta dmm  - StrongDMM-](https://user-images.githubusercontent.com/59303604/201556698-600ae964-822f-449a-a2af-45e43a85b0df.png)
