### ISSUE TITLE
Surgeons cannot select the Medical account on the cargo console

### ISSUE THREAD

**Issue by Miraviel** [ParadiseSS13/Paradise#19901]
**Issue Description**:

When you join as a Surgeon, you cannot select the Medical account for orders on the cargo console.

Only your own and Supply's account are visible.

**What did you expect to happen**: 

To be able to select the Medical account like Medical Doctors.

**What happened instead**:

Only my own and the Supply account show up.

**Why is this bad/What are the consequences**:

Seems like an oversight, alt titles should not affect this.

**Steps to reproduce the problem**:

1. Change medical doctor's alt title to Surgeon
2. Join the round
3. Go to cargo order console
4. Try to select Medical

**When did the problem start happening**:

Observed it today, round 33816, on Meta.

**Extra information**:

...

**Comment by Miraviel** [comment]
Looking at the code, it looks like alternate job titles are not handled at all. Not sure how to fix it, other than manually adding each one to the list!

**Comment by warriorstar-orion** [comment]
Can confirm. @Sirryan2002 I'm not sure how this is meant to work but it seems like /proc/get_departments_from_job should also check the alt_titles for each job, though it might be tricky because it doesn't look like departments actually track their associated roles, rather each job tracks its associated department. Maybe /datum/station_department/department_roles could be an associated list e.g. 

```
/datum/station_department/medical
  department_roles = list(
    "Chief Medical Officer" = /datum/job/cmo,
    "Medical Doctor" = /datum/job/doctor,
    ...
```

**Comment by Sirryan2002** [comment]
I'm just going to add the alt job titles to the list
