### ISSUE TITLE
Ion rifles are innefective against killer vending machines

### ISSUE THREAD

**Issue by theColdflame** [ParadiseSS13/Paradise#1994]
probably more of an oversight than a bug, but it doesn't make a lot of sense

**Comment by Fox-McCloud** [comment]
They're mobs, not machines.

**Comment by Markolie** [comment]
They should have an emp_act on them though - not sure how easy this is as mimics are a single mob type.

**Comment by FalseIncarnate** [comment]
Could make a new subtype, like mob/simple_animal/hostile/mimic/vend

Give this subtype the special emp_act effect, then have the brand intelligence event create the mimic/vend mobs instead of normal mimics. This would avoid people being able to ion rifle down the pine tree, while letting them EMP the Nanomed that is eating their face.
