### ISSUE TITLE
Can't Select Socks

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#2001]
Simply put, you can't select socks for your character; there's not a button to do so on the live server.

Locally, this manifests differently; the button appears, but if you click on it, nothing happens; you're stuck with whatever socks the random button decides to throw your way.

**Comment by TheDZD** [comment]
!(This might help)[https://i.gyazo.com/6b916cbaf7cfa32db5a979f291ab2155.png]

Fox posted this earlier somewhere, this is what the issue looks like on the live server.

**Comment by KasparoVy** [comment]
It's also missing a 'sockless' option, while there is a nude option for underwear and undershirt

![socks](https://cloud.githubusercontent.com/assets/12377767/9804354/cf3fc524-57fa-11e5-898e-6fec39828140.PNG)

Also-- not sure if by 'Vox Stripped' it means STRIPED or something else

**Comment by Earthdivine** [comment]
You can select socks on the server actually, the area for the button is there, but no icon for it. Clicking the area brings up the window.

**Comment by Fox-McCloud** [comment]
No such luck for that.

**Comment by NTSAM** [comment]
I think you can select socks from the dresser?

**Comment by Markolie** [comment]
This only happened to existing characters slot - these didn't have their default value set to "" instead of "Nude" due to the preferences not overwriting it. This has been fixed by setting the "socks" preferences for all players to "Nude", meaning that people will have to re-do their socks.

Will create a PR for the Vox thing.
