### ISSUE TITLE
A bug regarding hand drill

### ISSUE THREAD

**Issue by Sadhorizon** [ParadiseSS13/Paradise#20075]
**Issue Description**:
When hand drill (powertool one) is in screwdriver mode, it can fit inside of a wallet. Cannot do the same in wrench mode

**What did you expect to happen**: 
For it to be consistent between modes... also... it's a god damn drill, why would it fit there?

**What happened instead**:
![image](https://user-images.githubusercontent.com/108196626/210263172-b3898891-bacf-4f0f-b53a-cc42be5c1904.png)

**Why is this bad/What are the consequences**:
Inconsistency

**Steps to reproduce the problem**:
Take a hand drill, hide inside of a wallet, change modes, cannot do so anymore

**Comment by warriorstar-orion** [comment]
This is due to the fact that wallets are nominally meant to hold screwdrivers: 

https://github.com/ParadiseSS13/Paradise/blob/d1c80c8802b226b699b87eae4b21b5c47d7a799b/code/game/objects/items/weapons/storage/wallets.dm#L9-L28

and the power drill, when in screwdriver mode, is a subtype, `/obj/item/screwdriver/power`. When switched to wrench mode it becomes a `/obj/item/wrench/power`, so is no longer a type/subtype in that list, so no longer is allowed.

I imagine the power variants _have_ to be subtypes of their respective primitive tools in order to interact properly with other items in the world, but the power tools should definitely not fit in wallets whatsoever.
