### ISSUE TITLE
IPC Bugs

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#2011]
IPCs can crit at around 150, i think, it happend once when a carp attacked me in a hardsuit... 

More importantly you can revive IPC's without heads.

**Comment by FalseIncarnate** [comment]
To my knowledge, the first is definitely intended. They ignore pain (soft) crit, but still drop at 150 due to entering true crit

The second is likely intended too. IPCs store their brain in the chest, not head, and do not require all limbs to be revived. Headless IPCs are just blind since they lack visual sensors which are in the head.

**Comment by Markolie** [comment]
False is correct on both counts.

**Comment by Robertha89** [comment]
Oh, okaythen.
