### ISSUE TITLE
Sterilizine recipe no longer accessible - By extension, Degreaser.

### ISSUE THREAD

**Issue by fludd12** [ParadiseSS13/Paradise#2030]
Can we finally change this recipe? It bothers me that Degreaser requires something that was useless even before the goofchem update.

**Comment by veganzombeh** [comment]
The sterilizine recipe is `("ethanol" = 1, "charcoal" = 1, "chlorine" = 1)`. It's incorrectly listed on the wiki, but it should still be accessible.

**Comment by FalseIncarnate** [comment]
The recipe is not accessible, since charcoal (anti-toxin on the wiki) and ethanol creates the antihol reagent before the sterilizine reaction is able to occur.

Simple fix would be to change the sterilizine recipe to antihol and chlorine to maintain the same reagents used in the recipe, and not worry about a recipe conflict.

The more ideal fix, however, would be to either fix sterilizine into a properly functioning state or remove it entirely and replace it in any recipe that utilizes it (like Degreaser). I'd personally rather see it fixed up than scrapped, as it is intended to be a disinfectant for use in surgery (perhaps we can use it to clear infected wounds more efficiently than spaceacillin?).

**Comment by Fox-McCloud** [comment]
@FalseIncarnate 

Not necessarily; you'd have to try it out specifically charcoal+chlorine, then add ethanol last.

If doing so fails, then yeah, you can't make it, but it may still result in sterilizine.

**Comment by FalseIncarnate** [comment]
I took a minute during the testing for my recent PR to test this.

I tried it in a few orders and it did not work. I will check it again after I get some sleep to be sure.

**Comment by Fox-McCloud** [comment]
@FalseIncarnate 

Alright-regardless of whether or not it works, the recipe should probably be changed.
