### ISSUE TITLE
Mice can spawn on top of the supermatter crystal

### ISSUE THREAD

**Issue by Miraviel** [ParadiseSS13/Paradise#20621]
**Issue Description**:

Player joined as mouse. Logs showed he "Logged in" at (113, 062) on the Cyberiad, then he immediately died, because that is the SM's exact location.

This happened twice so far this year that I witnessed.

**What did you expect to happen**: 

Mice not to magically appear on top of the SM's tile.

**What happened instead**:

Player joined in, immediately delammed the SM.

**Why is this bad/What are the consequences**:

They made a map-wide issue by simply trying to become a rodent.

**Steps to reproduce the problem**:

Unsure. Both mice cases I noticed happened late into the round.

**When did the problem start happening**:

Only noticed it in 2023.

**Extra information**:

no

**Comment by Contrabang** [comment]
This might be fixed somewhat by #20414

**Comment by Henri215** [comment]
> This might be fixed somewhat by #20414

The PR has been merged and i do think that it spawning in places like this is no longer a problem.

**Comment by warriorstar-orion** [comment]
Completely fixed by #20414, as the mouse now starts somewhere in a pipenet, and the supermatter pipenet isn't returned as a potential spawn place from

https://github.com/ParadiseSS13/Paradise/blob/0541604174eb7b2311f0c8f3d1ce9babb530078a/code/modules/mob/mob.dm#L1197

because it has too few machines compared to the minimum default of 50.
