### ISSUE TITLE
Cake hat can only be found on Cyberiad

### ISSUE THREAD

**Issue by VEN0M5** [ParadiseSS13/Paradise#21015]
**Issue Description**:

The cake hat can only be found on the Cyberiad map in the bar. It is not available anywhere else (a mentor code dived for this info)

**What did you expect to happen**: 

Able to acquire a cake hat and bake a birthday cake regardless of the map.

**What happened instead**:

Can't make birthday cake without cake hat

**Why is this bad/What are the consequences**:

Crafting material should not be locked behind a map

**Steps to reproduce the problem**:

Try to find the cake hot on any map not Cyberiad 

**When did the problem start happening**:

Since new maps?

**Extra information**:

I totally did not make this report because I tried to make a living cake/hybird cat on Farragus and failed to find a cake hat

**Comment by Pennwick** [comment]
Changing the Birthday cake recipe might make a bit more sense actually. Its a little weird that the recipe contains a cake hat in the first place. Maybe instead it should just need the vanilla cake recipe plus candles and extra sugar.

If we want to go with making cake hats more accessible then It might be better to have a tablecrafting recipe to create cake hats rather than relying on a single spawn on each station. Something like 3 candles, igniter, 3 cable, and any intact cake. If we do both then the recipe could just be birthday cake + cable to tie it on with.

Either would mean that its possible to create unlimited cake cats instead of the maximum of 5 (4 from upgraded oven + 1 lavaland ruin) but I doubt they'd be an issue.
