### ISSUE TITLE
Cryo'd thralls still take up a thrall slot

### ISSUE THREAD

**Issue by smokincheez** [ParadiseSS13/Paradise#21185]
**Issue Description**:
If you are a Dantalion vampire, and a thrall enters cryo, they will still be taking up one of your thrall slots

**What did you expect to happen**: 
Well, if someone has to go for OOC reasons, and they cryo, they should free the slot up so the danta can go get a new one.

**What happened instead**:
After they went cryo, though I should have been able to have 2 thralls at that time, I only had one left and could not convert another as I had too many.

**Why is this bad/What are the consequences**:
If a dantalion can't have enough thralls at a given time due to OOC reasons, this is bad for them.

**Steps to reproduce the problem**:
Be dantalion, get thrall, thrall enters cryo, try to get another thrall, can't get another thrall.

**When did the problem start happening**:
Happened last night. I thought my thrall died or something, but it turns out they cryo'd without me noticing. (Which is fine because I was being stealthy and didn't really need their assistance.)

**Comment by SamAlby** [comment]
Just tested this on latest main branch - cryoing works as intended and removes the mindslave thrall from the master correctly

**Comment by smokincheez** [comment]
> Just tested this on latest main branch - cryoing works as intended and removes the mindslave thrall from the master correctly

Really? Unless something was up with my thralling, I definitely had 2 at 450 blood, one cryo'd, and I still couldn't add another due to having maximum thralls for my power, I was even at 450 blood at the time, after having two initially, losing one to cryo, and then trying to thrall another, resulting in a maximum thralls for current power message. I'd really like more testing before this is confirmed false as I remember this happening to me.

**Comment by SamAlby** [comment]
> > Just tested this on latest main branch - cryoing works as intended and removes the mindslave thrall from the master correctly
> 
> Really? Unless something was up with my thralling, I definitely had 2 at 450 blood, one cryo'd, and I still couldn't add another due to having maximum thralls for my power, I was even at 450 blood at the time, after having two initially, losing one to cryo, and then trying to thrall another, resulting in a maximum thralls for current power message. I'd really like more testing before this is confirmed false as I remember this happening to me.

Just tested again by becoming a 450 blood vampire, thralling two human mobs with minds, then taking control of them and cryoing them via hopping in the cryopod and ghosting, then trying to thrall again after. I am 100% certain the act of cryoing (body being processed and despawned) in fact removes the thrall from the vampire's servant list, which the code of thralling checks against in order to determine if the vampire can thrall someone or not. The only way I can see this happening is if the user were to disconnect then be taken to the cryopods, and not be cryo'd, they would still take up the slot because they were still in the world, and could feasibly reconnect and start playing again at any moment.

**Comment by Contrabang** [comment]
Like said above, cannot reproduce in conditions where the thrall cryos. If they're disconnected and brought to cryo, I believe its intended they stay a thrall until they fully cryo
