### ISSUE TITLE
Unable to disable GPS

### ISSUE THREAD

**Issue by tipoima** [ParadiseSS13/Paradise#21511]
**Issue Description**:

GPS cannot be turned off

**What did you expect to happen**: 

For the power button to turn GPS off/on

**What happened instead**:

The button is completely unresponsive

**Why is this bad/What are the consequences**:

I'd like to know where I am without everyone else also knowing where I am

**Steps to reproduce the problem**:

Open GPS UI, press the "On" toggle, see nothing change

**When did the problem start happening**:

Isn't working for at least a week or two.

**Extra information**:

GPS in mining's survival pods cannot be turned off either.

**Comment by warriorstar-orion** [comment]
I'm not noticing an issue with the handheld GPS units but I am seeing that the survival pod GPS can't be turned off. I suspect it is due to this code:

https://github.com/ParadiseSS13/Paradise/blob/d67b841e05e5734caffb3171eac004f1e214e7f5/code/modules/telesci/gps.dm#L57-L58

Which ensures that the GPS UI is valid to be interacted with, by seeing if the GPS is in the user's hand. Since the pod ones cannot be held, they cannot be toggled. Unsure if this is intended or not.

**Comment by tipoima** [comment]
I checked this on local server and it _does_ actually work fine there, but is still bugged on actual live version.
Can only assume it's caused by something being testmerged, probably modsuits

**Comment by warriorstar-orion** [comment]
Qwerty confirmed this and #21850 were due to the modsuit TM and have been addressed.
