### ISSUE TITLE
The 'false alarm' variant of the radstorm event does not trigger emergency maintenance access

### ISSUE THREAD

**Issue by Landerlow** [ParadiseSS13/Paradise#21592]
**Issue Description**:
The 'false alarm' variant of the radstorm event does not trigger emergency maintenance access

**What did you expect to happen**: 
Emergency maintenance access

**What happened instead**:
No emergency maintenance access

**Why is this bad/What are the consequences**:
The event is identifiable as fake

**Steps to reproduce the problem**:
Trigger falase alarm event, hope RNG gives you fake radstorm event

**When did the problem start happening**:
Not sure, but I noticed it just today

**Extra information**:

**Comment by warriorstar-orion** [comment]
Looks like the false alarm event only supports making the deceptive announcement; no additional actions. It doesn't seem like it had that ability before #20572 but I also can't tell what that PR was meant to fix. Maybe events could have a specific method for "telegraphing" events similarly to `/datum/weather`s, that include all the extra actions/announcements which can be used for both the real events and the false alarms.

I'm marking this a FR rather than a bug only because I can't tell if this was ever implemented, feel free to relabel.

**Comment by Henri215** [comment]
Closing because https://github.com/ParadiseSS13/Paradise/pull/22010 refactored the false alarm event and it no longer tries to replicate the radiation storm.
