### ISSUE TITLE
Spess pods transfer issues from one Z-level to another

### ISSUE THREAD

**Issue by Darkeraser** [ParadiseSS13/Paradise#2230]
Best way to state this, You are heading west to transfer a Z-level, you hit the end of the map, it does not transfer. You have to head ANY direction but west to transfer across the Z-level. This is a problem on all boundaries of Z-levels for pods right now, not a consistent issue per transfer but is one currently.

**Comment by Plotron** [comment]
Can confirm. Makes for less-than-seamless Z-level transfers, but at least I get to know (sometimes) when I transfer.

**Comment by tigercat2000** [comment]
Given that z-level transitions have been reworked multiple times since this was made, it's probably fixed.

**Comment by pinatacolada** [comment]
just stumbled upon this, it's not fixed

**Comment by Fox-McCloud** [comment]
can't really be fixed, to be honest.

The reason for this is that the edge of pods is considered the bottom left corner---therefore, when you go from left to right, you hit the edge and don't transfer, since the "pod" hasn't actually hit the edge.

When going from left to right, it works perfectly, since the "pod" does hit the edge.

**Comment by monster860** [comment]
Whoa, I think I might know what's going on here...

When the pod enters a space tile, the space tile checks to see if the pod's `loc` variable is set to the space tile, and if it's not, it cancels the transition. This is what's causing the problem here.
