### ISSUE TITLE
Modsuits never stop dusting on the SM

### ISSUE THREAD

**Issue by Bjamcham** [ParadiseSS13/Paradise#22698]
**Issue Description**:
Modsuit components never stop dusting when consumed by the SM, creating an infinite cycle of text popups, logs, and dusting. The core and modules are gone, but the external wear remains, creating logs.

**What did you expect to happen**: 
For the modsuit components to be destroyed once.

**What happened instead**:
They looped forever until the SM was deleted.

**Why is this bad/What are the consequences**:
Modsuit components shouldn't infinitely create logs and EER.

**Steps to reproduce the problem**:
1. Deploy a modsuit(Any modsuit works)
2. Dust yourself by walking into the SM
3. Wait
4. Witness the infinite logs

**When did the problem start happening**:
Probably since the addition of modsuits(?)

**Extra information**:
![image](https://github.com/ParadiseSS13/Paradise/assets/107899953/26f219b7-47a7-4d4d-a6d3-030671cb8b07)
![image](https://github.com/ParadiseSS13/Paradise/assets/107899953/3e17add3-a492-44c4-8d7a-8cb95ea89818)

**Comment by Contrabang** [comment]
This is probably caused by https://github.com/ParadiseSS13/Paradise/pull/22344
I can't figure out why besides maybe that the old version had 2 more seconds to qdel the modsuit properly?

The GC happens with all dustings it seems, I havent tried other methods like just outright qdeling the person wholly, so that could be the problem.

I tried searching by GC reference, but I couldnt find anything. I'm kinda clueless on this one.
