### ISSUE TITLE
UI overlay (both hands selected), beakers and hydroponics tray issue

### ISSUE THREAD

**Issue by MrRomainzZ** [ParadiseSS13/Paradise#23184]
### Exploit Reports

- [X] I confirm this issue is not an exploit. (Required)

### BYOND Version

515.1619

### Issue Description

After testing commits #22754 and #23117 I've noticed, that enabling emitters causes bugs with UI (like both hands selected simultaneously), beakers and hydroponics trays

### What did you expect to happen?

I expect no UI glitches

### What happened instead?

They happen

### Why is this bad/What are the consequences?

"Literally unplayable"

### Steps to reproduce the issue.

Turn your emitters on and swap hands or select different body part

### When did the problem start happening?

#22754

### Extra information

Videos without and with the issue

https://youtu.be/-IZ-HAyfvVo

https://youtu.be/w4TkHCg2lPI

**Comment by DGamerL** [comment]
Hello and thank you for making this issue report!
Sadly this is a duplicate of #23137 and #23184. This is also caused by the server being on an outdated version of Byond, which should hopefully be fixed soon. Thank you for making this issue report, and if it persists after the server update, feel free to make a new report!
If you have any questions, I'm alway available in the discord!
