### ISSUE TITLE
Attaching Magboots to Hardsuits and Wearing the Suit Doesn't Deploy Magboots

### ISSUE THREAD

**Issue by KasparoVy** [ParadiseSS13/Paradise#2352]
The title says it-- but I neglected to add that wearing a hardsuit with magboots attached even though you have NOTHING on YOUR OWN feet still doesn't deploy the hardsuit magboots.

It can be circumvented by wearing the magboots separately, but...
I don't know when this problem first started occurring. I suspect it was quite recent, though.

**Comment by Robertha89** [comment]
Hardsuit helmet not deploying can be included, currently neither automaticly deploy, and you have to do so manually, not sure if you can deploy magboots manually, as i never equip em to the hardsuit to begin with.

**Comment by taukausanake** [comment]
Can someone explain to me the purpose of deployable parts to hardsuits? Is it so you don't have to take off those parts of clothes so you can use a hardsuit?

**Comment by Robertha89** [comment]
if you could wear shoes, having magboots attached would be 100 times more usefull, currently the auto deploy does not work.

**Comment by Amauros** [comment]
@taukausanake You have to remove the any articles of clothing regardless to deploy the magboots and helmet. The only usefulness of this is that it removes the helmet and magboots when you take off the hardsuit. If you want to continue using the magboots without the hardsuit, you can screwdriver them off (or just never attach them in the first place), but the helmet must be attached to a hardsuit in order to be worn.
