### ISSUE TITLE
Only Radium/Mutagen or Floral Somatoray can mutate plants

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#2407]
The only things that will cause a plant to mutate are either added Radium/Unstable Mutagen, or a Floral Somatoray. Left4Zed only increases the chance of a given mutation occuring once the mutation is initiated. Is this behavior as intended?

**Comment by Fox-McCloud** [comment]
Indeed, it is, I believe.

@FalseIncarnate

**Comment by FalseIncarnate** [comment]
This is intentional.

Left4Zed is not a mutagen itself, but rather a mutagenic enhancer. It increase the mutation mod for the plant/tray, making it more likely to mutate when exposed to a mutagenic compound like radium or unstable mutagen.

I wanted to add some additional mutagenic compounds, but haven't gotten around to it yet.
