### ISSUE TITLE
Sentient Spaghetti (atmos rabbit) unable to function

### ISSUE THREAD

**Issue by Banderblitz** [ParadiseSS13/Paradise#24174]
### Exploit Reports

- [X] I confirm this issue is not an exploit. (Required)

### BYOND Version

515.1620

### Issue Description

When Spaghetti (the atmos pet rabbit on Farragus) rolls as sentient, you are unable interact with public doors, or any at all, so you cant tell someone you're stuck in a room, and you cant even move around in public.

### What did you expect to happen?

I expected to be able to do about what a normal sentient pet does, touch doors, go through public, etc.

### What happened instead?

I instead was stuck behind any and every door and was forced to either hope someone would grab and hold me as a rabbit, or to ahelp.

### Why is this bad/What are the consequences?

When a midround rolls (even something as simple as sentient rabbit), the role should function to some degree, and not just be stuck in whatever room its in unable to interact with anything.

### Steps to reproduce the issue.

1. Have sentient Spaghetti roll as midround.
2. Win the role.
3. Try to go through atmos, realize you cant even ping the door.
4. Get out of atmos and engineering somehow, then promptly get stuck behind a public door unable to interact with it either.

### When did the problem start happening?

As of 2/15/2024 on round 39199, has likely existed as long as rabbits have.

### Extra information

Spaghetti also has the ability to hide as lizards and mice do, but cannot crawl under doors, this is probably intentional though. However if it is not, something to note.

**Comment by FunnyMan3595** [comment]
The cause here is that bunnies are `MOB_SIZE_TINY` (same as mice and butterflies, making them too small to open doors), but have neither `ventcrawler = VENTCRAWLER_ALWAYS` (to go through vents) nor `pass_door_while_hidden = TRUE` (to hide under doors).  Changing any of the three would make playing as a bunny significantly less frustrating.

Ref: https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/simple_animal/friendly/bunny.dm
