### ISSUE TITLE
Random seeds have the potential to have the mutationtoxin and amutationtoxin reagent.

### ISSUE THREAD

**Issue by tigercat2000** [ParadiseSS13/Paradise#2439]
https://github.com/ParadiseSS13/paradise/blob/master/code/modules/hydroponics/seed.dm#L432-L433

Also known as, oh god, why is the botanist's food making everyone into slimes.

**Comment by Fox-McCloud** [comment]
This probably shouldn't be a thing.

**Comment by Mijhead** [comment]
I'm pretty sure this isn't a bug, considering it was put in on purpose, and it's random, or strange, seeds we're talking about. Seeds which you need to rely on cargo for to get, and then you need to beat the chances to both get a seed that won't die before you can harvest it, and that it actually -has- the reagents in it. Besides, there were plans to change it from a whitelist of chems, to all chems except a blacklist of chems a while ago, before it got dropped due to inactivity.

**Comment by tigercat2000** [comment]
@Mijhead Perhaps the balance label would fit better than bug, as yes, it is *intentional*, However people really shouldn't be able to be turned into slimes other than someone deliberately doing so as a xenobiologist.

**Comment by Fishocalypse** [comment]
This seems like something irrelevant, considering that it takes nearly twice the effort and much more interaction with the station than a xenobiologist sitting in xenobio and feeding monkeys, not to mention the fact that it involves pure RNG to even get it. 
It takes raising a random plant with random needs, feeding it enough nutriment/robust harvest to get a sizable amount, then using said fruit and giving the gene to something like wheat, before growing that wheat again and giving it to the chef. 
Half the time, cargo wouldn't work in your favour, and science would've already made enough gold/black slimes to grief the entire station with foam slime toxin grenades in the time it took you to poision some food in the chef's kitchen.

**Comment by taukausanake** [comment]
Why would someone even feed the plants of random seeds to the crew? Let alone any chef dumb enough to try feeding them to crew. I kind of want this to stay, maybe those plants came from the slime person home planet?
