### ISSUE TITLE
Puking is based off of the body decomposing, rather than how long you've been near a rotting corpse.

### ISSUE THREAD

**Issue by Fishocalypse** [ParadiseSS13/Paradise#2443]
This causes a lot of silly issues, leading to anyone walking into a large room with rotting corpses to rapidfire puke while being slowed down from all the nutriment lost/time spent frozen from puking. Running into a group of bodies causes you to smell all of the decomposing corpses at once, and once you start puking you continue puking on seperate timers based on the corpse itself.

**Comment by Robertha89** [comment]
yeah, puking is not a proc, and is litterally vomited all over the code.

**Comment by Fox-McCloud** [comment]
Some facts:

- Smelling decomposing bodies doesn't stun you when you vomit from it
- You don't lose nutriment from this style of puking either

This isn't a bug, really; you puking when being near a corpse was always intended to be something that happens when you're near particularly foul smelling corpse.

**Comment by Fishocalypse** [comment]
The issue behind it is that it's specifically based off of the corpse instead of how long you are there, leading to double-triple pukes off of corpses in a few seconds, instead of you actually smelling the rotting corpses.

**Comment by KasparoVy** [comment]
Rapid-fire chaingun pukes holy crap

Always funny hanging around a busy, poorly-managed cloning room

**Comment by NTSAM** [comment]
Good thing the SYNTHETIC MASTERRACE don't got noses, amirite.
