### ISSUE TITLE
Borg can run with 0 energy

### ISSUE THREAD

**Issue by Urbansprint12** [ParadiseSS13/Paradise#24451]
### Exploit Reports

- [X] I confirm this issue is not an exploit. (Required)

### BYOND Version

515.1630

### Issue Description

During the round as a borg I had my battery completely drained by a revenant but could keep running. Any subsequent time my by battery ran out of charge I was still able to function as normal hold using any of my borg module tools.

### What did you expect to happen?

To power down immobile and only being able to give a low battery alert ping.

### What happened instead?

Was able to keep running despite sprite updating to the unpowered variant.

### Why is this bad/What are the consequences?

It is not the intended effect.

### Steps to reproduce the issue.

Have a borg get it's battery completely drained by a revenant.

### When did the problem start happening?

3/5/2024 10PM EST Is when I encountered the issue. But I am unsure if this is a new issue or something that has existed long before.

**Comment by FunnyMan3595** [comment]
CNR.  Spawned a service cyborg, dropped a couple newdles to get low on power.  Spawned a revenant, gave it lots of essence, used Malfunction twice to drain the rest of the borg's power.  Borg couldn't equip a crowbar.

I have a suspicion that you were low on charge, but not fully out, because it does very much look like you're out of power if you aren't experienced and don't know to look at the numeric charge display in your status panel.

* When low, the charge meter will display a single flashing red bar at the bottom of its gauge, and diagnostic hud will show an empty flashing red gauge.
* When extremely low or completely drained, the charge meter will be empty, and the diagnostic hud will show an empty black gauge.
* The only visible difference between "extremely low" and "completely drained" is if you look at the Charge Left in the Status panel.

**Comment by Urbansprint12** [comment]
Ah I assumed when you ran out of power as a borg you'd stop functioning completely such as not being able to move and having no vision like when you're locked down.

**Comment by BiancaWilkson** [comment]
Yep, this is intended behavior! Thankfully borgs don't get sent to the boredom zone for running out of power.
