### ISSUE TITLE
The secway crate "View Contents" does not have any contents

### ISSUE THREAD

**Issue by spacegeese** [ParadiseSS13/Paradise#24556]
### Exploit Reports

- [X] I confirm this issue is not an exploit. (Required)

### BYOND Version

515.1630

### Issue Description

The secway crate "view contents" button has no contents

### What did you expect to happen?

For the View Contents button to allow me to view the contents of the secway crate

### What happened instead?

![image](https://github.com/ParadiseSS13/Paradise/assets/136994596/ff741a0e-92f2-43dd-aa63-99302ca00c28)

### Why is this bad/What are the consequences?

How many secways are in that crate? WE'LL NEVER KNOW

### Steps to reproduce the issue.

Go to any cargo console
Click the "View Contents" for the secway crate
![image](https://github.com/ParadiseSS13/Paradise/assets/136994596/0935b001-95b7-4e88-abeb-50e48e9db0a3)

### When did the problem start happening?

probably when #24460 was merged

**Comment by Oyu07** [comment]
This is the case for other containers aswell like buttlerfly. Images below.
![image](https://github.com/ParadiseSS13/Paradise/assets/66401072/c094dd37-e09b-48fb-8a07-e0241170960c)
![image](https://github.com/ParadiseSS13/Paradise/assets/66401072/a50e3f42-bb85-4140-bffb-6fe5daa8bb96)


Seems like it is caused by TGUI using the contains = list() to display it, but as these large crates dont use "contains" but rather ``new /mob/living/simple_animal/pet/cat(loc)``, it will be empty
