### ISSUE TITLE
Chemists cannot access the medbay on the Raven shuttle.

### ISSUE THREAD

**Issue by Kholdstare2** [ParadiseSS13/Paradise#24920]
### Exploit Reports

- [X] I confirm this issue is not an exploit. (Required)

### BYOND Version

N/A

### Issue Description

Chemists do not have access to the medbay doors on the Raven.

### What did you expect to happen?

Chemists, like all other medical staff, should have access to the shuttle medbay.

### What happened instead?

Access denied.

### Why is this bad/What are the consequences?

While not directly medical doctors, they can and do help out occasionally. Should probably be consistent about access.

### Steps to reproduce the issue.

1) Be a chemist.
2) Board the NTSS Raven.
3) Try to go into the shuttle's medbay.
4) Cry.

### When did the problem start happening?

When the Raven was added presumably.

### Extra information

Noticed on round 39750.

**Comment by Burzah** [comment]
I went and tested this today and things are working as intended. There are two doors in the Raven medbay area. One door is general access, that leads to and from the general seating area. The other door heads towards the bridge. That door access is set for heads of staff only, by design. I will be closing this issue as everything seems to be functioning as intended. If this issue some how arises again, or another issue comes up, please feel free to create another issue. Thank you for making a report!
