### ISSUE TITLE
People that jump off the shuttle land in the CentComm Z-level near the holodecks.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#2518]
![](http://i.imgur.com/8ev0W0x.png)
Been getting a lot of reports on this, then it happened to myself.
Also, small thing, when I got there, I was able to go left or right, but if I went off those south walls, or tried going north, I'd instantly be sucked into the southern direction and unable to go north at all.

**Comment by tigercat2000** [comment]
The south thing is easily explainable, when you step off any shuttle, you step into a trigger effect which continuously throws you downwards until you are no longer on top of a space turf. It doesn't stop just because you hit a wall. (before you ask, yes you totally could bluespace crystal past the trigger effect and end up in the hyperspace, but that's unlikely and fun)

The effects that teleport people probably just had their sanity checking removed for sending them to Z2 or something.

**Comment by TheDZD** [comment]
Somehow I didn't think to tag this as "High Priority" before.

**Comment by tigercat2000** [comment]
oh this is 

well this is probably fixed

**Comment by tigercat2000** [comment]
actually this probably isn't fixed

**Comment by tigercat2000** [comment]
Definately not fixed, I fucked up.
https://github.com/ParadiseSS13/Paradise/blob/master/code/game/turfs/space/transit.dm#L96
The 1 on that line should be a 3.
