### ISSUE TITLE
Statues make the server cry

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#2554]
The server's been chugging from the statue holding up the mob process for 90 seconds. High priority, as this will cause the server stutter heavily.

**Comment by Ar3nn** [comment]
It's not the statue itself, its that the statue breaks the mob controller, without fail, every time I've seen it on a server recently. When the mob controller breaks, all entities listed as a mob have to be handled individually, and even then, some processes break involving things like status updates. Like, for example, you can shoot freely at the monsters on the asteroid with your accelerator/resonator until the mobs update, and if it remembers enough of your shots, they'll 'die' at that point, otherwise they'll react to you for one frame, then the controller freezes for another minute or so.

**Comment by Robertha89** [comment]
Yeah, oddly enough monsters on mining can react for a bit after being killed, often moving, which seems weird.

**Comment by Ar3nn** [comment]
I think those are handled differently than most mobs, because they only seem to update when they move, and I don't know how to elaborate on that. We're getting off topic, though, so if you find me in-game, I can talk on mining mobs more, but when I say that, I refer to the fact that when they die, they still move and can attack if you're close enough.

**Comment by tigercat2000** [comment]
That's probably related to how simple animals handle damage- if Life() isn't running, they don't calculate when they should be dead.

This is a pretty weird bug.

**Comment by Robertha89** [comment]
actually, there is another weird bug where when the space bear moves, it loses the star marks on its fur, or is reverting to the bear icon when moving...
