### ISSUE TITLE
You cant import songs to musical instraments anymore

### ISSUE THREAD

**Issue by 1080pCat** [ParadiseSS13/Paradise#25726]
### Exploit Reports

- [X] I confirm this issue is not an exploit. (Required)

### BYOND Version

515.1639

### Issue Description

title

### What did you expect to happen?

for it to work.

### What happened instead?

the submit button doesn't work

### Why is this bad/What are the consequences?

instruments are broke.

### Steps to reproduce the issue.

1. get a instrument (im using a synth)
2. import a song
3. cry
4. 

### When did the problem start happening?

recently

**Comment by chuga-git** [comment]
Works ok on local for me using most recent master.
![image](https://github.com/ParadiseSS13/Paradise/assets/98280110/d11dbb2f-2582-402c-a9f2-c92865620791)

**Comment by Scribble-Sheep** [comment]
I managed to do this a couple hours ago just fine on life

**Comment by PsudoJudo** [comment]
it dosent work for me either(actively playing as i type this). specifically nothing over 30 lines long can be imported and clicking submit does simply nothing. anything under 30 lines works as normal.

**Comment by Carthusia** [comment]
Its really strange, ive got this to work with about 1300 charactrers in a song, but somtimes less before it will allow it

This all cropped up only a few days ago, so perhaps its linked to somthing updated?

In all my time on SS13 this has never been an issue till this last week

**Comment by longcyber2** [comment]
I had this same issue too. I just made a post, didn't realize this post already existed.

**Comment by Carthusia** [comment]
it makes me very sad

**Comment by lewcc** [comment]
It sounds like this might still be an issue. We need a consistent reproduction for this, however.

**Comment by Scribble-Sheep** [comment]
So, pasting some info from the discord, but this glitch first hit me when I was trying to paste Sea Shanty 2 into the ghost bar's minimoog. Not sure if that might be a way to activate it, but it's not gone away since then.

I did some testing, and I can get the songs to submit if I remove a bunch of characters, but it's not weirdly inconsistent.
Angry Birds theme (1471 chars length) needed to be trimmed down to 1370 in order to submit it..
Sam and Max Office theme (2326 total length) needed to be cut down to 1363.

HOWEVER if I remove the `BPM: 170` at the start of Sam and Max, it lets me play it at 1366 instead...which is 3 extra characters for removing 7.

**Comment by Scribble-Sheep** [comment]
I wonder if the different length limits are bc of how many chords the song has, but it seems to be consistently throwing a fit about anything longer than around the 1360-1370 range.

**Comment by Scribble-Sheep** [comment]
![image](https://github.com/ParadiseSS13/Paradise/assets/46016730/43170410-5dda-4c88-96c7-17aa54514e03)

Trying it with `C,` instead of `C6,` gives me a mere 978 characters total, which given that's got 3 enters (975) that's a max of 487 total notes in a song.

But that's not it, though. You can go past this arbitrary limit by pasting the song up to the point that it stops you, and then pasting the rest in as a single new line, though it sounds....odd when it gets to that long line.

![image](https://github.com/ParadiseSS13/Paradise/assets/46016730/15af8941-da0f-4eff-a55e-29f7a55d6796)

Though, pasting each individual line as a new line works fine, so this doesn't seem to be an issue with the song length, likely just something wrong the "import song" dialogue box!

**Comment by BakKeener** [comment]
I am also getting this problem, it's only allowing me to import songs under 1k Characters when it clearly displays limit to be 300k and there's lots of songs over it. This bug makes it annoying to put in songs over that limit and very tedious to switch songs.

**Comment by Scribble-Sheep** [comment]
Is this still an issue? bc I see #25865 was closed in June, and that seems to be a similar issue.

**Comment by silverplatedelta** [comment]
Unable to replicate, adding tag to indicate verification is needed.

**Comment by longcyber2** [comment]
Updating the game seems to have fixed this for me a while ago. If anyone has this problem, try getting the latest version from BYOND.

**Comment by silverplatedelta** [comment]
Thanks for the info!

With that, Ill be closing the issue as completed. Anyone who experiences this is advised to update their byond.
