### ISSUE TITLE
stealthbox misalignment on diagonal movement

### ISSUE THREAD

**Issue by HMBGERDO** [ParadiseSS13/Paradise#25945]
### Exploit Reports

- [X] I confirm this issue is not an exploit. (Required)

### BYOND Version

no matter

### Issue Description

if you run in stealthbox diagonally into a wall, you will move cardinal, but stealthbox will make both moves, slowly moving away from the center of your screen

### What did you expect to happen?

it should always be in the middle

### What happened instead?

^^^

### Why is this bad/What are the consequences?

bugs bad

### Steps to reproduce the issue.

activate stealthbox, go to a wall, press two movement buttons, enjoy your box walking away

### When did the problem start happening?

no clue

**Comment by BiancaWilkson** [comment]
I looked into this, it seems like it was caused by the extra Moved() called added by #21956. When you initially did the PR, what issues caused https://github.com/ParadiseSS13/Paradise/pull/21956#issuecomment-1824801541 this comment/change to be made? I'm worried that just taking out that statement would just break grabs again.

**Comment by HMBGERDO** [comment]
closing as resolved by https://github.com/ParadiseSS13/Paradise/pull/27351
