### ISSUE TITLE
General Air Control circuit boards are unprintable

### ISSUE THREAD

**Issue by YoureNotTheSharpest** [ParadiseSS13/Paradise#25991]
### Exploit Reports

- [X] I confirm this issue is not an exploit. (Required)

### BYOND Version

515.1620

### Issue Description

the General Air Alarm is unprintable, when it's attempted to be printed an Atmospherics Monitor is printed instead

### What did you expect to happen?

To get a General Air Alarm board

### What happened instead?

I was given the wrong board and there is now a finite amount of General Air Control Consoles

### Why is this bad/What are the consequences?

at the best its just two recipies in the circuit inprinter printing the same thing, at worst it makes it impossible to make General Air Control Consoles.

### Steps to reproduce the issue.

Get your levels in the RND console
Go print General Air Alarm in circuit imprinter
Get an Atmospherics Monitor

### When did the problem start happening?

N/A

### Extra information

I genuinely think I am the first person to fuckin attempt to print a General Air Control Board.

**Comment by pwbokie** [comment]
You pointed this out to me in-game! I'm gonna take a look and see if I can fix it.

**Comment by pwbokie** [comment]
Okay, I believe the actual issue is that the two circuit imprinter options General Air Control and Atmospherics Monitor print the same thing: a "circuit board (Atmospheric Monitor)". As far as I can tell, there isn't any such thing as an Atmospherics Monitor console OR a General Air Control console - only an "Air Sensor Monitor". Putting the aforementioned circuit board into a machine frame results in an Air Sensor Monitor.

My proposed fix is to remove both of these entries from the circuit imprinter, replacing them with an entry titled "Circuit Board (Air Sensor Monitor)", which would print a "circuit board (Air Sensor Monitor)", an item which would completely replace the "circuit board (Atmospheric Monitor)".

This was as hard to write as is probably is to read. Sorry.
