### ISSUE TITLE
Vox internals toggling bugged.

### ISSUE THREAD

**Issue by Rumiluntti** [ParadiseSS13/Paradise#2605]
You can toss away your tank and the internals stay on. You are fine unless you remove your mask too, you can't toggle it back on without the tank.
Sometimes When you toggle your internals off manually, as in not just removing your mask or tank, you can no longer toggle them on.

**Comment by ExitGame** [comment]
Adding something to this.
So, appearently something with the start-round spawned tank/mask is borked.
As we know, a vox internal starts off toggled on, but considering that when you take your mask off, it forces it to toggle off, and thats what happens, but then the tank "reaches" a state of being connected to a mask without it actually being connected to a mask (probably has to do something with the variables not syncing up) and well, then the tank be useless.
I also think that it must happen to Plasmamen Internals because it works on the same principle, but I did not try it out yet.

Happened to me 3 times now, and each time a admin had to set my no-breathe block on to prevent my from dying of oxygen poisoning.

**Comment by pinatacolada** [comment]
This also happens with anesthetics, after removing the tank but leaving the mask still on, the patient still is under. So I guess it's a general internals thing.

**Comment by TheDZD** [comment]
@tigercat2000 As far as I know, only rigsuits have touched internals recently, might be because of that.

**Comment by tigercat2000** [comment]
fffffffff
