### ISSUE TITLE
Binary Communications Loop.

### ISSUE THREAD

**Issue by kitsykats** [ParadiseSS13/Paradise#2616]
After severe damage in a borg body, sometimes when you're brought back online... the binary communications loops so badly the game crashes.
It'll just repeat the messages like a hundred times.

**Comment by Ar3nn** [comment]
I'll add to this, as the one fixing up the borg when this issue was discovered, that it was after printing a new chip. The old one was destroyed. I'll also add, since its on topic, that all borg replacement parts are buggy at best. Radios don't give back department encryptions unless you reset board them and have them select the module again. This could be fixed, I'll hazard a guess at pretty simply, by just throwing a couple lines of code into when borgs receive power and turn on again, to check and give module radio encryptions? The binary one, I have no idea what could happen to cause that. But I do believe it is because it was a printed one.
