### ISSUE TITLE
Pods after escape 

### ISSUE THREAD

**Issue by Ar3nn** [ParadiseSS13/Paradise#2617]
I know almost everyone already knows this bug exists about pods not opening their doors, but I've noticed on several occasions about this, so I thought today I'd open an issue that might help. Every time I have gotten on the security pod since the issue became well-known, it has opened for me,  but I think all the other pods remain closed. Maybe that helps narrow down the cause of the issue?

**Comment by Tastyfish** [comment]
I'm fairly certain it's always caused by people disabling the automated airlocks with the override controls; people mess with the override on both the pods and the escape shuttle airlocks so often it's hard to tell if it's always caused by that or if it ever sometimes bugs out.

Arguably though, the override should be rehauled since you can only force open the inner half of the doors that it's overriding.

**Comment by Fox-McCloud** [comment]
@Tastyfish 

It's not; it's an incorrect configuration; they always end up wrong; every other pod is fine.

**Comment by Tastyfish** [comment]
I swear the engineering pod works, though, interesting.

**Comment by Fox-McCloud** [comment]
They do work, so does security; it's only the arrivals pods that are borked.

**Comment by Tastyfish** [comment]
Ah OK

**Comment by Tastyfish** [comment]
Also so Fox doesn't look crazy, I accidentally hit delete instead of edit: I wrote that the engineering pod works between Fox's 2 comments.

**Comment by Tastyfish** [comment]
Oh yeah, those 2 pods (the arrival pods) just on the wrong frequency for no apparent reason. It never occurred to me to check. Fixing now.
