### ISSUE TITLE
Programmable unloaders don't deconstruct properly.

### ISSUE THREAD

**Issue by fludd12** [ParadiseSS13/Paradise#2668]
Deconstructing them simply duplicates their circuit and leaves them alone. It's technically a duplication bug, but it's almost completely worthless, because NOBODY USES THE THINGS (despite the fact that they're really nice, actually!)

**Comment by Fox-McCloud** [comment]
To be honest, we could probably nuke the damn things and no one would care...

**Comment by Crazylemon64** [comment]
Scientists would care, for the data theory 6 on the boards! Thing is, there's not really many situations where lots of items are being generated at a single spot and need to be sorted into various groups, since we're using the ore reclaimer back on-station instead of the smelter on the asteroid. The assembly line makes me think of this, but would probably need some other machines to make this have a point. Systems with large, interacting components are fun!

**Comment by TheDZD** [comment]
[Programmable unloader](https://github.com/ParadiseSS13/Paradise/blob/master/code/game/machinery/programmable_unloader.dm) circuit code is a monstrosity.

**Comment by Fox-McCloud** [comment]
>Programmable unloader circuit code is a monstrosity.

Or an abomination...maybe even heresey.

**Comment by Crazylemon64** [comment]
Actually, data theory DOES reduce the time it takes for the exosuit fabricator to process, but that's not TOO noticable of an effect. If the underlying code's crusty and unworkable, excise the tumor, sure.

**Comment by CrAzYPiLoT-SS13** [comment]
So, the decision is to cut this heresy in the roots?

**Comment by tigercat2000** [comment]
there isn't a decision anywhere here
