### ISSUE TITLE
Z-levels are bugged

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#2711]
Here is a map i made this round

#5#	#3#	#1#	#7#	#6#	#4#
313	131	444	656	565	777
#4#	#3#	#7#	#1#	#6#	#5#

I believe this can be solved by actually adding 3 empty z-levels. Cause a z-level going to itself???

**Comment by TheDZD** [comment]
Err, not certain how this map works. Do note that Z levels use a torus, as explained in #2193. The PR linked inside of #2193 should have a map that shows what the torus should look like.

**Comment by IAmBigCoat** [comment]
```
  4
  ^   
  7
  ^
  5>6>5>
  ^
  1>3>1>3>1
  ^
  4
```
The map seems to work out fine. It just doesn't make a ton of sense from a topological standpoint because all our Z-levels are the same size and our space people only move in two dimensions, which makes the shape sort of non-donut-like. (Because most people think of single-hole things when they hear the word torus.) If it were a single-holed torus, heading North then East would be the same as East then North.

I'm sure it's technically a multi-holed torus by topological standards but I just think of it as interconnected space loops.

**Comment by Tastyfish** [comment]
Yeah, the topology is really weird, but I'm pretty sure the behavior describe is what's intended. It is indeed multiple toruses connected in an arguably non-euclidean manner.
