### ISSUE TITLE
Putting an IPC into an activated cryo cell makes them fall asleep.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#2741]
Exactly as it says on the tin.

**Comment by Robertha89** [comment]
when an IPC is cooled down beyond acceptable parameters in a non-conductive liquid, they temporarily go into Sleep Mode, due to the fact that NT is shit at everything they do, and NSS Cybariad just being a Science Experiment, anno Vault Tec, where you collect an random number of retards on a station, to work together for a few hours, but I digress, after exiting the Cryo Cell, it takes time to do a complete system check, and purge any remaining chemicals not on the list of accepted chemicals, before a full re-boot awakes them from their sleep mode, shaking a sleeping IPC in this state will shake out fluids faster, and thus wake an IPC faster.

**Comment by tigercat2000** [comment]
also known as, cryo cells don't discriminate, and IPC's don't need another snowflake exception

**Comment by Spacemanspark** [comment]
They didn't fall asleep before.

**Comment by tigercat2000** [comment]
someone probably removed something weird then

**Comment by Plotron** [comment]
Seriously, wouldn't your PC shut itself down if it reached absolute zero? I feel it's for the better.

**Comment by tigercat2000** [comment]
This can probably be closed and marked as a feature request, because it would require yet another snowflake exception for IPCs.

**Comment by Tastyfish** [comment]
Put your cellphone into your freezer and see what happens. I don't really see why this is an issue.
