### ISSUE TITLE
Turbine upgrade breaks it.

### ISSUE THREAD

**Issue by GelatinousGlob** [ParadiseSS13/Paradise#2746]
I moved the turbine to atmosia and built it to produce 120,000 watts stock. Upon upgrading it with femto manipulators and quadric capacitors, it briefly gave 500,000 watts then just stopped running. 0 RPMs 0 power. I went in containment and messed with it a bit, opening and closing the hatch on the turbine lower part would briefly (less than 1 second) give the turbine a few RPMs and power and then it would instantly stop again. Could not fix, unknown cause. Possibly the upgrade parts? Ive had turbines running before with other upgraded parts no problem.

Possibly because science originally only gave me 5 femto manipulators instead of 6? I put another one in later but didn't realize the mistake the first time until afterwards. Still didnt fix it.

**Comment by Taaketa** [comment]
This sounds like awfully similar to #1850. TEG behaves the same when you hit a certain pressure point. On other servers I know the TEG can make a lot more from a lot higher pressure.

**Comment by Markolie** [comment]
I don't think it's necessarily related to the upgrade - this is probably mostly related to the RPM of the turbine in general. My guess is that if the RPM hits a certain height the maximum RPM is reset, which also resets the RPM. And because the gas/maxed out components make it so easy for the turbine to hit the ceiling very quickly, it will no longer get any RPM up.

I'm not sure how to fix it though... Looks like /tg/ has the same issue, they've just never reported it. 

(It kind of makes sense there's a hard cap on the turbine's RPM: if shit starts spinning too fast, it isn't going to work anymore. Still a bug though, as that's not intended).

**Comment by DesolateG** [comment]
fixed by #8132
