### ISSUE TITLE
Goliath didn't look dead after I killed it.

### ISSUE THREAD

**Issue by Ar3nn** [ParadiseSS13/Paradise#2751]
http://prntscr.com/9aw4zy

Relevant screenshot is relevant. That's about all I know about the situation, nobody was on to respond to my question in ahelp.

**Comment by RudiPardieck** [comment]
I killed a couple, and they showed their dead sprite. Not sure how to reproduce.

Are you sure yours is dead and not stuck or something?

**Comment by Ar3nn** [comment]
I don't know how to reproduce it either. The fact that it happened is basically the beginning and end of what I know. I lazarus'd it and it died properly the second time, even, so it had nothing to do with that particular mob. I know nothing of coding, so I couldn't begin to ask questions in that direction. I was just curious if anyone else could figure it out. Sorry for wasting time if it turns out to be something impossible to find cause for.

**Comment by Robertha89** [comment]
HOW TO REPRODUCE:
Step 1. Be xenobio
Step 2. Breed slimes
Step 3. Kill bad slimes
after a while you will notice a slime or several that are stuck in their alive animation instead of their dead. the fact that is is fucking random is what makes it hard to reproduce.

**Comment by tigercat2000** [comment]
slimes and simple_animals are very different things @Robertha89

**Comment by Fox-McCloud** [comment]
@tigercat2000 

It's still a somewhat valid point though---I can confirm that that does happen with slimes--whatever is causing it form them may be causing it for simple animals as well---MAY be.

**Comment by tigercat2000** [comment]
@Fox-McCloud doubtful

**Comment by Robertha89** [comment]
alternativly you can just spawn goliaths and kill them. Slimes is just the easiest way to reproduce ingame wtihout the use of admin tools, as admin tools tend to skew it off. 

The issue is, it's rare, and there are what 30 mobs on mining? thats too small of a sample.

Issue is, icon does not update on death, so it's either a proc they share that is derping out, or something in like carbon/life.dm that is borked, probably the only reason you do not see it more often, is cause humans dont have any life animations, and thats the only thing that dies in a high quantity.

**Comment by Ar3nn** [comment]
Well, I'm glad something came of my report, as ill-informative as it was!

**Comment by Fox-McCloud** [comment]
I can confirm that this does, indeed, happen; was mining yesterday---while I didn't notice it with goliaths, I did notice it for hive lords, though it was very rare.

no idea what's causing this.

**Comment by fludd12** [comment]
Wasn't this fixed?

**Comment by Aurorablade** [comment]
@Crazylemon64 @Fox-McCloud may be fixed.
