### ISSUE TITLE
Strange seed fruits can contain old chems.

### ISSUE THREAD

**Issue by Mijhead** [ParadiseSS13/Paradise#2798]
As far as I am aware, Lithium sodium tungstate is a chem that's been out of the code for a while, but I got it in a fruit recently. I suspect that fruits might still pull from old chem lists, including baychem.

**Comment by Ar3nn** [comment]
Since they're out of code, are they functionally useless, then? Like, or can you still use them the way they were before?

**Comment by Mijhead** [comment]
Well, Lithium sodium tungstate was for some very obscure old xenoarch usage, and I haven't gotten any other reagents to try it with, so it's mainly a suspicion right now, but based off of what I already got.

**Comment by Keilden** [comment]
Same thing with pills in Strange Pill bottles.

**Comment by TheDZD** [comment]
@Fox-McCloud or @FalseIncarnate ought to know more about this as our resident chem/botany nerds.

**Comment by FalseIncarnate** [comment]
The issue is not that these chems are being included in randomization, but rather that they are included in the code without any use.

Commenting out / deleting the reagent datums for these chems would be the best course of action if they are not used for anything. If they ARE used for something, but shouldn't be included in randomization for some reason, then they should be added to the blacklist.

Not sure if this is a bug, or a removal request.

**Comment by Fox-McCloud** [comment]
They can quite literally have every single chem in the game in them, minus a small blacklist of chems that are "too powerful" to be in random seeds (Initro, stimulants, etc). Lithium-sodium-tungstate is a reagent that is still around, for whatever reason---it being in there is just "bad luck" and not a bug.

That reagent, in particular, should probably be removed.

**Comment by Mijhead** [comment]
Just wanted to make sure it was intentional!
