### ISSUE TITLE
Ripley pretty much broken down will never move again and possibly related heat bug

### ISSUE THREAD

**Issue by Ar3nn** [ParadiseSS13/Paradise#2805]
http://prntscr.com/9cqurg

Ripley broke down, fully repaired it, but...

http://prntscr.com/9cqvdp

No issues other than a tank temp of 6000C, the cabin temp is 50C and I still take damage faster than Diona heal while riding, and it cannot move.

**Comment by Ar3nn** [comment]
http://prntscr.com/9cqwau

After riding in it for a couple minutes, almost critical.

**Comment by Crazylemon64** [comment]
Is this able to be reproduced?

**Comment by Jovaniph** [comment]
I had a similar issue about this. My job was a Roboticist, and some Shaft Miner brought a Ripley that had been damaged. I manage to fix everything but the Ripley kept draining the new batteries I put in it.

I think its more of a missing feature than a bug however because I had admins and mentors trying to figure out why nothing worked.

**Comment by KasparoVy** [comment]
Man that heat bug was such a throwback. Back when I first started playing it cooked me alive a few times and I thought I got fucked over by a 'solar flare' or some shit.

Haven't seen it in years.

**Comment by Fox-McCloud** [comment]
You can still get cooked inside it, under the right conditions.

There *IS* a damage flag for mechs that's like `damage_internal_fire` or something; that can cause you to heat up, yourself.

That said, damage oddities should be far more consistent now.
