### ISSUE TITLE
Logging out and back in as a simple mob Bursts their eardrums, Apparently

### ISSUE THREAD

**Issue by AceMcLazer** [ParadiseSS13/Paradise#2841]
When you disconnect and reconnect as a simple mob, Pets, Mice, Scarab swarms etc, you sudden become deaf and unable to hear. 

...You almost hear someone talking...

Can be fixed by a admin Rejuv, but that seems like busywork for the admins

**Comment by Robertha89** [comment]
There is also a var they can change to fix it, this is a old bug that has returned. I blame the the changes to simple_animals

**Comment by Crazylemon64** [comment]
The problem is that on logout, sleeping on simple animals is set to true, which will mute all heard messages, but on login, sleeping is never reset. In addition, simple animals never tick down sleeping, as that is handled in carbon/life.dm, under regular_status_updates, and no such handler exists under animal code. You can still walk around as an animal while "sleeping" because the consciousness variable doesn't adjust when sleeping is set as a simple animal.

**Comment by AceMcLazer** [comment]
@Crazylemon64 Ahh. See, I'd thought as much, because the text was the same for what you hear while sleeping as a Normal Player.

Which, to me, A non-coder, someone who does not really know the first thing about programming, still does not make much sense honestly, because logging out as a Alien larva (i'm assuming is also a simple animal), and logging back in I was still able to hear properly.

Could the Handler perhaps be "borrowed" over to the Simple Animal mob type? or maybe a periodical tick to update their status? or would that upset the Mob type's delicate balance?

I'm not trying to talk out of my ass, when it comes to code. Just a Layman's Idea.

**Comment by tigercat2000** [comment]
huh
living/Life() should probably just tick down sleeping
