### ISSUE TITLE
Losing cargo access doesn't impact the blueshield one bit.

### ISSUE THREAD

**Issue by Fishocalypse** [ParadiseSS13/Paradise#2857]
They can easily jut walk over to RnD to begin printing out ammo instead of going to cargo. A previous PR locked them out of going into cargo, but you only require basic science access to enter RnD.

**Comment by Plotron** [comment]
IMO that's IC issue.
If people refuse to print shit for you, then elevate the case. You should have the Captain on your side - after all, his life depends on your revolver.

I can see a good argument against cargo access, but not against basic RnD access. Oftentimes there's an emergency with RD in the Proto/Autolathe room. HoP rarely goes to cargo.

**Comment by Fishocalypse** [comment]
Likley, but there was a whole discussion about it on github. It seems pointless to remove basic cargo access to prevent blueshields from printing ammo when they can just take ~5 minutes to walk over to RnD and print over a few rounds of ammo/lethals without talking to anyone.

**Comment by Robertha89** [comment]
honestly, it seems pointless to have to begin with, the blueshield got basic departmental access to places where head of staff tend to be, thus he got access to space, engineering, brig and security, medbay, and science. Also, you can just ask cargo to print it, if they won't go to science, I doubt the access will change, since it was a huge drama before it changed. It's fine as is. I mean it's like saying "Why not give blueshield all access, they can just walk over to the HoP or Captain and ask for it and get it." I mean it seems odd, but it's unlikely to change.

**Comment by Plotron** [comment]
Removed cargo access also means that he can't order crates himself.
You want that cargo access restored or what? Is that the point of this "Issue"?

**Comment by Earthdivine** [comment]
The cargo access removal was so he couldnt walk into the lobby and start printing off ammo for his revolver without the QM's say, along with cutting down on Securi-Shields back then.

**Comment by Fishocalypse** [comment]
There's two different levels of cargo access, Plotron. One for the main lobby area and one for the actual warehouse(the one which is required to actively use cargo consoles). I'd rather have standardization in whether the blueshield should even have access to an autolathe or not.

Earthdivine, the blueshield can do the same thing by spending an extra minute going to science while printing off extra ammo.

**Comment by Spacemanspark** [comment]
As a scientist, I've tabled --> disposaled Blueshields that think they can make things randomly in RnD.
It's highly obnoxious.

**Comment by tigercat2000** [comment]
This isn't for the issue report sections, this is for the suggestions part of the forums.
