### ISSUE TITLE
Moving Nano UI Iterfaces

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#3016]
So, when a NanoUI window refreshes, it moves slightly down and to the right.

This is annoying if you're doing something like chemistry or virology and refresh the window a lot, as the window inevitably shifts from where you want it to be.

**Comment by Ar3nn** [comment]
Can confirm, I do really dislike this. Affects medical as well, the body scanner and sleepers I believe do the same thing. Just in case you have to apply whatever fix individually to each window.

**Comment by Spacemanspark** [comment]
Heard from someone that this is actually a Windows issue.

**Comment by CrAzYPiLoT-SS13** [comment]
It is. Try it with any Windows dialogue. It isn't an issue, per se. It is
an accessibility feature.

**Comment by tigercat2000** [comment]
this literally isn't possible to fix without very hacky workarounds

**Comment by PsiOmegaDelta** [comment]
Ah, I remember similar issues from Bay. As I recall it the issue was that someone tried to update the window by calling the ```ui_interact()``` (often indirectly through another proc like ```interact()``` or ```attack_hand()```) proc instead of ```nanomanager.update_uis(src)```, which would force close and re-open the window.
I could do some digging to double-check.

**Comment by tigercat2000** [comment]
If `ui_interact()` isn't supposed to be directly called via `attack_hand()/attack_alien()`, then we have a fairly significant issue, as every UI we currently have does exactly that. If I recall correctly, Nanomanager also does this in order to actually gather update data, as there is no `seperate` proc for nanoUI data lists- It's all handled inline under the `ui_interact()` proc.

**Comment by PsiOmegaDelta** [comment]
I admint, I wasn't clear enough. Note, on Bay the proc currently looks as follows: ```ui_interact(mob/user, ui_key = "main", var/datum/nanoui/ui = null, var/force_open = 1)```.

What I meant was that many older pieces of code would refresh the interface in Topic() by calling interact()/attack_hand(), etc. These in turn typically call ui_interact() with the force_open flag untouched (= 1), thus causing the full window refresh.

The Nano UI manager should be calling the same proc with force_open set to 0, be it when called manually (using ```update_uis()```) or automatically (having set the auto refresh timer), which avoids the force opening.

Preventing the window from moving about when someone intentionally clicks equipment with the window already open is much trickier to deal with yes, due to the reason why the force_open flag was added in the first place.

**Comment by tigercat2000** [comment]
Oh, I get you, right. So this is probably specific UI's that are getting fucked up.

**Comment by tigercat2000** [comment]
so @Fox-McCloud could you come up with a list of all the UI's that currently do this?

**Comment by Fox-McCloud** [comment]
- Chem Dispenser
- Pathogenic Isolator
- Pathogenic Incubator
- Disease Splicer
- Smart Fridge
- Vending Machines
- Crew Monitoring Console
- Air Alarms
- APCs
- Fire Alarm

I'm sure there's more.

**Comment by tigercat2000** [comment]
@Fox-McCloud Are you sure about Fire Alarms? Because that's the one I definitely know doesn't normally move about when refreshing for me at least
