### ISSUE TITLE
Internals leak onto tiles

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#3146]
Basically the reason why people yawn when on the surgery table even without internals.

**Comment by tigercat2000** [comment]
Not a bug, just an unfortunate consequence of how breathing works. No real clean solution, either.

**Comment by Plotron** [comment]
http://nanotrasen.se/forum/viewtopic.php?f=48&t=6248
Not a bug.

**Comment by IAmBigCoat** [comment]
It's not realistic, but you could just have the entire breath converted into whatever the exhale type is, instead of only partially. It's not realistic and it's a waste of oxygen for everyone who doesn't need internals, but it'd fix the leaking issue.

**Comment by Vivalas** [comment]
It is actually completely realistic, in real life dentists have been documented getting high off of the N2O their patients exhale. This is in part due to the fact N2O doesn't metabolize well in the bloodstream. The game does not actually simulate the metabolism of gases in the blood (but it does for reagents). The game simply dumps most of the gases back into the environment that were inhaled in the first place. While this doesn't actually simulate real life metabolism, the end result is the same, which is neat.

**Comment by IAmBigCoat** [comment]
Right. I meant my suggestion wasn't/isn't realistic, but would fix the deadly gas leak issue. The current system's actually a reasonable-enough approximation of reality.

**Comment by Vivalas** [comment]
Debate on the forums relevant to the issue generally concluded the issue wasn't that bad for plasamamen, due to the fact that even SSD plasmamen generally only exhale enough plasma for one tile orange fires, if that.

**Comment by IAmBigCoat** [comment]
But... GIGGLING PATIENTS MOMENTS BEFORE SURGERY!
