### ISSUE TITLE
Wizard Winrate is 2 last year

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#3151]
as in two successfull wizards... Honestly, wizard has been hard nerfed so much, and i blame /tg/ godhand bs, 

Something anno 

```
/obj/effect/proc_holder/spell/aoe/disitegrate

	if(!is_mob && isturf(src.loc))
		for(var/mob/H in oview(src,1))
			if(src)
				continue
			gib(H)
	..()
```

Replace the vealrenders with veilrenders, I mean honestly, space wizards should be feared, not "oh, looks like another 10 minute round, lol"

**Comment by Robertha89** [comment]
Remove i ded tag please, I am one of the successfull wizards.

**Comment by Crazylemon64** [comment]
This DOES sound like a good excuse to give them a bunch of hilarious tools...
*sinisterly rubs hands together and cackles*

**Comment by Fox-McCloud** [comment]
Wizard has *always* had a horrendously bad win-rate, even when we were much higher RP and had less amounts of robust/knowledgeable players; it's just the nature of the antag; you're a single powerful entity vs the entire station, and one small screwup is going to cost you your life.

TG's wizards are considerably more powerful than ours are, and yet their win-rates are still in the single digits.

Also part of the problem is...wizard is rare and only one person gets to be the wizard, so generally there's veryyyy few experienced wizard players unless they've been playing for a good year or more.

**Comment by Spacemanspark** [comment]
Make the wizards into a full team mode, perhaps.
Have the staff of animation not attack any wizard, as well.

**Comment by TheDZD** [comment]
> Honestly, wizard has been hard nerfed so much, and i blame /tg/ godhand bs,

Wat. The only significant nerf that wizards has received as of late is the thing with disintegrate and flesh to stone becoming actual touch spells, instead of a boring "I click button you are out of the round permanently" spell. If anything, wizards have consistently received buffs in the form of countless new additions to their toolkit over the last year or so; however nobody ever seems to use them, despite several items (such as the wand belt) being incredibly versatile and/or powerful.

That said, there is still one major problem with wizards, that being that their spell selection is incredibly limited. Magic missile and one or two mobility spells are necessary if a wizard wants to survive even one encounter with security. Giving those to the wizard by default could definitely help diversify the choices wizards can make with their spell selection, and would likely result in less 10 minute wizard rounds. 

Fox makes a fairly good point, wizard is a rare gamemode, in which only a single player is chosen to be the antag, and is set against the entire station. This sort of situation isn't exactly forgiving, and makes it very difficult to actually *learn* how to play as the wizard.

**Comment by Crazylemon64** [comment]
Ragin' Mages, anyone?

**Comment by TheDZD** [comment]
@Crazylemon64 That gamemode fixes the issue of wizards being "one person versus the world," sadly it's completely broken at the moment.

**Comment by Crazylemon64** [comment]
Well, I think I know my next project, then...

**Comment by Tastyfish** [comment]
I think another problem wizard has, which is a similar problem in nuke ops, is that the wizard starts trying to murderbone everyone first, (or tries to be peaceful regardless of one of the objectives always being an assasination, heh) instead of just doing their objectives. The wizard spells are ihmo strongly geared toward stealthily going in and precisely accomplishing specific tasks, but I guess the reason people have trouble with this is due to what Fox touched on.

**Comment by Robertha89** [comment]
there are three ways to play wizard. 1. Murder everyone who is a threat, from highest to lowest, starting with the ai, then hos, hop and captain, not in that order, then you kill of everyone with access, ntrep, blueshield, rd, cmo, ce before killing those who are a threat, science, and medical, before taking care of cargo, engineering and security, followed by killing anyone who gets in your way, call the shuttle, keep the killing up till you dominate the station by fear.
2. Mindswap, mindswap literally everyone, it's chaos, and you are likely to lose a spell, which is dumb was added because !funremoval!, also, the worst way of doing it.
3. The most secure way, complete objective, kill/steal/etc, then prepare for your escape.

Now, the main issue behind wizard win rate is, it's a rare gamemode, and all gamemodes should honestly be equal in rarity at secret + random. It's also due too the fact that you never win as wizard people either do try to murder everyone in bad way, or friendly wizard, because they don't stand a chance in hell, Wizard as is is geared towards medium to high rp servers, it's also made for good players.

I mean, take shadowling for example, you can just help the others with keeping people stunned and whatnot, or even do nothing at all, just waiting for 15 thralls, and you ascend, and then you litterally can't fail, even when acended shadowling is rare, because it's so absurdly over powered, but i digress, wizard needs to take from acended shadowling.

Even that is not the main issue, Wizard got an issue they share with traitors, they don't get progressivly stronger, they usually get weaker the longer a round lasts, while changeling, vampire, shadowling, cultists all get stronger, thus having wizard balanced by, say using spells, and upgrading some of them, flesh to stone and disintergrate mainly from hand to aoe, and make them stronger by successfull use, i.e lower cooldown.

Also, wands was mentioned, and it goes along with the weaker as the round progresses thing of thoughts, each wand got anywhere from 8 to what, 16 uses? That makes it not worth it, mainly since wizard only happen after 30 players, and often it's 60-80.

Fixing it would not be too hard, issue is getting the changes merged, and best way to start is by pointing out the issue, as an issue. I mean, I want to be afraid of wizard, not lol no threat here.

**Comment by Crazylemon64** [comment]
Ragin' Mages, again.

**Comment by Earthdivine** [comment]
Wizards barely got nerfed. No one knows how to play it. That's all that the issue is.

**Comment by Deanthelis** [comment]
It's not just nobody knowing how to play it, it's also people not paying attention to other wizards when it's someone else's turn.

**Comment by Crazylemon64** [comment]
Can't... wait... for ragin' mages...

**Comment by HereticChurch** [comment]
The objectives the wizard gets should be altered, I think. Removing the Hijack and Escape Alive objectives and just giving them assassination and theft objectives might be nice, or some interesting unique objectives.

**Comment by Tastyfish** [comment]
This should probably be a Suggestions forums thread.

**Comment by Robertha89** [comment]
suddenly i got an idea for an Arch-Wizard mode....

**Comment by Fox-McCloud** [comment]
>This should probably be a Suggestions forums thread.
