### ISSUE TITLE
Necrosis Symptom Bug

### ISSUE THREAD

**Issue by fludd12** [ParadiseSS13/Paradise#3169]
So, apparently, the necrosis symptom in viruses tends to break... a lot of things. Someone, at the time of writing, has a Toxins damage value of " " and a similar oxygen damage value. Not only that, but they seem to be stuck in some sort of limbo of not being able to do things but also not dying, and you can't examine them.

What the everloving hell.

**Comment by Regen1** [comment]
http://puu.sh/mKD6G/85327a92ca.png

**Comment by Crazylemon64** [comment]
The ORGAN_DEAD tag for external limbs is likely busted as all heck.

**Comment by LufgtHuron** [comment]
Supporting this issue as I infected myself with necrosis to see what it would do. 

Here's a list:

* Didnt change the sprite to the correct one
* Made me unable to use my inventory - I had a vial in my hand, couldn't do anything to it other than drop it. 
* I was unable to examine myself - whether it was with shift click or left click with help intent. 
* It removed 7 other symptoms. I was infected with two viruses, one that dealt brain damage (it was filling me with meth I believe) and other that cured it,
* After being stunbatoned (because HoS could somehow click me) I wasn't able to get up until the round ended.
* Energy guns set to non-lethal didnt work on me. This means that if I didnt slow down to let the HoS baton me to see if it would work, I was practically unstoppable (but also unable to do practically anything).
* Uncuffing didn't work either.
