### ISSUE TITLE
Outpost exterior becoming 'cold'?

### ISSUE THREAD

**Issue by kylejen** [ParadiseSS13/Paradise#3197]
![The Picture](http://puu.sh/ms7TE/84ad11c87c.png)
Not sure how to explain this one but why would the 'space' (or in the case, the dust on the outpost which has no atmosphere) become 'cold' (and get applied the freezing overlay that usually gets applied inside the station) 

I've only seen this on the outpost in the gateway.
Another Example: http://puu.sh/ms8bh/23e3d10d96.png

I don't know if it's exactly an issue, but it just seems a bit strange.

**Comment by fludd12** [comment]
Things only really become cold when there is air to be cold, and so when the doors are opened, a minute amount of air escapes, and freezes on the surface. This is actually kind of sense-making, really.

**Comment by FalseIncarnate** [comment]
it's exactly as Fludd12 phrased it. When the door opens, some air gets out. That air then freezes because it comes into contact with near absolute 0 "atmosphere" on the asteroid turf there (it's technically airless, but that means it also has a 0 temp for when you do add air to it), thus causing the overlay.

Not a bug.

**Comment by kylejen** [comment]
Ah, that makes sense. Thanks you two.
Feel free to close this if you think it should be.
