### ISSUE TITLE
Borers are not affected by sugar

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#3210]
they should be put to sleep, but their not.
Also, they take over stupidly fast now.

**Comment by TheDZD** [comment]
They [should be affected by sugar just fine](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/simple_animal/borer.dm#L72), were you eating a sugar pill, or some food item to try to put one to sleep?
The takeover time hasn't been changed in well over a year, it's 30 seconds plus 5 times the host's brain damage.

**Comment by Crazylemon64** [comment]
Sugar doesn't look like it actually makes the borer unconscious, or prevents them from secreting chemicals. The only thing it prevents, is assuming direct control. Should its effects be enhanced?

**Comment by TheDZD** [comment]
@Crazylemon64 [It should be preventing them from secreting chemicals](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/simple_animal/borer.dm#L256-L258), since having sugar in the host's reagents sets the docile var to 1. To my knowledge, it has not specifically knocked out the borer in quite a long time, if it even ever did that.

**Comment by Crazylemon64** [comment]
Oho! I missed that check! As for whether it actually sets the docile variable, I haven't been able to test, however...

**Comment by Robertha89** [comment]
Sugar is supposed to put the borer to sleep.

**Comment by Fox-McCloud** [comment]
No, it's not....It's been this way for literally ever.

**Comment by TheDZD** [comment]
Closing this as this isn't a bug, and the balance complaint is about a change that was never made.
