### ISSUE TITLE
Curse of the Horseman spell/Changeling transformation sting non-functional

### ISSUE THREAD

**Issue by Doukhan** [ParadiseSS13/Paradise#3217]
As per title, thanks to my crappy hardware I suffer from a lot of client side problems, but these two have been consistent for a while.

The wizard spell pops up some blue text in the chatbar that "it'd be silly to cast this on -intended victim- and does nothing, and the ling sting won't even get to the "you prepare your sting" stage, just nothing.

As mentioned above this may or may not be caused by stuff on my end, but here's the helpdesk right? ;)

**Comment by TheDZD** [comment]
I believe that the wizard spell will fail on anybody wearing any kind of had, which admittedly makes it useless. As for the transformation sting, I will have to take a look at that.

**Comment by Crazylemon64** [comment]
Wouldn't it be as easy as, like,  to have it get rid of the hat if the hat isn't NODROP, like the horseman virus does?

**Comment by FalseIncarnate** [comment]
For the horsemask spell, it actually gets caught up on a logic check that seems to have been written in such a way that the spell is unable to be cast on humanoids.

I noticed this a while back, but didn't fix it at the time due to being outside the scope of the PR at the time (broomstick horses), then forgot until now.

Not sure on the changeling one, probably a similar issue with a bad check.

**Comment by Lady-Luck** [comment]
Still active.

**Comment by Aurorablade** [comment]
@Crazylemon64 @Fox-McCloud looks like was fixed

**Comment by DesolateG** [comment]
If this was fixed can we get it closed please?
