### ISSUE TITLE
Can't bless water to holy water

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#3229]
Basically, this line https://github.com/ParadiseSS13/Paradise/blob/c7ae1fef0db8acfe4111036d5ff337507b2538ab/code/game/objects/items/weapons/storage/bible.dm#L103
does not work.

**Comment by TheDZD** [comment]
The logic on that specific line looks fine to me and has not been changed as of late (and water blessing was working fine at least a few weeks ago). If you would actually start explaining the situation in which you experienced or witnessed this bug, explaining it would be helpful.

**Comment by Robertha89** [comment]
Righto!
Step 1. Be Chaplin. Step 2. Hit water tank bible. The message that the water tank has been blessed does not respond, nor does it respond for anything else other then floor tiles.

**Comment by Plotron** [comment]
3a) Use a reagent scanner to scan for holy water, or alternatively  3b) pour the water into glass to see if it's murky and named *what....?*

**Comment by Robertha89** [comment]
reagent scanner says the name of water and holy water is... water, which makes it hard to check. but the glass one is valid.

**Comment by Fox-McCloud** [comment]
Please at least freaking test your things before submitting a bug report and get confirmation that it is the case before filing a kneejerk reactionary bugfix about it:

![img1(https://i.gyazo.com/fa14bf2012a994e7cf94f535da8721a2.png)

So yeah, please test and confirm before submitting, otherwise this is going to happen:

![img2](https://i.gyazo.com/ae813cde2adab8486fcf3ebaf2638e88.png)
