### ISSUE TITLE
Removing a posibrain from an SSD IPC results in an empty posibrain

### ISSUE THREAD

**Issue by marlyn-x86** [ParadiseSS13/Paradise#3281]
<a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/logout.dm#L4-L5>This bit results in the IPC's mind becoming inactive on SSD.</a>
<a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/datums/mind.dm#L93-L94>These two lines prevent an SSD mob from having their key set.</a>
<a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/organs/subtypes/machine.dm#L105-L115>Thus, the brainmob's key doesn't get set.</a>
<a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/brain/posibrain.dm#L19>Without a key, you can request a new posibrain personality.</a>

**Comment by Plotron** [comment]
*I shall harvest the brains!^

**Comment by Ar3nn** [comment]
You can reset a brain even if it's occupied, or could last I checked. Use it in-hand, it wipes and simultaneously asks for a ghost to fill it.

**Comment by Crazylemon64** [comment]
Oh, so if the brain's client has left, then...?

**Comment by matt81093** [comment]
What would be an appropriate solution? The brain can keep the player key info sure (in some mannor), but they can still be replaced. Also can anyone confirm if this is still an issue? Attempting to, but was placed immediately in a borg last time.

**Comment by Will-Bohlen** [comment]
Testing this now, looks like it isn't an issue anymore.

Brain removed from SSD IPC:
![image](https://user-images.githubusercontent.com/15622691/175859866-28f5092f-dc9f-48f5-a570-476720377c85.png)

SSD player can successfully rejoin as the brain:
![image](https://user-images.githubusercontent.com/15622691/175860326-dcc564a8-49c8-4100-b523-6de7a86acb78.png)

...and even continue playing after the brain is returned:
![image](https://user-images.githubusercontent.com/15622691/175860857-33f66081-5f19-4349-95d7-04ef42f3efeb.png)

Guessing that somewhere in the many refactors since the issue was made, it got solved on accident.

(no IPCs were harmed in the making of this comment)

**Comment by Will-Bohlen** [comment]
> e

Don't think so. Activating the brain only toggles the speaker, I couldn't find any way to make it search for ghosts.

**Comment by matt81093** [comment]
@SteelSlayer Is that a desired feature if they have been ssd for a length of time? Actually, it's been a while, so it might be. I really need to brush up.

**Comment by Miraviel** [comment]
> @Will-Bohlen At the stage when the brain is removed, and the IPC player is SSD, could you activate the brain in hand and have it search for ghost candidates? That seems to be one of the issues from the original post.

If the player ghosts from their posibrain, it can be re-activated to look for candidates.

Every problem in this issue report has been fixed over the years.
