### ISSUE TITLE
Efficient Money Trees literally break the client.

### ISSUE THREAD

**Issue by Dumbdumn5** [ParadiseSS13/Paradise#3471]
I'll put it simply. A player was really efficient with money trees with 20 credits per seed popping out very rapidly.

This got to the point where anybody within rendering distance of botany, as far as bar, lost connection and could not reconnect until dragged out of the area.

All I know is deleting all of the food and seeds appears to have fixed the problem. Keroman may know more.

**Comment by TheDZD** [comment]
@FalseIncarnate

**Comment by Fox-McCloud** [comment]
I doubt this is a problem specifically with the; all you're doing is creating new instance of money (which don't really have any particularly special properties).

This seems like it's a combination of things...could be wrong though.

**Comment by FalseIncarnate** [comment]
As fox said, I rather doubt this is an issue with money trees, or any part of botany. That aside, I have no clue as to what could cause this, perhaps something related to [crashes near the tesla engine](https://github.com/ParadiseSS13/Paradise/issues/3422) is to blame, due to sheer number of objects to render.

**Comment by Kerroman** [comment]
Well basically we had all but 3 trays full of money trees with 20+ Potency and using Robust Harvest, so there were lots of seed piles and lots of money piles.  There wasn't any food on the ground that I'm aware of but the smartfridge had tons and after we were able to reconnect the chef remarked that the fridge was no longer functioning (although there was still power to it.)

It really does seem like it was just a perfect storm of things that caused it.

**Comment by FalseIncarnate** [comment]
For the record, the cash pods from the money tree are considered food, though why you'd actually eat one is beyond me.

The fridge not working was likely just coincidence, or caused by the admin intervention causing the machine to freak out.

I'd have to guess it was simply a matter of too many objects in the area that caused the issues, which would be a BYOND issue and thus not something we can feasibly correct. However, I will try to confirm that hypothesis when I get some free time.

**Comment by Vivalas** [comment]
Newer versions of BYOND have been rather instable when it comes to rendering objects, like crashing while teleporting as AI. Also not sure how BYOND renders objects on the client side but it's wierd that copious amounts of offscreen objects crash the client.

**Comment by Spacemanspark** [comment]
This is why I'm extremely worried about when Paradise will push an update that will force me to update my Byond version.
All the newer ones after 508.1292 crash a lot more, in my experience.

**Comment by tigercat2000** [comment]
@Spacemanspark shit already won't work if you aren't running 509, minimum

**Comment by Spacemanspark** [comment]
...I'm able to connect to Paradise just fine and everything works just fine.

**Comment by alexkar598** [comment]
Weren't money trees removed?

**Comment by taukausanake** [comment]
I hope not but it wouldn't be hard to find out. Too lazy though, maybe later

**Comment by Birdtalon** [comment]
Outdated @Fox-McCloud

**Comment by Fox-McCloud** [comment]
these don't exist anymore.
