### ISSUE TITLE
Assault belt cannot hold stun batons

### ISSUE THREAD

**Issue by theColdflame** [ParadiseSS13/Paradise#3478]
I'm not sure if this is intentional or not- It doesn't make much sense.

**Comment by Plotron** [comment]
Military assault belts are like syndi military belts only they hold less.
Whatever that means.

Man, just carry the baton in your bag! Much easier to click.

**Comment by theColdflame** [comment]
Seems pretty odd, considering that it can carry both knives and telebatons, but I guess it's consistent.

**Comment by TheDZD** [comment]
@Fox-McCloud

**Comment by Fox-McCloud** [comment]
Not a bug.

The security belt can hold larger weight-class items, which is why it can hold the stun baton--that said, it can only hold a few very *specific* items.

The military belt, by contrast, can literally hold anything, without item restriction, provided it's the proper weight class---the stun baton is one of those items that happens to be outside of that weightclass.
