### ISSUE TITLE
Weird breath mask positioning!

### ISSUE THREAD

**Issue by Yukiona** [ParadiseSS13/Paradise#3523]
When you face south it looks like they are around your <s>waist</s> chest, I don't think they used to look like that before the mask changes, did they?

**Comment by Fox-McCloud** [comment]
@KasparoVy

**Comment by KasparoVy** [comment]
What species and what mask?

**Comment by KasparoVy** [comment]
Alright, I found what the issue was. Something I had back when I was doing Vox masks, too. I was unsure of which breath mask state to use as reference, and I picked the wrong one. For whatever reason, the sprite with the '_up' suffix is used as the one when the mask is pushed off your face and not '_down'. On it
