### ISSUE TITLE
Bug report - IPC sprite issue when coloured

### ISSUE THREAD

**Issue by eljacko1** [ParadiseSS13/Paradise#3646]
Not sure if this is an actual bug or not, but i noticed that when the body of an IPC is coloured, the sprite sticks out slightly from certain angles. Again, unsure if it's a bug or not, but thought i'd mention it.

**Comment by Crazylemon64** [comment]
Please retitle this issue to be more descriptive of the problem itself!

**Comment by eljacko1** [comment]
ah yes, sorry i'll do that

**Comment by KasparoVy** [comment]
If you could take screenshots that feature the problem that'd be amazing! Thank you. Did you notice this happen in the character editor, or once you spawned in? Maybe both?

**Comment by eljacko1** [comment]
luckily i was in a game right now, so i could screenshot it, and it's mostly when i'm spawned in. The shot shows that part of my leg/foot is showing, yet i'm wearing both socks and shoes. I've not noticed it before i coloured the sprite though.
![image](https://cloud.githubusercontent.com/assets/17344258/13188738/3f0deeec-d74b-11e5-9b10-d427bb5881ab.png)

**Comment by KasparoVy** [comment]
Ah, right. I'll guess that's due to how IPC legs are sprited.
It looks a bit like a dog's leg near the bottom, in the sense that the heel is up off the ground all the time. This is the case for IPCs, and it also means that their 'heels' will poke back out of uniforms (pants) most of the time, unless you're wearing boots, your uniform is adjusted, or you have a space suit/hella long jacket on. It's only a single pixel, it appears. To sort this out, one would have to sprite every uniform this happens with in the leg region in order to accommodate that one pixel

**Comment by TheDZD** [comment]
The alternative of course is to remove said pixel from IPC sprites entirely.

**Comment by eljacko1** [comment]
ah, yeah i see the problem with that. Well, i thought it was worth mentioning so you're welcome.

**Comment by Henri215** [comment]
Its only one rogue pixel on the west/east directions next to the foot, and only with one type of chassis.
