### ISSUE TITLE
Closet Bugs

### ISSUE THREAD

**Issue by Gummin** [ParadiseSS13/Paradise#3687]
**Problem Description**:
With a macro of the Toggle-open verb you can get just about any amount glass shards in the a locker and do ridiculous amounts of damage for what it is.
I suppose my point is lockers should be tweaked a bit, like attempting to avoid leaving a locker counting as walking.
Same as how lockers used to slip you if there was a slippery item in the locker when opened.
You also can use the Toggle-open verb to open closets through glass.

**What did you expect to happen**: 
For this to hopefully not be the case.
I honestly have nothing to put here.

**What happened instead**:
This being the case.
I honestly have nothing to put here either.

**Why is this bad/What are the consequences**:
Leaving a locker counting as walking is generally annoying and could probably be used for many other things that are somewhat unintentional.
And being able to open closets through glass is just strange.

**Steps to reproduce the problem**:
Would prefer to not make this repetitive by copy and pasting the beginning.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
_Sorry for the horrible use of half of the categories._

**Comment by Robertha89** [comment]
well, the stepping on one glass shard vs stepping on hundred is working as intended, and used to be a popular way to kill people, cuff, remove shoes, drag over a few times, it's still used, but rarely in a great amount, and more often by accident or not. This seems to be more of an issue with the closet code, rather then it being an exploit, since leaving the closet counts as 'walking', since you can also put 8 people in a closet, spam the macro, and get dirty floors. This is more difficult then cuffing someone, removing their headset, and spacing them.

**Comment by Gummin** [comment]
@Robertha89 I do think it could be toned down a bit though.
But closets have a lot of issues yeah, like being able to be opened through certain obstructions and other things like that.
