### ISSUE TITLE
Nano UI issue

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#3729]
**Problem Description**:
The Nano UI has been reported as broken. It doesn't show up at all, supposedly.

**What did you expect to happen**: 
The interface to show up, and life to be good.

**What happened instead**:
Blank Screens of Doom using PDA's, APC's, Computers, anything using the Nano UI

**Why is this bad/What are the consequences:**
This seems self explanatory.

**Steps to reproduce the problem**:
Relogging, Toggling fancy UI on and off

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Cult round, happened after a patch. The person who reported to me said it was fine yesterday, not so much today. Contact Codenamegordan if you require additonal information.

Edit: They tried cache clearing, as well trying Byond Beta. Nothing happens.
Expanding on Blank Screen of doom: The window opens with the colour of the Nano UI, but no content.

**Comment by nopm** [comment]
I don't know if it is related to the same issue that happened to me, but apparently this happens because of special characters (ç, ã, unicode, most things ABNT2). I managed to fix that by replacing any "special" character for the "normal" one. Example ç for c, ã for a. I can't really confirm if what happened to you is the same issue, but it's worth giving a try.

**Comment by Anticept** [comment]
I am experiencing this issue from time to time. The game has to be restarted to clear it up.
