### ISSUE TITLE
Comms Report Paragraph Bug

### ISSUE THREAD

**Issue by TullyBurnalot** [ParadiseSS13/Paradise#3741]
When using the Communications Report Administrator verb, any paragraphs are instead replaced with "##" (sans quotation marks), with the text continuing without an actual paragraph.

This of course makes it immensely harder on the eyes, in addition to just looking plain ugly, especially when paragraphs are actually required, such as in listings.

**Comment by TheDZD** [comment]
Paragraphs meaning line breaks you add when pressing Enter?

**Comment by TullyBurnalot** [comment]
Precisely.

**Comment by Fox-McCloud** [comment]
I suspect something broke this; I noticed, the other day, that it was also doing this for things in notes (the IC notes, not admin player notes).

I added in the wire color functions to my notes, and instead of putting each one on a new line, it just make them all jammed together with "#" between them.
