### ISSUE TITLE
can't do internal bleeding surgery on limbs?

### ISSUE THREAD

**Issue by pinatacolada** [ParadiseSS13/Paradise#3908]
**Problem Description**:
guy had an internal bleeding on his left arm, when scalpaling him aiming for the arm, the only surgeries that show up are bone repair, bullet removal and amputation. trying bone repair surgery and applying fix o vein after the retractor only generates attacks on the vic- patient

**What did you expect to happen**: 
i expected to have a way to start internal bleeding surgery, either by organ manip, or preferentially by it's own surgery i guess

**What happened instead**:
can't do it, can't start it even

**Why is this bad/What are the consequences:**
well i did fix the guy's internal bleeding, by removing his arm. good thing he was a slime dude

**Steps to reproduce the problem**:
get internal bleeding on a limb, try to start surgery, get confused at the options

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: the guy was a slime person, but what I think is happening is that since internal bleeding surgery is under organ manip, you can't do it on limbs, since limbs don't have internal organs

**Comment by MindLeaker** [comment]
Hiya! I was the mentor during that problem, here's a little clarification from what I have:

I found out later with testing that the surgery for internal bleeding is actually just called internal bleeding, but it only appears when it's needed, and as the Issue shows, only on the lower body, upper body, and head.

Otherwise, I had originally thought it had to do with slime-bleeding specifically, but after shooting multiple races on my own server, it seems to affect everyone.

**Comment by Crazylemon64** [comment]
Will be fixed in #3849
