### ISSUE TITLE
Mindslave notes lasting after removal

### ISSUE THREAD

**Issue by scrubmcnoob** [ParadiseSS13/Paradise#4015]
**Problem Description**:
Even after you remove a mindslave implant, no text saying that you are back to normal appears. Your notes also stay the same, saying you are to protect and serve your master.

**What did you expect to happen**: 
I expected it to say I am a free man once more.

**What happened instead**:
The text never appeared but I assume it was a bug considering the implant was removed and then had two loyalty implants shoved into me.

**Why is this bad/What are the consequences:**
Some people may still act as an antag, thinking they are one, even though they are not.

**Steps to reproduce the problem**:
1. Mindslave a guy
2. Remove the mindslave implant.

**Comment by Fox-McCloud** [comment]
Random fact--much like traitors, you can't de-mindslave someone.

Once they're implanted, they're a mindslave forever.

**Comment by scrubmcnoob** [comment]
Wish there was an informative rating on github, I guess a party hooray will make do. Thanks for the information.

**Comment by FlattestGuitar** [comment]
Okay, I'm pretty sure this is another one of those bug-turned-feature situations. What's the point of being able to extract the implant if the person won't lose their status as a mindslave? How does that make any sense?

I'm pretty sure it would be better to allow people to get their mindslave removed. You get unlucky with a traitor once and your whole round is spent at perma because it's impossible to make sure you won't do evil stuff? Seems silly to me.
