### ISSUE TITLE
Losing your head as an IPC causes you to be irreparably blind

### ISSUE THREAD

**Issue by LittleBigKid2000** [ParadiseSS13/Paradise#4043]
If an IPC loses their head, they are blind for the rest of the round. It seems nothing will fix it. 
I'd like to be able to get EMPed or lose at a game of russian roulette with myself and not be blind for the rest of the round, even if it does result in blind, drunken robot shenanigans if I happened to chug several cans of synthahol before losing my head.

**Comment by NTSAM** [comment]
First you wouldn't go blind, and now you can't not be blind, oh boy :S

**Comment by Spacemanspark** [comment]
I want to get off this ride.

**Comment by Crazylemon64** [comment]
<a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/surgery/organs/subtypes/machine.dm#L118-L150>When the eyes are "removed", you get the blind disabilities</a>, however, <a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/surgery/organs/organ_internal.dm#L252-L286>regular eyes do not do so</a>. <a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/surgery/organs/subtypes/diona.dm#L188-L212>I imagine the same is the case with diona eyes,</a> though I imagine it doesn't come up much because their head is good at staying on their shoulders.

The "Surgeryize" would offer a possible means of fixing it, <a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/surgery/robotics.dm#L401-L406>except robolimb surgery doesn't call that proc</a>.

**Comment by Crazylemon64** [comment]
@Aurorablade

**Comment by TheDZD** [comment]
Before, losing your head didn't blind you, now losing head permanently blinds you. 10/10

**Comment by Crazylemon64** [comment]
Hmm, lemme look at vision organ code...
