### ISSUE TITLE
Cult Mask Locker Bug

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#410]
A Mask of Nar'sie who watches/follows a cultist who closes themselves inside a locker/closet/etc. cannot teleport to other cultists.

**Comment by Deanthelis** [comment]
Upon further investigation, I have realized that the mask mob itself moves, but the view of the mask does not. I tested this by following a cultist, having the cultist close the locker, attempting to teleport elsewhere to another cultist, and then having the locker-cultist open the locker. The mask sprite was missing, and my view became stuck on the locker.

**Comment by Markolie** [comment]
At this point I'd rather remove the mask. I had to scrap its viewpoint system a while back as it was difficult to maintain, and this is probably a remnant of that. So unless someone else is willing to fix this, I'd say we'll just leave this be until /tg/'s cult is ported.

**Comment by Fox-McCloud** [comment]
:+1: to Mark's suggestion; universal observers tend to either be horrendously bad, because they don't pass along vital info (problem in Battlfield series, as well, for the commander role), or gamebreakingly good because they offer their team quasi omniscience.

Cultists have long-range communication runes for a reason.
