### ISSUE TITLE
Genetics Console Buffers Change, on the Fly

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#4193]
If you save someone's genetic code to a buffer, any time that genetic code changes, it automatically changes it in the buffer as well. This is frustrating if you're working with the same test subject, but have multiple, different, states you want to save to the buffer.

There was a similar problem with genetics disks: https://github.com/ParadiseSS13/Paradise/issues/3657

How to reproduce:
- Save someone's DNA, in a clean state, to buffer
- Toggle a block or two or three on
- Save to a different buffer
- Take note that the original, clean, buffer will give the same powers as the buffer you just saved

**Comment by VampyrBytes** [comment]
Having trouble recreating this. I put a monkey in the machine, saved it's dna to buffer 1, toggled it to human, saved to buffer 2. If now make an injector from buffer 1, it monkifies me just fine.

As far as the code goes, I have found 2 places which still use references instead of copies, the dna in an injector is a reference to the dna in the buffer record, and using the transfer button sends a reference to the dna in the buffer record into the subject.

Did you use the transfer button? If you transfer the dna from a buffer into a subject, then you could get the behaviour your describing

I'll get a fix for both the injector and the transfer button up as soon as I'm sure it will fix the issue you encountered

**Comment by Fox-McCloud** [comment]
>using the transfer button

Yup, that's what I was doing, is using transfer to.
