### ISSUE TITLE
medibots think they are ais....

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#4307]
Had medibots showing up in the AI law list (and on the mob tracking with an AI eye set to them), and the round i was in had 37 medibots so they all showed up at round in.

This is simmilar to what happend with brig cells and death alarms.

**Comment by Fox-McCloud** [comment]
I've seen medibots show up in the crew manifest as well.

Strongly suspect there's improper use of `autosay` in bots---I know a similar issue occurred with the supermatter---most likely it's an improper argument that's causing this.

**Comment by Bigtimetripod** [comment]
This is happening every round. Why is it bad? As RD we have Emagged borgs. Locked em down and dragged em ti my office to reset ai "slave" link to station AI. So get out multitool and start pulsing wire... medbot,medbot,medbot,cell 3, medbot, cell 3, cell 3, cell 3... ye get the point. Since Borgs AI changing pick a random/line of availible AIs, it almost possible to find correct AI. One of the borgs i magicaly found the real AI, gave up on the secind borg after 20 minutes of pulsing and checking robotics console to make sure its the right AI... no, one borg was running around as Cell 3 as their slaved AI

**Comment by FlattestGuitar** [comment]
Cells and other fun things also show up on the messenger list on PDAs, if that changes anything.

**Comment by pinatacolada** [comment]
I've even seen beepsky and mulebot1 do arrivals and cryo announcements instead of the active AI
