### ISSUE TITLE
Deconstructing and reconstructing vendors with a restock module allows you to restock them.

### ISSUE THREAD

**Issue by tigercat2000** [ParadiseSS13/Paradise#4443]
**Problem Description**:
If you deconstruct a vendor with a restocking module, it will produce the restocking module. Upon rebuilding the vendor, you can use this to refill the vendor, regardless of what it had left.

**What did you expect to happen**: 
You would not be able to get more items out of a vendor until cargo restocks it.

**What happened instead**:
You can deconstruct and reconstruct the vendor to refill it's inventory.

**Why is this bad/What are the consequences:**
Nothing major, but it allows you to get infinite insulated gloves with a coin, for example.

**Steps to reproduce the problem**:
- Deconstruct a vendor that has a restock module.
- Reconstruct the vendor.
- Use the dropped restock module.

**Comment by FalseIncarnate** [comment]
Gonna require some discussion on how we want to address this, as there are a few ways we can do it but each has their disadvantages. Still, it's about time someone decided to finally post this, even though we've all known of it forever.

**Comment by CrAzYPiLoT-SS13** [comment]
IMO, why don't you just add some vars specific to each restocking module, transfer them to the machine when inserted and be done with it?

**Comment by FalseIncarnate** [comment]
There are a number of ways to handle that, ranging from the simple to the more complex, each with their own advantages and disadvantages.

On the simpler end, the refill units would keep the same number of items as were in the machine when taken apart, but this leads to the issue of the inventory building starting at the top of the list, thus you can end up "transforming" items at the bottom of the list into ones higher up.

On the more complex end, we can make the refill units track the type and number of each item, but then this can lead to weird cases where you might end up with "unusable" refills because they only have items that the other canisters already covered, or you end up with having multiple refill canister types per machine, that each cover a portion of the total inventory's items (items 1-5, 6-10, 11-15 each as separate refills).

The problem is not preventing the exploit, but rather doing so in a fair and logical way.

**Comment by Dumbdumn5** [comment]
If you look over here at the possible machines(https://github.com/ParadiseSS13/Paradise/blob/a3fdeaa57cdf5b84dc3be2057c0eb0373a41352a/code/game/objects/items/weapons/vending_items.dm), the hell are the infinite insulated gloves coming from if there's not a tool vendor?  Also, if this is getting fixed, is there any way we could possibly increase the stock on the clothing vendors, cargo won't order more because there's much more important things to order, science likely won't build restock units if they could, engineering would be too busy with other projects to resupply the aesthetic vendors, etc. Any way we could have more base stock or have an infinite supply that requires a reasonable amount of cash to purchase?

**Comment by FalseIncarnate** [comment]
Dumbdumn5: cargo can order crates of insulated gloves. That's probably where all the gloves game from.

As for adjusting the stock of vendors, particularly clothing ones, I'd be okay with that for some of the more generic options like jeans and such, but the real costume-y stuff in the autodrobe probably is fine as-is. We don't really need everyone running around dressed in imperium robes or maid outfits without some legwork to accomplish that.

**Comment by Dumbdumn5** [comment]
Was mostly talking about this, from the initial report by tiger.

> **Why is this bad/What are the consequences:**
Nothing major, but it allows you to get infinite insulated gloves with a coin, for example.

**Comment by Spacemanspark** [comment]
Ya, you cannot deconstruct the youtools or really any of the 'important' machines.

**Comment by AceMcLazer** [comment]
Honestly? as long as this only stands with the Cosmetics/booze/Food Vendors, etc Is it really worth the code changes to fix? 

People seem to like to have their snuflaeke customization cosmetics and those that are popular tend to run out.

_Shrugs_

**Comment by Markolie** [comment]
https://github.com/tgstation/tgstation/commit/2cf4b90ba81f4f126d264375e31961c857c8b6b1 is probably the solution to this issue. Will most likely need to wait for the feature freeze though.
