### ISSUE TITLE
Fudge Recipe Bug

### ISSUE THREAD

**Issue by apophis775** [ParadiseSS13/Paradise#4457]
**Problem Description**:
Recipe for Fudge doesn't match wiki

**What did you expect to happen**: 
2 sugar, 5 cream, 1 chocolate barin candymachine = fudge

**What happened instead**:
An unholy abomination.  
Found out on the git,  it's 5 sugar 5 cream which is the same a Caramel.

**Why is this bad/What are the consequences:**
Cooking.

**Steps to reproduce the problem**:
Read wiki, compare to code, notice it's wrong.  Try to make it, get Caramel instead (if you follow the github recipe) or poopy cooking if you follow the wiki recipe.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing really...

**Comment by FalseIncarnate** [comment]
Wow I messed that one up... technically both can be considered wrong. I'll be fixing this soon to avoid such issues

**Comment by FalseIncarnate** [comment]
UPDATE: The recipe actually functions properly with cream as the ingredient, except that it uses a CHOCOLATE BAR not a CANDY BAR. I'm going to change it to use milk anyways, so that using the wrong type of bar will result in failure (burned mess), not some weird chocolately-caramel.

I'll also be adding some new types of fudge, because why not
