### ISSUE TITLE
Appendicitis Shows up as Virus on Advanced Scanner

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#4564]
Appendicitis shows up as a virus on the advanced scanner.

I can understand why, but this causes confusion to players as they think it's a virus, then they take them to virology and the virus scanner there can't pick up anything.

**Comment by tigercat2000** [comment]
not really a bug?
appendicitis is a non-hidden virus
but the only cure is removing the appendix

**Comment by QQCucumber** [comment]
What does the message for Appendicitus say for cure? It could be changed to 'Appendix Removal'

**Comment by taukausanake** [comment]
Xeno larva inside you is also treated like a virus, yes? It's only cure is removal too but good luck doing it in time. Maybe a small refactor or check is needed?

**Comment by tigercat2000** [comment]
the real bug here seems like the virus scanner not picking anything up

**Comment by Tastyfish** [comment]
Since technically appendicitis is a _disease_ in code (and not curable using the Pandemic™ equipment), and just an inflammation in real life, the issue is probably more that the scanner labels all diseases as viruses.

Also @tigercat2000 it is hidden from the virology equipment, since it's not a surgery issue.

**Comment by Miraviel** [comment]
The cure text was changed to "Surgery" and it is by design hidden from the pandemic, so this is fixed
