### ISSUE TITLE
Emote Issues

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#4776]
Wasn't able to test out the emote refactor before it got merged in, so I'm posting this here.
- When you do an emote that has a parameter, it gives a pop-up box for all current options for who to target. This is particularly annoying for emotes like *flip and *slap, which were previously instantaneous if you didn't manually provide a parameter 
- Can no longer manually type out a parameter, can only select it from a pre-set list (and a number of emote have unlimited range when it's meant to only be someone right next to you...as with flip)
- Emotes are now always blue---this wasn't the format before; the format was that the name of the emoter would be bolded and then the action they did would be displayed in black (by default); there were some exceptions to this, of course
- No one deathgasps when dying (this is pretty critical)
- Emotes contextually vary based on who's viewing them, meaning, if you do a flip, it says "you flip" when it previously says "`your mob` does a flip!" and the like. This is more preference than anything else, but some of the amusement for emotes is lost when it's just something like "you flip"
- Can't use *johnny on yourself.

I'm sure there's more, and I'll post them as they come.

@VampyrBytes

**Comment by KasparoVy** [comment]
I've been getting runtimes when I try to flip on a local branch. It used to be where I could just hit my flip macro 'F' and flip, but now it throws up a selection box that forces me to select who I'm going to flip at... Either no-one, or myself-- and if I try to flip at no-one, it just runtimes while saying the flip message, where if I select myself as the target it'll actually flip.

However, my SCREAM macro still works the exact same as it did before. Hit E, scream-- no target chatbox mumbo-jumbo.

**Comment by VampyrBytes** [comment]
@Fox-McCloud 
> When you do an emote that has a parameter, it gives a pop-up box for all current options for who to target.  

This was clearly shown in the PR post, the changelog and in a discussion with @Krauses, which went into the reasons for the change.

> This is particularly annoying for emotes like *flip and *slap, which were previously instantaneous if you didn't manually provide a parameter

For any emote that can run without a target the first entry in the box is always none, meaning that you can just do *flip hit enter twice and you'll barely even see the popup.

> Can no longer manually type out a parameter, can only select it from a pre-set list 

again, discussed at length in the PR.

> (and a number of emote have unlimited range when it's meant to only be someone right next to you...as with flip)

none have an unlimited range. As noted in the changelog, I combined the old flip with the new one, so if you aren't next to a target that you have a grab on it does the old one, if you are next to the target with a grab it does the new one

@KasparoVy 

> I've been getting runtimes when I try to flip on a local branch

If you update to the latest version that has been fixed

> Emotes are now always blue---this wasn't the format before; the format was that the name of the emoter would be bolded and then the action they did would be displayed in black (by default); there were some exceptions to this, of course

Hmm, bug. Mainly caused by the fact that all old emotes used color macros, which I swiched to spans. If someone can point me in the right direction on which classes to use for black text and for bold, I'll get it fixed

> No one deathgasps when dying (this is pretty critical)

Hmm, bug

> Emotes contextually vary based on who's viewing them, meaning, if you do a flip, it says "you flip" when it previously says "your mob does a flip!" and the like. This is more preference than anything else, but some of the amusement for emotes is lost when it's just something like "you flip"

Feature, again, well documented in the PR. Really not sure how it detracts from the amusement.

> Can't use *johnny on yourself.

It makes no sense to use *johnny on yourself. If really wanted I can add it back in

**Comment by Fox-McCloud** [comment]
>For any emote that can run without a target the first entry in the box is always none, meaning that you can just do *flip hit enter twice and you'll barely even see the popup.

Which is particularly annoying for people who use emotes on the fly, particularly with binds/macros.

People won't be able to spin/run/walk/do another action and do any emote that has a parameter, at the same time---there's a good portion of players who actively do this, and not for powergamey purposes either (running and screaming, for instance is...well, definitely an RP thing, though I realize it doesn't have a parameter, just giving an example).

**Comment by VampyrBytes** [comment]
Hmmm, ok, I think I have a solution to the macro issue. Rather than combining the non-parameter and parameter versions into one, I can make the parameter versions overrides of the non-parameter versions. So you could have flip as the non-parameter one which you can macro and (for example) flip_t as the targeted one that brings up the input box.

I'm busy today, so I'll look into the deathgasp and other bugs, as well as splitting the emotes tomorrow

**Comment by Fox-McCloud** [comment]
deathgasp is the biggest one, at the moment---the others are usability; *deathgasp is actually one that can negatively impact players a lot.

I'd say that and the color being black are the most important ones, at teh moment.

**Comment by VampyrBytes** [comment]
That's those ones fixed. There's a fair bit to do to split all the targetted versions off, so I'll chip away at it and get a pr up soon(tm)

**Comment by Krausus** [comment]
When I was the only one who complained about the target pop-up, I thought I had been taking crazy pills. But I'm not alone!

What if "classic"-style emotes (say "*flip) turn off the targeting pop-ups, so they pretty much act like they used to, and using the new verbs gives you the pop-ups? That would solve the problem without requiring a bunch of new "this emote, but now with a target!" verbs.

**Comment by VampyrBytes** [comment]
@Krausus 
Yeah, I'm not overly keen on the number of new verbs it would lead to either... I was trying to find a quick fix as rl is really busy atm, and will be for some time.

> What if "classic"-style emotes (say "*flip) turn off the targeting pop-ups, so they pretty much act like they used to, and using the new verbs gives you the pop-ups?

I guess that's got possibilities, but again, I just don't have the time atm to be rewriting the system to use multiple input methods... If you want to have a go at implementing it then feel free, all I'd ask is that you bear in mind some of the issues I raised in our discussion, for example the ability for future emotes to take more than one parameter

**Comment by Fox-McCloud** [comment]
After having seen this on live.

Overwhelmingly, people dislike two things: 

- How parameters are handled (they like the old way better)
- "You does the emote action" as opposed to "mob name does the emote action"--basically the like the old methodology of things here too.

**Comment by Spacemanspark** [comment]
I kinda like the "you" thing.
But the parameter thing is annoying.

**Comment by VampyrBytes** [comment]
I've started working on the suggestion made by @Krausus so using say *emotes will act as they used to and only the verbs will use input boxes.
As pointed out above, I have very limited time atm, so can't make any promises on when other than it's coming

**Comment by Fox-McCloud** [comment]
Yeah, it's fine---I understand.

**Comment by Tastyfish** [comment]
Side issue, `miming` seems to make audible emotes not make a noise as intended, but the text still implies they're making the noise, rather than miming it.

**Comment by VampyrBytes** [comment]
@Tastyfish I've just booted it up locally to test the mime emotes and got 

> You open your mouth rather obnoxiously.
You clutch your throat desperately.
You appear to chuckle.
You clap silently.

So it seems to be working. Some emotes do give the same text as the non-mime version, but those always have done. The system was a fairly neutral PR as far as the emotes themselves were concerned. I'm planning another PR once all the bugs are out and people are happy with the functionality of the system that will add functionality and address inconsistencies in the emotes themselves, at that point I'll deal with the mime versions, because yeah, I do agree that the mime versions should always differ from the audible ones, even more so now that deaf people get the mime version of the emote.
