### ISSUE TITLE
Spess pods are broken once again: episode XIV the revenge of electric boogaloo's son

### ISSUE THREAD

**Issue by Rumiluntti** [ParadiseSS13/Paradise#4985]
**Problem Description**:
Spess pod cargo system eats everything you put in it

**What did you expect to happen**: 
For me to get my swag out of that damn bluespace bag of devouring. To be honest, why did I even think that pods would work at all.

**What happened instead**:
Pressed the "empty cargo system" button
Herp derp, pod has no cargo system!!!
Cursed a little
Tried opening the maint hatch and taking out the system to check
Hurr durr, empty the cargo system before removing it
Cursed the shitty pod system to lowest levels of hell

**Why is this bad/What are the consequences:**
Muh swag loot is GONE 4ever!

**Steps to reproduce the problem**:
Make pod
Install a cargo system
Get loot
Put loot in pod
Try to get your loot
Rage

**Comment by Taaketa** [comment]
Goons podcode seems to work. Can't we just toss what we got and import that?

**Comment by tigercat2000** [comment]
goon podcode is goon code

**Comment by Ar3nn** [comment]
We ported Goonchem, arguably a more vital piece of functionality, and that's goon code.

**Comment by tigercat2000** [comment]
we never ported goonchem, goof and fox remade it in their own code based on how goonchem functions

**Comment by Ar3nn** [comment]
Oh. Don't mind me, then.

**Comment by TheDZD** [comment]
Spacepods are one of the most consistently buggy things in the codebase.

**Comment by Davdichan** [comment]
Remove Mechanic and Sec Pod pilot, refunds for everyone?

**Comment by Twinmold93** [comment]
Sounds like the issue is merely not moving the stored items out of the pod's list properly and giving it the proper location... I can take a look.

**Comment by Twinmold93** [comment]
@Rumiluntti @TheDZD Upon further examination, I have found this isn't actually a bug, but undocumented usage of how the loot storage module works. When you have the loot storage system in the pod, and the hatch is of course closed, when you click on the pod with an open hand, you can access the inventory. Everything is there. Once everything is out, then you can take the module out.

I will update the mechanic wiki to note this.

**Comment by Twinmold93** [comment]
@TheDZD Since it seems it was overlooked when I last made my notice: This issue was deemed not a bug by me back in July, but rather an undocumented mechanic usage of the loot storage module, which requires the user to click on a pod with an open hand when the hatch is closed to access the inventory of the system.

The ore box system works by dragging an ore box onto the pod when it has the ore box module installed. Someone did report a bug with trying to resist out of pods when cuffed, but that's a totally different issue and not present to this bug. The current bug report isn't a bug.
