### ISSUE TITLE
Ghosts are still fucked

### ISSUE THREAD

**Issue by taukausanake** [ParadiseSS13/Paradise#5034]
Ghosts still turn up with default sprite when darkness is toggled as a ghost.

**Possibly related stuff**: The Arrivals shuttle ends up with a bunch of clientless (verified by Sothangel) ghosts that are not transparent at all but rather solid with only underwear on. Sothangel and some other ghost also appear as solid mobs as well. These solid ghost mobs are not affected by Toggle Darkness

**Comment by TheDZD** [comment]
@Krausus

**Comment by Krausus** [comment]
Weeeeell, really, we should be pinging @monster860, since it was mostly his work. *Some* ghosts don't seem to get the ghost icons for whatever reason. I haven't really looked into it too much, I was just the only person who really... *tested* it...

The ghosts in arrivals, however, are from people who quit through cryodorms. When they despawn, their body is deleted, and by the time their ghost pops out, it's in nullspace, so they get moved to an arrivals spawn point. We *could* make cryodorms ghost the body *before* deleting it, but I kinda like the spooky arrivals shuttle. :ghost:

**Comment by Spacemanspark** [comment]
Ya, saw this yesterday.
Some do have their full sprites and some don't.

**Comment by SamHPurp** [comment]
Appears to be resolved and can be closed.

**Comment by Spacemanspark** [comment]
It's not.

**Comment by SamHPurp** [comment]
@tigercat2000 seems #5145 didn't sort it then, as you had mentioned

**Comment by taukausanake** [comment]
I don't know, I haven't seen any solid or old ghost sprites lately. I think it was fixed at some point

**Comment by Spacemanspark** [comment]
I still see old ghosts when I toggle darkness off

**Comment by taukausanake** [comment]
I have seen it too just now. It's not all ghosts for some reason now

**Comment by Mitchs98** [comment]
Is this still a thing?

**Comment by AffectedArc07** [comment]
Have not seen this in a loooong time. If it crops up agan feel free to re-open.
