### ISSUE TITLE
Can't pick up objects trough plasma

### ISSUE THREAD

**Issue by FireFlashie** [ParadiseSS13/Paradise#5195]
**Problem Description**:
I can't pick up objects or use something, when plasma on the same tile. Even open firelocks!

**Steps to reproduce the problem**:
Open a plasma canister, then try to open console or pick up item.

**Comment by TheDZD** [comment]
Does this happen with N2O overlays too?

**Comment by Belario** [comment]
I think this _might_ be WIP, to represent the whole "cloudy gas" thing, does the same with the water in the beach away mission.
To get through use alt click.

**Comment by FireFlashie** [comment]
It happens with N20 overlay too.

**Comment by Twinmold93** [comment]
TheDZD Need to make it so people can click through the overlay, I take it? Shouldn't be hard to find, I'd imagine.

**Comment by CrAzYPiLoT-SS13** [comment]
@Belario, for future reference, WIP means 'Work in Progress', not 'Working as Intended' :)

**Comment by Belario** [comment]
@CrAzYPiLoT-SS13  I maybe might have had a brainfart.

**Comment by GelatinousGlob** [comment]
This same bug also prevents you from interacting or screwing or unscrewing glass thats in the tile infront of you and is facing you with the gas overlay. The gas prevents you from direct interaction while the glass you are trying to unscrew is blocking you from alt-clicking that same tile.

It essentially makes any gas chambers with interior glass walls (IE any chamber built by players) impenetrable besides throwing items at the window until it breaks.


It was fun watching 2 hours of build time for a custom turbine go to waste because I could neither get inside the chamber with plasma in it without breaking the glass and also preventing me from replacing the glass I broke without standing inside the chamber myself and being permanently stuck without throwing shit to break the glass.

**Comment by Davdichan** [comment]
Honest question: What is the purpose of having the gas overlay clickable? Or is it just a beyond thing where what ever is 'ontop' blocks everything under it? Maybe move the gas layer above the floor tiles but below structures and such? If that makes any sense.

**Comment by tigercat2000** [comment]
@TheDZD is not technically bug, it's an oversight, no one set mouse_opacity after updating the icons

**Comment by Chakirski** [comment]
Totally wasn't me.

**Comment by Chakirski** [comment]
Actually it seems like changing mouse_opacity doesn't fix it. I'll see what I can do.

**Comment by Crazylemon64** [comment]
Actually, it's not the gas overlay itself that's the matter: The turf itself is what is blocking the click. <a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/LINDA/LINDA_turf_tile.dm#L240-L258>Source</a>

**Comment by Krausus** [comment]
Yeah, overlays ignore `mouse_opacity` and use the opacity of their atom, which would be the turf the gas overlay is attached to. They would need to be a separate effect atom to behave as desired.
