### ISSUE TITLE
Round start mechnic is broke

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#5202]
What do?
I set mechnic to high

What happen?
Did not get picked for mechnic..NO ONE ELSE WAS PICKED FOR MECHNIC either
I next round set everything to low BUT mechnic..and mechnic as high...still did not get the job slot. and no one else was round start mechnic either.

**Comment by Twinmold93** [comment]
Sounds like the job slot itself isn't listed to be selected on round start for some reason. Blacklisted or just not listed role?

**Comment by TheDZD** [comment]
[Except it is, strangely enough.](https://github.com/ParadiseSS13/Paradise/blob/master/code/game/jobs/job/engineering.dm#L114-L115)

**Comment by Twinmold93** [comment]
That's strange. Let me check something.

**Comment by Twinmold93** [comment]
@TheDZD You can reproduce it with Magistrate, as far as I can tell, since it's the same theoretical issue. And it's a bug that's been occurring for a pretty long time. I was able to do it last night on live: Didn't get Magistrate when set to high. Booted back to lobby (since the position I wanted I didn't get + the setting I have set does so). Was able to join as Magistrate since no one in game was one.

**Comment by TheDZD** [comment]
What an odd bug, I wonder if this happens with other jobs as well, or just karma-locked ones.
