### ISSUE TITLE
Character Join menu timer and round clock are not synchronized.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#5210]
**Problem Description**:
![](https://i.gyazo.com/ee6d02fda4deb7f51b071c2ffbd41426.png) It's not synchronized.

**What did you expect to happen**: 
It should be synchronized

**What happened instead**:
It wasn't synchronized.

**Why is this bad/What are the consequences:**
I dunno, it should be synchronized.

**Steps to reproduce the problem**:
-Open menu
-See things not synchronized.
-Cry.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: N/A

**Comment by taukausanake** [comment]
Maybe related to #4874?

**Comment by FlattestGuitar** [comment]
@Krausus I TOLD YOUUUUUU!

**Comment by Twinmold93** [comment]
It's not synchronized because 12:00 is when the shift itself starts, but the round does actually start 3 minutes before (11:57 is time servers starts at), so when 12:00 hits, the shift and main game begins. It's an inconsistency as far as being shift duration, but it does say round duration, so it's giving you the actual time that the server has been up since last restart/first person to join the server.

**Comment by Krausus** [comment]
The clock is actually stuck at 12:00 until the round starts. Problem is, when I updated how the round is timed, I tried to find everything that used time since world start-up, and, uh, missed this one. It's an easy fix, though...
