### ISSUE TITLE
Advanced Pinpointer points you to the nearest emergency autoinjector when set to hypospray

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#5232]
More futzing about with traitor items on my private server.

This one takes the cake, I think emergency autoinjector must be a child of the hypospray, because when you set the advanced pinpointer up to locate it, I was directed to a medkit box that had an emergency autoinjector in it. Sure enough, taking it out and taking it with me, the advanced pinpointer showed that I had the hypospray.

**Comment by monster860** [comment]
Emergency injectors *are* hyposprays, however, there is snowflaked code in the traitor procs to check for emergency injectors

**Comment by Lady-Luck** [comment]
Setting it to locate a compact defib doesn't make it locate all defibs. I think it's pretty clear what it's supposed to do.

Emergency autoinjectors are EVERYWHERE. Everyone has one.

**Comment by monster860** [comment]
Yes, but defibs are not compact defibs.

Emergency injectors are hyposprays though, in the code. The pinpointer is just missing the snowflekked shit that the traitor item shit has.

**Comment by Lady-Luck** [comment]
So is this not going to be changed? I know I would be pissed if my objective were to steal a hypospray and I bought an advanced pinpointer because I couldn't find it, and it pointed me at a medkit.

**Comment by PJB3005** [comment]
No it's still a bug it's just that your comparison with compact defibs makes no sense.

**Comment by Lady-Luck** [comment]
ho-kay.

**Comment by Twinmold93** [comment]
Code-wise. Compact defibs are part of the /defib set, so you are going /defib/compact, whereas hypospray is just /injector/hypospray whereas auto-injectors are /injector/hypospray/emergency. This is the simplified version of it, but essentially what it's doing. It's looking for the item, but since auto-injectors are in fact emergency bound under hypospray, it counts them since they are children of the thing you are trying to find. Really just needs the same check as the steal objective's check itself is.
