### ISSUE TITLE
Syndicate HEadsets: Removing/Adding Keys

### ISSUE THREAD

**Issue by Fox-McCloud** [ParadiseSS13/Paradise#526]
For whatever reason you can't add or remove keys to this headset; no idea why.

I've tried setting it to start out in keyslot 2 and 1 and it still has the same issue.

I suspected it may have been due to the fact that it only has one key and that it starts out in keyslot 1, but the binary headset has the same thing (but a different key, of course), and you can add/remove keys to it just fine.

**Comment by Earthdivine** [comment]
Whoops I talked to False and DZD about this yesterday and forgot to put this up. They think they might know whats up.

@TheDZD

**Comment by TheDZD** [comment]
If you're trying to add a hacked syndicate keycard to a syndicate headset (the one that ops start with), you cannot have both it and the default card in at the time time due to the fact that the hacked keycard is a subtype of the syndicate keycard.

**Comment by Fox-McCloud** [comment]
@TheDZD 

Yeah, I was attempting to try with the binary key--likewise, you should be able to at least *remove* the current key, which you cannot.

**Comment by Krausus** [comment]
This seems to be caused by syndicate headsets having a special `attackby` proc to let you refund Syndicate Cyborg Teleporters through an uplink headset (which I'm not sure is even a thing anymore). [Here is the code responsible](https://github.com/ParadiseSS13/Paradise/blob/master/code/game/objects/items/devices/uplinks.dm#L256-L265):
```
//Refund proc for the borg teleporter (later I'll make a general refund proc if there is demand for it)
/obj/item/device/radio/headset/syndicate/attackby(obj/item/weapon/W as obj, mob/user as mob, params)
	if(istype(W, /obj/item/weapon/antag_spawner/borg_tele))
		var/obj/item/weapon/antag_spawner/borg_tele/S = W
		if(!S.used && !S.checking)
			hidden_uplink.uses += S.TC_cost
			qdel(S)
			user << "<span class='notice'>Teleporter refunded.</span>"
		else
			user << "<span class='notice'>This teleporter is already used, or is currently being used.</span>"
```
This clobbers the parent `attackby` proc (which handles adding/removing keys), and doesn't call it, so it never gets a chance to handle keys.

Oh, and trying to refund a Syndicate Cyborg Teleporter through a syndicate headset causes a runtime, because the proc doesn't seem to care whether the headset is actually a hidden uplink or not. It may be best to simply remove this proc entirely.
