### ISSUE TITLE
Picking up a PAI that is in a "rest" verb state makes them "vanish"

### ISSUE THREAD

**Issue by AceMcLazer** [ParadiseSS13/Paradise#5262]
**Problem Description**:
Picking up a PAI that is in a "rest" verb state makes them "vanish"

**What did you expect to happen**: 
Pick up the rested pai, as normal when non-rested

**What happened instead**:
They seem to have vanished when this happens.

 While They're still there, and they are easily fixed by resisting, they're invisible or...non existant

**Steps to reproduce the problem**:
Pai unfolds from card form to chassis form, Rests. Human scoops them up.

**Comment by taukausanake** [comment]
This is because they don't have an icon in the holder dmi file, kind of like how when I made mice holdable they'd vanish when dead and picked up. All that would be required is adding the icon to the holders dmi and it should work but that means adding quite a few icons. Or changing the icon var to get them from the pAI file

**Comment by AceMcLazer** [comment]
Wouln't it just be a matter of copy-pasting the icons used for the non resting state?

**Comment by taukausanake** [comment]
It totally is but I don't know if anyone wanted to do that or not. There must have been a reason, couldn't have been oversight
