### ISSUE TITLE
death by low blood is fucked

### ISSUE THREAD

**Issue by pinatacolada** [ParadiseSS13/Paradise#5538]
![asdf](http://puu.sh/qM6X1/73ed8e6d45.jpg)

I don't even know what's going on. The people around me think I'm dead, their HUD says I'm dead, yet I have a pulse, my HUD says I'm alive, but most of my body is dead? Defib will think I'm alive, which is correct I guess?

Also this was post internal bleeding. The guy fixing me said he fixed the internal bleeding, but I kept loosing blood until I lost literally all of it

**Comment by Crazylemon64** [comment]
Yeah, running out of blood tends to cause weird things to happen - you can observe this with an excanguinated blood monkey, for example

**Comment by taukausanake** [comment]
What does it mean when your HUD body parts are gray even? That happened to me once before on some of my limbs but it went away

**Comment by Fox-McCloud** [comment]
@taukausanake 

It's supposed to happen when you're missing limbs, but when you die and get revived, it tends to screw things up.

**Comment by Ar3nn** [comment]
Gray body parts are missing/don't work (i.e losing an arm in an explosion turns the related arm green, death makes everything not work, so it turns it all grey as an additional hint.) As for why this doesn't work...Hm. Isn't blood loss supposed to inflict a proportionate amount of oxy damage?

**Comment by Crazylemon64** [comment]
It's because while the main body of `Life` only runs while the mob is still alive, `handle_blood`, which kills the human if they run out, will kill the human while inside the section of code that assumes the human to be alive. Then, code that makes the human unconscious if they are paralyzed runs, which brings back the human to life, letting them die of blood loss again the next tick, resulting in infinite fun.
