### ISSUE TITLE
No music animation if head phones are equiped right ear (the ear equip slot on bottom)

### ISSUE THREAD

**Issue by Trubuss** [ParadiseSS13/Paradise#5648]
**Problem Description**:
No music note animation when head phones are equipped on the bottom ear slot and turned on.

**What did you expect to happen**: 
Music note animation to appear

**What happened instead**:
Wearing headphones and they appear to be off.

**Why is this bad/What are the consequences:**
No.

**Steps to reproduce the problem**:
Equipping to bottom ear equip slot with head phones.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:  Traitors;  Equipping headphones; No.

**Comment by Deanthelis** [comment]
Please edit this issue to bring it in line with the other issues in this repository. More specifically, you should actually fill out the last two portions of the form. "Kitten assuming coding" doesn't help solve the issue, and because this is a graphical error, the last question should probably include the other items your character was wearing at the time.

And please, don't use the third person in a bug report.

**Comment by Trubuss** [comment]
@Deanthelis Done.

**Comment by Fox-McCloud** [comment]
>And please, don't use the third person in a bug report. 

Don't use IC in a bug report either, for that matter. This isn't the game world.

**Comment by Trubuss** [comment]
I'm well aware.

**Comment by LittleBigKid2000** [comment]
Seems like the bug only happens if the headphones are equipped in the l_ear (bottom) slot and there's anything in the r_ear (top) slot.

**Comment by AffectedArc07** [comment]
Headphones got refactored and this no longer applies
