### ISSUE TITLE
Doomsday Device does not work for traitor AI hijack objective.

### ISSUE THREAD

**Issue by GoblinBackwards** [ParadiseSS13/Paradise#5773]
Description:
When playing as a traitor AI, using the doomsday device does not succeed the hijack-style objective, even though no-one escaped.

What I expected:
I expected it would work as there would be no shuttle so no-one could escape alive.

What actually happened:
I failed the objective.

Why it's bad:
Causes what should be a won objective to be lost.

Steps to replicate:
When playing as a traitor AI with the objective to let no-one escape other than AI cores, pAIs and borgs, use the doomsday device in the malfunction tab. When the timer runs out the objective will still fail. 

Gamemode: Traitor, Traitor/Ling, Traitor/Vamp. Not sure which one it was.

**Comment by Twinmold93** [comment]
I'm not familiar with how the doomsday device works, but I'd assume it only affects Z-level 1, so anyone off station counts as alive. If the doomsday device then instantly ends the round (why?), it will note people like miners are still alive, thus fail objective if it looks through all player z-levels. If it DOESN'T end the round, then anyone who comes back and escapes on the shuttle counts as alive, and fails the objective. I need more details pertaining to the doomsday device in order to know exactly what I'm looking for.

**Comment by Shadow-Quill** [comment]
Still doesn't work. (We're, what a Necropost)
