### ISSUE TITLE
Player-controlled spiders can bite themselves, dealing damage.

### ISSUE THREAD

**Issue by Bone-White** [ParadiseSS13/Paradise#5778]
**Problem Description**:
As title.

**What did you expect to happen**: 
No attack to be performed.

**What happened instead**:
"The giant spider bites the giant spider!"
*damage dealt to self

**Why is this bad/What are the consequences:**
People who manage to re-enter the round as a spider can often hurt themselves.

**Steps to reproduce the problem**:
Be an even spider, click ANY item in the same loc as yourself (including but not limited to your own sprite) this includes a lot of other objects such as windows.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
Nothing else to add.

**Comment by taukausanake** [comment]
Can't you also punch yourself as a human? Harm intent at least. Also I forget if simple animals can nuzzle themselves anymore. That might have been fixed

**Comment by Markolie** [comment]
Pretty sure all simple animals can attack themselves, and that it's intended.

**Comment by Kyep** [comment]
Difference:
- Simple_animals are often clicking on objects (like windows) to bash through them, so are more prone to it happening
- Simple_animals are always on harm intent, unlike humans, so have no safety against it happening
- Simple_animals have no way to heal themselves when it happens

The problem isn't unique to spiders.
Really, the AttackingTarget for simple_animals should really abort if you're clicking on yourself.

**Comment by Markolie** [comment]
If we do remove this, make sure all simple_animals have a suicide verb.

**Comment by Kyep** [comment]
I don't think that's a good idea, because:
- I don't think having a suicide verb in general is a good thing, because it results in people doing things that strain suspension of disbelief. E.g. suiciding over trivial things, and doing it in ways that would be so painful, most people wouldn't actually be able to go through with them.
- Most simple_animal type mobs are animals. Animals do not generally commit intentional suicide. Their self-preservation instinct is just too strong.
- Unlike PCs, simple_animals all have a basic AI. If you simply ghost out of them, the AI takes over, and that's both better for the round, and more realistic, than them simply dying to suicide.
- Adding a suicide verb to all simple_animals would be a feature, and we're in a feature freeze. So, it isn't viable.

**Comment by Markolie** [comment]
Keep in mind that simple_animal doesn't necessarily mean it's an animal. It's a simple mob that doesn't have all the excessive processing a human does. As such, simple mobs also include things like Syndicate operatives that do need to have the feature to kill themselves.

Just yesterday I killed myself as a Faithless after being captured. The only way to do that is to attack oneself. By removing the ability to attack oneself, you're also removing the **feature** of simple_animals being able to kill themselves. As such, a way of killing yourself as a simple_animal needs to be present. 

Players killing themselves when they shouldn't has always and will always be an administrative issue.

**Comment by Kyep** [comment]
I know what a simple_animal is.

There is no way for a player to end up in control of a Syndicate Operative simple_animal short of adminbus. Even then, those operatives cannot be stunned, are 100% obvious syndicate, are equipped with burst fire weapons, and shoot PCs on sight in 99% of cases. The chances of someone wanting to take one alive is slim, and even if they wanted to, there is no way to cuff them, and no way to subdue them short of killing them. I can't imagine a case where a syndie operative *NPC* would want to suicide rather than simply ghosting.

Faithless are pretty much the same as npc syndicate. Always hostile, players always shoot them, no way to stun/detain them reliably short of building walls around them. I have never seen a faithless taken captive, and even if I did, I still think that ghosting out of the faithless would be a better option than suicide.

The issue here isn't "players can kill themselves". That's impossible to prevent. The issue here is that the mechanics lead to players *accidentally* harming / killing themselves. I know. I have seen it many times.

**Comment by Markolie** [comment]
Xenobiology can spawn sentient Faithless. We had a dozen different simple_animals running around the station yesterday interacting with the crew. These need to be able to kill themselves: imagine if their Xeniobiologist owner tells them to? I played a sentient Faithless, and an ERT was called in. The situation went out of hand. 

And by your reasoning, this is not a bug. It's a quality of life improvement so mobs no longer kill themselves (which is why I also stated this isn't really a bug before). As such, the feature freeze would prevent this from being "fixed" because it's more so a feature request.

**Comment by Kyep** [comment]
If their owner tells them to kill themselves, they can run into space, kill themselves on a shocked grille, run up to a sec officer, just stand there while their owner kills them, or otherwise die by any number of other methods. Or simply ghost. They won't be talking after that, and its not like they can be objective targets or cloned anyway, so suicide has little advantage over ghosting.

This isn't about stopping simple_animals from killing themselves at all. That isn't even possible. This is about stopping them from *accidentally* crippling or killing themselves because clicking on a window, or other object on their tile, results in them accidentally attacking themselves.

Bug is defined at https://en.wikipedia.org/wiki/Software_bug 
"A software bug is an error, flaw, failure or fault in a computer program or system that causes it to produce an incorrect or unexpected result, or to behave in unintended ways. "
This is a flaw which causes a result that is unexpected, unintended, and I would argue, obviously incorrect.
It is a bug.

**Comment by Markolie** [comment]
Just because they can kill themselves indirectly, doesn't mean it's fair to take away a direct way of killing themselves. Your primary reason for not letting simple_animals kill themselves because there's "no need to". But the game yesterday proved that there is indeed a reason for simple_animals to kill themselves, and I've mentioned that as well. Just check the logs of yesterday's game and judge for yourself.

And I agree that simple_animals shouldn't kill themselves by accidentally misclicking. If you check yesterday's log, you'll see that when I played a sentient spider for the same Xenobiologist I accidentally killed myself while trying to destroy some glass. This'd certainly be a major QoL improvement.

But that doesn't justify taking away this option, when I can prove to you based on yesterday's log that players use this to intentionally kill themselves, and that there's just cases where they do need to be able to do so.

Objectively speaking I really do not think it's a bug. I understand your reasoning, but it's also subjective. **You** consider it to be an unintended/incorrect effect, but I, and I know other players do too, do not.

**Comment by Bone-White** [comment]
Then as a compromise, may I suggest not forwarding attacks to yourself when you click other objects in the tile you are in?  As an example, try breaking through a two-pane one-directional window and grille tile as a spider by standing in the tile after you break the grille.  Clicking on the one-directional window will result in you attacking yourself.

Sentient animals rarely hurt themselves intentionally in real life, humans are exceptional in this behaviour.  I'm more concerned about the unintentional effect.  simple_animal controllers are hurting themselves out of non-intuitive self-harming controls, not because they choose to.

**Comment by IcyV** [comment]
Looked into it more. Hostile mobs specifically are intentionally designed to take up the entire tile. mouse_opacity is set to 2 in their file meaning that they take up the entirety of it. This is very intentional to make it easier to hit hostile mobs. That or we would have one hell of a time trying to hit mobs like bees or viscerators due to their tiny sprites.

The solution to hostile mobs being able to hit themselves by clicking any part of their tile would literally be just changing that number to 1 instead. This actually already happens for a lot of them when they die, I believe.

So it's not actually an issue or broken at all, it's working entirely as intended. Any changes to this would be balance.

**Comment by taukausanake** [comment]
> That or we would have one hell of a time trying to hit mobs like bees or viscerators due to their tiny sprites.

So that's why those fucks are always in the way. Dammit, now I can't complain about bees being in the way

**Comment by Bone-White** [comment]
The expectation was not to make spiders harder to hit by changing their sprite covering a tile.

The expectation was to stop spiders hitting themselves by clicking themselves.

**Comment by taukausanake** [comment]
You'll just have to alt-click the tile if you're going to click something you're standing on. This was a feature that was applied so humans can hit creatures easier. It didn't take into consideration whenever those creatures would be players and attack things they were standing on
