### ISSUE TITLE
Announcements can be seen in lobby and when out of communication range

### ISSUE THREAD

**Issue by Markolie** [ParadiseSS13/Paradise#5808]
This is partially a bug report, but also a discussion to determine whether this is actually a bug. Currently, announcements (both crew and command ones) can be seen when in the lobby and when out of communication range (you're not on Z1 or Z3).

The question is: is this a bug, or intended? I definitely don't think people in the lobby should see announcements because of metagaming, but I'm not 100% on announcements showing on, say a random away mission. And then the question is, should only admin announcements show when you're not in communication range, or should no announcements show at all?

Discuss, and I'll make the necessary changes based on the consensus.

**Comment by AndriiYukhymchak** [comment]
I agree that alert level changes and announcements shouldn't be visible. I remember myself picking security officer over medic (that I wanted) based on announcement about shadowlings. This was some time ago. OOC in lobby is ok if OOC is watched upon for any round info

**Comment by Plotron** [comment]
I love valid metagaming. "Yo guys, I heard ya got some problems, so here I am!"

That being said, realistically speaking normal announcements shouldn't be visible out of communication range.

**Comment by AndriiYukhymchak** [comment]
also same should be for unc characters

**Comment by taukausanake** [comment]
This has bugged me a bit before. I would go out as Mechanic ~~because fuck the station~~ and radio silence. It was nice but I still got announcements so I knew things were happening. You shouldn't be getting those if you aren't getting radio.
As for lobby announcements I don't think those are too bad. Chances are if you're joining a round late then you'll sooner than later learn what's going on even without announcements. By then you're more or less cannon fodder anyways. Seeing announcements in the lobby also tell you, early or late, that the round is actually going somewhere than not and no one wants a boring round.

Semi-related to this, but wouldn't announcements travel the same way as radio? At least station and CentComm bound, even the escape shuttle I'd think. They could otherwise still use Bluespace radio like headsets do when in range of broadcasters. That's just a thought though

**Comment by KasparoVy** [comment]
While radio chatter is generally restricted to channels, I feel that a wide-band multi-channel broadcast would be more suitable for announcements, being that it ensures that if you're out of the range of the P.A. system, there is no chance you'll miss it-- so long as you've got a functioning radio

**Comment by GelatinousGlob** [comment]
You might want to make sure CC messages are still sent to everyone even if station announcements aren't because their can be IC and OOC consequences for not following CC announcements.

**Comment by Markolie** [comment]
So Central Command messages are sent to everyone except for ghosts (because metagaming), and other announcements go to everyone in range of a radio with common channel enabled (https://github.com/ParadiseSS13/Paradise/blob/18f4aa18b98fcf8503f7173d3e294d581aa2acff/code/game/objects/items/devices/radio/radio.dm#L561). Will look into modifying that proc so it allows multiband checks.

**Comment by GelatinousGlob** [comment]
Im not sure if CC announcements should ever be blocked otherwise it gives people an excuse as to why they ignored a CC command. It doesn't bug me too much but its more of an admin's problem than a player's problem at that point.

**Comment by taukausanake** [comment]
Damn that poses a problem now that it's mentioned. I forgot that CC is literally admin IC and those need to be heard. But yeah, I guess CC announcements can be justified with a universal radio signal rather than the station's limited range one. I mean why would they want the station's radio signals to head out anywhere else? Contrast, CC probably doesn't care what Jenkins sends out from their location and they'd want to make sure it is reached whenever comms are up or down

**Comment by Kyep** [comment]
I'm going to go against the grain here, and say its a good thing that announcements (both CC and crew) can be heard by players in the lobby.
I think it gives a reason for people who were afk at round start to join in. It gives them a little taste of what they are missing.

If you have to change it, then:
- CC announcements should still reach everywhere, including the lobby
- Crew announcements should reach all zlevels with telecomms, and (ideally) also the lobby. But at the very least, everywhere with telecomms.

**Comment by Fox-McCloud** [comment]
It makes no sense that players can discern anything about the game from sitting in lobby; it's literally IC in OOC info that could influence what job you pick or if you even join or not ("oh nukies--I'll go security and pew pew them with my taser").

**Comment by Plotron** [comment]
It is literally IC in OOC, yes.
