### ISSUE TITLE
FIX THE MONSTROSITY THAT IS IPCS WITH SUNGLASS SEC HUDS

### ISSUE THREAD

**Issue by Wheatley29** [ParadiseSS13/Paradise#5839]
![image](https://cloud.githubusercontent.com/assets/20046182/19949294/c247e91c-a148-11e6-8f37-d07cc58c3b30.png)
IT IS HALFWAY DOWN MY FACE
I have the figure of eight monitor
And I have fashion
Fix this monstrosity

**Comment by Plotron** [comment]
You look evil in that picture.

Please do not fix!

**Comment by taukausanake** [comment]
Make IPCs unable to wear glasses like kidan but give them upgrades/special implants or such. Saying you place glasses in a slot behind the screen sounds a little dumb.
On that subject, what kind of screens do they even use? LCD? CRT? I would imagine CRT because of the box shaped head. You don't want things being put behind that screen. If it was an LCD screen though, then what is there to put behind it? Be flat then

**Comment by Wheatley29** [comment]
This is space station 13
You explode if you defecate on a bible
We have carps that are in space
And your primary concern is IPCs wearing glasses.
Also making IPC unable to play a good portion of jobs because they cannot wear the HUD is an awful idea

**Comment by Ratvar** [comment]
==>Also making IPC unable to play a good portion of jobs because they cannot wear the HUD is an awful idea
Ahhem,implants,and :
==>Also making kidan unable to play a good portion of jobs because they cannot wear the HUD is an awful idea

**Comment by Crazylemon64** [comment]
Good luck getting people coordinated to arrange for a cyber implant - especially a roboticist competent at IPC component manipulation.

**Comment by taukausanake** [comment]
I feel like that's shots fired at me @Crazylemon64 just because I IC and OOC (refuse to) don't know how to fix IPCs.
But if you honestly think about it, glasses shouldn't fit either Kidan or IPC with what weird head/face shapes they have. Every other specie has a humanoid head but these two don't. And let's be more honest here, if IPCs had this restriction at creation like Kidan they'd have pretty much the same argument and debatable the same player usage. I'm not saying no one would play IPCs if they did have this restriction, but it could possibly match Kidan usage if not be a bit higher than them

**Comment by Taaketa** [comment]
IPCs do not need another weakness added to them, they are already highly vulnerable to brute damage.. This is just stupid discussion.

People keep posting "It doesn't make sense." Why would a manufactured unit, presumably by humans. Not be compatible with a "HUD" (they aren't glasses). That at least 6 other races can wear, who all have vastly different anatomy. Yet for some reason "IPC haz scree derp, scree don't do glasses, derp, it no mak senze!"

Come up with a genuine reason, a **GAMEPLAY** reason as to why IPC's should have HUDs and rely exclusively on a limited cybernetic implant. Which requires research to be done, a Robotist to fit it and materials ready to print them. AND why IPCs need to wait for them and any other race can choose to have them fitted afterwards as well. Don't pull out some stupid lore shit, because that was abandoned LONG ago for the various races already. Vox can't leap on people anymore, Grey's aren't vulnerable to water, Vul[kin no longer have their incredible scratch attack damage, or overheat when it's too warm. This was all race stuff that was abandoned for gameplay. 

It wasn't fun to be stun locked by a fucking Vox leap. 

It wasn't fun losing every fight to a Vulpkin because they could do an extra 5 damage per attack.

It wasn't fun dying a Vulpkin to someone putting you on fire, or getting a virus that would raise your body temperature and you'd die from your body reacting to the virus.

And before ANYONE goes on about Kidan and their lack of HUDs. The same argument can be made, THEY can go get implants then, they CAN wait. They already get extra armour to compensate them for their HUD weakness. I see no counter offer to IPCs. They are naturally weak to EMPs (insta death) and weak to brute. The only positive about an IPC is they are easy to repair from a gib if their main body remains intact.

**Comment by Ratvar** [comment]
Why would a manufactured unit, presumably by humans. Not be compatible with a "HUD" (they aren't glasses).==>Those HUDs also give you antiflash defence,even if they dont cover your "TVscreen". 
Lore really shitty,dont use those arguments even if you said that nobody use it.
Bad argument.

Still dont know how 10% nonstackable brute defence can contribute to kidan in any situation and overcome noglasses dissability,even security suits have this armour.It really nerfed.It can help only to kidan that fight in hand combat without any addiditonal armour.This is not compensation,this is snowflake.Brute defence have no correlation to noHUDs,as EMP weakness have no correlation to HUDs.
Bad argument.

It wasn't fun  getting a virus that would raise your body temperature and you'd die from your body reacting to the virus.(death from reacting to the virus not fun.)==>it not fun to die to  virus that specify race dissability,but this is fun to die to sensory deconstruction,deafness, and hallugen that kills your brain while stunlocking you in hallucinations and making machines unusable for you?Viruses still do those "No fun" things,with or without supervulp furr.No correlation.Bad argument.

It wasn't fun dying to Vulpkin from fire==> Dying to EMP as IPC instanitly=fun,cause it not removed?/Dying to PlantBGone as diona instanitly=fun,cause it not removed?
There is MANY methods to kill any race with instant memes,why not make them more unique for every race,not for some of them?Ah,cause it "No fun,no fun",and still we have prions,EMP,                       Diona-B-Gone,memechems and such that work on all races.                                                                  Not a good argument,again(wow).

The same argument can be made, THEY can go get implants then, they CAN wait.==>IPC cannot wait for implants cause someone can...EMP them or throw floortiles from distance cause they dont have flashprotecting HUDs?Where is the connection?I dont understand.Can you explain?

The only positive about an IPC is they are easy to repair from a gib if their main body remains intact.==>Things as you cannot intoxicate IPC, no relise CO2 in atmosphere,no parapen them,fast selfrepair,no viruses and other problems of organic life dont work on them not positive at all,or dont exist?        
Bad argument.

...What are we arguing about?This is just pull about bugged sprite.

But,still,one-sided arguments.Eh.Also,sorry for language,kinda not my native.

**Comment by Wheatley29** [comment]
@taukausanake If you refuse to repair IPCs as non robotics, thats fine, however if you explicitly choose robotics and then pretend you don't know how then thats a problem

**Comment by Fox-McCloud** [comment]
Guys, the Git really isn't the place to be debating something like this; it's a simple issue report---if you have suggestions for this race (or any other), please make them on the forums.

**Comment by FlattestGuitar** [comment]
This actually comes from #5416, where glasses started being overlayed on hair. 

While I think it partially depends on the fashion and personal preference, hair is generally not tucked behind glasses, and this is indeed an issue. 

I do believe the change was undocumented in the changelog, so it shouldn't have been in the PR in the first place. 

:o

**Comment by Plotron** [comment]
:O, Holy shit!

So that is why my glass-enabled characters are looking strange now...

**Comment by Fox-McCloud** [comment]
@FlattestGuitar 

It was covered in the PR

`Glasses are no longer covered by facial hair and head accessories. You can now see glasses on Vulpkanin`

**Comment by FlattestGuitar** [comment]
Huh, didn't notice that.

What would be the suggested fix here?

Create IPC-exclusive glasses sprites?
Lock IPCs from wearing glasses altogether?
Remove (FINALLY) all IPCs from the game and replace them with toasters?

**Comment by KasparoVy** [comment]
IPC-exclusive glasses sprites seems like the way to go.

**Comment by jughu** [comment]
Implants would make more sense and gives robotics morr jobs to do

**Comment by KasparoVy** [comment]
Addressed the glasses covering all hair issue you guys brought up, didn't mention this issue so it wouldn't close it because the PR doesn't give IPCs their own glasses sprites.
