### ISSUE TITLE
Mobs able to attack across z levels

### ISSUE THREAD

**Issue by sothangel** [ParadiseSS13/Paradise#5856]
**Problem Description**:
Two mobs (Faithless and Goliath) have been seen attacking Spacepods and Ripleys respectively, despite being on different Z levels to the player.

**What did you expect to happen**: 
Nothing, since telekinesis isn't a thing for them.

**What happened instead**:
Pod went boom and APLU was attacked.

**Why is this bad/What are the consequences:**
Because it isn't meant to be this way.

**Steps to reproduce the problem**:
I believe you need to be in a mech on the same/near X/Y co-ordinates as a mob, not 100% on the details

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
It seems to me that mobs are ignoring Z level - Two goliaths were attacking a Ripley that had a player inside, whilst the Ripley was on the station. The goliaths and Ripley had the same X/Y co-ordinates; but the Goliaths stopped attacking when the player exited.

**Comment by Markolie** [comment]
My hypothesis is that this was caused by the Life() refactor changes.

This can_see() proc was recently added: https://github.com/ParadiseSS13/Paradise/blob/564e4af0cbab677b80ea57aa36cfe7a2f09cd5dc/code/modules/mob/living/update_status.dm#L46

It's overwriting the global can_see() proc: https://github.com/ParadiseSS13/Paradise/blob/18f4aa18b98fcf8503f7173d3e294d581aa2acff/code/__HELPERS/unsorted.dm#L550

Which is breaking the spacepod/mecha check here: https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/simple_animal/hostile/hostile.dm#L70

Which is causing this issue. Is this something you can fix @Crazylemon64?

**Comment by Crazylemon64** [comment]
Yeah, I can fix it, just gotta clean out my real-life TODO box first
