### ISSUE TITLE
Balaclava adjust intent removes it from your agent

### ISSUE THREAD

**Issue by gcole09** [ParadiseSS13/Paradise#5932]
**Problem Description**:
When wearing the balaclava (mask slot item), using the adjust intent (top-left icon, "Adjust balaclava") with an empty hand will remove it from your worn items and place it in your hand. "You push the balaclava out of the way." You will be unable to wear the item again until you use the adjust intent again ("You push the balaclava back into place."), and add it to your mask slot.

**What did you expect to happen**: 
The adjust intent should cause a sprite change and not result in removing the item from worn items.

**What happened instead**:
See #1

**Why is this bad/What are the consequences:**
It really doesn't matter that much, but why not fix it?

**Steps to reproduce the problem**:
See #1

**Comment by taukausanake** [comment]
I went to PR 1 and it can't see how they relate. :P Be careful when you use pound sign and a number.

I forget if this was the deal with most masks. I can't recall because the only job I ever play as that uses a mask is Botanist and I just go double mask (face and head) so I never adjust it. I do recall however adjusting it puts it in your hand and not the slot you would imagine it to go into (i.e. head) so maybe it's not so much an issue?

Have you tried putting it on your head after you adjust it? From mask item it turns into a head item and vise-versa

**Comment by Plotron** [comment]
It used to be possible to wear a bandana as a hat while it was on your face (by using the intent), effectively having the appearance of wearing two hats simultaneously.

I guess this issue is a result of a certain tweak that killed the 'exploit'.
