### ISSUE TITLE
Server-Crashing Infinite Loop

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#596]
http://pastebin.com/ubfnnPFC
Not entirely certain of how it was done, but this crashed the live server. Needs to be fixed ASAP.

EDIT: Seems to be related to trying to take a picture of exposed pipe manifold with the handheld photo camera.

**Comment by Krausus** [comment]
It seems this recently happened again, so I decided to take a peek at [the line it refers to](https://github.com/ParadiseSS13/Paradise/blob/fd5e0e289c813a6581fac542d1e04cc2125050a9/code/__HELPERS/icons.dm#L702)...
```
while(TRUE)
	if(curIndex<=process.len)
		current = process[curIndex]
		if(!current)	continue
```
That last line, at the end? If `!current` ever evaluates as true, it jumps back to the start of the `while` loop, without incrementing the `curIndex`, meaning it keeps checking the same overlay over and over, looping every time it realizes it doesn't exist. Blatant infinite loop. I don't know if incrementing `curIndex` will make the code behave properly, since I have no clue how this code actually works, but it at least probably won't loop forever.
