### ISSUE TITLE
IPC Glasses are still horrible

### ISSUE THREAD

**Issue by Wheatley29** [ParadiseSS13/Paradise#5970]
![image](https://cloud.githubusercontent.com/assets/20046182/21072623/ccae70e8-bec0-11e6-935d-476e4f53d86e.png)
The recent bug-fix did not work

**Comment by KasparoVy** [comment]
It was intentionally left that way. The bug was that glasses were being covered by IPC screen styles. I opted to leave this as-is since the last step of sorting glasses for IPCs is to add logic in update_inv_glasses to check whether the user's head's species has the all_rparts flag, the head is robotic and is a monitor then to species_fit the glasses.

Nowhere in the bugfix PR were IPCs mentioned until the very end where I clarified for someone that I wouldn't be re-breaking the IPC glasses just so I could re-unbreak it for a monitor-head IPC glasses-sprite feature PR that I can't do at the moment.

**Comment by Spacemanspark** [comment]
I like the way that the HUD glasses look, but the sunglasses/ HUDsunglasses just look... eh, on monitor heads.

**Comment by KasparoVy** [comment]
If anyone has IPC glasses sprite design suggestions, feel free to post them here. I don't play the race enough to know what most people would prefer

**Comment by KingPhilipIII** [comment]
I never really thought of IPCs seeing through the moniter. I just figured they had a microcamera somewhere along the frame. The moniter was just how they provided feedback like we smile or cry. 

I think just keeping them on the side like clip on enhancers makes more sense than anything else. The logic of how it can transform from a computer-compatible piece of hardware to glasses just by taking them off? Let's just say bluespace unless someone feels like giving IPCs their own special variety of glasses. Which I'm certain nobody does.
