### ISSUE TITLE
Floor Tiles won't update in Security Maintenance.

### ISSUE THREAD

**Issue by CodingCarl** [ParadiseSS13/Paradise#601]
So I was a drone and I was laying down some floor tiles in Security Maintenance. Specifically the room to the right of security. With the desk and the Atmos room. Well when I tried to lay down tiles in the atmos room the picture didn't change. It registered as having floor tiles being laid down, but the image stayed the same. I logged out and logged back in and it was the same.

It only happened in that little atmos room though.

**Comment by Tastyfish** [comment]
It's because they are plating tiles with striped edges, which were done by changing the `icon_state`, which the floor system also uses to know the style of the floor tiles there. Thus, you are placing floor tiles, but they look like the exact (striped) plating that's already there. Probably the only solution is to remove any instances of that striped plating.
