### ISSUE TITLE
Several Plasmamen Issues

### ISSUE THREAD

**Issue by FreeStylaLT** [ParadiseSS13/Paradise#606]
Now I'm not entirely sure which of these are meant to be functioning like that and which are not, so I am instead just listing all of them and will make sure to filter them out once it becomes more clear what's a bug and what isn't.

- If you equip any other hardsuit/softsuit you will still react with the atmosphere and combust, but equipping an advanced firesuit or atmospherics' hardsuit will not get you hot enough to take damage from the fire, effectively allowing you to be on fire indefinitely as long as you have those suits on. [NOT A BUG]

- Firestacks are applied every single time the "your body reacts with the atmosphere!" message is displayed, meaning you can't put yourself completely out by resisting once if it gets displayed more than once

- The firestacks also add light to Plasmamen, so if you have a way of denying the damage caused by being on fire, like with the previously mentioned suits, you can effectively become a permanent, max-brightness walking beacon, the light not getting reduced or going away even after your fire becomes extinguished.

- Being in a shower with running, normal-temperature water does not keep you extinguished for long and you will combust eventually even under the stream of water.

- Hot temperature seems to take longer to fade from Plasmamen than other species, meaning they take more damage even after the fire is put out. [NOT A BUG]

**Comment by Fox-McCloud** [comment]
CE's rig, atmos rig, and the atmos firesuits are all meant to protect you from fire in totality---up to and including being on fire, so that's 100% intentional; I figured that was a mechanic that could happen; not shocked to hear about it happening with them.

The other issues are just part of plasmamen; if you don't have your suit own, you're going to combust and keep combusting indefinitely until you put your suit back on; there's no way to stop this other than to have your suit on--this is why it doesn't matter what situation you're in (other than space); you're going to combust and keep on combusting; you can't stop this except by wearing your very original suit.

The on-fire+firesuit thing is something every single person can do that has access to an atmos fire suit, atmos rig, or CE rig; it's completely intentional.

Yes, they have lower thresholds for the various temperature damage levels; this is definitely a function of the species themselves.
