### ISSUE TITLE
ERT turrets start unwrenched, but are unmovable.

### ISSUE THREAD

**Issue by Fishocalypse** [ParadiseSS13/Paradise#613]
As seen in the title, they still have their anchored variable set to 1 I believe. Makes it so you have to unwrench turrets twice to move it.

**Comment by Krausus** [comment]
In the map itself, the turrets are set to be unanchored by default. Problem is, [turrets automatically create a turret cover](https://github.com/ParadiseSS13/Paradise/blob/a497411d8985f9f444bc6f5936e9f54928633bfe/code/game/machinery/portable_turret.dm#L73-L75) to snuggle up under, and the turret cover [starts off anchored](https://github.com/ParadiseSS13/Paradise/blob/a497411d8985f9f444bc6f5936e9f54928633bfe/code/game/machinery/portable_turret.dm#L873) regardless of whether the turret itself is. Since the turret is technically unanchored, however, when the cover [passes the wrenching on to the turret](https://github.com/ParadiseSS13/Paradise/blob/a497411d8985f9f444bc6f5936e9f54928633bfe/code/game/machinery/portable_turret.dm#L887-L888), it thinks you're wrenching it into place, so you need to wrench it a second time for the proper unwrenching to occur. Pretty sure setting the cover's `anchored` to match the turret's when it's created will fix this.
