### ISSUE TITLE
Cult Continues to Summon Eldritch Horros

### ISSUE THREAD

**Issue by LightFire53** [ParadiseSS13/Paradise#6162]
**Problem Description**:
It sends a message saying:

Summoning eldritch horrors...
Cult of Pyr'Kaeus has risen!

After round start. Just the once, not like the spammed variant earlier.
**What did you expect to happen**: 
This message shouldn't exist at round start.

**What happened instead**:
Summoning eldritch horrors...
Cult of Pyr'Kaeus has risen!

**Why is this bad/What are the consequences:**
Because this was supposedly fixed already.

**Steps to reproduce the problem**:
Round Start. Need I say more?

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Not even a cult round! Just boring changeling!

**Comment by Crazylemon64** [comment]
Not a bug, this is working as intended. This is for when admins spawn in cult things in a non-cult round.

**Comment by Markolie** [comment]
I think he's referring to the fact that this message is showing up @Crazylemon64, not the fact that the datum is created. There's no reason for the "Summoning eldritch horrors" message to display in-game to admins or in Dream Daemon during startup like the controller debug messages as it only relates to a single game mode.

**Comment by Krausus** [comment]
Yeah... the cult messages...
- Occur during game mode setup, rather than server startup.
- Show to all players. **While the round is starting.**
- Don't show for some game modes, because some don't call their parent `pre_setup` procs.
  - This also means some game modes don't get the cult datum set up, leaving adminbus-cult unusable.

Initialization of the cult datum is all kinds of wrong.
