### ISSUE TITLE
Injecting plasma into things isn't !!fun!!

### ISSUE THREAD

**Issue by Doukhan** [ParadiseSS13/Paradise#6238]
**Problem Description**:
Plasma injected lights/power cells don't go boom

**What did you expect to happen**: 
The stun stick to explode when used/lights to explode when turned on.

**What happened instead**:
Nothing, total inertness.

**Why is this bad/What are the consequences:**
It's a great way to ghetto explode things that's rather underutilised, it'd be a real shame for it to float into the abyss.

**Steps to reproduce the problem**:
Acquire lightbulb/power cell, inject with plasma of desired quantity, put bulb in socket and turn on the lights/put power cell in baton turn it on and hit something.

**Possibly related stuff**
Just a wild guess but could this have something to do with the plasma/plasma dust differentiation a while back?
For reference I was using ground plasma I got from electric storage.

**Comment by Bigtimetripod** [comment]
This makes emagging the light replacer useless. Emagging light replacer makes replaced lights contain plasma and since it does not ignite or exist for that matter, its useless.

**Comment by FalseIncarnate** [comment]
Emagged light replacers actually don't deal with reagents at all, they just rig the light through the vars directly.

This issue is most likely that the rigging of bulbs and cells looks for the "plasma" reagent you would get from a chem dispenser and not the "plasma dust" one you get from grinding up sheets of plasma. I'll look into this more to ensure that is the culprit before making the fix (which frankly is as simple as either changing the required reagent to "plasma dust" or making it work with both).

**Comment by Bigtimetripod** [comment]
Oh, i always thought that light replacer just removed the "injecting" part. I guess i should have tested it first. My bad.
