### ISSUE TITLE
Cryogenic Oversight Control doesn't store proper items

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#6262]
Cryogenic Oversight Control in Cryodorms had only these items after storing and deleting over a dozen crewmembers.

bomber jacket
paramedic vest
bomber jacket
winter coat
geneticist labcoat
hazard vest
chef's apron
magboots
bomber jacket
geneticist labcoat

The crewmembers were put in with full gear, making their items lost forever.

**Comment by Crazylemon64** [comment]
This doesn't sound like a bug to me - most crew items should be deleted when put into cryo storage, and a bare few should remain, such as posibrains, or unique equipment(though all those jackets remaining seems anomalous). Can you make a argument why this should not be the case?

**Comment by awellwisher** [comment]
I've seen it countless times: someone joins a department, gears up, goes SSD into cryo after a few minutes.

All that department gear is now forever lost until new is ordered/manufactured. It makes no sense for items to disappear from station just because someone had them once equipped and decided to leave server.

Each time someone gets deleted in cryo a new job slot is opened in place, the next person to join will be missing gear and will have to run around station ordering it before being allowed to do even basic things.

**Comment by DesolateG** [comment]
Like chappy sword, bartender shotty, sec gear

**Comment by DesolateG** [comment]
Hardsuits too
