### ISSUE TITLE
Can't examine player named "Janos Audron III"

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#6275]
There seems to be an issue either with the name or some combination of his species, but I am unable to examine him for a few rounds now. Examining everything else works fine.

**Comment by Spacemanspark** [comment]
Ya, none of us have been able to, kinda weird.

**Comment by KasparoVy** [comment]
Anyone able to view vars and see his flavour text? What species was he?
Is it possible they're using an HTML exploit w/ flavour text?

**Comment by awellwisher** [comment]
He was a slime person.

**Comment by Davdichan** [comment]
I thought I could examine him as a borg when he was an atmos tech but I wasn't aware others couldn't see them so didn't take much notice.

**Comment by FalseIncarnate** [comment]
He is a slime person, and his flavor text didn't seem to be anything unusual (something like he's some number tall or another typical tidbit). There were no related runtimes when I was told of this a couple nights ago, but didn't have a chance to see if it was just a one-off glitch or something that always happened at the time.

This issue seems to apply to living mobs as well as ghosts, confirmed by multiple people at the time I mentioned. Other mobs were examineable just fine, so I suspect it must be some sort of issue limited to just that particular character, will have to contact the player to get their cooperation with trying to replicate and determine the cause

**Comment by Birdtalon** [comment]
I also have this problem with the player. I have asked him in LOOC before and he said he had no idea. It is quite annoying however and should be used to an advantage.

**Comment by Iamgoofball** [comment]
make an obj that saves his actual mob into a .sav file

we can dissect it that way

**Comment by Kyep** [comment]
This also happened with a "Boris S. Vals".

**Comment by Iamgoofball** [comment]
#6308 because it took you chucklefucks way too long to do this

**Comment by Certhic** [comment]
PR #9674 probably fixes this
