### ISSUE TITLE
Plastic flaps cannot be constructed/deconstructed

### ISSUE THREAD

**Issue by awellwisher** [ParadiseSS13/Paradise#6287]
There is no way to build, move or remove plastic flaps. Airtight or not.

**Comment by Spacemanspark** [comment]
This has always been a thing... perhaps even intentional honestly.

**Comment by awellwisher** [comment]
There was first the plastic flap, only after it came plastic. Please don't treat it as a sacred scripture with clear intent, it's a leftover from older times.

**Comment by tigercat2000** [comment]
This is 100% intentional. Plastic flaps are magical structures made specifically for MULEbots to deliver things- You can get into areas way too easily if you can just rip them down, because they are designed that way.

**Comment by awellwisher** [comment]
There's welders, wrenches and hacking takes a few seconds. It's a cosmetic obstacle at most.

**Comment by Spacemanspark** [comment]
It's not a few seconds, most of the areas with flaps around them have R-walls nearby. Even with thermite, that takes time. And it is most certainly intentional.

**Comment by awellwisher** [comment]
Can you show me who intended it to be so?

**Comment by Necaladun** [comment]
I did most of the original mapping stuff, and yeah, it was intended that those aren't able to be gotten through. HTH.

**Comment by Draconic-saint** [comment]
I see no reason to change their current position. Doors can shock you, walls take a fairly long time to tear down. That's for a reason, so you can't just waltz in everywhere without risk of getting hurt/being discovered.

Having the flaps be deconstruct able means you'd also have to add a serious downside to doing so. Because they often only have single pane of r-glass behind it to prevent people from entry.

And if deconstructing them is not an option, neither should be construction. Filling hallways with unremovable constructions is easily done, and tedious to undo for the administration.

All in all, this is not an issue. It is, or has become (since you're so keen on "intention") a conscious decision.

**Comment by Crazylemon64** [comment]
Oh, yeah, deconstructing easily is a deffers no-no. And if you can't deconstruct these easily, they'd be an effective means of wallgrief

**Comment by awellwisher** [comment]
I never used the word easily.

**Comment by Bigtimetripod** [comment]
Im not here to say that to make em (de)constructable, just here to point out a few things. 

If ye know the power wire, hacking a door open takes 2-3 seconds. 

Since im fairly familiar with game mehanics and how they work, flaps can be passed "under" if laying down. With the help of another crew member or smart use of atmos system, getting past flaps is a easy thing... hacking doors is just faster. So the talk about them being "unpassable" expect mulebots is a rumor.

**Comment by awellwisher** [comment]
@Bigtimetripod
There's always certain things various servers hold sacred regardless of logic or reason, it's merely protected because it was always so and can't possibly be different. Hence my reference to sacred scripture.

**Comment by Spacemanspark** [comment]
And that's a bad thing?

**Comment by awellwisher** [comment]
If you can't see the beauty of being able to rebuild or deconstruct anything you see then I can't make you to see it through my eyes.
