### ISSUE TITLE
Unholy water kills cultists

### ISSUE THREAD

**Issue by awellwisher** [ParadiseSS13/Paradise#6324]
Description of item is either wrong or it's intended to be a suicide trap.

"Toxic to nonbelievers; this water renews and reinvigorates the faithful of a cult."

Yet actually drinking the flask kills user after a minute or two due to braindamage which is not mentioned anywhere.

**Comment by jughu** [comment]
INTENDED EVEN CULT SELF DOESNT BELIEVE IN NARSIE

**Comment by KasparoVy** [comment]
LMAO, interesting. It's clear that the cult check in this reagent's processing no longer works.

**Comment by awellwisher** [comment]
No the braindamage application isn't in the cult check.

**Comment by Crazylemon64** [comment]
[1u of unholy water corresponds to 3 points of brainloss.](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/reagents/chemistry/reagents/water.dm#L351)
[At 60p of brainloss, you start to randomly say things.](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/human/life.dm#L111-L146)
[At 100p of brainloss you lose the ability to talk, breathe, and move - effectively a death sentence](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/human/life.dm#L148-L151)
[At 120p of brainloss you die outright, no saving throw](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/human/life.dm#L153-L155)

You'll reach 60p after 60/3 (20) chem processing ticks(since unholy water depletes at 1u/tick) - or 40 seconds - from 20u of unholy water.

You'll reach 100p after 100/3 (34, rounding up) chem processing ticks - 68 seconds - from 34u of unholy water.

120p will be reached in 40 ticks - 80 seconds, from 40u of unholy water.

[For a holy water cultist deconversion, at least .4 * 75 = 30u of holy water is needed](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/reagents/chemistry/reagents/water.dm#L283)

This means, that a standard dose of holy water given to a cultist for deconversion, transformed into unholy water, will give them at least 90 points of brain damage - near the point of total disfunction. GIven that you'll want more than 30u (exactly that amount will only have a 33% chance of working) - at least 35u, given the increments of 5 most reagent containers work with - turning the water inside you unholy is effectively suicide, unless you time it extremely well such that the remaining unholy water will not outright kill you.

I'm not sure why unholy water was designed as an "answer" to holy water conversions, besides a means of making others who've been saturated with it vulnerable to a lethal poisoning.

**Comment by awellwisher** [comment]
>120p will be reached in 40 ticks - 80 seconds, from 40u of unholy water.
Coincidentally that is the entire unholy water flask you can summon as an aid item at altar. So it is resources spent on suicide.

**Comment by Crazylemon64** [comment]
@awellwisher In that case, one is capable of moderating one's use of the flask - one does not need to drink the entire flask to obtain the benefits of a more moderate amount. Nonetheless, the damage makes it difficult to use without mannitol - 3*5 = 15  brain damage per quaff, for a stun-resistance+speed bonus for 10 seconds.

**Comment by awellwisher** [comment]
It could at least have its description altered to indicate the fact that it will kill you if even if cult.

**Comment by Crazylemon64** [comment]
I'll mark this like so, as I agree that it is not intuitive.

**Comment by Crazylemon64** [comment]
Comparable buff chems:
[Meth does 0.5 damage/reagent tick](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/reagents/chemistry/reagents/drugs.dm#L306-L307)
[Crank provides similar benefits, and causes brain damage only by occasionally injecting meth, using the same damage as above for those rare moments](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/reagents/chemistry/reagents/drugs.dm#L157-L175)
[Bath salts have the same chance as crank to inject other brain-damaging drugs, although some are more extreme than others](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/reagents/chemistry/reagents/drugs.dm#L349-L379)

Now as for straight brain *poisons*, there's sarin, neurotoxin, and mercury.
[Neurotoxin does 1p/tick, up to 80 points - at which point that nosedives to 0.1p/tick](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/reagents/chemistry/reagents/toxins.dm#L495-L499)
[Sodium Thiopental does 0.1p/tick - not a strong brain poison](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/reagents/chemistry/reagents/toxins.dm#L709-L711)
[Sarin does 1p/tick normally, and 2p/tick after it's been in the victim's system for 120 seconds](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/reagents/chemistry/reagents/toxins.dm#L894)
[Mercury does 0.7p/tick](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/reagents/chemistry/reagents/toxins.dm#L104-L105)

**Comment by jughu** [comment]
Cultists arent supposed to get braindamage only.non believers

**Comment by jughu** [comment]
Cults are supposed to heal from it and purge holy water

**Comment by Crazylemon64** [comment]
[It braindamaging everyone is very much intentional, right  from the outset of its addition.](https://github.com/ParadiseSS13/Paradise/pull/1944)

**Comment by Crazylemon64** [comment]
[For comparison, here is what -tg- has for its unholy water](https://github.com/tgstation/tgstation/blob/d5d36a691f849e7cc9a84efbc150f74143c1da94/code/modules/reagents/chemistry/reagents/other_reagents.dm#L224)

Note that the brain damage is now for non-cultists only, and it actually heals cultists of permanent damage, instead of simply reducing status effects.
