### ISSUE TITLE
Science Misc Test Lab - First Round Testing

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#637]
-There is an Electropack. Why?
-There is no way to vent the gas testing chamber. The pipe is disconnected from the exterior vent and there's no way to turn it on anyway. There's also no vent inside the chamber to suck anything out. This means if you pump any gas in, it's in there forever.
-There are toolboxes, but no toolbelts.
-There's no paper bin.
-You start off with large beakers, but not large grenade casings. 
-The walls of the test chamber are not smoke-proof, meaning you can't test your smoke grenades on monkeys safely, since you get gassed too. I killed myself with a plasma smoke grenade in this way, as the gas generated by the smoke that escaped filled the room, and later caught on fire.

**Comment by Spacemanspark** [comment]
I do know that some people used Misc research for changeling study. That might have something to do with the electropack.

**Comment by fj45** [comment]
-The walls of the test chamber are not smoke-proof, meaning you can't test your smoke grenades on monkeys safely, since you get gassed too. I killed myself with a plasma smoke grenade in this way, as the gas generated by the smoke that escaped filled the room, and later caught on fire.

Weird...I would think thats an issue with smoke, but if it isn't....

**Comment by Fox-McCloud** [comment]
-The electropack being part of misc research is something almost as old as Rev. 4407; our misc. research lab got converted over to a telesci lab--and with it, stuff was lost. It's just a way to torment or torture things, quite frankly---and since science has easy access to as many as they want anyway.

-Yep; may need addressing in the future, but generally speaking you should utilize the scrubber and airpump in the test chamber if you're going to be testing massive amounts of gas---it's not a burn chamber, after all (that's what tox lab is for).

-Intentional; not every scientists needs to be toting around a toolbelt what with the ridiculous amount of stuff they have 

-could probably be added,but hardly important

-this is an R&D research item--they're not meant to just be laying around. The large beakers are there largely for convenience as science can make them at round start; large grenade casing need to be researched----plus science doesn't need more free tech levels just lying around.

-Larger issue with smoke that has nothing to do with all--this will persist until smoke is recoded...and even then, it may still pass glass; not much I can suggest other than to wear a gas mask and stop dumping copious amount of plasma into the air.

**Comment by Telvayne** [comment]
I'm seconding the paper bin.  We have a pen, folders, and a voice recorder, but no paper bin.  Has to be a simple oversight/bug.

**Comment by Fishocalypse** [comment]
Random but somewhat related, the glass in misc research is not plasma glass... If reinforced glass was not made fire proof this would end horribly in any burn experiments.

**Comment by Deanthelis** [comment]
To respond to fox:

-An item being in there that can only be used for torture purposes is weird. It being there since 4407 doesn't really justify it, but it also doesn't really hurt anything, I guess.

-Firstly, there is no scrubber. There is a disposals outlet, and a gas injector, and that is it. There is no scrubber and air pump in there, I don't know what on earth you're talking about. http://puu.sh/gNRGp.png Secondly, there is no way to throw things like smoke grenades into the toxins burn chamber, and if all gas-related things are to be tested in the toxins chamber, then there is no point to the misc lab test chamber at all.

-Fair.

-Good!

-If that is the case, replace the big pile of large beakers with a box of normal beakers, like Xenobotany has. Doesn't make much sense otherwise. If they want large beakers for large grenades, they'll have to autolathe them, like you said.

-It's not just plasma smoke. All smoke goes through the glass and occupies the tiles of the walls, meaning anything smoke-wise you test in there will always backfire. How are we supposed to test our grenades on monkeys without burning our own faces off? As a side note, smoke really should be redone, at least to not penetrate objects that also block atmos.
