### ISSUE TITLE
Cryoing then ghosting sometimes won't show the warning

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#6541]
**Problem Description**:
Ghosting while in cryo will sometimes not display the respawn rights warning. EDIT: even before the 30 minute mark, it sometimes wont.

**What did you expect to happen**: 
It's very unpredictable. Sometimes ghosting in cryo won't even give you the warning.

**What happened instead**:
Even if you don't get the warning, it is likely respawn rights are removed (though I've had it work fine too before).

**Why is this bad/What are the consequences:**
If we're removing respawn rights, it should absolutely display the warning in all cases.

**Steps to reproduce the problem**:
Go to cryo and click ghost. Hope it doesn't display the warning so that my point is proven.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Why is cryoing and ghosting prohibiting respawn? It's a clean way to remove a body from the round and clear the job slot. There is hate on the suicide verb which people use to respawn as NPC. Even if that were removed, they could just biblefart too, so why not just get rid of this limitation period?

**Comment by uraniummeltdown** [comment]
They added it because apparently people were cryoing when they weren't antag, if you suicide+ghost/cryo before 30 mins you get respawn rights taken away. I think it's stupid because, like you said, you can just biblefart, throw yourself out an airlock, set yourself on fire, beat yourself to death, breathe empty internals...

**Comment by Anticept** [comment]
I had a person this shift ghost before the 30 minutes, and it did NOT warn them. They had their respawn rights revoked and an admin had to intervene.

**Comment by Krausus** [comment]
> Ghosting while in cryo will sometimes not display the respawn rights warning.

This should not be possible. The code that ghostizes you into a non-respawnable state only runs if you get the warning and choose to ghost. It *is* possible to accidentally proceed with the ghosting by pressing enter or spacebar when the warning pops up, as "ghost" is the default option; that's probably something we should change.

> They added it because apparently people were cryoing when they weren't antag

Yep. People would hog a round-start job slot they wanted to antagonize with, not spawn as an antag, and immediately suicide or go to cryo so they would have a chance at being an event antag. That sucks for anyone who wanted to start as that job or who depends on having someone actually doing that job.

> I think it's stupid because, like you said, you can just biblefart, throw yourself out an airlock, set yourself on fire, beat yourself to death, breathe empty internals...

Yes, there are ways to skirt around the respawnability system, because it's not possible to automatically and reliably detect all methods of suicide. Intentionally abusing the limitations of the system is unwise, however.

**Comment by Crazylemon64** [comment]
The reproduction method seems painfully vague, unfortunately. Please enumerate scenarios, and the station time at which one attempted to cryo

**Comment by Anticept** [comment]
It's not a consistent thing, @Crazylemon64. I can do some testing to see if its possible to reliably reproduce, but I figured I would bring this up anyways in case it was a simple oopsie.

**Comment by Anticept** [comment]
Haven't been able to duplicate. If it comes up again, will reopen.
