### ISSUE TITLE
Karma not being awarded to players with spaces in their ckey name

### ISSUE THREAD

**Issue by Allfd** [ParadiseSS13/Paradise#6595]
**Problem Description**:
When karma is given, sometimes it is to "Your Ckey" instead of "yourckey".  For purposes of the karma store, only the amount for "yourckey" is considered.

**What did you expect to happen**: 
Karma to be recorded for "yourckey" in all cases.

**What happened instead**:
Karma is instead sometimes stored in "Your Ckey"

**Why is this bad/What are the consequences:**
Players with spaces in their byond login often have a second Karma Account which accumulates karma they have earned but do not have access to.

**Steps to reproduce the problem**:
I have no idea how to reproduce this.

**Comment by Krausus** [comment]
> When karma is given, sometimes it is to "Your Ckey" instead of "yourckey".

That's how it's designed to work, actually. The karma database queries use full keys, not canonical keys. That's not the way it *should* be done, of course, but actually fixing it would require someone with access to the database to put effort into correcting it.

> For purposes of the karma store, only the amount for "yourckey" is considered.

This should not be the case. Every query in the code uses full keys... though, uhh, those may not necessarily always be the full key, since BYOND doesn't actually care whether they are. Which is part of the reason you should always use ckeys.

We should probably go through the effort to shift it over to ckeys at some point.

**Comment by Allfd** [comment]
I can merge the duplicate accounts once the code is updated
