### ISSUE TITLE
Showering triggers Plasmaman's auto-extinquishing

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#6628]
**Problem Description**:
Showering triggers Plasmaman's auto-extinquishing

**What did you expect to happen**: 
Getting clean and soapy

**What happened instead**:
I was so damned hot that I released my extinguisher.

**Why is this bad/What are the consequences:**
Wastes use of extinquishers

**Steps to reproduce the problem**:
Be plasmaman. Require a wash. Shower.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing of note.

**Comment by SamHPurp** [comment]
@KasparoVy

**Comment by KasparoVy** [comment]
:eye: :eye:

Sorry I've not seen this, been really ill for the past while. Strange, because the Plasmaman suit auto-extinguishing handled [here](https://github.com/ParadiseSS13/Paradise/pull/6555/files) only does it if the mob's got firestacks.

You know what, it's probably because I didn't check for `H.on_fire` as well. Just a moment.
