### ISSUE TITLE
Mech Mounted Teleporter is disfunctional

### ISSUE THREAD

**Issue by Crazylemon64** [ParadiseSS13/Paradise#6633]
This happens both with the precise and standard mech teleporters.
Clicking results in no effect.

@Kyep

**Comment by Kyep** [comment]
Just tested it, and it worked fine for me.

Need repro steps to investigate this further (include the type of mech you are using).

**Comment by Crazylemon64** [comment]
Mech type: RIPLEY
Clicking tiles inside my vision cone with either the regular or precise teleporters raised resulted in no message or apparent effect.

**Comment by Kyep** [comment]
@Crazylemon64 Tested it. Worked fine for me. The only time that it fails with no notice, as you describe, is when you are in a no-teleport area, such as z2. If you use it on the actual station, or really anywhere outside z2, it works. I don't consider it a bug that mech teleporters don't work on z2, because Z2 is meant to have *all* teleport effects disabled, AFAIK.

**Comment by Crazylemon64** [comment]
Oh, z2 - that would explain it. Silly me!
