### ISSUE TITLE
Colourblind disabilities not functionning correctly

### ISSUE THREAD

**Issue by Delnth** [ParadiseSS13/Paradise#6768]
**Problem Description**:
It is possible to see the color of vox's blood when colourblind (disability).

**What did you expect to happen**: 
It is self-explanatory, really.

**What happened instead**:
I expected it to be darker for dark blood, only using white/black color.

**Why is this bad/What are the consequences:**
It's not so bad, but somewhat doesn't makes any sense when playing a colourblind character.

**Steps to reproduce the problem**:
I don't think it is necessary.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It was probably vampire. And I was going to the brig then stabbed myself with a knife because of a missclick, the vox blood had the blue color.

There's two screenshots here : http://imgur.com/a/sk3mq

**Comment by KasparoVy** [comment]
That's just how it works rn because of how it's handled, blood is currently exempt from the process that changes the colour of stuff on screen for colour blindness in order to get noir glasses to render blood with more emphasis against the black-and-white of everything else. We rationalize it for certain species that most likely'd have a keener sense of smell, but that's just about the extent of it.

**Comment by tigercat2000** [comment]
@Fox-McCloud Not a bug either, known side effect of blood having the NO_CLIENT_COLOR flag. We'd have to do something crazy like /vg/ with client overlays and make a grand old mess to change this.
