### ISSUE TITLE
META: Science has access to an EVA Suit

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#6874]
The Toxins Launch Room has a Suit Storage Unit inside for an EVA suit. Science had EVA access removed long ago, so this seems like a mistake.

**Comment by taukausanake** [comment]
It's supposed purpose is so that Toxins can rebuild their minimalistic bomb range. I actually like it because testing bombs only works once. You need another test area or your risk blowing up the observation room. Then again, Science doesn't need EVA access but someone to rebuild the range would be greatly appreciated

**Comment by Lady-Luck** [comment]
Scientist antags have enough advantages, having the plausible deniability of their EVA suit being legit (even if someone else took and it was stolen from EVA) would not be a good thing.

**Comment by Fox-McCloud** [comment]
Meta is a different map than Box; this was intentionally added.
