### ISSUE TITLE
IPCs can use DNA scramblers

### ISSUE THREAD

**Issue by sothangel** [ParadiseSS13/Paradise#6931]
**Problem Description**:
IPCs can use DNA scramblers despites having no DNA.

**What did you expect to happen**: 
Nothing at all.

**What happened instead**:
DNA scrambled as would with a human, given a human name.

**Why is this bad/What are the consequences:**
It just makes... no sense.

**Steps to reproduce the problem**:
Get DNA scrambler, use DNA scrambler.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Traitor round.

**Comment by granodd** [comment]
IPCs and DNA is a bit of an oddball, to say the least. On one hand, IPCs are near completely immune to most things a changeling could do to them (outside the EMP), don't take rad damage, don't take genetic damage, and aren't affected by viruses (though I'm pretty sure this one isn't related to DNA).

On the other hand, IPCs still need to select a blood-type in character creation, will still "bleed" onto items that hit them (I know this all to well from accidentally hitting myself with a wrench in atmos), and also leave behind fingerprints. All of this (the blood and fingerprints) have a DNA string that can be linked back to that specific IPC. It's something that's bothered me for a bit, though I've always just assumed that most of it was due to balance, though it does sorta beg the question of how a DNA scrambler would ICly work on an IPC.

I guess it's also the question of how an IPC with a monitor head can smoke. It just works.

**Comment by Anoonki** [comment]
[Alright, calm down, Mister Howard.](http://i.imgur.com/6Ll8YVs.mp4)

**Comment by taukausanake** [comment]
@granodd Said the guy with Canti as his avatar who mind, is a robot that can eat ramen. But yeah, all valid points otherwise

**Comment by AffectedArc07** [comment]
I was that IPC with a human name that used a DNA scrambler on a traitor round. Fun but no sense made.

**Comment by SamHPurp** [comment]
Can re-produce... on it...
