### ISSUE TITLE
Pulling maintenance drones onto the same tile as an airlock opens that airlock

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#6941]
**Problem Description**:
Pulling a maintenance drone into an airlock opens the airlock.

**What did you expect to happen**: 
I expected the airlock to reject the attempt at access.

**What happened instead**:
The airlock opened.

**Why is this bad/What are the consequences:**
Allows people to access areas they shouldn't be able to.

**Steps to reproduce the problem**:
1. Be pulling a maintenance drone
2. Alt-click the airlock
3. Click the turf underneath the airlock

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

This also works with anyone who has access to that airlock, or with cyborgs.

**Comment by KasparoVy** [comment]
Movement code working as intended as far as I'm aware.

**Comment by Lady-Luck** [comment]
This isn't actually a bug. It's just far easier to do with density=0 mobs because right-angles.

**Comment by tigercat2000** [comment]
This is *sorta* a bug, you aren't supposed to be able to trigger mob movement checks at all if the turf is blocked. However, the access part isn't, mobs Bump() causes doors to open. You can throw humans with grab mode at doors to do the same thing.

**Comment by Lady-Luck** [comment]
I personally wouldn't want the current functionality to change because it's going to make it a bigger hassle to do it with a prone mob, you'd have to do the throw thing you described every time.

But meh... it's not a huge deal either way.

**Comment by Citinited** [comment]
The problem is you have that functionality in the first place -- you shouldn't be able to open doors with prone mobs at all.

**Comment by taukausanake** [comment]
You're not opening the door with a prone mob though. You're opening it with the ID on that prone mob. You think the doors are smart enough to know someone alive/awake is in front of it? It only cares about the access.
I suppose this is kind of an exploit but not a bad one. Thinking a little more, it's something antags can use in their favor, instead of stealing an ID from someone just throw the guy at the door you want to get through. Repeatedly if needed. This only becomes a problem when non-antags start doing it but at that point it's most likely greytide

**Comment by king5327** [comment]
Or grab drones and toss them at doors for infinite access, ignoring their pleas for escape.
