### ISSUE TITLE
Missing scrubber from genetics

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#6971]
**Problem Description**:
What is the problem?

See this image. Scrubber pipe stops at the table, I suspect it was supposed to be connected to a scrubber.

![image](https://cloud.githubusercontent.com/assets/521038/24411044/d134b5e6-13a2-11e7-988d-4ee3f4240e93.png)

**Comment by SamHPurp** [comment]
Myself, @FreeStylaLT @Kyep and several others all have open map update PRs... mine is for bugfixes, so I guess it'd fit into mine... but... realistically the issue right now is not knowing whose PRs are going to get merged and when, because updating these maps are a right pain in the ass, to accommodate other peoples future merges....

Good catch though, I'll try to stick it onto my bugfix PR... as soon as the Maintainers can give us more guidance on these.... (Kyeps have been open a month now!)
