### ISSUE TITLE
Light Floors are not affected by shadowling abilities

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#7103]
Shadowlings can't disable light floors with their abilities and get screwed over by light floors covered by glass.

**Comment by Lady-Luck** [comment]
Uhh. People put reinforced windows on top of them specifically to protect them, as to turn them off you only need to click on them.

**Comment by Twinmold93** [comment]
Use a thrall to remove the window, then turn it off. Then put a window back over it so others have to go through the heck of removing the window, too. I do know what you mean, however, and part of the issue is light tiles don't have a broken state. In theory, it'd be just add a cracked icon to it, turn it off. Then just use glass on it to fix it and allow you to turn it back on. Crowbar it would drop the wire, metal, and glass shard.

**Comment by taukausanake** [comment]
Light floors should really just be connected to the power grid in the area. Act like normal lights. It's really weird when you have the power cut off somewhere but you still got these magic powered tiles lighting up a room
