### ISSUE TITLE
[META] Airlocks don't have cyclers

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#7144]
**Problem Description**:
What is the problem?
Airlocks don't have a cycler on metastation. Not a major issue, but if linda is being sped up or made more lethal, it will eject people into space.

**Comment by tigercat2000** [comment]
Not a bug in the slightest, cycling airlocks aren't part of Metastation, and they're being partially phased out on the Cyberiad as well

**Comment by Aurorablade** [comment]
Replace all airlocks with autogibbers

**Comment by SamHPurp** [comment]
@tigercat2000 What is the decision behind phasing these out? This seems like a significant design decision / step backwards.

**Comment by Anticept** [comment]
@tigercat2000 again, if we start using the sped up linda, people will be launched out of airlocks if there are no magboots.

**Comment by tigercat2000** [comment]
@Anticept @SamHPurp It's up to the person implementing fastmos to deal with issues such as that. So far they've been slowly phased out on Cyberiad because most of the coders strongly dislike the way they function- even mapping them in, they're confusing, and under the hood they use the old Bay12 radio communication system to deal with all of their parts. Metastation never had them in the first place.

**Comment by Anticept** [comment]
@tigercat2000 as long as it's not a "fuck airlocks" or "linda is fine don't change it" attitude, then I'm OK with what you say. Yes they are a pain.

There's a problem with linda 2.0 that we've got to also consider before it can be pushed live, and that's blobs and atmosphere. Alffd and I seem to think inflatables are the answer, but we need some kind of quick to set up airlock and pumping system so people can get an inflata-airlock set in under a minute. Otherwise, this linda refactor is going to be a HUGE buff to blobs as people get launched into space.

**Comment by Fox-McCloud** [comment]
Yeah, cycling airlocks are on their way out, even with a faster LINDA.

**Comment by SamHPurp** [comment]
😕

**Comment by Anticept** [comment]
For now @Fox-McCloud but there's going to be real problems in the future if it's just a "fuck cycling airlocks" attitude. Unless you have good reason, you're going to be holding back a proper atmos sim as long as you hold that attitude.

**Comment by SamHPurp** [comment]
> Metastation is the standard

🤢

**Comment by Kyep** [comment]
@Fox-McCloud You need to actually explain and *justify* why Metastation is the standard. You can't just presume its the standard and dismiss anything that differs from it. That's like answering the question "why is this box red" with "every box in this building is red". It doesn't actually *explain* or *justify* anything. A proper answer would be something like "cycling airlocks are bad because they are tedious and don't have any atmos benefits over normal two-door sally port airlocks". Or in the box case: "the box is bright red to make it visible, even in low-light environments".

**Comment by taukausanake** [comment]
If Metastation is the standard then we should just switch to it and solve all its issues. After all, Boxstation has maint tunnels no one likes and cycling airlocks that just get in the way. Rest in peace Boxstation, the one station we always use but secretly disliked because it not /tg/
