### ISSUE TITLE
Sometimes breaches are shrouded in darkness

### ISSUE THREAD

**Issue by ghost** [ParadiseSS13/Paradise#7163]
This happened the other night with a admin bus blob round and fastmos. I am told there is something screwy going on with lighting and turfing, was linked this in chat: 

![](https://cdn.discordapp.com/attachments/145700319819464704/302724155680358400/unknown.png)

Hopefully it can get resolved before fastmos is implemented full time.

**Comment by Anticept** [comment]
This can happen regardless if it's a breach or not. There's a couple tiles near the north end of atmos next to the tanks that like to do this. Unfortunately, its difficult to replicate.

**Comment by Fox-McCloud** [comment]
I don't think that runtime has anything to do with the problem at hand, in *this* case anyway.


Most of the time, when something fails to update, it's because something, that emits light, had its `loc` set directly instead of calling `forceMove`, which can result in lights updating weirdly/not at all.

**Comment by Contrabang** [comment]
This hasn't been seen this in game or runtime wise recently, likely fixed by SSlighting
