### ISSUE TITLE
Dionas

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#7216]
What is the problem?
When a diona evolves it can no longer steal blood

Why do you think this is a bug?
Cause evolving should get only better stuff not downsides

How is what happened different from what you expected?
i expected my diona verbs to stay

The most important section. Review everything you did leading up to causing the issue.
be diona --> evole --> lose verbs --> be sad

**Comment by SamHPurp** [comment]
You've really got to work on your Bug report titles....

Are you saying that once you're a full Diona no longer a nymph you can no longer steal blood?... That seems entirely intentional.

**Comment by alexkar598** [comment]
is it?

**Comment by FalseIncarnate** [comment]
Yes, this is intentional. Diona only use blood to become qualified to evolve into a humanoid form. Once in a humanoid form, they have nothing else to really gain from doing it since they can't become MORE humanoid. Evolved Diona also can't eat weeds from hydro trays or refill the nutrients of the trays, which is something limited to their primitive/larval stage.

And yes, please make your issue titles actually like a quick summary of the issue, like "Evolved Diona can't steal blood" or something like that. It aids in figuring out what the issue is about at a glance.

**Comment by alexkar598** [comment]
well it seems i can not learn new languages when evolved...
