### ISSUE TITLE
Deep Fried Grab

### ISSUE THREAD

**Issue by granodd** [ParadiseSS13/Paradise#7239]
![image](https://cloud.githubusercontent.com/assets/22057974/25770668/a60988da-3209-11e7-9ae7-c385adb986ad.png)

While fooling around in my test server, I came to found that when you go to dunk someone's head into the deep fryer, it will snag your grab intent and deep fry it...

Similar to the issue where grab intents could be placed into display cases. Other kitchen combat moves may have the same effect of taking in the grab as an "ingredient", though I've only observed it with the deep fryer so far. Able to be done with both the reinforced grab and kill grab, likely able to be done with the first level grab as well.

**Comment by Crazylemon64** [comment]
ahahaaaha

**Comment by Crazylemon64** [comment]
@FalseIncarnate

**Comment by FalseIncarnate** [comment]
Seems like more an issue of whoever did the lethal kitchen PR didn't properly handle the grabs after dunking the victim than something I did wrong. I'll look into it though.

**Comment by Crazylemon64** [comment]
Oh oops I misremembered who did the Lethal Kitchen PR
@Twinmold93

**Comment by Twinmold93** [comment]
See, here's the interesting thing: When I tested it prior to the PR being merged, I NEVER got the grab to do this. I heard recently there has been an issue with grab also being able to be put inside display cases, so... This issue, from what I've heard, has only recently shown, and wasn't apparent, or even active, when the PR was merged. I can see if I can try to fix it later today, but I honestly have no idea what the fuck happened to cause this, since it was supposed to, when you did the action for grabs, completely remove the grab such as it does with cult forges (which has the same general code for the concept). @Aurorablade
