### ISSUE TITLE
Clown attacks with PDA and banana peels are not logged, giving clowns a free ride to grief

### ISSUE THREAD

**Issue by whiskeyfur** [ParadiseSS13/Paradise#7267]
**Problem Description**:
Clown attacks and antics are not logged, so AHelp is rarely useful to actually catch a clown who is griefing. And most clowns KNOW this and will use it to their advantage.

**What did you expect to happen**: 
It becomes near impossible to catch problem players using clown as a way to grief without getting caught. I've already had rounds ruined by clowns pulling antics that resulted in patients dying in medical.

**What happened instead**:
Clowns reported through AHelp should be held accountable for their actions. They are not due to lack of evidence.

**Why is this bad/What are the consequences:**
They have RUINED ROUNDS for people because they can get away with it.

**Steps to reproduce the problem**:
Have a clown use his PDA tricks or banana peels, and see if they appear in the log. I've been told they do not. Now imagine said clown doing this in medical when there's a crisis situation. He is usually held blameless for lack of evidence.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Crisis situation, working on three patients at once, even though I'm the CMO I'm still a doctor too. Then a clown comes in and starts throwing peels around in sleeper 1. AHelp did nothing as they could not catch him doing it.

**Comment by SamHPurp** [comment]
Did you call sec?

Handle this IC... this isn't something that requires logging.

**Comment by whiskeyfur** [comment]
Security was called, nothing happened. the AHelp happened long after because I was just that busy.

The only reason that griefer backed off was because I basically screamed in OOC that he was 'fking pissing me off' (toned down from the actual language). Only then did he leave. 

The response I got was ICK OCK.. this has nothing to do with knowledge, this has everything to do with failure to RP a clown. They're there on station to entertain.. you don't entertain people by pulling the doctor down to the ground when he's got three critical patients on hand. That's just plain common sense and it DID get people killed.

And AHelp was useless because the admins didn't know who it was, since it wasn't logged.

**Comment by FalseIncarnate** [comment]
Slipping on things doesn't leave generate a log. This applies to water, lube, banana peels, soap, clownfish, and the clown's PDA equally. The only thing of what I just mentioned that IS logged is lube being sprayed from a spray bottle.

If a clown is actively interfering with medical treating patients, ESPECIALLY critical patients and during emergencies, the clown is in direct violation of space law (creating a workplace hazard at minimum, convincing the officer it is an act of sabotage or even manslaughter sounds rather easy when it was more than one patient on the line) and their own SOP (since they are directly endangering other personnel and continuously slipping someone for no apparent reason is not considered attempting to entertain).

A clown slipping you repeatedly is an entirely IC issue, and should ideally be handled as such. If the clown seems to be specifically targeting you (and only you) with his antics, and does so over multiple rounds, then it begins to be an OOC issue that you would want to bring to the attention of an admin as there is a potential meta-grudge or at the very least a major annoyance.

**Comment by Fox-McCloud** [comment]
This has little to do with logging or non-logging, to be honest; this is more whether an ahelp gets answered or not...which isn't a codebase issue. Closing.
