### ISSUE TITLE
[s] Paper Engines

### ISSUE THREAD

**Issue by tigercat2000** [ParadiseSS13/Paradise#7375]
**Problem Description**:
You can produce infinite power by exploiting paper and electrified grilles with Tesla Coils

**What did you expect to happen**: 
There would be no extra power generated

**What happened instead**:
You can multiply the power of a zap with tesla coil bounces

**Why is this bad/What are the consequences:**
![https://www.youtube.com/watch?v=3aLyiI2odhU](https://img.youtube.com/vi/3aLyiI2odhU/0.jpg)

**Steps to reproduce the problem**:
[Redacted]

**Comment by Anticept** [comment]
The tesla is also silly in this regard, as it too generates infinite power with no satisfying lore explanation.

All other engines use plasma as a fuel (well, except the turbine at idle which is also silly, but generates negligible amounts):
- SM and Singularity use plasma in collectors, a finite resource. You can also use heat from the SM to power TEGs.
- Solars obviously use solar energy.
- Turbine needs plasma for fire.

The SM, in general SS13 lore (but not necessarily paradise lore) is a plasma supercrystal that interacts with bluespace. Heat causes criticality, where the lattice delaminates very slowly, releasing enormous amounts of energy. Too much heat actually causes a run-away delamination event, much like supercriticality in nuclear fission.

**Comment by Allfd** [comment]
The problem in my mind anyways, is that the arcing does not cost energy from the grid.

Fixing it probably is not so simple, I have zero frame of reference for how much energy things cost

**Comment by Anticept** [comment]
The whole thing with grilles arcing from throwing things at them is absolutely silly period. I really feel like the better answer would have been to make them ridiculously resistant to throw damage, rather than doing this whole arcing thing. That way, you would have to throw a lot of things at them to get them to break.

**Comment by Fox-McCloud** [comment]
This is a mistake in math; as @Crazylemon64 @Aurorablade and I went over, it generates a net loss of power; @FalseIncarnate further reconfirmed this after he noticed a divisor in it the total calculations.

Basically put

![img](https://i.gyazo.com/d36504d06060ed2c601c29c3a219090e.png)

Which is the best case scenario will generate a net loss of power unless admins var edit the tesla coil's default divisor (doesn't count), or var edit the strength of the capacitor's past the game's allowable 1-4 (again, doesn't count).

Players simply can't generate power in this way; it's a net loss, and again, the above is a theoretical that can't really happen on station; once you get even closer to reality (APC that is also getting charged which has power drain from the disposals and conveyors), it's even worse.

**Comment by Allfd** [comment]
@Anticept 

I was making a reference to the fact that our power numbers seem arbitrary sometimes.

@Fox-McCloud 

Thanks for doing this!

**Comment by KasparoVy** [comment]
Syndicate Vulpkanin science at work.

**Comment by Anticept** [comment]
@Allfd indeed, but in order to actually get an idea of what those power numbers should be, there needs to be energy relationships. As it stands, power is pretty arbitrary because we don't actually have interrelated systems; we have power going in, but nothing coming out other than magical items popping into existence.

That said, as I plan out more of adv powernets for a proposal, I'll be visiting much of these power systems and consumption.
