### ISSUE TITLE
Simple animals run as fast as humans

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#7420]
#7066 refactor sped up simple animals to be as fast as shoe-wearing humans.

That impacted the balance around simple animal antags such as swarmers or slaughter demons and seemingly wasn't really intended, seeing as it was a refactor, not a balance PR.

I'm not sure if this is actually an issue or was intended, but I feel it's best to sort this out before making any PRs or stuff.

**Comment by Bram961** [comment]
Swarmers are way to fast making the fast multiplying, ventcrawling team enemy a huge issue because single units are also hard to hit and therefor kill now

Slaughter demons are meant to ambush people from blood, but be moderatly easy to run away from if they don't manage to corner you or surprise you from closeby.

Giant spiders are to fast, for reasons see Swarmers.

Cult constructs especially wraiths are much to fast for the amount of damage they do.

**Comment by alexkar598** [comment]
Not an issue anymore please close

**Comment by tigercat2000** [comment]
Fixed by #7528
