### ISSUE TITLE
Cable laying

### ISSUE THREAD

**Issue by Bram961** [ParadiseSS13/Paradise#7475]
A large chunk of cable laying code is gone since the RCL pr which means one of the ways to lay cables is not functional right now. @davipatury 
https://github.com/ParadiseSS13/Paradise/pull/6691/files#diff-2cb8ad94e36a11c784068dc31a1236f7L700

The part of the code is right there, the comments give a pretty good description of what is supposed to happen. 
when in https://puu.sh/wbO0Z/a3e586cdea.png this situation clicking the cable should create https://puu.sh/wbO41/ecb8aedd64.png this situation, not create a knot ontop of the clicked cable.

**Comment by Anticept** [comment]
I actually prefer what we have now. It allows you to place cable at the far end of the tile next to you. This is useful when fixing wires that people cut under the engineering SMES by using alt click examine. Under the old way, you end up having to deconstruct the area behind the SMES to repair those wires, or decon the SMES themselves.

**Comment by Bram961** [comment]
the diff I posted is actually not the issue but the part of code that does what it needs to do is definitly not functioning propperly, Ill look further.

**Comment by Bram961** [comment]
![wat, no.](https://puu.sh/whirf/3cf8666007.gif)

**Comment by Anticept** [comment]
Ok that last part is hilarious.

But it is because of how that is functioning that I find it more useful. As said, you can lay cable from the center of the next tile to the outer side of it. This is extremely useful for laying cable to the walls without deconstructing machines.

What we really need is the old system with the possibility laying wire in any manner on the next tile. I'll have to think on it.

**Comment by Crazylemon64** [comment]
I think I fixed this one.
