### ISSUE TITLE
Grabbing someone and a banana at the same time lets you drag them indefinitely without any chance of recovery

### ISSUE THREAD

**Issue by theColdflame** [ParadiseSS13/Paradise#757]
As above. This gets used a lot, but I'm pretty sure it's not actually an intended feature (might be though, so this may be a false flag). It presents a pretty large balance issue given the availability of banana peels and isn't fun for the victim.

**Comment by Ultimate-Chimera** [comment]
I find this funny to take revenge on the clown, but it does get abused.

**Comment by Earthdivine** [comment]
This isn't a bug and has been around for a VERY long time, it's only now getting abused because no one is bothering to help anyone anymore. The victim can easily call over their headset as this does not stop that from happening and security should really be handling a clown or anyone else doing this. 

Fixing this feature can potentially break other useful things like pulling two people at once to medbay. Banana pulling isn't really all that bad, but the fact people are becoming self centered is allowing this kind of abuse to go without interruption.

**Comment by Fox-McCloud** [comment]
yeah; this isn't a bug--it's a semi-exploit, but not a bug.

**Comment by Spacemanspark** [comment]
It's pretty funny, let's keep it.
