### ISSUE TITLE
Terror Spiders damage from Atmospheric doesn't scale with heat/cold level

### ISSUE THREAD

**Issue by ktoma36** [ParadiseSS13/Paradise#7727]
**Problem Description**:
What is the problem?
Terror spiders seem to be fully immune to the affects of fire and heat

**What did you expect to happen**: 
The big scary spiders would scream as they burned to death from a plasma inferno
**What happened instead**:
They ignored the fire and proceeded to beat us to death
**Why is this bad/What are the consequences:**
Terror spiders are already hard enough to deal with, immunity to heat and cold makes them almost unstoppable once they build numbers. Right now it seems they only take damage from pressure and even then the damage is negligible.

**Steps to reproduce the problem**:
Set up a plasma tank (Preferably heated) in a room with a terror spider. Let the plasma out and set it ablaze. Watch as the spider laughs in your face, only taking damage from the slightly increased pressure as the room heats up. Alternatively use a flame thrower and dowse a spider in flames. Same effect.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Had nearly roundstart terror spiders. After getting approval I set up distro to pump plasma through all the vents. Me and another atmos tech were heading towards sec from engineering with flamethrowers. None of the spiders died to our fire (Over 400 degrees Celsius) and the proceeding massive fire from the plasma canister I opened up (that was around 500 degrees Celsius heated plasma being released). The spiders that specifically ignored the fire were the purple, red, white, and a grey (Those are the ones who swarmed us). 
![fire damage](https://user-images.githubusercontent.com/10539415/27899431-2cb3314c-61f8-11e7-95db-b04705724d7a.png)

**Comment by Anticept** [comment]
@Kyep weren't you going to fix this?

**Comment by taukausanake** [comment]
Only if we can get flaming terror spiders, I hate these things just enough to want to see a flavor of many kinds

**Comment by Citinited** [comment]
...Did you actually test this at all?

Terror spiders *do* take damage from high temperature, albeit slowly.

**Comment by ktoma36** [comment]
It seemed negligible, I witnessed none of the spiders dying to the inferno. When I asked around no spider in deadchat said they died to the fires. If they do take damage it doesnt seem to be based off of how hot the fire is and only if a fire is present. It needs more testing yes, thats why I posted this issue

**Comment by ktoma36** [comment]
Given that most of the bigger spiders have a large health pool that damage is quite laughable. Considering that they can regain all lost health from feeding on a dead body makes it even more so

**Comment by Citinited** [comment]
In that case you should consider making a feature request on the forums regarding it

**Comment by Kyep** [comment]
Last I tested this, they can die from heat. Or oxyloss. Or cold.0

That said:
- It takes a little time for their internal temperature to rise to the point it starts hurting them.
- When it does start hurting them, the initial damage will be counteracted by their regeneration... unless of course they've used that up, or they stay in it for some time.
- Once they're at the point that they're hot and have no regen points, they'll start losing health at a fair speed.
- This will continue until they exit the hot area *and* cool down enough / accumulate enough regen points. In the times I've tested this, I actually died as a TS well after leaving the area - because my internal temperature was still too high, and it took a surprisingly long time to cool down. During that time, I died.
- There are some exceptions to this general rule, such as spiders with slow/fast regen who take damage sooner/later and/or faster/slower, or spiders who are simply immune to atmos (queen).
- The shift-click description text given when you examine a spider isn't precise. It doesn't give a % health. Health readouts from examining a spider, even as a ghost, are grouped into big percentage bands. So if you are using it to try to estimate when a spider takes damage.... this will be hard.

In general, though, they *do* take atmos damage, and they *can* die from it, but you won't notice them taking damage right away.  

More generally, the damage from bad atmos (too hot, too cold, no air, etc) is *not* intended to kill TS quickly. It is only intended to provide them a reason not to camp areas (like space). That is all. If it is failing to do that, then I may adjust it. Still, that's a feature addition, not an issue/bug.

**Comment by ktoma36** [comment]
I agree, fire and explosives usually do end up doing more damage to the crew than anything. I just think the thresholds are a little high given that with heaters alone you can only heat up to 593 degrees Celsius. If people try and cook the vents it would take nearly half the shift just to get it to a damaging level (Not to mention the atmos tinkering it would take to reroute distro into a row of heaters). Same can be said for the opposite of trying to cool the pipes.

**Comment by ktoma36** [comment]
Given that effectively cooling/heating rooms to the levels necessary to reach the damage thresholds for terror spiders would take a great deal of time using safe methods, fire and breaches are the only effective method of area denial.

**Comment by ktoma36** [comment]
I would like to amend my earlier statement, I have found a simple way to cook the pipes safely using the turbine. Worked well stopping both xenomorphs and spiders from getting around in the pipes. Just takes a bit more ingenuity.

**Comment by Anticept** [comment]
Be very very careful about doing this. It's fine for the scrubbers but any atmos preaches will cause distro to dump hot air into the are and deny crew from getting in too. That's why I've never done this as CE.

**Comment by ktoma36** [comment]
I usually set up a valve that controls whether or not distro gets cooked. I kinda realized that alongside funky atmos things for breaches (Usually the air alarm and the general coldness caused by the vacuum can cool the room to livable levels after about 5-10 min, or a blast of nano-frost works too) cooking the pipes shuts down a lot of random events for ghost. Borers, morphs, vent crawling pets, xenos, spiders (dont need to always destroy them), and poor traitors that try using contortionist jumpsuits.
