### ISSUE TITLE
AI runtime when trying to get powers from DNA vault

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#7795]
AI runtimes when trying to get powers from DNA vault.

So said twinmold during our shift.

Don't think anymore need be said.

**Comment by Sirryan2002** [comment]
Confirmed still an issue with synthetics in general
```
[2022-06-25T15:17:50] Runtime in dna_vault.dm,300: Cannot read null.species
   usr: M.O.V.E. (**CKEY**) (/mob/living/silicon/robot)
   usr.loc: The floor (198,124,2) (/turf/simulated/floor/plasteel)
```
Issue is on [ L300 of dna_vault.dm], (https://github.com/ParadiseSS13/Paradise/blob/308814c0d9903bb0213c6e1462ee2363f201178a/code/modules/station_goals/dna_vault.dm#L300) since synthetics aren't human and don't have DNA, this runtimes because it's trying to access a non-existent variable on synthetics

```dm
/obj/machinery/dna_vault/proc/upgrade(mob/living/carbon/human/H, upgrade_type)
	if(!(upgrade_type in power_lottery[H]))
		return
	if(!completed)
		return
	var/datum/species/S = H.dna.species    <-------------
	if(HAS_TRAIT(H, TRAIT_GENELESS))
		to_chat(H, "<span class='warning'>Error, no DNA detected.</span>")
		return
```
