### ISSUE TITLE
Smite 'assasination' role offers are given to everyone regardless of account age

### ISSUE THREAD

**Issue by SamHPurp** [ParadiseSS13/Paradise#7925]
10 minute old tunnel clown just got sent in.

Went as well as could be expected.

**Comment by Kyep** [comment]
I'm not sure this is really a problem, or, if it is, the best way to solve it.

Sure, 10-minute-old tunnel clowns are going to be inept... but they don't have to be particularly competent to play a hunter. The role is literally 'follow the flashing pointer to your target, then kill them'. Anyone who has played for more than a few minutes can take a stab at this. If they attempt, and get killed, they'll be dusted automatically by their implant, so their gear is generally safe. Admins can then simply send a replacement. Or they could spawn multiple hunters for the same target. Hunters are not a round-defining antag role, so it doesn't really matter how competent or otherwise they are.

It would be nice, though, if the hunter options in bless/smite asked the admin if they wanted to set a playtime requirement for the role. That way they would have the option of allowing new players in, or not. I may add that.

**Comment by SamHPurp** [comment]
Putting a minimum on it like we do Tot though makes sense to me.

**Comment by Kyep** [comment]
Does it, though?
Tots are antags that define the round. They have many, many options, with varied objectives, powerful and versatile gear, etc.
Hunters don't define the round. They have very few options. They have only one objective, and a pointer straight to it. Their gear tends to be single-purpose and destroyed on death. They're a far more specialized, niche role. They're actually a lot simpler to play than Traitors are, and Traitors only require about 5 hours of playtime as is.
If I put a lower playtime requirement on Hunter than on Traitor, it would be 1-4 hours, and I'm not sure how much of a difference 0 to 4 hours makes in the game, especially when it isn't 0-4 hours playing SS13, it is 0-4 hours playing Paradise, which means they probably have dozens of hours on other servers, which means its really something like, say, 20 v 24 hours.... which I'm not sure is a significant gap.

I am still tempted to let admins specify a playtime requirement for them. I am just not convinced that we should add one *because* Traitors have one. I don't think the comparison to Traitors is a strong argument here.

**Comment by SamHPurp** [comment]
@Kyep The dude ran around with no idea what he was doing until the point where the admins gave up (10 mins) and offered the role up to ghosts.

**Comment by tigercat2000** [comment]
This should follow the same age limit and, more importantly, jobban status as any other Syndicate role.
