### ISSUE TITLE
Unable to store items into the Crates/RCS unable to interact with Crates.

### ISSUE THREAD

**Issue by GutTC** [ParadiseSS13/Paradise#7960]
**Problem Description**:
Apparently you cannot manually store items in the crate with hands or use the _RCS_ on them.
However, you can still open/close/pulling it normally.

**What did you expect to happen**: 
Just what everyone would do with the crates in general, you store items into them and Cargo Tech would use RCS to send them back to Cargonia.

**What happened instead**:
It's impossible to store the items into the Crates manually by picking up items in your hands and try to store them into the Crates. **But it is still possible to store items by pulling the Crate on the same tile where the items are and close the crate.**

**Why is this bad/What are the consequences:**
Not a big deal but one simply annoyance to the player who wishes to use the Crate to transport something or especially Cargo Tech for not being able to use RCS.

**Steps to reproduce the problem**:
None, the problem are the Crates themselves.

**Comment by FalseIncarnate** [comment]
Please provide more information, simply saying the issue is the crates doesn't give us much to work on.

What were you trying to put in a crate, where was the crate, what was the RCS charge at, did you get any sort of messages, etc. While this may seem like unimportant info, it can be the difference between being able to isolate / resolve an issue and not being able to reproduce it.

**Comment by KasparoVy** [comment]
RCS gives no messages. RCS works on closets but not cargonia crates. The crates can be full or empty, open or closed. No messages.
