### ISSUE TITLE
Shadowlings being flashbanged while in shadow walk

### ISSUE THREAD

**Issue by Balthusdire** [ParadiseSS13/Paradise#8005]
**Problem Description**:
Shadowlings being hit by flashbangs while shadow walking.

**What did you expect to happen**: 
To pass by a flashbang harmlessly because you are not corporeal and are not affected by things.

**What happened instead**:
The flashbang detonated while I was in shadow walk stunning and serverely injuring me.

**Why is this bad/What are the consequences:**
I was immediately killed because I could not escape.

**Steps to reproduce the problem**:
Throw a flashbang, shadow walk and stand on it, it detonates and you get stunned.

**Comment by DesolateG** [comment]
I mean, you're one with the darkness, and a bright flash removes said darkness for a brief moment...

Logic seems fine to me

**Comment by FlattestGuitar** [comment]
Well, you're not blind while being ethreal. You still...see things.

Logically, it makes sense for you to be affected by sights and sounds while jaunting.

**Comment by Birdtalon** [comment]
What doesn't make sense is when it happens though a wall.

**Comment by Balthusdire** [comment]
I would argue it is not logical at all to be affected in this way. The whole point of jaunting is that you are able to observe the world while being unaffected by it. A flashbang is very much being affected. If we are supposed to be affected by sights and sounds while jaunting then that means light should burn you, lasers should hit you, and you should be able to hear everyone's conversations around you.

**Comment by Ralta** [comment]
I was initially in agreement with Desolate and Flattest, but you're not wrong; if Flashbangs affect you, then so should other lights. This should probably be addressed.

**Comment by The-Driker** [comment]
Unless I am remembering incorrectly, Shadowlings can use powers and abilities while shadow-walking/jaunting. If they are capable of interacting with the world while in this state, that would suggest they aren't actually outside reality, so it makes sense for a flash bang, a thing that removes the darkness you are moving through, to affect you. 

I've heard people complain about them using icy veins on people while shadow walking. If this is not intentional, then I suppose a couple things do indeed need fixed.

**Comment by Balthusdire** [comment]
That seems bad as well. Shadowlings should be disconnected while shadow walking, so they cant be stunned, but they cant hurt others as well.
