### ISSUE TITLE
Terror spider eggs from Gateway spiders gib you as well as release spiderlings

### ISSUE THREAD

**Issue by ktoma36** [ParadiseSS13/Paradise#8059]
**Problem Description**:
What is the problem?
^
**What did you expect to happen**: 
To have the terrifying description of spiders ripping out of my skin to happen
**What happened instead**:
Gibbed in under two minutes
**Why is this bad/What are the consequences:**
This is not how its supposed to work
**Steps to reproduce the problem**:
Get munched on by white terror spider, wait for gib
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Was a cargo tech exploring the terror spider gateway. I was a vox.

**Comment by warior4356** [comment]
Working as intended I think. If you get infected on the gateway and try to bring them back you just gib instead.

**Comment by ktoma36** [comment]
Mmm.. then why did spiders still pop out?

**Comment by ktoma36** [comment]
And it doesnt explain why it was coded like that in the first place with no PR

**Comment by alexkar598** [comment]
We don't have any stealth commit on this code base at least I think...there must have been a pr and I think it's the one who prevented you from bringing spiders to the station from gateway

**Comment by ktoma36** [comment]
Soooooo it gibs you to stop the spiders but spiders still come out? Something is weird here O.O

**Comment by warior4356** [comment]
The Gibbing is a punishment for trying to bring spiders back, because it's assumed you are trying to grief. The spiders it makes are stillborn and die immediately after you do.

**Comment by ktoma36** [comment]
They didnt... spiderlings came out. Also there are no surgery tools on the mission, what do they expect you to do? Lay down and die?

**Comment by Kyep** [comment]
If:
- You go into the gateway
- AND the gateway is terror spider
- AND you get bitten by the white terror in the gateway
- AND you return to the station
- AND you don't get the eggs extracted before they hatch

Then, yes, you will get gibbed. And it will spawn spiderlings, BUT none of those spiderlings will grow up into spiders.

This is an intentional catch in the code, designed to punish people who try to bring spider infections to the station by deliberately getting infected, returning to the station, and letting the eggs hatch.

If you get infected in the gateway and stay there, it will crit you and spawn spiderlings that do grow up.

If you get infected by a white terror from the Cyberiad, it'll again proceed normally.

This gibbing behavior only triggers when you, intentionally or not, try to bring a terror spider infection FROM the gateway TO the main station.

**Comment by ktoma36** [comment]
Then why not give a little notification or something to inform the person that they are making a horrible decision and turn back?

**Comment by Kyep** [comment]
If we want to be kind and gentle to people who attempt this, the ideal solution would be to simply make them unable to enter the gateway if they have eggs in them. Just like an exile implant. 

But, the question is: do we want to be gentle with people who try to return from gateway carrying an infestation that could destroy the station? I'm really not sure. Actions should have consequences, and if you're dumb, self-centered or malicious enough to put the whole station at risk to save your own hide...

**Comment by ktoma36** [comment]
Perhaps at least having the surgical tools necessary to remove the eggs in the medical room inside the gateway would work. I otherwise you are giving the person the option of seeking medical attention (and risking gibbing for contrived reasons) or dying in the gateway. The white terror spider can infest someone in one hit if they are unlucky, giving them four minutes to get the things out or suffer massive toxin damage as well as a massive stun. 

@Kyep At least make it known to the general populous that they will be *gibbed* if they leave. I asked around on discord as well as in OOC, nearly everyone I asked had no idea about the player being gibbed (from the specific circumstance with gateway terror spiders). Punishing people who dont know better for the deeds of a malicious few (Yes I have heard the multiple stories about different ways people started terror spider infestations using that gateway mission) is wrong. And when people are panicking they make hasty decisions, self preservation kicks in and the only way you can survive is to make a dash for medical. Who sits there and thinks *oh well just going to kick back and let spiders rip out of my flesh and kill me*? Actions should have consequences yes but being punished with gibbing by getting hit *once* by a white terror spider is just ridiculous, IC and gameplay wise.

**Comment by tigercat2000** [comment]
The spiderlings still hatch when you gib, but they're made as stillborn. When their grow chance is finally triggered, they'll just die on the spot instead of becoming fully fledged terror spiders.

While I agree that the gibbing is rather harsh against any players that don't mean any harm, that is a conversation best left for the suggestions forum as to how to improve the away mission.

**Comment by ktoma36** [comment]
Fair enough

**Comment by adamkad1** [comment]
but what is someone hauls a terror out of gateway?
