### ISSUE TITLE
Vampire Glare without Eyes

### ISSUE THREAD

**Issue by Ralta** [ParadiseSS13/Paradise#8074]
**Problem Description**:
Vampires can use glare after their eyes have been surgically removed.

**What did you expect to happen**: 
Because glare requires eyes. They have no eyes. But they can still glare. But they have no eyes. But...

**What happened instead**:
...they can still glare.

**Why is this bad/What are the consequences:**
My revenge plan was ineffective. And the consequences were both embarrassing and hilarious.

**Steps to reproduce the problem**:
Use surgery (organ manipulation) to remove the eyes of a vampire.
Cry as you're dropped the ground after being glared by the eyeless vampire.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Vampire round. Didn't test with any other abilities, unfortunately.

**Comment by taukausanake** [comment]
Working as Intended:tm:. Have you ever seen an eyeless person? I wouldn't.
Yeah, half serious about the above but it might be a problem. A fix though will need to check for eyes that the mob is missing and for mobs that don't physically have eyes (or most organs for that matter).

I wonder if Glare works if you are blinded or otherwise have vision protection? If you can't see or people can't see your eyes should you still be able to glare?

**Comment by Ralta** [comment]
Reason I figured it shouldn't work is 'cause you can blindfold a vamp and glare won't work. So the eyes are clearly an important factor :P

As for eye protection, I would assume that most would be fine but maybe things which protect identity (such as welding mask and gask mask) would prevent eye contact? Not too sure about being blind.

**Comment by tigercat2000** [comment]
Not really a bug. This would just be adding behavior.

**Comment by SamHPurp** [comment]
I'd support someone adding this behaviour though.

**Comment by tigercat2000** [comment]
Sure, I would too- but it belongs on the suggestions forum.

**Comment by SamHPurp** [comment]
@tigercat2000 Yep, I just felt like I should encourage them/someone to make such a change. Its a good point. :)
