### ISSUE TITLE
Greys are harmed by inactive showers

### ISSUE THREAD

**Issue by StreakyHaddock** [ParadiseSS13/Paradise#8082]
**Problem Description**:
Showers harm Greys even when they're turned off.

**What did you expect to happen**: 
This is a bug because water harms greys. Not the things that produce water.

**What happened instead**:
I expect to be harmed for walking under a shower pouring out water. Not one that isn't producing any water at all.

**Why is this bad/What are the consequences:**
Walking under an apparently harmless shower can reduce a limb to red damage, and even kill a grey who's badly hurt.

**Steps to reproduce the problem**:
Be a Grey. Walk under a shower that isn't on.

**Comment by Ralta** [comment]
That is hilarious.

**Comment by Citinited** [comment]
I found the offending code - if anyone wants to fix it then it's here https://github.com/ParadiseSS13/Paradise/blob/6e9d89204a7fa4ff622e8c1591634a1e7391772c/code/game/objects/structures/watercloset.dm#L359

For some reason there's a proc `check_heat` that applies water to the mob regardless of if the shower is on. Because reasons?

**Comment by SamHPurp** [comment]
That goddamn proc. It used to set off Plasmaman auto-extinquishes too.

**Comment by Birdtalon** [comment]
It's too funny to fix.

**Comment by StreakyHaddock** [comment]
it's not though

**Comment by Birdtalon** [comment]
It kinda' is funny. It put me into crit within a few seconds!
