### ISSUE TITLE
Clicking "follow" as a ghost on the labour camp beepsky teleports you to botany bees.

### ISSUE THREAD

**Issue by fj45** [ParadiseSS13/Paradise#825]
See above. I have no idea.

**Comment by CrAzYPiLoT-SS13** [comment]
Maybe it's var is set to beesky? Maybe it reads that as just bees and
follows them? I don't have a clue.

**Comment by Krausus** [comment]
Following bees was simply a coincidence. Bots use a weird workaround to talk over the radio; instead of the bot itself broadcasting, a separate mob is created, performs the broadcast, and then is deleted. The follow link is for this temporary mob, but since it gets deleted instantly, the follow link references a mob that doesn't exist... unless a new mob gets created, in which case it will end up with the (now unused) ID that the temporary mob had. In this case, bees spawned after the radio message went out, so they ended up with the ID used in the follow link.

I'm not actually sure what it would take to fix this, though. Might need to tweak something somewhere in the say code.

**Comment by fj45** [comment]
Oh, that is VERY interesting!

**Comment by CrAzYPiLoT-SS13** [comment]
Hm, why would they code it like that? From what you said it can be easily
fixed. Remove the mob, make beepsky announce. Simple as that.

**Comment by Krausus** [comment]
I don't know the specifics of how the say code works, but if I had to guess, it's probably written such that only mobs can broadcast over the radio. Bots are technically machinery, which would preclude them from broadcasting. It may very well be simpler to just add a way to specify an arbitrary follow target for ghosts (and maybe the AI, if this affects them too).

**Comment by CrAzYPiLoT-SS13** [comment]
Maybe make it spawn and move with the bot, and leave it's ID on it?

**Comment by Fox-McCloud** [comment]
This would require another saycode overhaul for this to not really be a thing; TG allows for anything to effectively talk/use a radio---Baycode, AFAIK, does not.

**Comment by veganzombeh** [comment]
A potential solution is to make the temporary mob permanent and inside beepsky, although I'm not sure how feasible that is.

**Comment by CrAzYPiLoT-SS13** [comment]
It is completely possible. While tinkering with the camera I found
something called a 'visibility test dummy' which lived in the camera.
Although I'm not sure what it is exactly used for, it will help our case.

**Comment by clusterfack** [comment]
Change the way your href links work then so it is sending beepsky as the argument to follow instead of the virtual speaker
