### ISSUE TITLE
Virology bug

### ISSUE THREAD

**Issue by Kalrirr** [ParadiseSS13/Paradise#8326]
**Problem Description**:
Having ocular restoration and Sensory restoration as symptoms in a virus causes mannitol and
antihol to not be produced by the body, thus nullifying Sensory restoration.

**What did you expect to happen**: 
There is no logical reason for the chemicals to not be produced in the body.

**What happened instead**:
Expected to see mannitol, antihol and occuline in blood, only occuline is produced.

**Why is this bad/What are the consequences:**
It nullifies the Sensory Restoration symptom.

**Steps to reproduce the problem**:
Create a virus with ocular restoration and sensory restoration, inject it and check the chemicals produced by the body.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
No additional comments

**Comment by farie82** [comment]
This is due to how sensory restoration and ocular restoration works. Both create chemicals and check for their amounts in the body before doing so. Sensory checks if any chemical is over X amount of units. If so it won't create the chemicals. Thus if ocular rest is called first it'll go over X units. Nullifying sensory restoration.
