### ISSUE TITLE
Spacepods have a habit of shooting themselves

### ISSUE THREAD

**Issue by RatElemental** [ParadiseSS13/Paradise#8341]
**Problem Description**:
If you keep moving forward while firing a spacepod, or the server decides to be particularly laggy for a moment (if, say, mining decided to dump a million ores into the ORM all at once), then you stand a pretty good chance of shooting your own pod with its own weapons.

**What did you expect to happen**: 
Should not be possible for your front mounted weapons to be able to shoot yourself in the back.

**What happened instead**:
Able to shoot self in the back.

**Why is this bad/What are the consequences:**
A single volley from a basic mining laser, the weakest (to my knowledge) weapon a pod can have, puts a civilian pod in critical condition. two shots is enough to cause a meltdown and gib the pilot. Does the mechanic not get a bad enough rap already without their pods having a tendency to kill the user?

**Steps to reproduce the problem**:
Mount weapon on pod, continue flying while firing pod, you will eventually hit yourself. Especially if you add in some lag.

**Comment by taukausanake** [comment]
I remember this being an issue at one point a long time ago. Only reference I can find for it is #3575 but that may be incorrect. Anyone else remember this issue before?

**Comment by sampaiii** [comment]
I've actually exploded a pod while mining with it because of this before, granted it was a long time ago...

**Comment by Ar3nn** [comment]
I've seen this reported before every other time people said it was unfixable.

**Comment by Twinmold93** [comment]
There may be a way to fix it, but it would be very difficult. Part of the issue is the beams 'should' appear a tile in front of the pod (if there is nothing there, that is). Since you can move forward at the same time, you can actually move onto the beams, therefore getting hit. The only way I could see making it so this doesn't happen is to temporarily (half a second) disable pod movement. I will have to look at this in the near future and converse with some other people on it.
