### ISSUE TITLE
Surgery infections rarer than they should be

### ISSUE THREAD

**Issue by Ralta** [ParadiseSS13/Paradise#8538]
**Problem Description**:
Performing surgery in dirty rooms using unhygienic practices is supposed to cause infections in patients. I am certain this used to happen regularly and as expected, but it now seems to happen _very_ rarely, if at all. Original PR that merged these changes was #6896

**What did you expect to happen**: 
Performing surgery in a blood-filled room without gloves or mask would cause infections in the patient.

**What happened instead**:
Multiple types of surgery performed in various situations with/without gloves, with/without mask, clean/unclean floor, patient experienced no infections.

**Why is this bad/What are the consequences:**
Spaceacillin is useless, OR's no longer need to be kept clean, Surgeons require a job title change to Butcher.

**Steps to reproduce the problem**:
1. Have patient requiring surgery.
2. Smoke cigar, wear fingerless gloves.
3. Scratch butt. Sniff if you feel so inclined.
4. Perform surgery. Cough incessantly.
5. Close up patient. Send them on their merry way, infection-free.
6. (optional) Scratch n sniff again.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
This has happened to me numerous times in both medbay and brigbay. I have yet to attempt ghetto surgery and test for infections, but presumably the results are the same. Having mentioned it on Discord, other medbay-regulars indicated they had noticed it as well.
I believe this has not been working for quite a while, but wasn't sure if it was just luck or something else. At this point, i feel like there must be a bug _somewhere._

**Comment by taukausanake** [comment]
That's weird. We still have #7868 open that argues the opposite. Which is it?

**Comment by Ralta** [comment]
That PR is older than this issue and no longer relevant in my opinion. 

I noticed this issue a couple of months ago (around October/November maybe), and it has persisted ever since.

**Comment by taukausanake** [comment]
I'm willing to bet infections got nerfed to hell or something. Maybe on accident. I wonder if there's a PR about that somewhere

**Comment by Ralta** [comment]
Welp, apparently #7743 is a thing and it probably borked the surgery PR. Sad times.

**Comment by Miraviel** [comment]
I wish to see this fixed/reworked. I see doctors vomitting next to surgery tables because they forgot to wear a mask but who needs it when you can operate without gloves as well?

Removing the chance to infect bleeding patients while dragging them across a blood-filled Medbay just encourages the doctors really not giving a damn about hygiene of the place. With the introduction of pain to surgery, Medbay _did_ start to resemble a medical department but it briefly ended there. As @Ralta said, medicals are just butchers with fancier tools now. I wish to see infections again.

@Fox-McCloud What are your thoughts on it? Since you were the one handling infections back in summer.
