### ISSUE TITLE
Issues with chem smoke

### ISSUE THREAD

**Issue by Squirgenheimer** [ParadiseSS13/Paradise#8636]
Credit to EldritchSigma for discovering the issue, I just ran a bunch of tests
**Problem Description**:
When using beakers and chem dispensers, one can create a smoke reaction using phosphorous potassium and sugar. Adding in an additional reagent, for example sulfur, creates a smoke that transfers these additional reagents to the user. The colors also mix. Seems completely reliable.

Example with sulfur smoke: 
https://www.dropbox.com/s/y2juksgsv1af27a/2018-02-02_05-34-29.webm?dl=0

However, when deploying smoke with a grenade, occasionally the reagents do not transfer to humans properly.

- Sulfur smoke grenade:
https://www.dropbox.com/s/ay0hb6l8m61lm7u/2018-02-02_05-40-58.webm?dl=0

- Phlog Black powder smoke grenade in large casing: 
https://www.dropbox.com/s/5rtfn5ub2qher7x/2018-02-02_05-49-40.webm?dl=0

- Phlog Black powder smoke grenade in pyro casing (black powder seems to only have been transferred to 1-2 mobs, maybe a fluke and not related to the bug):
https://www.dropbox.com/s/ldny4j25dh7uju0/2018-02-02_05-53-34.webm?dl=0

- Same recipe as above in another pyro casing, total destruction that was expected:
https://www.dropbox.com/s/6w8vwvpzvnofw5u/2018-02-02_06-05-13.webm?dl=0

- Same as above except the black powder is removed, phlogiston not transferred:
https://www.dropbox.com/s/18dn6kdluvtirzt/2018-02-02_06-08-47.webm?dl=0

- Again phlogiston removed but all in one beaker
https://www.dropbox.com/s/i31j9xl5dbfqezo/2018-02-02_07-17-58.webm?dl=0

- This time the whole recipe in one beaker with reduced amounts:
https://www.dropbox.com/s/cso50g0s9dwg7y7/2018-02-02_07-03-12.webm?dl=0
Black powder explodes before smoke reaction goes off (not entirely unexpected)
Phlog isn't transferred, maybe because the grenade reagents are destroyed? But a smoke reaction does still go off.

- Chlorine phlogiston smoke, nothing transferred
https://www.dropbox.com/s/2hlhpadydsw0shf/2018-02-02_07-40-57.webm?dl=0

- Bunch of random reagents, nothing transferred
https://www.dropbox.com/s/pvo8elakvo9hu6j/2018-02-02_07-47-08.webm?dl=0

- Bunch of random reagents again but different ones, not entirely sure what I did as there
was a turf reaction (and radium goo left behind) nothing transferred:
https://www.dropbox.com/s/vav3gzx5pr6maos/2018-02-02_07-56-07.webm?dl=0

- Fluoro and smoke, nothing transferred but grenade melts
https://www.dropbox.com/s/4hgumpdk8rkekaf/2018-02-02_07-51-17.webm?dl=0

Clearly there is some inconsistency here, I believe it may have something to do with the effect system refactor #8331 but I'm not sure at all.
This is all on one server session. On an earlier session I was able to successfully use fluorosulfuric acid grenades with the large casing against mobs which produced the correct on touch effect, but I was having similar transferring problems with other reagents.

Side Note: sometimes smoke powder was used instead of potassium phosphorous sugar in the grenade

**Comment by EldritchSigma** [comment]
Looking into your tests I know exactly whats happening in most cases: The grenades content gets spilled on activating before the smoke is formed. It used to be that reagents are being formed and then spilled not vise versa. I am fairly sure this explains why foam is still working like it used to and smoke is currently more or less defunct. I took a break from Para mid october. Smoke was working like it should. 
I come back I see smoke isnt working anymore. Checking for any balance PRs changing mechanics... nothing. Only a PR that massivly changes the behavior of smoke but which was not supposed to change its ability to carry reagents. 

Observations so far:
Smoke from grenades doesnt contain ANY reagents. This is now proven by multiple players. 
Smoke does formation is delayed on grenade detonation. The contents are spilled before activation.

So why is this change bad:

Sarin gas SMOKE doesnt work. Its the spill that goes through the skin. The Sarin itself goes through the skin. The smoke does nothing at all.

Teargas, while still being utterly underpowered when function, does nothing at all.

Any and all smoke grenades, be it for antags or eccentric chemists making synthflesh smoke are completly defunct, further limiting creativity and antag freedom. There are tons of mixes that are none hull damaging but those cannot be used either. Its not just "Gibsmoke" that is affected by it. It was noticed that Gibsmoke didnt work however and people tested to see if some kind of "stealth nerf" was employed (Hey, dont look at me like that I get suspicious at stuff after certain syringe gun nerfs instead of nerfing the reagents)... which it wasnt because it is smoke itself being either ompletly defunct or most of the time utterly inconsistent.

**Comment by DesolateG** [comment]
@uraniummeltdown
