### ISSUE TITLE
Russian Roulette vs IPC 

### ISSUE THREAD

**Issue by SnaxMang** [ParadiseSS13/Paradise#8699]
**Problem Description**:
I was playing as an ipc this round. 
So the round had just started and I went to the bar. I was challenged to Russian Roulette and I accepted and bit the first bullet. I targeted my mouth and clicked myself as usuall. But when the bullet fired, by screen went compleatly black instead of "blind".  
Normally as an ipc, if your head is blown off in this way, you can talk, hear, walk, and just carry your head back to robotics for repairs. 
However this time my screen was nothing but pitch black, even my hud was gone. The game said I was unable to speak due to my speaker being turned off. This is usually a sign of being gibbed as an ipc and being reduced to a posibrain. This was not the case as posibrains can see and hear the world around them. After waiting for some time I decided to ghost myself and see what had happened. When I went to my death site, there was no brain, just a micro battery, my headset, and my right arm and hand. 
I asked some of the on-site admins and mentors if this was an update to the roulette gun and they were all stumped as well and directed me to report this issue here. Hope this helps!

Admin spoken to: Pazneria12,

**Comment by dapocalypse** [comment]
Honestly if you lose russian roulette you should die. Being able to be revived removes the risk.

**Comment by Eddyskingdom** [comment]
wait you have no body only parts?

**Comment by SnaxMang** [comment]
Yep. No body to be revived. It was like it fibbed me.

**Comment by taukausanake** [comment]
I think I want a Russian revolver that now does that. It totally destroys/gibs your body and drops your brain but leaves your arm that was holding the gun left. That would be a way to go

**Comment by SnaxMang** [comment]
It didn't drop my brain. It was totally erased.

**Comment by taukausanake** [comment]
I know but I _totally_ want one that does work like I said

**Comment by alexkar598** [comment]
did a bit of testing,this is caused by the posibrain being litterally nowhere.For some reason the posibrain is in what is called null space.Screen shot of VVing the posibrain,brain mob and the player screen:
![image](https://user-images.githubusercontent.com/25136265/36811620-685edb38-1c9c-11e8-8a87-eb1f64dd9bf0.png)

**Comment by Citinited** [comment]
Well I prodded this for a few hours, and I found that the following proc is called when russian roulette happens, and it causes the issue: https://github.com/ParadiseSS13/Paradise/blob/571f86c7f0787991fbc8511af81579c54284b7a9/code/modules/surgery/organs/organ_external.dm#L526

This proc is probably not to blame (but could probably do with rewriting so that it doesn't default to the chest), but it did in turn lead me to this proc: https://github.com/ParadiseSS13/Paradise/blob/c1c4b08807c0eb23e7e2c89ed50310f4c7551f88/code/modules/surgery/organs/organ.dm#L296

I think this proc is the culprit. If you call it on a posibrain, it sends your posibrain to nullspace. However, if you call it on an actual human brain, then you do not. This proc is probably causing this issue, so the question is: why?
