### ISSUE TITLE
door copying with the RCD

### ISSUE THREAD

**Issue by Eddyskingdom** [ParadiseSS13/Paradise#8700]
**Problem Description**: wen a door gets constucted with the RCD and then try to deconstruct by hand it wont work and then deconstruct with the RCD it will spawn in more doors
What is the problem?

**What did you expect to happen**: i expected that the door will just deconstruct 
Why do you think this is a bug?

**What happened instead**: instead about 20 doors spawn becouse i tryd to remove the circuit about 20 times
How is what happened different from what you expected?

**Why is this bad/What are the consequences:** dis is bad becouse if you try to remove the door by hand it wont work and plus it will spawn more door and you can do metal farming with dis bug
Why do you think this is an important issue?

**Steps to reproduce the problem**:now i build a door with the RCD on accident then i tryd to remove the ciruits but it diden work so i tryd a 20 times more till i sayd to my self to use the RCD insted but then it spawn the 20 doors in
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us. i was doing dis in armoury sort of in space

**Comment by tigercat2000** [comment]
@uraniummeltdown

**Comment by uraniummeltdown** [comment]
could not reproduce

**Comment by Eddyskingdom** [comment]
sell i send a screenshot of dis so you can see it for your self

**Comment by alexkar598** [comment]
Are you sure you did not click the door 20 times with the rcd?

**Comment by uraniummeltdown** [comment]
Reproduced it: Build an airlock with RCD, try to deconstruct that airlock manually with tools
Runtime in airlock.dm,1279: Cannot read null.len
   proc name: deconstruct (/obj/machinery/door/airlock/deconstruct)
   usr: Henderson Hincken (Guest) (/mob/living/carbon/human)
   usr.loc: The floor (55,143,1) (/turf/simulated/floor/plasteel)
   src: Airlock (/obj/machinery/door/airlock)
   src.loc: the floor (54,143,1) (/turf/simulated/floor/plasteel)

The problem is in how the RCD sets airlock accesses

**Comment by Eddyskingdom** [comment]
I'm a 100% sure that i only contructed one door
