### ISSUE TITLE
All portable oxygen tanks hold same maximum capacity.

### ISSUE THREAD

**Issue by notafed** [ParadiseSS13/Paradise#8729]
**Problem Description**:
All portable oxygen tanks have the same capacity.

**What did you expect to happen**: 
Have different max caps, as described.

**What happened instead**:
Extended capacity and large oxygen tanks hold the same maximum pressure as regular emergency oxygen tanks.

**Why is this bad/What are the consequences:**
Misleading, and imbalanced for large tanks.

**Steps to reproduce the problem**:
Fill each tank in the same canister at max pressure.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: N/A

**Comment by davidchan13** [comment]
This isn't a bug. You're reading KpA which is the density of the air in the canister, not how much air is in the canister.

The tank capacities are in moles, which is not a feature typically available to a person (unless you use an atmos PDA gas scanner or maybe an analyzer) 

Long and short [https://tgstation13.org/wiki/Guide_to_Atmospherics#Physical_Characteristics_of_Gases](click expand to see how many moles each object holds.)
The short version is an Emergency Oxygen Tank (standard blue one in your internals box) holds 3 moles, an Extended Emergency Oxygen Tank (engineering gets these instead of blue ones and spares can be found around the station) holds 6, a Double Emergency Oxygen Tank (Captain, ERT and other high level roles get these) holds 10 and an Oxygen Tank (the blue/red ones that you can get from tank storage, fire closets and maint in general) holds 70

Pressure isn't a good way to judge volume because it's like trying to judge how much water you have in a bucket by checking the temperature.

**Comment by notafed** [comment]
Wow, that's pretty smart actually.
