### ISSUE TITLE
Tape is invisible

### ISSUE THREAD

**Issue by Spartan6** [ParadiseSS13/Paradise#8951]
**Problem Description**:
Engineering and Police Tape is invisible and therefore impossible to remove without admin intervention

**What did you expect to happen**: 
You should be able to put police tape and engineering down in a line to block hallways and corridors, have it visible, and be able to remove it with harm intent.

**What happened instead**:
The tape is invisible when placed, meaning unless you have a sec/eng ID, you are unable to pass the tile without admin intervention.

**Why is this bad/What are the consequences:**
This could lead to cheeky chaps using the tape to block antags/security or general grief.

**Steps to reproduce the problem**:
Get security or engineering tape.
Click the tape to start placing it.
Move a few tiles.
Click the tape to stop placing it.
Tape is invisible but is still there; it is visible in right click and requires an admin to delete it.

**Comment by Kyep** [comment]
You can alt-click the title that its on, and click it in the list of things on that tile, destroying it and allowing you to pass. I've done this in order to bypass invisible tape in the hotel gateway mission.

HOWEVER that doesn't mean this isn't still a serious problem. Most players don't try the alt-click trick. From their POV... tape just manifests as an invisible wall. That's really bad. This should definitely be fixed. Just saying... there IS a way to bypass it if you're expecting it.

**Comment by KasparoVy** [comment]
Alt-click everything. Especially large stacks.

**Comment by Spartan6** [comment]
Okay so apparently recording tapes are bugged as well.
It acts like Police tape.

**Comment by FalseIncarnate** [comment]
This can probably be closed as the police and engineering tape have been replaced by holosign projectors.
