### ISSUE TITLE
New ATMOS holofan projectors do not update airflow when removed

### ISSUE THREAD

**Issue by DrewTuber** [ParadiseSS13/Paradise#9036]
The holoprojectors create a temporary wall that blocks atmos, but allows you to walk through it. However, when removed, they do not update the atmos system. An easy way to reproduce is to put an air pump in a corner, use two holograms to block it off, then turn it on to max to vacuum out the tile. Now turn off the pump and move it, and remove the holograms. What you are left with is a 1x1 vacuum that does not interact with the rest of the room.

**Comment by Fox-McCloud** [comment]
Great, this means that fans, inflatable barriers, and goodness knows what else, that is a single tile, atmos blocker, is broken too.

There's nothing special about the atmos hologram; this is atmos code issue.

**Comment by Fox-McCloud** [comment]
@DrewTuber lemme know if this also occurs with inflatable barriers.

I bet it does.

**Comment by Allfd** [comment]
If I had to guess, its not calling air_update_turf() properly on the location it is removed from.

**Comment by FalseIncarnate** [comment]
This also affects the inflatable barriers @Fox-McCloud as you suspected

**Comment by FalseIncarnate** [comment]
I took a quick peek at it in my bug fix PR I did recently, found both weren't working, and promptly nope'd out of tackling that one.

Someone bolder than I will have to delve that abyss.

**Comment by ID404-NotFound** [comment]
something I've noticed with messing around with atmos, is that making the flooring different on a tile, either adding flooring to plating, or removing it, will update the atmos properly, allowing either air to flow through a 'frozen' tile from removing a holofan, or in another situation caused by same problem, where a directional window placed over a breach can still act as if air is being sucked through it, and can knock you against the window until it breaks, unflooring/reflooring also fixes it to realize there is a window there.
