### ISSUE TITLE
Syndiborg Emag

### ISSUE THREAD

**Issue by Earthdivine** [ParadiseSS13/Paradise#907]
The Syndiborg's Emag is unable to emag the covers of other borgs, making the Flash>Emag>Crowbar>Emag combo they are meant to use nonexistant.

I do not quite know what the cause of this is, but they do not got the "You emag the cover" message when clicking a borg, while doing so while a organic will. Their Emag works on everything else though.

**Comment by veganzombeh** [comment]
The cause is [this](https://github.com/ParadiseSS13/Paradise/blob/e2a4ccc8a637c3d9c728c0546a74581ed23a755d/code/modules/mob/living/silicon/robot/robot.dm#L822) inhuman check that returns if the user is not human. I guess when this was coded emags weren't intended to be used by anything other than humans.

**Comment by tigercat2000** [comment]
@veganzombeh it was probably put there so monkeys couldn't use emags to make an army
