### ISSUE TITLE
Eating Deep Fried Foods Holder Obj.

### ISSUE THREAD

**Issue by IIWOLFII** [ParadiseSS13/Paradise#9097]
**Problem Description**:
After deep frying meatball made from synthetic meat, and poking it with fork and eating it, character will eat Deep Fried Foods Holder Obj, instead of deep fried meatball.

**What did you expect to happen**: 
I expected for my character to eat meatball, not placeholders meals.

**What happened instead**:
![unknown](https://user-images.githubusercontent.com/11389033/41036496-e6a7e3a6-6998-11e8-88d5-94e67d8e2cf3.png)

**Why is this bad/What are the consequences:**
Muh immersun

**Steps to reproduce the problem**:
1. Pick synthetic meat from dirty medbay's floor.
2. Break into kitchen.
3. Grind the synthetic meat slab into a meatball by using food processor.
4. Deep fry the meatball.
5. Scoop it with fork.
6. Eat fork.
7. Enjoy taste of Deep Fried Foods Holder Obj

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Prolly works with other deep fried food items as well idk, didn't test

**Comment by FalseIncarnate** [comment]
This will occur with any deep-fried food or (less noticeably) any renamed food item.

This is because [this code](https://github.com/ParadiseSS13/Paradise/blob/68b4815e768af31bd41d1aa59b822f7ef89dfdc9/code/modules/food_and_drinks/food/snacks.dm#L101-L104) makes a new snack object of the food's type, but doesn't carry over the name of the source, resulting in the default name of that snack being used instead (in this case the Deep Fried Foods Holder Obj name)

1-line fix, will handle tonight

**Comment by taukausanake** [comment]
@IIWOLFII 🍪

**Comment by Fox-McCloud** [comment]
Duplicate: https://github.com/ParadiseSS13/Paradise/issues/7203
