### ISSUE TITLE
AI bot control not working properly. 

### ISSUE THREAD

**Issue by RobloxPlayer16** [ParadiseSS13/Paradise#9100]
**Problem Description**:
As AI I am unable to call any robots to any floor location. It only registers a call if I click on a door. 

**What did you expect to happen**: 
The bot to respond to my call and make its way there. 

**What happened instead**:
Nothing happened when I clicked the ground. 

**Why is this bad/What are the consequences:**
It removes the AI's ability to command bots. 

**Steps to reproduce the problem**:
Be AI. Open robot control. Attempt to call a bot to any floor location. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**
 I have tried restarting my client several times, and the problem is consistent between rounds.

**Comment by RobloxPlayer16** [comment]
I have done more testing and it seems any object over a floor tile will register the robot call. But floor tiles themselves do not register and it acts like no click was given. Objects like bats, chairs and such all work for calling robots to a location.

**Comment by Spacemanspark** [comment]
Oh, someone already reported this, I just ran into this as well.

**Comment by RobloxPlayer16** [comment]
Did more testing. Middle clicking while in a mech as AI has the same responsiveness as robot control. IE, needing to click on an object for it to work, as the ground does nothing.

**Comment by alex-gh** [comment]
The issue is somewhere here: https://github.com/ParadiseSS13/Paradise/blob/6fe83a698757f023d26171355fff906d95ee764b/code/_onclick/ai.dm#L37-L61

Most likely because because get_turf_pixel only works on movable atoms, and turfs are not movable.

I was poking around there and was able to get it fixed, but I don't fully understand the security implications of the code above so I left it alone for now.
