### ISSUE TITLE
Cannot Centre on Robots Making Announcements as AI

### ISSUE THREAD

**Issue by Surrealistik** [ParadiseSS13/Paradise#925]
While playing as AI you cannot centre on a robot by clicking its name when it makes an announcement; you will _always_ get an error message, even if that robot is within sight of a camera. You can, however, centre on them via the 'track' command in the Robot Control window.

**Comment by Fox-McCloud** [comment]
This is because of how our saycode works vs how it works on TG (where the basis of the idea came from); on TG, anything can speak into a radio, including objects---that's not the case here so Mark had to implement a bit of a work-around. It works great, functionally, but this can happen.

Not really a particular easy or straight-forward way to fix this without completely overhauling saycode again.
