### ISSUE TITLE
Invisible false walls

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#9404]
**Problem Description**:
Some walls in maint appear invisible, though they are still there and I can't see through them, just to the floor under them

**What did you expect to happen**: 
For walls to be visible.

**What happened instead**:
The wall was not, in fact, visible.

**Why is this bad/What are the consequences:**
It makes me try to walk through a tile and get stopped by an invisible wall.

**Steps to reproduce the problem**:
No clue, I just walk into maint and a single wall is invisible.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: See picture, you can still 'examine' the invisible wall and it does show up in the rightclick menu, but interestingly the plating under it also shows up.

![untitled](https://user-images.githubusercontent.com/32099540/44546253-a76fab80-a717-11e8-9089-bd9212cdd231.png)

**Comment by Kyep** [comment]
Just a theory, but I suspect that this might be caused by random spawners in maint. Specifically that the random spawners are spawning things in Initialize() rather than New(). For random spawners to work, they have to spawn things in New(), otherwise the things they spawn don't end up initialized properly, which leads to them having broken sprites, or no sprites at all.
I'm not certain this is the cause of the problem... but I have encountered something similar in the past with other random spawners, and that was the source of the problem then... so it might be here also.
Pinging @Aurorablade as I believe they're working on changes to random spawners that may be relevant here.

**Comment by Aurorablade** [comment]
its not going to effect random loot spawners, just corpse spawners. What it looks like its it perhaps using the base object of the wall thats not supposed to be used. Not sure unless someone with admin abilitys finds some and VVs the path of the offending wall.

**Comment by TDSSS** [comment]
So should I ahelp the next time I see an invisible wall so an admin can take a look at it?

**Comment by variableundefined** [comment]
Yes

**Comment by datlo** [comment]
As far as I can tell these are actually bugged false walls. If you weld them by alt clicking the tile, it will remove the plating as if the wall was reinforced. Look at false walls spawner, whoever's gonna fix this

**Comment by farie82** [comment]
It is a fake wall aye. If you alt click on it and click on the name with empty hands you'll open it. Once opened once it will work as intended.

**Comment by Contrabang** [comment]
False walls now have the default wall texture and wall smoothing instead of being invisible now
