### ISSUE TITLE
Atmospherics external access airlocks are not usable by AI and Borgs.

### ISSUE THREAD

**Issue by alex-gh** [ParadiseSS13/Paradise#9510]
**Problem Description**:
The atmospherics external access airlocks (Just above the transit tube to the AI sat) are vardited to have AI control disabled and hack proof enabled. 

**What did you expect to happen**: 
I expected the airlocks have the same settings as all other external airlocks on the station.

**What happened instead**:
Airlocks are neither controllable nor hackable by AI/Borgs

**Why is this bad/What are the consequences:**
Cyborgs can not use these airlocks to enter or exit the station.

**Steps to reproduce the problem**:
Be cyborg or AI, click on the airlock.

**Comment by Agameofscones** [comment]
Atmos airlocks use a different airlock system than the other ones (As in a different entity)
I only know this because I used them on my whiteship test rework because their pixel placement was cool & good.
They're a different object entirely in the object tree. While in comparison the vox skipjack airlock controls are the same entity as the public airlock at arrivals, just with different variables, etc , etc.

**Comment by TDSSS** [comment]
I just tried it out and was able to use the button just fine as a borg. It's just the airlock itself which refuses the connection.

**Comment by alex-gh** [comment]
Well, yes the buttons work fine. But for some reason the airlocks themselves are firewalled.
