### ISSUE TITLE
Re entering corpse on an IPC posibrain can boot you to the lobby

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#9559]
**Problem Description**:
When you re-enter your corpse as an IPC that has been de-brained.  If the posibrain is active and you re enter while its in the signup stage, your game will crash and upon re connection, you will be kicked to the lobby. Suiciding as the brain also bricks it but thats out the scope of this.

**What did you expect to happen**: 
Me to stay in my brain and not crash to the lobby

**What happened instead**:
Crashed to lobby.

**Why is this bad/What are the consequences:**
I can think of 2 main ones
1) God knows how many runtimes this produced
2) I could re-join as the character again, which is pretty immersion breaking

**Steps to reproduce the problem**:
You will need 3 people
Person 1 is a dead IPC, with posibrain removed.
Person 2 has the psoibrain in their hand
Person 3 is a normal ghost

Person 1 ghosts
Person 2 activates the posibrain signup
Person 1 re enters
Person 3 signs up for the brain
Person 1 crashes and goes to lobby on reconnection
Person 2 ends up in the brain
Person 3 is confused
Person 1 is salting everywhere

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Nothing else important

**Comment by dandykong** [comment]
Disregard my old comment, turns out the loss of your IPC brain is legit. It just needs to be handled better.

When an IPC's brain is removed, the IPC is still alive. Normal respawn rules still apply, therefore you forfeit respawn when you click the ghost button on the warning popup. There is an exploit regarding this, however. Debrain an IPC and they're out of the round until the brain is retrieved. There are some bugs with ghosted posibrains, but this is largely in part due to a massive mechanics oversight.

**Comment by TravisAngeI** [comment]
Is this now technically fixed with how posibrain signing up works now?

**Comment by silverplatedelta** [comment]
As IPCs brains are no longer offered, this return to lobby vector has been fixed. Thanks for the report.
