### ISSUE TITLE
IPCs take too much damage

### ISSUE THREAD

**Issue by shazbot194** [ParadiseSS13/Paradise#9566]
**Problem Description**:
IPCs take about 15% extra damage.

**What did you expect to happen**: 
IPCs to take only 50% extra damage.

**What happened instead**.
IPCs take 65% extra damage.

**Why is this bad/What are the consequences:**
They take more damage then they are meant to.

**Steps to reproduce the problem**:
Shoot them with a revolver, it should do 90 damage, it instead does 99. Or review the code that dictates damage, [here](
https://github.com/ParadiseSS13/Paradise/blob/619885d35e5bcac95925ee585cc16433fa8ea820/code/modules/surgery/organs/organ_external.dm#L634) and [here](
https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/human/species/machine.dm#L18).

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
Nothing really, this is purely a code based issue.

This should probably either be fixed by adjusting the brute/burn mod to 2.27, or all documentation like the in code description and wiki to say 165%.

**Comment by AffectedArc07** [comment]
![image](https://user-images.githubusercontent.com/25063394/45639862-fc010f00-baa8-11e8-858c-acd70054985f.png)

**Comment by AffectedArc07** [comment]
![image](https://user-images.githubusercontent.com/25063394/45639862-fc010f00-baa8-11e8-858c-acd70054985f.png)

**Comment by FalseIncarnate** [comment]
Error is due to order of operations on damage calculation.

Revolver shoots bullets that deal 60 brute damage.
IPCs naturally take 2.5x brute damage, increasing this to 150 damage.
Robotic limbs then reduce damage by 66% (x 0.66), reducing this down to the resultant 99 damage observed.

Because the damage reduction from robotic limbs is calculated AFTER increasing the damage from the IPC weakness, this causes the end result to be higher than if you combined the two numbers prior to calculating the damage change.

Effectively, the math currently looks like this: (base_damage * species_mod) * limb_resist
Your expecting it to look like this: base_damage * (species_mod * limb_resist)

Things look nicer on paper (documentation) when you don't account for the actual ordering of things.

**Comment by shazbot194** [comment]
It’s less an error of order of operations and more an error in math, as multiplication doesn’t care what order it’s in, that only applies when you start doing other things to it. To put it simply, someone a few years ago didn’t double check their math.

**Comment by Pennwick** [comment]
Seconding what Shazbot said. Though its less of bad math and the fact that I believe whoever chose 2.5 to be the IPC multiplier thought that damage for mechanical limbs was multiplied by .6 and not .66 which its actually multiplied by. This is indicated by the comment.
