### ISSUE TITLE
Cyborg Station Bounced Radio Transmits Only On Common

### ISSUE THREAD

**Issue by CStarker** [ParadiseSS13/Paradise#9845]
**Problem Description**:
The Station Bounced Radio for the Cyborgs can only transmit on the Common channel, despite displaying your department's channel as the only possible channel.

**What did you expect to happen**: 
The radio should have transmitted on the displayed channel only.

**What happened instead**:
The radio transmitted sensitive information on the Common channel instead of the Security channel, which was the only channel listed in the radio's menu at the time.

**Why is this bad/What are the consequences:**
This obviates the use of the station bounced radio for cyborgs in most situations. They are unable to communicate with their department members due to their information being lost in the common chat. Dangerous or sensitive information is broadcast to everyone on the station.

**Steps to reproduce the problem**:
Telecoms must be deactivated.

Open the radio menu.

If you are a cyborg, only your department's channel will be listed. Common will not be listed.

Turn the microphone to On.

Say anything in normal voice using the command, say.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Telecomms was deactivated.

**Comment by Kyep** [comment]
Enabling your headset mic causes all text to be transmitted over your default comm frequency.
Both humans and borgs can re-tune the default frequency of their radio, within a very limited range.
They cannot, however, re-tune their default frequency to be a department frequency, even if they have access to that department comms.

Altering radios so that they can be set to transmit on a department channel by default is probably a feature, not a bugfix.

**Comment by Kyep** [comment]
@AffectedArc07 Should be closable
